Repository Azure/azure-sdk-for-node, pull requests merged in 2018-11, with the labels that each got.

#4004 [AutoPR] cosmos-db/resource-manager
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/virtualNetworkRule.js
  lib/services/cosmosdbManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3999 [AutoPR containerinstance/resource-manager] Update Microsoft.Containerinstance swagger with DNSConfig and GPU
  lib/services/containerinstanceManagement/lib/models/container.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/dnsConfiguration.js
  lib/services/containerinstanceManagement/lib/models/gpuResource.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/resourceLimits.js
  lib/services/containerinstanceManagement/lib/models/resourceRequests.js
  lib/services/containerinstanceManagement/lib/models/resourceRequirements.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4008 [AutoPR] containerinstance/resource-manager
  lib/services/containerinstanceManagement/lib/models/container.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/dnsConfiguration.js
  lib/services/containerinstanceManagement/lib/models/gpuResource.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/resourceLimits.js
  lib/services/containerinstanceManagement/lib/models/resourceRequests.js
  lib/services/containerinstanceManagement/lib/models/resourceRequirements.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3996 [AutoPR reservations/resource-manager] Reservations RP 2018-06-01 Preview: Add new reserved resource type RedHat
  lib/services/reservationsManagement/LICENSE.txt
  lib/services/reservationsManagement/README.md
  lib/services/reservationsManagement/lib/models/index.d.ts
  lib/services/reservationsManagement/lib/models/reservationProperties.js
  lib/services/reservationsManagement/lib/models/reservationResponse.js
Labels: RestPRMerged, in progress

#3998 [AutoPR visualstudio/resource-manager] Added patch API to swagger doc in Visual studio RP
  lib/services/visualstudioManagement/lib/models/accountTagRequest.js
  lib/services/visualstudioManagement/lib/models/index.d.ts
  lib/services/visualstudioManagement/lib/models/index.js
  lib/services/visualstudioManagement/lib/operations/accounts.js
  lib/services/visualstudioManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4011 [AutoPR containerregistry/resource-manager] ACR: Add contextAccessToken to Task step
  lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStep.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStep.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/taskStepProperties.js
  lib/services/containerRegistryManagement/lib/models/taskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/tasks.js
Labels: RestPRMerged, in progress

#4013 [AutoPR] containerregistry/resource-manager
  lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStep.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStep.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/taskStepProperties.js
  lib/services/containerRegistryManagement/lib/models/taskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/tasks.js
  lib/services/containerRegistryManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4012 [AutoPR] visualstudio/resource-manager
  lib/services/visualstudioManagement/lib/models/accountTagRequest.js
  lib/services/visualstudioManagement/lib/models/index.d.ts
  lib/services/visualstudioManagement/lib/models/index.js
  lib/services/visualstudioManagement/lib/operations/accounts.js
  lib/services/visualstudioManagement/lib/operations/index.d.ts
  lib/services/visualstudioManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4010 [AutoPR] reservations/resource-manager
  lib/services/reservationsManagement/LICENSE.txt
  lib/services/reservationsManagement/README.md
  lib/services/reservationsManagement/lib/models/index.d.ts
  lib/services/reservationsManagement/lib/models/reservationProperties.js
  lib/services/reservationsManagement/lib/models/reservationResponse.js
  lib/services/reservationsManagement/lib/package.json
  lib/services/reservationsManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4014 [AutoPR] domainservices/resource-manager
  lib/services/domainservicesManagement/lib/models/domainService.js
  lib/services/domainservicesManagement/lib/models/index.d.ts
  lib/services/domainservicesManagement/lib/models/index.js
  lib/services/domainservicesManagement/lib/models/resource.js
  lib/services/domainservicesManagement/lib/operations/domainServices.js
  lib/services/domainservicesManagement/lib/operations/index.d.ts
  lib/services/domainservicesManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4006 [AutoPR cognitiveservices/data-plane/VisualSearch] [Visual Search API] Update encoding format documentation per PM request
  lib/services/visualSearch/LICENSE.txt
  lib/services/visualSearch/lib/models/action.js
  lib/services/visualSearch/lib/models/imageAction.js
  lib/services/visualSearch/lib/models/imageEntityAction.js
  lib/services/visualSearch/lib/models/imageInfo.js
  lib/services/visualSearch/lib/models/imageKnowledge.js
  lib/services/visualSearch/lib/models/imageModuleAction.js
  lib/services/visualSearch/lib/models/imageRecipesAction.js
  lib/services/visualSearch/lib/models/imageRelatedSearchesAction.js
  lib/services/visualSearch/lib/models/imageShoppingSourcesAction.js
  lib/services/visualSearch/lib/models/imageTag.js
  lib/services/visualSearch/lib/models/imageTagRegion.js
  lib/services/visualSearch/lib/models/imagesImageMetadata.js
  lib/services/visualSearch/lib/models/imagesModule.js
  lib/services/visualSearch/lib/models/index.d.ts
  lib/services/visualSearch/lib/models/knowledgeRequest.js
  lib/services/visualSearch/lib/models/mediaObject.js
  lib/services/visualSearch/lib/models/point2D.js
  lib/services/visualSearch/lib/models/query.js
  lib/services/visualSearch/lib/models/recipesModule.js
  lib/services/visualSearch/lib/models/relatedSearchesModule.js
  lib/services/visualSearch/lib/models/visualSearchRequest.js
  lib/services/visualSearch/lib/operations/images.js
  lib/services/visualSearch/lib/operations/index.d.ts
  lib/services/visualSearch/package.json
Labels: RestPRMerged, in progress

#4021 [AutoPR] cognitiveservices/data-plane/VisualSearch
  lib/services/visualSearch/LICENSE.txt
  lib/services/visualSearch/lib/models/action.js
  lib/services/visualSearch/lib/models/imageAction.js
  lib/services/visualSearch/lib/models/imageEntityAction.js
  lib/services/visualSearch/lib/models/imageInfo.js
  lib/services/visualSearch/lib/models/imageKnowledge.js
  lib/services/visualSearch/lib/models/imageModuleAction.js
  lib/services/visualSearch/lib/models/imageRecipesAction.js
  lib/services/visualSearch/lib/models/imageRelatedSearchesAction.js
  lib/services/visualSearch/lib/models/imageShoppingSourcesAction.js
  lib/services/visualSearch/lib/models/imageTag.js
  lib/services/visualSearch/lib/models/imageTagRegion.js
  lib/services/visualSearch/lib/models/imagesImageMetadata.js
  lib/services/visualSearch/lib/models/imagesModule.js
  lib/services/visualSearch/lib/models/index.d.ts
  lib/services/visualSearch/lib/models/knowledgeRequest.js
  lib/services/visualSearch/lib/models/mediaObject.js
  lib/services/visualSearch/lib/models/point2D.js
  lib/services/visualSearch/lib/models/query.js
  lib/services/visualSearch/lib/models/recipesModule.js
  lib/services/visualSearch/lib/models/relatedSearchesModule.js
  lib/services/visualSearch/lib/models/visualSearchRequest.js
  lib/services/visualSearch/lib/operations/images.js
  lib/services/visualSearch/lib/operations/index.d.ts
  lib/services/visualSearch/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4023 Regenerate azure-cognitiveservices-customsearch
  lib/services/cognitiveServicesCustomSearch/lib/operations/customInstance.js
  lib/services/cognitiveServicesCustomSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesCustomSearch/package.json
Labels: Planned-Sprint-126, Started-Sprint-126, in progress

#4024 [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra
  lib/services/authorizationManagement/lib/authorizationManagementClient.d.ts
  lib/services/authorizationManagement/lib/authorizationManagementClient.js
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/index.js
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/index.js
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
Labels: RestPRMerged, in progress

#4007 [AutoPR datafactory/resource-manager] Enable delete activity
  lib/services/datafactoryManagement/lib/models/deleteActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
Labels: RestPRMerged, in progress

#4031 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/azureBlobStorageLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureMySqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/azurePostgreSqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureSqlDWLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureSqlDatabaseLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureStorageLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureTableStorageLinkedService.js
  lib/services/datafactoryManagement/lib/models/cosmosDbLinkedService.js
  lib/services/datafactoryManagement/lib/models/couchbaseLinkedService.js
  lib/services/datafactoryManagement/lib/models/deleteActivity.js
  lib/services/datafactoryManagement/lib/models/drillLinkedService.js
  lib/services/datafactoryManagement/lib/models/greenplumLinkedService.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/mariaDBLinkedService.js
  lib/services/datafactoryManagement/lib/models/mySqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/netezzaLinkedService.js
  lib/services/datafactoryManagement/lib/models/oracleLinkedService.js
  lib/services/datafactoryManagement/lib/models/postgreSqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/verticaLinkedService.js
  lib/services/datafactoryManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4030 [AutoPR] authorization/resource-manager
  lib/services/authorizationManagement/lib/authorizationManagementClient.d.ts
  lib/services/authorizationManagement/lib/authorizationManagementClient.js
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/index.js
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/index.js
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
  lib/services/authorizationManagement/package.json
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_assign_Key_Vault_the_operator_role_on_a_storage_account.nock.js
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4032 [AutoPR sql/resource-manager] Fix blob auditing documentation
  lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
Labels: RestPRMerged, in progress

#4038 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4039 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessmentScans.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4049 [AutoPR cognitiveservices/resource-manager] fixing sample names in cognitive services
  lib/services/cognitiveServicesManagement/LICENSE.txt
  lib/services/cognitiveServicesManagement/README.md
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResultList.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountEnumerateSkusResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js
  lib/services/cognitiveServicesManagement/lib/models/errorModel.js
  lib/services/cognitiveServicesManagement/lib/models/operationEntity.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSku.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictions.js
  lib/services/cognitiveServicesManagement/lib/models/usage.js
  lib/services/cognitiveServicesManagement/lib/models/usagesResult.js
  lib/services/cognitiveServicesManagement/package.json
Labels: RestPRMerged, in progress

#4056 Update SwaggerToSDK generator version to 2.1.114
  swagger_to_sdk_config.json
Labels: Started-Sprint-126, Unplanned-Sprint-126, in progress

#4055 [AutoPR] cognitiveservices/resource-manager
  lib/services/cognitiveServicesManagement/LICENSE.txt
  lib/services/cognitiveServicesManagement/README.md
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResultList.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountEnumerateSkusResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountKeys.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountListResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js
  lib/services/cognitiveServicesManagement/lib/models/errorBody.js
  lib/services/cognitiveServicesManagement/lib/models/errorModel.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/metricName.js
  lib/services/cognitiveServicesManagement/lib/models/operationDisplayInfo.js
  lib/services/cognitiveServicesManagement/lib/models/operationEntity.js
  lib/services/cognitiveServicesManagement/lib/models/operationEntityListResult.js
  lib/services/cognitiveServicesManagement/lib/models/regenerateKeyParameters.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSku.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictionInfo.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictions.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkusResult.js
  lib/services/cognitiveServicesManagement/lib/models/sku.js
  lib/services/cognitiveServicesManagement/lib/models/usage.js
  lib/services/cognitiveServicesManagement/lib/models/usagesResult.js
  lib/services/cognitiveServicesManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4057 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/managedBackupShortTermRetentionPolicy.js
  lib/services/sqlManagement2/lib/models/managedBackupShortTermRetentionPolicyListResult.js
  lib/services/sqlManagement2/lib/models/managedInstance.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/managedBackupShortTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/managedInstances.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4058 [AutoPR subscription/resource-manager] update folder to generate arm subscription to subscriptionManagement2 for node.js
  lib/services/subscriptionManagement2/LICENSE.txt
  lib/services/subscriptionManagement2/README.md
  lib/services/subscriptionManagement2/lib/models/adPrincipal.js
  lib/services/subscriptionManagement2/lib/models/errorResponse.js
  lib/services/subscriptionManagement2/lib/models/index.d.ts
  lib/services/subscriptionManagement2/lib/models/index.js
  lib/services/subscriptionManagement2/lib/models/location.js
  lib/services/subscriptionManagement2/lib/models/locationListResult.js
  lib/services/subscriptionManagement2/lib/models/operation.js
  lib/services/subscriptionManagement2/lib/models/operationDisplay.js
  lib/services/subscriptionManagement2/lib/models/operationListResult.js
  lib/services/subscriptionManagement2/lib/models/subscription.js
  lib/services/subscriptionManagement2/lib/models/subscriptionCreationParameters.js
  lib/services/subscriptionManagement2/lib/models/subscriptionCreationResult.js
  lib/services/subscriptionManagement2/lib/models/subscriptionListResult.js
  lib/services/subscriptionManagement2/lib/models/subscriptionOperation.js
  lib/services/subscriptionManagement2/lib/models/subscriptionOperationListResult.js
  lib/services/subscriptionManagement2/lib/models/subscriptionPolicies.js
  lib/services/subscriptionManagement2/lib/models/tenantIdDescription.js
  lib/services/subscriptionManagement2/lib/models/tenantListResult.js
  lib/services/subscriptionManagement2/lib/operations/index.d.ts
  lib/services/subscriptionManagement2/lib/operations/index.js
  lib/services/subscriptionManagement2/lib/operations/operations.js
  lib/services/subscriptionManagement2/lib/operations/subscriptionFactory.js
  lib/services/subscriptionManagement2/lib/operations/subscriptionOperations.js
  lib/services/subscriptionManagement2/lib/operations/subscriptions.js
  lib/services/subscriptionManagement2/lib/operations/tenants.js
  lib/services/subscriptionManagement2/lib/subscriptionClient.d.ts
  lib/services/subscriptionManagement2/lib/subscriptionClient.js
  lib/services/subscriptionManagement2/package.json
Labels: RestPRMerged, in progress

#4061 [AutoPR authorization/resource-manager] remove duplicate entry for Go SDK build
  lib/services/authorizationManagement/README.md
  lib/services/authorizationManagement/lib/models/classicAdministrator.js
  lib/services/authorizationManagement/lib/models/classicAdministratorListResult.js
  lib/services/authorizationManagement/lib/models/denyAssignment.js
  lib/services/authorizationManagement/lib/models/denyAssignmentFilter.js
  lib/services/authorizationManagement/lib/models/denyAssignmentListResult.js
  lib/services/authorizationManagement/lib/models/denyAssignmentPermission.js
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/permission.js
  lib/services/authorizationManagement/lib/models/permissionGetResult.js
  lib/services/authorizationManagement/lib/models/principal.js
  lib/services/authorizationManagement/lib/models/providerOperation.js
  lib/services/authorizationManagement/lib/models/providerOperationsMetadata.js
  lib/services/authorizationManagement/lib/models/providerOperationsMetadataListResult.js
  lib/services/authorizationManagement/lib/models/resourceType.js
  lib/services/authorizationManagement/lib/models/roleAssignment.js
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/models/roleAssignmentFilter.js
  lib/services/authorizationManagement/lib/models/roleAssignmentListResult.js
  lib/services/authorizationManagement/lib/models/roleDefinition.js
  lib/services/authorizationManagement/lib/models/roleDefinitionFilter.js
  lib/services/authorizationManagement/lib/models/roleDefinitionListResult.js
  lib/services/authorizationManagement/package.json
Labels: RestPRMerged

#4066 [AutoPR cognitiveservices/data-plane/Face] FaceAPI Split Python conf in it's own file
  lib/services/cognitiveServicesFace/LICENSE.txt
  lib/services/cognitiveServicesFace/README.md
  lib/services/cognitiveServicesFace/lib/models/aPIError.js
  lib/services/cognitiveServicesFace/lib/models/accessory.js
  lib/services/cognitiveServicesFace/lib/models/blur.js
  lib/services/cognitiveServicesFace/lib/models/coordinate.js
  lib/services/cognitiveServicesFace/lib/models/detectedFace.js
  lib/services/cognitiveServicesFace/lib/models/emotion.js
  lib/services/cognitiveServicesFace/lib/models/errorModel.js
  lib/services/cognitiveServicesFace/lib/models/exposure.js
  lib/services/cognitiveServicesFace/lib/models/faceAttributes.js
  lib/services/cognitiveServicesFace/lib/models/faceLandmarks.js
  lib/services/cognitiveServicesFace/lib/models/faceList.js
  lib/services/cognitiveServicesFace/lib/models/faceRectangle.js
  lib/services/cognitiveServicesFace/lib/models/facialHair.js
  lib/services/cognitiveServicesFace/lib/models/findSimilarRequest.js
  lib/services/cognitiveServicesFace/lib/models/groupRequest.js
  lib/services/cognitiveServicesFace/lib/models/groupResult.js
  lib/services/cognitiveServicesFace/lib/models/hair.js
  lib/services/cognitiveServicesFace/lib/models/hairColor.js
  lib/services/cognitiveServicesFace/lib/models/headPose.js
  lib/services/cognitiveServicesFace/lib/models/identifyCandidate.js
  lib/services/cognitiveServicesFace/lib/models/identifyRequest.js
  lib/services/cognitiveServicesFace/lib/models/identifyResult.js
  lib/services/cognitiveServicesFace/lib/models/imageUrl.js
  lib/services/cognitiveServicesFace/lib/models/index.d.ts
  lib/services/cognitiveServicesFace/lib/models/largeFaceList.js
  lib/services/cognitiveServicesFace/lib/models/largePersonGroup.js
  lib/services/cognitiveServicesFace/lib/models/makeup.js
  lib/services/cognitiveServicesFace/lib/models/nameAndUserDataContract.js
  lib/services/cognitiveServicesFace/lib/models/noise.js
  lib/services/cognitiveServicesFace/lib/models/occlusion.js
  lib/services/cognitiveServicesFace/lib/models/persistedFace.js
  lib/services/cognitiveServicesFace/lib/models/person.js
  lib/services/cognitiveServicesFace/lib/models/personGroup.js
  lib/services/cognitiveServicesFace/lib/models/similarFace.js
  lib/services/cognitiveServicesFace/lib/models/trainingStatus.js
  lib/services/cognitiveServicesFace/lib/models/updateFaceRequest.js
  lib/services/cognitiveServicesFace/lib/models/verifyFaceToFaceRequest.js
  lib/services/cognitiveServicesFace/lib/models/verifyFaceToPersonRequest.js
  lib/services/cognitiveServicesFace/lib/models/verifyResult.js
  lib/services/cognitiveServicesFace/package.json
Labels: RestPRMerged, in progress

#4067 [AutoPR cognitiveservices/data-plane/CustomWebSearch] Py conf in its own file
  lib/services/cognitiveServicesCustomSearch/LICENSE.txt
  lib/services/cognitiveServicesCustomSearch/lib/models/answer.js
  lib/services/cognitiveServicesCustomSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesCustomSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesCustomSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesCustomSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesCustomSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesCustomSearch/lib/models/query.js
  lib/services/cognitiveServicesCustomSearch/lib/models/queryContext.js
  lib/services/cognitiveServicesCustomSearch/lib/models/response.js
  lib/services/cognitiveServicesCustomSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesCustomSearch/lib/models/searchResponse.js
  lib/services/cognitiveServicesCustomSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesCustomSearch/lib/models/thing.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webMetaTag.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webPage.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webWebAnswer.js
  lib/services/cognitiveServicesCustomSearch/package.json
Labels: RestPRMerged, in progress

#4069 [AutoPR] cognitiveservices/data-plane/CustomWebSearch
  lib/services/cognitiveServicesCustomSearch/LICENSE.txt
  lib/services/cognitiveServicesCustomSearch/lib/models/answer.js
  lib/services/cognitiveServicesCustomSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesCustomSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesCustomSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesCustomSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesCustomSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesCustomSearch/lib/models/query.js
  lib/services/cognitiveServicesCustomSearch/lib/models/queryContext.js
  lib/services/cognitiveServicesCustomSearch/lib/models/response.js
  lib/services/cognitiveServicesCustomSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesCustomSearch/lib/models/searchResponse.js
  lib/services/cognitiveServicesCustomSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesCustomSearch/lib/models/thing.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webMetaTag.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webPage.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webWebAnswer.js
  lib/services/cognitiveServicesCustomSearch/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4068 [AutoPR] cognitiveservices/data-plane/Face
  lib/services/cognitiveServicesFace/LICENSE.txt
  lib/services/cognitiveServicesFace/README.md
  lib/services/cognitiveServicesFace/lib/models/aPIError.js
  lib/services/cognitiveServicesFace/lib/models/accessory.js
  lib/services/cognitiveServicesFace/lib/models/blur.js
  lib/services/cognitiveServicesFace/lib/models/coordinate.js
  lib/services/cognitiveServicesFace/lib/models/detectedFace.js
  lib/services/cognitiveServicesFace/lib/models/emotion.js
  lib/services/cognitiveServicesFace/lib/models/errorModel.js
  lib/services/cognitiveServicesFace/lib/models/exposure.js
  lib/services/cognitiveServicesFace/lib/models/faceAttributes.js
  lib/services/cognitiveServicesFace/lib/models/faceLandmarks.js
  lib/services/cognitiveServicesFace/lib/models/faceList.js
  lib/services/cognitiveServicesFace/lib/models/faceRectangle.js
  lib/services/cognitiveServicesFace/lib/models/facialHair.js
  lib/services/cognitiveServicesFace/lib/models/findSimilarRequest.js
  lib/services/cognitiveServicesFace/lib/models/groupRequest.js
  lib/services/cognitiveServicesFace/lib/models/groupResult.js
  lib/services/cognitiveServicesFace/lib/models/hair.js
  lib/services/cognitiveServicesFace/lib/models/hairColor.js
  lib/services/cognitiveServicesFace/lib/models/headPose.js
  lib/services/cognitiveServicesFace/lib/models/identifyCandidate.js
  lib/services/cognitiveServicesFace/lib/models/identifyRequest.js
  lib/services/cognitiveServicesFace/lib/models/identifyResult.js
  lib/services/cognitiveServicesFace/lib/models/imageUrl.js
  lib/services/cognitiveServicesFace/lib/models/index.d.ts
  lib/services/cognitiveServicesFace/lib/models/largeFaceList.js
  lib/services/cognitiveServicesFace/lib/models/largePersonGroup.js
  lib/services/cognitiveServicesFace/lib/models/makeup.js
  lib/services/cognitiveServicesFace/lib/models/nameAndUserDataContract.js
  lib/services/cognitiveServicesFace/lib/models/noise.js
  lib/services/cognitiveServicesFace/lib/models/occlusion.js
  lib/services/cognitiveServicesFace/lib/models/persistedFace.js
  lib/services/cognitiveServicesFace/lib/models/person.js
  lib/services/cognitiveServicesFace/lib/models/personGroup.js
  lib/services/cognitiveServicesFace/lib/models/similarFace.js
  lib/services/cognitiveServicesFace/lib/models/trainingStatus.js
  lib/services/cognitiveServicesFace/lib/models/updateFaceRequest.js
  lib/services/cognitiveServicesFace/lib/models/verifyFaceToFaceRequest.js
  lib/services/cognitiveServicesFace/lib/models/verifyFaceToPersonRequest.js
  lib/services/cognitiveServicesFace/lib/models/verifyResult.js
  lib/services/cognitiveServicesFace/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4073 [AutoPR apimanagement/resource-manager] Remove readonly attribute from identities collection in users
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/userContract.js
  lib/services/apimanagement/lib/models/userCreateParameters.js
  lib/services/apimanagement/lib/models/userEntityBaseParameters.js
  lib/services/apimanagement/lib/models/userUpdateParameters.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/user.js
Labels: RestPRMerged, in progress

#4076 [AutoPR] apimanagement/resource-manager
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/userContract.js
  lib/services/apimanagement/lib/models/userCreateParameters.js
  lib/services/apimanagement/lib/models/userEntityBaseParameters.js
  lib/services/apimanagement/lib/models/userUpdateParameters.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/user.js
  lib/services/apimanagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4075 [AutoPR network/resource-manager] Make NIC VM readOnly
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/networkInterface.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkInterfaces.js
Labels: RestPRMerged, in progress

#4078 [AutoPR security/resource-manager] Add Allowed Connections REST API
  lib/services/securityManagement/lib/models/allowedConnectionsList.js
  lib/services/securityManagement/lib/models/allowedConnectionsResource.js
  lib/services/securityManagement/lib/models/connectableResource.js
  lib/services/securityManagement/lib/models/connectedResource.js
  lib/services/securityManagement/lib/models/index.d.ts
  lib/services/securityManagement/lib/models/index.js
  lib/services/securityManagement/lib/operations/allowedConnections.js
  lib/services/securityManagement/lib/operations/index.d.ts
  lib/services/securityManagement/lib/operations/index.js
  lib/services/securityManagement/lib/securityCenter.d.ts
  lib/services/securityManagement/lib/securityCenter.js
Labels: RestPRMerged

#4077 [AutoPR] network/resource-manager
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/networkInterface.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkInterfaces.js
  lib/services/networkManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4050 [AutoPR containerinstance/resource-manager] Azure Container Instance: Add start container group API
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: RestPRMerged, in progress

#4080 [AutoPR] containerinstance/resource-manager
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4081 [AutoPR network/resource-manager] [AzureFirewall] Mark private IP address read-only
  lib/services/networkManagement2/lib/models/azureFirewallIPConfiguration.js
  lib/services/networkManagement2/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4087 [AutoPR web/resource-manager] Add GeoRegion to DeletedSite Model
  lib/services/websiteManagement2/lib/models/deletedSite.js
  lib/services/websiteManagement2/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4051 [AutoPR datafactory/resource-manager] DataFactory: add table name in dataset
  lib/services/datafactoryManagement/lib/models/amazonMWSObjectDataset.js
  lib/services/datafactoryManagement/lib/models/azurePostgreSqlTableDataset.js
  lib/services/datafactoryManagement/lib/models/concurObjectDataset.js
  lib/services/datafactoryManagement/lib/models/couchbaseTableDataset.js
  lib/services/datafactoryManagement/lib/models/drillTableDataset.js
  lib/services/datafactoryManagement/lib/models/eloquaObjectDataset.js
  lib/services/datafactoryManagement/lib/models/googleBigQueryObjectDataset.js
  lib/services/datafactoryManagement/lib/models/greenplumTableDataset.js
  lib/services/datafactoryManagement/lib/models/hBaseObjectDataset.js
  lib/services/datafactoryManagement/lib/models/hiveObjectDataset.js
  lib/services/datafactoryManagement/lib/models/hubspotObjectDataset.js
  lib/services/datafactoryManagement/lib/models/impalaObjectDataset.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/jiraObjectDataset.js
  lib/services/datafactoryManagement/lib/models/magentoObjectDataset.js
  lib/services/datafactoryManagement/lib/models/mariaDBTableDataset.js
  lib/services/datafactoryManagement/lib/models/marketoObjectDataset.js
  lib/services/datafactoryManagement/lib/models/netezzaTableDataset.js
  lib/services/datafactoryManagement/lib/models/paypalObjectDataset.js
  lib/services/datafactoryManagement/lib/models/phoenixObjectDataset.js
  lib/services/datafactoryManagement/lib/models/prestoObjectDataset.js
  lib/services/datafactoryManagement/lib/models/quickBooksObjectDataset.js
  lib/services/datafactoryManagement/lib/models/responsysObjectDataset.js
  lib/services/datafactoryManagement/lib/models/salesforceMarketingCloudObjectDataset.js
  lib/services/datafactoryManagement/lib/models/serviceNowObjectDataset.js
  lib/services/datafactoryManagement/lib/models/shopifyObjectDataset.js
  lib/services/datafactoryManagement/lib/models/sparkObjectDataset.js
  lib/services/datafactoryManagement/lib/models/squareObjectDataset.js
  lib/services/datafactoryManagement/lib/models/storedProcedureParameter.js
  lib/services/datafactoryManagement/lib/models/verticaTableDataset.js
  lib/services/datafactoryManagement/lib/models/xeroObjectDataset.js
  lib/services/datafactoryManagement/lib/models/zohoObjectDataset.js
Labels: RestPRMerged, in progress

#4091 [AutoPR storage/resource-manager] Adds storage account Quick Failover API
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
Labels: RestPRMerged, in progress

#4098 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4096 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/amazonMWSObjectDataset.js
  lib/services/datafactoryManagement/lib/models/azurePostgreSqlTableDataset.js
  lib/services/datafactoryManagement/lib/models/concurObjectDataset.js
  lib/services/datafactoryManagement/lib/models/couchbaseTableDataset.js
  lib/services/datafactoryManagement/lib/models/drillTableDataset.js
  lib/services/datafactoryManagement/lib/models/eloquaObjectDataset.js
  lib/services/datafactoryManagement/lib/models/googleBigQueryObjectDataset.js
  lib/services/datafactoryManagement/lib/models/greenplumTableDataset.js
  lib/services/datafactoryManagement/lib/models/hBaseObjectDataset.js
  lib/services/datafactoryManagement/lib/models/hiveObjectDataset.js
  lib/services/datafactoryManagement/lib/models/hubspotObjectDataset.js
  lib/services/datafactoryManagement/lib/models/impalaObjectDataset.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/jiraObjectDataset.js
  lib/services/datafactoryManagement/lib/models/magentoObjectDataset.js
  lib/services/datafactoryManagement/lib/models/mariaDBTableDataset.js
  lib/services/datafactoryManagement/lib/models/marketoObjectDataset.js
  lib/services/datafactoryManagement/lib/models/netezzaTableDataset.js
  lib/services/datafactoryManagement/lib/models/paypalObjectDataset.js
  lib/services/datafactoryManagement/lib/models/phoenixObjectDataset.js
  lib/services/datafactoryManagement/lib/models/prestoObjectDataset.js
  lib/services/datafactoryManagement/lib/models/quickBooksObjectDataset.js
  lib/services/datafactoryManagement/lib/models/responsysObjectDataset.js
  lib/services/datafactoryManagement/lib/models/salesforceMarketingCloudObjectDataset.js
  lib/services/datafactoryManagement/lib/models/serviceNowObjectDataset.js
  lib/services/datafactoryManagement/lib/models/shopifyObjectDataset.js
  lib/services/datafactoryManagement/lib/models/sparkObjectDataset.js
  lib/services/datafactoryManagement/lib/models/squareObjectDataset.js
  lib/services/datafactoryManagement/lib/models/storedProcedureParameter.js
  lib/services/datafactoryManagement/lib/models/verticaTableDataset.js
  lib/services/datafactoryManagement/lib/models/xeroObjectDataset.js
  lib/services/datafactoryManagement/lib/models/zohoObjectDataset.js
  lib/services/datafactoryManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4097 [AutoPR network/resource-manager] Port fix from PR 4459 to 2018-10-01
  lib/services/networkManagement2/lib/models/containerNetworkInterfaceConfiguration.js
  lib/services/networkManagement2/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4103 [AutoPR authorization/resource-manager] Add latest authorization tag to java config
  lib/services/authorizationManagement/lib/models/index.d.ts
Labels: RestPRMerged

#4100 [AutoPR datalake-store/data-plane] Add maximum chunk size to data lake store docs.
  lib/services/datalake.Store/lib/filesystem/dataLakeStoreFileSystemManagementClient.d.ts
  lib/services/datalake.Store/lib/filesystem/dataLakeStoreFileSystemManagementClient.js
  lib/services/datalake.Store/lib/filesystem/models/aclStatus.js
  lib/services/datalake.Store/lib/filesystem/models/aclStatusResult.js
  lib/services/datalake.Store/lib/filesystem/models/adlsAccessControlException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsBadOffsetException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsError.js
  lib/services/datalake.Store/lib/filesystem/models/adlsFileAlreadyExistsException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsFileNotFoundException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsIOException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsIllegalArgumentException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsRemoteException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsRuntimeException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsSecurityException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsThrottledException.js
  lib/services/datalake.Store/lib/filesystem/models/adlsUnsupportedOperationException.js
  lib/services/datalake.Store/lib/filesystem/models/contentSummary.js
  lib/services/datalake.Store/lib/filesystem/models/contentSummaryResult.js
  lib/services/datalake.Store/lib/filesystem/models/fileOperationResult.js
  lib/services/datalake.Store/lib/filesystem/models/fileStatusProperties.js
  lib/services/datalake.Store/lib/filesystem/models/fileStatusResult.js
  lib/services/datalake.Store/lib/filesystem/models/fileStatuses.js
  lib/services/datalake.Store/lib/filesystem/models/fileStatusesResult.js
  lib/services/datalake.Store/lib/filesystem/models/index.d.ts
  lib/services/datalake.Store/lib/filesystem/models/index.js
  lib/services/datalake.Store/lib/filesystem/operations/fileSystem.js
  lib/services/datalake.Store/lib/filesystem/operations/index.d.ts
  lib/services/datalake.Store/lib/filesystem/operations/index.js
Labels: RestPRMerged, in progress

#4104 [AutoPR] authorization/resource-manager
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#4117 [AutoPR logic/resource-manager] Microsoft.Logic - Don't make ResourceReference id readonly
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/keyVaultReference.js
  lib/services/logicManagement/lib/models/resourceReference.js
  lib/services/logicManagement/lib/operations/index.d.ts
  lib/services/logicManagement/lib/operations/integrationAccounts.js
  lib/services/logicManagement/lib/operations/workflows.js
Labels: RestPRMerged, in progress

#4084 [AutoPR hdinsight/resource-manager] [HDInsight] - Support KV URL
  lib/services/hdInsightManagement/lib/models/cluster.js
  lib/services/hdInsightManagement/lib/models/clusterCreateParametersExtended.js
  lib/services/hdInsightManagement/lib/models/clusterCreateProperties.js
  lib/services/hdInsightManagement/lib/models/clusterDiskEncryptionParameters.js
  lib/services/hdInsightManagement/lib/models/clusterGetProperties.js
  lib/services/hdInsightManagement/lib/models/diskEncryptionProperties.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/index.js
  lib/services/hdInsightManagement/lib/operations/clusters.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4116 [AutoPR cognitiveservices/data-plane/AutoSuggest] Description of Autosuggest usage needs improvement.
  lib/services/cognitiveServicesAutoSuggest/LICENSE.txt
  lib/services/cognitiveServicesAutoSuggest/lib/autoSuggestAPIClient.d.ts
  lib/services/cognitiveServicesAutoSuggest/lib/autoSuggestAPIClient.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/action.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/creativeWork.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/errorModel.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/errorResponse.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/identifiable.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/index.d.ts
  lib/services/cognitiveServicesAutoSuggest/lib/models/queryContext.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/response.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/responseBase.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/searchAction.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/suggestions.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/suggestionsSuggestionGroup.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/thing.js
  lib/services/cognitiveServicesAutoSuggest/package.json
Labels: RestPRMerged, in progress

#4072 [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Update ApiVersion 2018-10-01
  lib/services/storagesyncManagement/README.md
  lib/services/storagesyncManagement/lib/models/azureEntityResource.js
  lib/services/storagesyncManagement/lib/models/backupRequest.js
  lib/services/storagesyncManagement/lib/models/checkNameAvailabilityParameters.js
  lib/services/storagesyncManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/storagesyncManagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncManagement/lib/models/cloudEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/operationDisplayInfo.js
  lib/services/storagesyncManagement/lib/models/operationDisplayResource.js
  lib/services/storagesyncManagement/lib/models/operationEntity.js
  lib/services/storagesyncManagement/lib/models/operationEntityListResult.js
  lib/services/storagesyncManagement/lib/models/postBackupResponse.js
  lib/services/storagesyncManagement/lib/models/postRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/preRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/recallActionParameters.js
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/lib/models/registeredServerCreateParameters.js
  lib/services/storagesyncManagement/lib/models/resource.js
  lib/services/storagesyncManagement/lib/models/resourcesMoveInfo.js
  lib/services/storagesyncManagement/lib/models/restoreFileSpec.js
  lib/services/storagesyncManagement/lib/models/serverEndpoint.js
  lib/services/storagesyncManagement/lib/models/serverEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpointUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncApiError.js
  lib/services/storagesyncManagement/lib/models/storageSyncError.js
  lib/services/storagesyncManagement/lib/models/storageSyncErrorDetails.js
  lib/services/storagesyncManagement/lib/models/storageSyncService.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceCreateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/subscriptionState.js
  lib/services/storagesyncManagement/lib/models/syncGroup.js
  lib/services/storagesyncManagement/lib/models/syncGroupCreateParameters.js
  lib/services/storagesyncManagement/lib/models/trackedResource.js
  lib/services/storagesyncManagement/lib/models/triggerRolloverRequest.js
  lib/services/storagesyncManagement/lib/models/workflow.js
  lib/services/storagesyncManagement/package.json
Labels: RestPRMerged, in progress

#4108 [AutoPR engagementfabric/resource-manager] Add new resource provider Microsoft.EngagementFabric
  lib/services/engagementFabricManagement/LICENSE.txt
  lib/services/engagementFabricManagement/README.md
  lib/services/engagementFabricManagement/lib/engagementFabric.d.ts
  lib/services/engagementFabricManagement/lib/engagementFabric.js
  lib/services/engagementFabricManagement/lib/models/account.js
  lib/services/engagementFabricManagement/lib/models/accountList.js
  lib/services/engagementFabricManagement/lib/models/accountPatch.js
  lib/services/engagementFabricManagement/lib/models/channel.js
  lib/services/engagementFabricManagement/lib/models/channelList.js
  lib/services/engagementFabricManagement/lib/models/channelTypeDescription.js
  lib/services/engagementFabricManagement/lib/models/channelTypeDescriptionList.js
  lib/services/engagementFabricManagement/lib/models/checkNameAvailabilityParameter.js
  lib/services/engagementFabricManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/engagementFabricManagement/lib/models/index.d.ts
  lib/services/engagementFabricManagement/lib/models/index.js
  lib/services/engagementFabricManagement/lib/models/keyDescription.js
  lib/services/engagementFabricManagement/lib/models/keyDescriptionList.js
  lib/services/engagementFabricManagement/lib/models/operation.js
  lib/services/engagementFabricManagement/lib/models/operationDisplay.js
  lib/services/engagementFabricManagement/lib/models/operationList.js
  lib/services/engagementFabricManagement/lib/models/proxyOnlyResource.js
  lib/services/engagementFabricManagement/lib/models/regenerateKeyParameter.js
  lib/services/engagementFabricManagement/lib/models/resource.js
  lib/services/engagementFabricManagement/lib/models/sKU.js
  lib/services/engagementFabricManagement/lib/models/skuDescription.js
  lib/services/engagementFabricManagement/lib/models/skuDescriptionList.js
  lib/services/engagementFabricManagement/lib/models/skuLocationInfoItem.js
  lib/services/engagementFabricManagement/lib/models/trackedResource.js
  lib/services/engagementFabricManagement/lib/operations/accounts.js
  lib/services/engagementFabricManagement/lib/operations/channels.js
  lib/services/engagementFabricManagement/lib/operations/index.d.ts
  lib/services/engagementFabricManagement/lib/operations/index.js
  lib/services/engagementFabricManagement/lib/operations/operations.js
  lib/services/engagementFabricManagement/lib/operations/sKUs.js
  lib/services/engagementFabricManagement/package.json
Labels: RestPRMerged, in progress

#4115 [AutoPR cognitiveservices/data-plane/QnAMaker] Adding API For QnAMaker v4.0
  lib/services/cognitiveServices/qnamaker/LICENSE.txt
  lib/services/cognitiveServices/qnamaker/README.md
  lib/services/cognitiveServices/qnamaker/lib/models/alterationsDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/createKbDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/createKbInputDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/deleteKbContentsDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/endpointKeysDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/errorModel.js
  lib/services/cognitiveServices/qnamaker/lib/models/errorResponse.js
  lib/services/cognitiveServices/qnamaker/lib/models/errorResponseError.js
  lib/services/cognitiveServices/qnamaker/lib/models/fileDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/index.d.ts
  lib/services/cognitiveServices/qnamaker/lib/models/index.js
  lib/services/cognitiveServices/qnamaker/lib/models/innerErrorModel.js
  lib/services/cognitiveServices/qnamaker/lib/models/knowledgebaseDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/knowledgebasesDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/metadataDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/operation.js
  lib/services/cognitiveServices/qnamaker/lib/models/qnADTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/qnADocumentsDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/replaceKbDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateKbContentsDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateKbOperationDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateKbOperationDTOAdd.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateKbOperationDTODelete.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateKbOperationDTOUpdate.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateMetadataDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateQnaDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateQnaDTOMetadata.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateQnaDTOQuestions.js
  lib/services/cognitiveServices/qnamaker/lib/models/updateQuestionsDTO.js
  lib/services/cognitiveServices/qnamaker/lib/models/wordAlterationsDTO.js
  lib/services/cognitiveServices/qnamaker/lib/operations/alterations.js
  lib/services/cognitiveServices/qnamaker/lib/operations/endpoint.js
  lib/services/cognitiveServices/qnamaker/lib/operations/index.d.ts
  lib/services/cognitiveServices/qnamaker/lib/operations/index.js
  lib/services/cognitiveServices/qnamaker/lib/operations/knowledgebase.js
  lib/services/cognitiveServices/qnamaker/lib/operations/operations.js
  lib/services/cognitiveServices/qnamaker/lib/qnAMakerClient.d.ts
  lib/services/cognitiveServices/qnamaker/lib/qnAMakerClient.js
  lib/services/cognitiveServices/qnamaker/package.json
Labels: RestPRMerged, in progress

#4140 [AutoPR cdn/resource-manager] typo: cdn/resource-manager/Microsoft.Cdn/cdn.json
  lib/services/cdnManagement/lib/models/cacheExpirationActionParameters.js
  lib/services/cdnManagement/lib/models/checkNameAvailabilityInput.js
  lib/services/cdnManagement/lib/models/checkNameAvailabilityOutput.js
  lib/services/cdnManagement/lib/models/cidrIpAddress.js
  lib/services/cdnManagement/lib/models/customDomain.js
  lib/services/cdnManagement/lib/models/customDomainListResult.js
  lib/services/cdnManagement/lib/models/customDomainParameters.js
  lib/services/cdnManagement/lib/models/deepCreatedOrigin.js
  lib/services/cdnManagement/lib/models/deliveryRule.js
  lib/services/cdnManagement/lib/models/deliveryRuleAction.js
  lib/services/cdnManagement/lib/models/deliveryRuleCacheExpirationAction.js
  lib/services/cdnManagement/lib/models/deliveryRuleCondition.js
  lib/services/cdnManagement/lib/models/deliveryRuleUrlFileExtensionCondition.js
  lib/services/cdnManagement/lib/models/deliveryRuleUrlPathCondition.js
  lib/services/cdnManagement/lib/models/edgeNode.js
  lib/services/cdnManagement/lib/models/edgenodeResult.js
  lib/services/cdnManagement/lib/models/endpoint.js
  lib/services/cdnManagement/lib/models/endpointListResult.js
  lib/services/cdnManagement/lib/models/endpointPropertiesUpdateParametersDeliveryPolicy.js
  lib/services/cdnManagement/lib/models/endpointUpdateParameters.js
  lib/services/cdnManagement/lib/models/errorResponse.js
  lib/services/cdnManagement/lib/models/geoFilter.js
  lib/services/cdnManagement/lib/models/index.d.ts
  lib/services/cdnManagement/lib/models/ipAddressGroup.js
  lib/services/cdnManagement/lib/models/loadParameters.js
  lib/services/cdnManagement/lib/models/operation.js
  lib/services/cdnManagement/lib/models/operationDisplay.js
  lib/services/cdnManagement/lib/models/operationsListResult.js
  lib/services/cdnManagement/lib/models/origin.js
  lib/services/cdnManagement/lib/models/originListResult.js
  lib/services/cdnManagement/lib/models/originUpdateParameters.js
  lib/services/cdnManagement/lib/models/profile.js
  lib/services/cdnManagement/lib/models/profileListResult.js
  lib/services/cdnManagement/lib/models/profileUpdateParameters.js
  lib/services/cdnManagement/lib/models/purgeParameters.js
  lib/services/cdnManagement/lib/models/resource.js
  lib/services/cdnManagement/lib/models/resourceUsage.js
  lib/services/cdnManagement/lib/models/resourceUsageListResult.js
  lib/services/cdnManagement/lib/models/sku.js
  lib/services/cdnManagement/lib/models/ssoUri.js
  lib/services/cdnManagement/lib/models/supportedOptimizationTypesListResult.js
  lib/services/cdnManagement/lib/models/trackedResource.js
  lib/services/cdnManagement/lib/models/urlFileExtensionConditionParameters.js
  lib/services/cdnManagement/lib/models/urlPathConditionParameters.js
  lib/services/cdnManagement/lib/models/validateCustomDomainInput.js
  lib/services/cdnManagement/lib/models/validateCustomDomainOutput.js
  lib/services/cdnManagement/lib/models/validateProbeInput.js
  lib/services/cdnManagement/lib/models/validateProbeOutput.js
  lib/services/cdnManagement/lib/operations/customDomains.js
  lib/services/cdnManagement/lib/operations/endpoints.js
  lib/services/cdnManagement/lib/operations/index.d.ts
  lib/services/cdnManagement/lib/operations/profiles.js
  lib/services/cdnManagement/package.json
Labels: RestPRMerged, in progress

#4139 [AutoPR cosmos-db/resource-manager] typo: cosmos-db/resource-manager/Microsoft.DocumentDB/cosmos-db.json
  lib/services/cosmosdbManagement/README.md
  lib/services/cosmosdbManagement/lib/models/capability.js
  lib/services/cosmosdbManagement/lib/models/consistencyPolicy.js
  lib/services/cosmosdbManagement/lib/models/databaseAccount.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountConnectionString.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountCreateUpdateParameters.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountListConnectionStringsResult.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountListKeysResult.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountListReadOnlyKeysResult.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountPatchParameters.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountRegenerateKeyParameters.js
  lib/services/cosmosdbManagement/lib/models/errorResponse.js
  lib/services/cosmosdbManagement/lib/models/failoverPolicies.js
  lib/services/cosmosdbManagement/lib/models/failoverPolicy.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/location.js
  lib/services/cosmosdbManagement/lib/models/metric.js
  lib/services/cosmosdbManagement/lib/models/metricAvailability.js
  lib/services/cosmosdbManagement/lib/models/metricDefinition.js
  lib/services/cosmosdbManagement/lib/models/metricName.js
  lib/services/cosmosdbManagement/lib/models/metricValue.js
  lib/services/cosmosdbManagement/lib/models/operation.js
  lib/services/cosmosdbManagement/lib/models/operationDisplay.js
  lib/services/cosmosdbManagement/lib/models/operationListResult.js
  lib/services/cosmosdbManagement/lib/models/partitionMetric.js
  lib/services/cosmosdbManagement/lib/models/partitionUsage.js
  lib/services/cosmosdbManagement/lib/models/percentileMetric.js
  lib/services/cosmosdbManagement/lib/models/percentileMetricValue.js
  lib/services/cosmosdbManagement/lib/models/regionForOnlineOffline.js
  lib/services/cosmosdbManagement/lib/models/resource.js
  lib/services/cosmosdbManagement/lib/models/usage.js
  lib/services/cosmosdbManagement/lib/models/virtualNetworkRule.js
  lib/services/cosmosdbManagement/lib/operations/collection.js
  lib/services/cosmosdbManagement/lib/operations/database.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
  lib/services/cosmosdbManagement/package.json
Labels: RestPRMerged, in progress

#4148 [AutoPR authorization/resource-manager] Grlin/adding principal typeto ra
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/roleAssignment.js
Labels: RestPRMerged, in progress

#4128 Regenerate azure-arm-resource and bump the SwaggerToSDK generator ver…
  lib/services/resourceManagement/lib/models/appliance.js
  lib/services/resourceManagement/lib/models/appliancePatchable.js
  lib/services/resourceManagement/lib/resource/models/genericResource.js
  lib/services/resourceManagement/package.json
  swagger_to_sdk_config.json
Labels: Started-Sprint-127, Unplanned-Sprint-127, customer-reported, in progress

#4133 [AutoPR network/resource-manager] Application gateway Identity and Keyvault support
  lib/services/networkManagement2/lib/models/applicationGateway.js
  lib/services/networkManagement2/lib/models/applicationGatewaySslCertificate.js
  lib/services/networkManagement2/lib/models/applicationGatewayTrustedRootCertificate.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/managedServiceIdentity.js
  lib/services/networkManagement2/lib/models/managedServiceIdentityUserAssignedIdentitiesValue.js
  lib/services/networkManagement2/lib/operations/applicationGateways.js
  lib/services/networkManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4137 [AutoPR apimanagement/resource-manager] typo: Fix apimanagement/resource-manager/Microsoft.ApiManagement/apimbackends.json
  lib/services/apimanagement/lib/models/backendBaseParameters.js
  lib/services/apimanagement/lib/models/backendContract.js
  lib/services/apimanagement/lib/models/backendProperties.js
  lib/services/apimanagement/lib/models/backendServiceFabricClusterProperties.js
  lib/services/apimanagement/lib/models/backendUpdateParameters.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/operations/backend.js
  lib/services/apimanagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4160 [AutoPR storage/resource-manager] Adds canFailover boolean flag under storage account's GeoReplicationS…
  lib/services/storageManagement2/lib/models/accountSasParameters.js
  lib/services/storageManagement2/lib/models/azureEntityResource.js
  lib/services/storageManagement2/lib/models/blobContainer.js
  lib/services/storageManagement2/lib/models/blobServiceProperties.js
  lib/services/storageManagement2/lib/models/checkNameAvailabilityResult.js
  lib/services/storageManagement2/lib/models/corsRule.js
  lib/services/storageManagement2/lib/models/corsRules.js
  lib/services/storageManagement2/lib/models/customDomain.js
  lib/services/storageManagement2/lib/models/deleteRetentionPolicy.js
  lib/services/storageManagement2/lib/models/dimension.js
  lib/services/storageManagement2/lib/models/encryption.js
  lib/services/storageManagement2/lib/models/encryptionService.js
  lib/services/storageManagement2/lib/models/encryptionServices.js
  lib/services/storageManagement2/lib/models/endpoints.js
  lib/services/storageManagement2/lib/models/geoReplicationStats.js
  lib/services/storageManagement2/lib/models/iPRule.js
  lib/services/storageManagement2/lib/models/identity.js
  lib/services/storageManagement2/lib/models/immutabilityPolicy.js
  lib/services/storageManagement2/lib/models/immutabilityPolicyProperties.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/keyVaultProperties.js
  lib/services/storageManagement2/lib/models/legalHold.js
  lib/services/storageManagement2/lib/models/legalHoldProperties.js
  lib/services/storageManagement2/lib/models/listAccountSasResponse.js
  lib/services/storageManagement2/lib/models/listContainerItem.js
  lib/services/storageManagement2/lib/models/listContainerItems.js
  lib/services/storageManagement2/lib/models/listServiceSasResponse.js
  lib/services/storageManagement2/lib/models/managementPoliciesRulesSetParameter.js
  lib/services/storageManagement2/lib/models/metricSpecification.js
  lib/services/storageManagement2/lib/models/networkRuleSet.js
  lib/services/storageManagement2/lib/models/operation.js
  lib/services/storageManagement2/lib/models/operationDisplay.js
  lib/services/storageManagement2/lib/models/resource.js
  lib/services/storageManagement2/lib/models/restriction.js
  lib/services/storageManagement2/lib/models/sKUCapability.js
  lib/services/storageManagement2/lib/models/serviceSasParameters.js
  lib/services/storageManagement2/lib/models/serviceSpecification.js
  lib/services/storageManagement2/lib/models/sku.js
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCheckNameAvailabilityParameters.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountKey.js
  lib/services/storageManagement2/lib/models/storageAccountListKeysResult.js
  lib/services/storageManagement2/lib/models/storageAccountManagementPolicies.js
  lib/services/storageManagement2/lib/models/storageAccountRegenerateKeyParameters.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/models/tagProperty.js
  lib/services/storageManagement2/lib/models/trackedResource.js
  lib/services/storageManagement2/lib/models/updateHistoryProperty.js
  lib/services/storageManagement2/lib/models/usage.js
  lib/services/storageManagement2/lib/models/usageName.js
  lib/services/storageManagement2/lib/models/virtualNetworkRule.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
Labels: RestPRMerged, in progress

#4156 [AutoPR web/resource-manager] typo: web/resource-manager/Microsoft.Web/AppServiceEnvironments
  lib/services/websiteManagement2/lib/models/appServiceEnvironmentPatchResource.js
  lib/services/websiteManagement2/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4162 [AutoPR cognitiveservices/data-plane/TextAnalytics] Change default generation to TextAnalytics 2.1
  lib/services/cognitiveServicesTextAnalytics/LICENSE.txt
  lib/services/cognitiveServicesTextAnalytics/lib/models/entitiesBatchResultItemV2dot1.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/entitiesBatchResultV2dot1.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/entityRecordV2dot1.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/index.d.ts
  lib/services/cognitiveServicesTextAnalytics/lib/models/index.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/matchRecordV2dot1.js
  lib/services/cognitiveServicesTextAnalytics/lib/textAnalyticsClient.d.ts
  lib/services/cognitiveServicesTextAnalytics/lib/textAnalyticsClient.js
Labels: RestPRMerged, in progress

#4157 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric/servicefabric
  lib/services/serviceFabric/lib/models/applicationHealthPolicy.js
  lib/services/serviceFabric/lib/models/applicationHealthPolicyMapItem.js
  lib/services/serviceFabric/lib/models/applicationUpgradeDescription.js
  lib/services/serviceFabric/lib/models/applicationUpgradeProgressInfo.js
  lib/services/serviceFabric/lib/models/applicationUpgradeUpdateDescription.js
  lib/services/serviceFabric/lib/models/composeDeploymentUpgradeDescription.js
  lib/services/serviceFabric/lib/models/composeDeploymentUpgradeProgressInfo.js
  lib/services/serviceFabric/lib/models/index.d.ts
  lib/services/serviceFabric/lib/models/serviceTypeHealthPolicy.js
  lib/services/serviceFabric/lib/models/serviceTypeHealthPolicyMapItem.js
  lib/services/serviceFabric/lib/serviceFabricClient.d.ts
  lib/services/serviceFabric/lib/serviceFabricClient.js
  lib/services/serviceFabric/package.json
Labels: RestPRMerged, in progress

#4182 [AutoPR applicationinsights/resource-manager] typo: applicationinsights/resource-manager/Microsoft.Insights/componentFeaturesAndPricing_API
  lib/services/applicationinsights/lib/models/applicationInsightsComponentAvailableFeatures.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentBillingFeatures.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentDataVolumeCap.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentFeature.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentFeatureCapabilities.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentFeatureCapability.js
  lib/services/applicationinsights/lib/models/componentPurgeBodyFilters.js
  lib/services/applicationinsights/lib/models/index.d.ts
  lib/services/applicationinsights/lib/operations/componentCurrentBillingFeatures.js
  lib/services/applicationinsights/lib/operations/componentFeatureCapabilities.js
  lib/services/applicationinsights/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4175 [AutoPR storage/resource-manager] typo: storage/resource-manager/Microsoft.Storage/storage
  lib/services/storageManagement2/lib/models/dimension.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/listServiceSasResponse.js
  lib/services/storageManagement2/lib/models/sKUCapability.js
  lib/services/storageManagement2/lib/models/serviceSasParameters.js
  lib/services/storageManagement2/lib/models/sku.js
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCheckNameAvailabilityParameters.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountRegenerateKeyParameters.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
Labels: RestPRMerged, in progress

#4183 [AutoPR eventhub/resource-manager] typo: eventhub/resource-manager/Microsoft.EventHub/EventHub
  lib/services/eventHubManagement/README.md
  lib/services/eventHubManagement/lib/models/accessKeys.js
  lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
  lib/services/eventHubManagement/lib/models/armDisasterRecoveryListResult.js
  lib/services/eventHubManagement/lib/models/authorizationRule.js
  lib/services/eventHubManagement/lib/models/authorizationRuleListResult.js
  lib/services/eventHubManagement/lib/models/captureDescription.js
  lib/services/eventHubManagement/lib/models/checkNameAvailabilityParameter.js
  lib/services/eventHubManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/eventHubManagement/lib/models/consumerGroup.js
  lib/services/eventHubManagement/lib/models/consumerGroupListResult.js
  lib/services/eventHubManagement/lib/models/destination.js
  lib/services/eventHubManagement/lib/models/eHNamespace.js
  lib/services/eventHubManagement/lib/models/eHNamespaceListResult.js
  lib/services/eventHubManagement/lib/models/errorResponse.js
  lib/services/eventHubManagement/lib/models/eventHubListResult.js
  lib/services/eventHubManagement/lib/models/eventhub.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/messagingPlan.js
  lib/services/eventHubManagement/lib/models/messagingRegions.js
  lib/services/eventHubManagement/lib/models/messagingRegionsListResult.js
  lib/services/eventHubManagement/lib/models/messagingRegionsProperties.js
  lib/services/eventHubManagement/lib/models/operation.js
  lib/services/eventHubManagement/lib/models/operationDisplay.js
  lib/services/eventHubManagement/lib/models/operationListResult.js
  lib/services/eventHubManagement/lib/models/regenerateAccessKeyParameters.js
  lib/services/eventHubManagement/lib/models/resource.js
  lib/services/eventHubManagement/lib/models/sku.js
  lib/services/eventHubManagement/lib/models/trackedResource.js
  lib/services/eventHubManagement/lib/operations/consumerGroups.js
  lib/services/eventHubManagement/lib/operations/disasterRecoveryConfigs.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
  lib/services/eventHubManagement/package.json
Labels: RestPRMerged, in progress

#4130 [AutoPR resources/resource-manager] Add type for DeploymentExtend and ResourceGroup
  lib/services/resourceManagement/lib/resource/models/deploymentExtended.js
  lib/services/resourceManagement/lib/resource/models/index.d.ts
  lib/services/resourceManagement/lib/resource/models/resourceGroup.js
Labels: RestPRMerged, in progress

#4197 Update azure-cognitiveservices-vision
  lib/services/cognitiveServicesVision/package.json
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#4198 [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory
  lib/services/datafactoryManagement/lib/models/blobEventsTrigger.js
  lib/services/datafactoryManagement/lib/models/blobTrigger.js
  lib/services/datafactoryManagement/lib/models/concurObjectDataset.js
  lib/services/datafactoryManagement/lib/models/concurSource.js
  lib/services/datafactoryManagement/lib/models/copyActivity.js
  lib/services/datafactoryManagement/lib/models/factory.js
  lib/services/datafactoryManagement/lib/models/factoryRepoConfiguration.js
  lib/services/datafactoryManagement/lib/models/factoryRepoUpdate.js
  lib/services/datafactoryManagement/lib/models/hubspotObjectDataset.js
  lib/services/datafactoryManagement/lib/models/hubspotSource.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/jiraObjectDataset.js
  lib/services/datafactoryManagement/lib/models/jiraSource.js
  lib/services/datafactoryManagement/lib/models/paypalObjectDataset.js
  lib/services/datafactoryManagement/lib/models/paypalSource.js
  lib/services/datafactoryManagement/lib/models/recurrenceScheduleOccurrence.js
  lib/services/datafactoryManagement/lib/models/shopifyObjectDataset.js
  lib/services/datafactoryManagement/lib/models/shopifySource.js
  lib/services/datafactoryManagement/lib/models/squareObjectDataset.js
  lib/services/datafactoryManagement/lib/models/squareSource.js
  lib/services/datafactoryManagement/lib/models/userProperty.js
  lib/services/datafactoryManagement/lib/models/xeroObjectDataset.js
  lib/services/datafactoryManagement/lib/models/xeroSource.js
  lib/services/datafactoryManagement/lib/operations/factories.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/integrationRuntimes.js
  lib/services/datafactoryManagement/lib/operations/pipelines.js
Labels: RestPRMerged, in progress

#4136 [AutoPR graphrbac/data-plane] add customKeyIdentifier to password credential
  lib/services/graphManagement/lib/models/aDGroup.js
  lib/services/graphManagement/lib/models/addOwnerParameters.js
  lib/services/graphManagement/lib/models/appRole.js
  lib/services/graphManagement/lib/models/application.js
  lib/services/graphManagement/lib/models/applicationCreateParameters.js
  lib/services/graphManagement/lib/models/applicationListResult.js
  lib/services/graphManagement/lib/models/applicationUpdateParameters.js
  lib/services/graphManagement/lib/models/checkGroupMembershipParameters.js
  lib/services/graphManagement/lib/models/checkGroupMembershipResult.js
  lib/services/graphManagement/lib/models/directoryObject.js
  lib/services/graphManagement/lib/models/directoryObjectListResult.js
  lib/services/graphManagement/lib/models/domain.js
  lib/services/graphManagement/lib/models/getObjectsParameters.js
  lib/services/graphManagement/lib/models/graphError.js
  lib/services/graphManagement/lib/models/groupAddMemberParameters.js
  lib/services/graphManagement/lib/models/groupCreateParameters.js
  lib/services/graphManagement/lib/models/groupGetMemberGroupsParameters.js
  lib/services/graphManagement/lib/models/groupListResult.js
  lib/services/graphManagement/lib/models/index.d.ts
  lib/services/graphManagement/lib/models/keyCredential.js
  lib/services/graphManagement/lib/models/keyCredentialsUpdateParameters.js
  lib/services/graphManagement/lib/models/passwordCredential.js
  lib/services/graphManagement/lib/models/passwordCredentialsUpdateParameters.js
  lib/services/graphManagement/lib/models/passwordProfile.js
  lib/services/graphManagement/lib/models/permissions.js
  lib/services/graphManagement/lib/models/requiredResourceAccess.js
  lib/services/graphManagement/lib/models/resourceAccess.js
  lib/services/graphManagement/lib/models/servicePrincipal.js
  lib/services/graphManagement/lib/models/servicePrincipalCreateParameters.js
  lib/services/graphManagement/lib/models/servicePrincipalListResult.js
  lib/services/graphManagement/lib/models/servicePrincipalUpdateParameters.js
  lib/services/graphManagement/lib/models/signInName.js
  lib/services/graphManagement/lib/models/user.js
  lib/services/graphManagement/lib/models/userBase.js
  lib/services/graphManagement/lib/models/userCreateParameters.js
  lib/services/graphManagement/lib/models/userGetMemberGroupsParameters.js
  lib/services/graphManagement/lib/models/userListResult.js
  lib/services/graphManagement/lib/models/userUpdateParameters.js
  lib/services/graphManagement/package.json
Labels: RestPRMerged, in progress

#4196 [AutoPR storagesync/resource-manager] Microsoft.StorageSync - Fix Issue 4559 and other known problems with preview version
  lib/services/storagesyncManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4199 [AutoPR analysisservices/resource-manager] typo: analysisservices/resource-manager/Microsoft.AnalysisServices
  lib/services/analysisServices/lib/models/analysisServicesServer.js
  lib/services/analysisServices/lib/models/analysisServicesServerUpdateParameters.js
  lib/services/analysisServices/lib/models/checkServerNameAvailabilityParameters.js
  lib/services/analysisServices/lib/models/checkServerNameAvailabilityResult.js
  lib/services/analysisServices/lib/models/errorResponse.js
  lib/services/analysisServices/lib/models/gatewayDetails.js
  lib/services/analysisServices/lib/models/gatewayError.js
  lib/services/analysisServices/lib/models/gatewayListStatusError.js
  lib/services/analysisServices/lib/models/gatewayListStatusLive.js
  lib/services/analysisServices/lib/models/iPv4FirewallRule.js
  lib/services/analysisServices/lib/models/iPv4FirewallSettings.js
  lib/services/analysisServices/lib/models/index.d.ts
  lib/services/analysisServices/lib/models/operation.js
  lib/services/analysisServices/lib/models/operationDisplay.js
  lib/services/analysisServices/lib/models/operationListResult.js
  lib/services/analysisServices/lib/models/operationStatus.js
  lib/services/analysisServices/lib/models/resource.js
  lib/services/analysisServices/lib/models/resourceSku.js
  lib/services/analysisServices/lib/models/serverAdministrators.js
  lib/services/analysisServices/lib/models/skuDetailsForExistingResource.js
  lib/services/analysisServices/lib/models/skuEnumerationForExistingResourceResult.js
  lib/services/analysisServices/lib/models/skuEnumerationForNewResourceResult.js
  lib/services/analysisServices/lib/operations/index.d.ts
  lib/services/analysisServices/lib/operations/servers.js
  lib/services/analysisServices/package.json
Labels: RestPRMerged, in progress

#4207 Generate azure-arm-kusto
  lib/services/kustoManagement/LICENSE.txt
  lib/services/kustoManagement/README.md
  lib/services/kustoManagement/lib/kustoManagementClient.d.ts
  lib/services/kustoManagement/lib/kustoManagementClient.js
  lib/services/kustoManagement/lib/models/azureCapacity.js
  lib/services/kustoManagement/lib/models/azureEntityResource.js
  lib/services/kustoManagement/lib/models/azureResourceSku.js
  lib/services/kustoManagement/lib/models/azureSku.js
  lib/services/kustoManagement/lib/models/checkNameResult.js
  lib/services/kustoManagement/lib/models/cluster.js
  lib/services/kustoManagement/lib/models/clusterCheckNameRequest.js
  lib/services/kustoManagement/lib/models/clusterListResult.js
  lib/services/kustoManagement/lib/models/clusterUpdate.js
  lib/services/kustoManagement/lib/models/database.js
  lib/services/kustoManagement/lib/models/databaseCheckNameRequest.js
  lib/services/kustoManagement/lib/models/databaseListResult.js
  lib/services/kustoManagement/lib/models/databasePrincipal.js
  lib/services/kustoManagement/lib/models/databasePrincipalListRequest.js
  lib/services/kustoManagement/lib/models/databasePrincipalListResult.js
  lib/services/kustoManagement/lib/models/databaseStatistics.js
  lib/services/kustoManagement/lib/models/databaseUpdate.js
  lib/services/kustoManagement/lib/models/eventHubConnection.js
  lib/services/kustoManagement/lib/models/eventHubConnectionListResult.js
  lib/services/kustoManagement/lib/models/eventHubConnectionUpdate.js
  lib/services/kustoManagement/lib/models/eventHubConnectionValidation.js
  lib/services/kustoManagement/lib/models/eventHubConnectionValidationListResult.js
  lib/services/kustoManagement/lib/models/eventHubConnectionValidationResult.js
  lib/services/kustoManagement/lib/models/index.d.ts
  lib/services/kustoManagement/lib/models/index.js
  lib/services/kustoManagement/lib/models/listResourceSkusResult.js
  lib/services/kustoManagement/lib/models/listSkusResult.js
  lib/services/kustoManagement/lib/models/operation.js
  lib/services/kustoManagement/lib/models/operationDisplay.js
  lib/services/kustoManagement/lib/models/operationListResult.js
  lib/services/kustoManagement/lib/models/proxyResource.js
  lib/services/kustoManagement/lib/models/resource.js
  lib/services/kustoManagement/lib/models/trackedResource.js
  lib/services/kustoManagement/lib/models/trustedExternalTenant.js
  lib/services/kustoManagement/lib/operations/clusters.js
  lib/services/kustoManagement/lib/operations/databases.js
  lib/services/kustoManagement/lib/operations/eventHubConnections.js
  lib/services/kustoManagement/lib/operations/index.d.ts
  lib/services/kustoManagement/lib/operations/index.js
  lib/services/kustoManagement/lib/operations/operations.js
  lib/services/kustoManagement/package.json
Labels: Planned-Sprint-127, Started-Sprint-127, in progress

#4118 [AutoPR msi/resource-manager] Update manage service identity api version
  lib/services/msiManagement/LICENSE.txt
  lib/services/msiManagement/README.md
  lib/services/msiManagement/lib/managedServiceIdentityClient.d.ts
  lib/services/msiManagement/lib/managedServiceIdentityClient.js
  lib/services/msiManagement/lib/models/identity.js
  lib/services/msiManagement/lib/models/index.d.ts
  lib/services/msiManagement/lib/models/operation.js
  lib/services/msiManagement/lib/models/operationDisplay.js
  lib/services/msiManagement/lib/models/operationListResult.js
  lib/services/msiManagement/lib/models/userAssignedIdentitiesListResult.js
  lib/services/msiManagement/package.json
Labels: RestPRMerged, in progress

#4208 Add README.md and regenerate azure-arm-network
  lib/services/networkManagement2/README.md
  lib/services/networkManagement2/lib/models/httpConfiguration.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/trafficQuery.js
  lib/services/networkManagement2/lib/operations/virtualWANs.js
  lib/services/networkManagement2/package.json
Labels: Started-Sprint-127, Unplanned-Sprint-127, in progress

#4214 [AutoPR resources/resource-manager] Fix the ARM R2062 error for Microsoft.Resources
  lib/services/resourceManagement/lib/resource/models/index.d.ts
  lib/services/resourceManagement/lib/resource/models/tagDetails.js
Labels: RestPRMerged, in progress

#4213 [AutoPR timeseriesinsights/resource-manager] Add a new preview api-version for Time Series Insights
  lib/services/timeseriesinsightsManagement/LICENSE.txt
  lib/services/timeseriesinsightsManagement/README.md
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyResource.js
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/azureEventSourceProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/createOrUpdateTrackedResourceProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentResource.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentStateDetails.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentStatus.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceCommonProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceResource.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceCommonProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceMutableProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceResource.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/index.d.ts
  lib/services/timeseriesinsightsManagement/lib/models/ingressEnvironmentStatus.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceCommonProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceResource.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/localTimestamp.js
  lib/services/timeseriesinsightsManagement/lib/models/localTimestampTimeZoneOffset.js
  lib/services/timeseriesinsightsManagement/lib/models/operation.js
  lib/services/timeseriesinsightsManagement/lib/models/operationDisplay.js
  lib/services/timeseriesinsightsManagement/lib/models/operationListResult.js
  lib/services/timeseriesinsightsManagement/lib/models/partitionKeyProperty.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetKeyProperty.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetResource.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/resource.js
  lib/services/timeseriesinsightsManagement/lib/models/resourceProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/sku.js
  lib/services/timeseriesinsightsManagement/lib/models/trackedResource.js
  lib/services/timeseriesinsightsManagement/package.json
Labels: RestPRMerged, in progress

#4220 [AutoPR resources/resource-manager] Revert "Fix the ARM R2062 error for Microsoft.Resources"
  lib/services/resourceManagement/lib/resource/models/index.d.ts
  lib/services/resourceManagement/lib/resource/models/tagDetails.js
Labels: RestPRMerged

#4229 [AutoPR cdn/resource-manager] typo: Microsoft.Cdn
  lib/services/cdnManagement/lib/models/cidrIpAddress.js
  lib/services/cdnManagement/lib/models/customDomain.js
  lib/services/cdnManagement/lib/models/endpoint.js
  lib/services/cdnManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4135 [AutoPR containerregistry/resource-manager] [ACR] Add empty resource group name validation, minor cleanup
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/networkRuleSet.js
  lib/services/containerRegistryManagement/lib/models/registry.js
  lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/virtualNetworkRule.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/registries.js
  lib/services/containerRegistryManagement/lib/operations/replications.js
  lib/services/containerRegistryManagement/lib/operations/runs.js
  lib/services/containerRegistryManagement/lib/operations/tasks.js
  lib/services/containerRegistryManagement/lib/operations/webhooks.js
Labels: RestPRMerged, in progress

#4233 [AutoPR apimanagement/resource-manager] Added example for template params
  lib/services/apimanagement/lib/models/apiManagementServiceBaseProperties.js
  lib/services/apimanagement/lib/models/apiManagementServiceResource.js
  lib/services/apimanagement/lib/models/apiManagementServiceUpdateParameters.js
  lib/services/apimanagement/lib/models/backendReconnectContract.js
  lib/services/apimanagement/lib/models/certificateConfiguration.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/reportRecordContract.js
  lib/services/apimanagement/lib/models/requestReportRecordContract.js
  lib/services/apimanagement/lib/models/subscriptionCreateParameters.js
  lib/services/apimanagement/lib/operations/apiDiagnosticLogger.js
  lib/services/apimanagement/lib/operations/apiIssue.js
  lib/services/apimanagement/lib/operations/apiIssueAttachment.js
  lib/services/apimanagement/lib/operations/apiIssueComment.js
  lib/services/apimanagement/lib/operations/apiManagementService.js
  lib/services/apimanagement/lib/operations/backend.js
  lib/services/apimanagement/lib/operations/diagnosticLogger.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/property.js
  lib/services/apimanagement/lib/operations/reports.js
  lib/services/apimanagement/lib/operations/subscription.js
  lib/services/apimanagement/lib/operations/tagDescription.js
Labels: RestPRMerged

#4226 Azure Pipeline for KeyVault
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
  .gitignore
  package.json
Labels: in progress

#4217 [AutoPR automation/resource-manager] typo: Microsoft.Automation
  lib/services/automationManagement/lib/models/agentRegistration.js
  lib/services/automationManagement/lib/models/dscConfigurationParameter.js
  lib/services/automationManagement/lib/models/dscNode.js
  lib/services/automationManagement/lib/models/dscNodeConfiguration.js
  lib/services/automationManagement/lib/models/dscNodeUpdateParameters.js
  lib/services/automationManagement/lib/models/dscNodeUpdateParametersProperties.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/runAsCredentialAssociationProperty.js
  lib/services/automationManagement/lib/models/runbookCreateOrUpdateDraftProperties.js
  lib/services/automationManagement/lib/models/runbookDraftUndoEditResult.js
  lib/services/automationManagement/lib/models/runbookParameter.js
  lib/services/automationManagement/lib/models/softwareUpdateConfigurationMachineRun.js
  lib/services/automationManagement/lib/models/softwareUpdateConfigurationRun.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
  lib/services/automationManagement/lib/models/updateConfiguration.js
  lib/services/automationManagement/lib/models/variable.js
  lib/services/automationManagement/lib/operations/connectionTypeOperations.js
  lib/services/automationManagement/lib/operations/dscNodeOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress
