Repository Azure/azure-sdk-for-node, pull requests merged in 2018-03, with the labels that each got.

#2449 Rename keyvault type def file to match case
  lib/services/keyVault/lib/keyVault.d.ts
  lib/services/keyVault/package.json
Labels: KeyVault, in progress

#2448 keyvault type definition file changes to resolve problems with typescript
  lib/services/keyVault/lib/keyVault.d.ts
  lib/services/keyVault/package.json
Labels: KeyVault, in progress

#2453 ensure that the provided object is a Duration like object.
  runtime/ms-rest/Changelog.md
  runtime/ms-rest/lib/serialization.js
  runtime/ms-rest/package-lock.json
  runtime/ms-rest/package.json
  runtime/ms-rest/test/serializationTests.js
Labels: in progress

#2454 multiple auth related changes
  package-lock.json
  runtime/ms-rest-azure/Changelog.md
  runtime/ms-rest-azure/index.d.ts
  runtime/ms-rest-azure/lib/credentials/deviceTokenCredentials.js
  runtime/ms-rest-azure/lib/credentials/msiTokenCredentials.js
  runtime/ms-rest-azure/lib/login.js
  runtime/ms-rest-azure/package-lock.json
  runtime/ms-rest-azure/package.json
Labels: in progress

#2463 Use nodejs.output-folder autorest argument
  gulpfile.js
Labels: in progress

#2467 Add Azure Stack resource management client from latest swagger
  codegen_mappings.json
  gulpfile.js
  lib/services/azurestackManagement/README.md
  lib/services/azurestackManagement/lib/azureStackManagementClient.d.ts
  lib/services/azurestackManagement/lib/azureStackManagementClient.js
  lib/services/azurestackManagement/lib/models/activationKeyResult.js
  lib/services/azurestackManagement/lib/models/customerSubscription.js
  lib/services/azurestackManagement/lib/models/customerSubscriptionList.js
  lib/services/azurestackManagement/lib/models/dataDiskImage.js
  lib/services/azurestackManagement/lib/models/display.js
  lib/services/azurestackManagement/lib/models/extendedProduct.js
  lib/services/azurestackManagement/lib/models/iconUris.js
  lib/services/azurestackManagement/lib/models/index.d.ts
  lib/services/azurestackManagement/lib/models/index.js
  lib/services/azurestackManagement/lib/models/operation.js
  lib/services/azurestackManagement/lib/models/operationList.js
  lib/services/azurestackManagement/lib/models/osDiskImage.js
  lib/services/azurestackManagement/lib/models/product.js
  lib/services/azurestackManagement/lib/models/productLink.js
  lib/services/azurestackManagement/lib/models/productList.js
  lib/services/azurestackManagement/lib/models/productProperties.js
  lib/services/azurestackManagement/lib/models/registration.js
  lib/services/azurestackManagement/lib/models/registrationList.js
  lib/services/azurestackManagement/lib/models/registrationParameter.js
  lib/services/azurestackManagement/lib/models/resource.js
  lib/services/azurestackManagement/lib/models/virtualMachineExtensionProductProperties.js
  lib/services/azurestackManagement/lib/models/virtualMachineProductProperties.js
  lib/services/azurestackManagement/lib/operations/customerSubscriptions.js
  lib/services/azurestackManagement/lib/operations/index.d.ts
  lib/services/azurestackManagement/lib/operations/index.js
  lib/services/azurestackManagement/lib/operations/operations.js
  lib/services/azurestackManagement/lib/operations/products.js
  lib/services/azurestackManagement/lib/operations/registrations.js
  lib/services/azurestackManagement/package.json
Labels: in progress

#2469 [AutoPR cdn/resource-manager] Add example for checkNameAvailability
  lib/services/cdnManagement/lib/cdnManagementClient.d.ts
  lib/services/cdnManagement/lib/cdnManagementClient.js
Labels: RestPRMerged, in progress

#2481 [AutoPR mysql/resource-manager] Fix swagger->sdk tag for go
  lib/services/mysqlManagement/lib/models/index.d.ts
  lib/services/mysqlManagement/lib/models/index.js
  lib/services/mysqlManagement/lib/models/logFile.js
  lib/services/mysqlManagement/lib/models/nameAvailabilityRequest.js
  lib/services/mysqlManagement/lib/models/performanceTierProperties.js
  lib/services/mysqlManagement/lib/models/performanceTierServiceLevelObjectives.js
  lib/services/mysqlManagement/lib/models/server.js
  lib/services/mysqlManagement/lib/models/serverForCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForDefaultCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForRestore.js
  lib/services/mysqlManagement/lib/models/serverUpdateParameters.js
  lib/services/mysqlManagement/lib/models/sku.js
  lib/services/mysqlManagement/lib/models/storageProfile.js
  lib/services/mysqlManagement/lib/mySQLManagementClient.d.ts
  lib/services/mysqlManagement/lib/mySQLManagementClient.js
  lib/services/mysqlManagement/lib/operations/checkNameAvailability.js
  lib/services/mysqlManagement/lib/operations/index.d.ts
  lib/services/mysqlManagement/lib/operations/index.js
  lib/services/mysqlManagement/lib/operations/servers.js
Labels: RestPRMerged, in progress

#2470 [AutoPR] cdn/resource-manager
  lib/services/cdnManagement/lib/cdnManagementClient.d.ts
  lib/services/cdnManagement/lib/cdnManagementClient.js
Labels: ServicePR, in progress

#2491 Ignore databricks resource provider since it doesn't generate an SDK
  gulpfile.js
Labels: in progress

#2504 [AutoPR apimanagement/resource-manager] Fix issue with 2017-03-01 version of api-management
  lib/services/apimanagement/lib/apiManagementClient.d.ts
  lib/services/apimanagement/lib/apiManagementClient.js
  lib/services/apimanagement/lib/models/requestReportCollection.js
Labels: RestPRMerged, in progress

#2503 Add azure-arm-datacatalog
  codegen_mappings.json
  gulpfile.js
  lib/services/datacatalogManagement/lib/README.md
  lib/services/datacatalogManagement/lib/dataCatalogRestClient.d.ts
  lib/services/datacatalogManagement/lib/dataCatalogRestClient.js
  lib/services/datacatalogManagement/lib/models/aDCCatalog.js
  lib/services/datacatalogManagement/lib/models/aDCCatalogsListResult.js
  lib/services/datacatalogManagement/lib/models/index.d.ts
  lib/services/datacatalogManagement/lib/models/index.js
  lib/services/datacatalogManagement/lib/models/operationDisplayInfo.js
  lib/services/datacatalogManagement/lib/models/operationEntity.js
  lib/services/datacatalogManagement/lib/models/operationEntityListResult.js
  lib/services/datacatalogManagement/lib/models/principals.js
  lib/services/datacatalogManagement/lib/models/resource.js
  lib/services/datacatalogManagement/lib/operations/aDCCatalogs.js
  lib/services/datacatalogManagement/lib/operations/aDCOperations.js
  lib/services/datacatalogManagement/lib/operations/index.d.ts
  lib/services/datacatalogManagement/lib/operations/index.js
  lib/services/datacatalogManagement/lib/package.json
Labels: in progress

#2486 [AutoPR] cosmos-db/resource-manager
  lib/services/cosmosdbManagement/lib/cosmosDBManagementClient.d.ts
  lib/services/cosmosdbManagement/lib/cosmosDBManagementClient.js
  lib/services/cosmosdbManagement/lib/models/capability.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
Labels: ServicePR, in progress

#2508 Bump cosmosdbManagement to 1.1.1-preview
  lib/services/cosmosdbManagement/package.json
Labels: in progress

#2513 Add codegen_mappings schema file and small gulpfile tweak
  codegen_mappings.json
  codegen_mappings.schema.json
  gulpfile.js
Labels: in progress

#2468 update AKV dataplane
  lib/services/keyVault/lib/keyVaultClient.d.ts
  lib/services/keyVault/lib/keyVaultClient.js
  lib/services/keyVault/lib/models/backupCertificateResult.js
  lib/services/keyVault/lib/models/certificateBundle.js
  lib/services/keyVault/lib/models/certificateCreateParameters.js
  lib/services/keyVault/lib/models/certificateImportParameters.js
  lib/services/keyVault/lib/models/certificatePolicy.js
  lib/services/keyVault/lib/models/certificateRestoreParameters.js
  lib/services/keyVault/lib/models/certificateUpdateParameters.js
  lib/services/keyVault/lib/models/index.d.ts
  lib/services/keyVault/lib/models/index.js
  lib/services/keyVault/lib/models/x509CertificateProperties.js
  lib/services/keyVault/package.json
Labels: in progress

#2532 Update codegen and codegen_mappings to support generatePackageJson an…
  codegen_mappings.json
  codegen_mappings.schema.json
  gulpfile.js
Labels: in progress

#2507 [AutoPR servicebus/resource-manager] ServiceBus: added 'properties' to CorrelationFilter
  lib/services/serviceBusManagement2/lib/models/correlationFilter.js
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/rule.js
  lib/services/serviceBusManagement2/lib/models/sBQueue.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/queues.js
  lib/services/serviceBusManagement2/lib/operations/rules.js
  lib/services/serviceBusManagement2/lib/serviceBusManagementClient.d.ts
  lib/services/serviceBusManagement2/lib/serviceBusManagementClient.js
Labels: RestPRMerged, in progress

#2528 Add deviceprovisioningservices SDK
  codegen_mappings.json
  lib/services/deviceprovisioningservicesManagement/lib/README.md
  lib/services/deviceprovisioningservicesManagement/lib/iotDpsClient.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/iotDpsClient.js
  lib/services/deviceprovisioningservicesManagement/lib/models/asyncOperationResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateBodyDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateListDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateProperties.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateResponse.js
  lib/services/deviceprovisioningservicesManagement/lib/models/errorDetails.js
  lib/services/deviceprovisioningservicesManagement/lib/models/errorMesssage.js
  lib/services/deviceprovisioningservicesManagement/lib/models/index.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/models/index.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsPropertiesDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsSkuDefinition.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsSkuDefinitionListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsSkuInfo.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotHubDefinitionDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/nameAvailabilityInfo.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operation.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operationDisplay.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operationInputs.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operationListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/provisioningServiceDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/provisioningServiceDescriptionListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/resource.js
  lib/services/deviceprovisioningservicesManagement/lib/models/sharedAccessSignatureAuthorizationRuleAccessRightsDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/sharedAccessSignatureAuthorizationRuleListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/tagsResource.js
  lib/services/deviceprovisioningservicesManagement/lib/models/verificationCodeRequest.js
  lib/services/deviceprovisioningservicesManagement/lib/models/verificationCodeResponse.js
  lib/services/deviceprovisioningservicesManagement/lib/models/verificationCodeResponseProperties.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/dpsCertificate.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/dpsCertificates.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/index.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/operations/index.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/iotDpsResource.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/operations.js
  lib/services/deviceprovisioningservicesManagement/lib/package.json
Labels: in progress

#2535 [AutoPR automation/resource-manager] Remove automation parameters from client
  lib/services/automationManagement/lib/automationClient.d.ts
  lib/services/automationManagement/lib/automationClient.js
  lib/services/automationManagement/lib/operations/activityOperations.js
  lib/services/automationManagement/lib/operations/agentRegistrationInformation.js
  lib/services/automationManagement/lib/operations/certificateOperations.js
  lib/services/automationManagement/lib/operations/connectionOperations.js
  lib/services/automationManagement/lib/operations/connectionTypeOperations.js
  lib/services/automationManagement/lib/operations/credentialOperations.js
  lib/services/automationManagement/lib/operations/dscCompilationJobOperations.js
  lib/services/automationManagement/lib/operations/dscCompilationJobStream.js
  lib/services/automationManagement/lib/operations/dscConfigurationOperations.js
  lib/services/automationManagement/lib/operations/dscNodeConfigurationOperations.js
  lib/services/automationManagement/lib/operations/dscNodeOperations.js
  lib/services/automationManagement/lib/operations/fields.js
  lib/services/automationManagement/lib/operations/hybridRunbookWorkerGroupOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/jobOperations.js
  lib/services/automationManagement/lib/operations/jobScheduleOperations.js
  lib/services/automationManagement/lib/operations/jobStreamOperations.js
  lib/services/automationManagement/lib/operations/linkedWorkspaceOperations.js
  lib/services/automationManagement/lib/operations/moduleOperations.js
  lib/services/automationManagement/lib/operations/nodeReports.js
  lib/services/automationManagement/lib/operations/objectDataTypes.js
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
  lib/services/automationManagement/lib/operations/runbookOperations.js
  lib/services/automationManagement/lib/operations/scheduleOperations.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationMachineRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
  lib/services/automationManagement/lib/operations/sourceControlOperations.js
  lib/services/automationManagement/lib/operations/sourceControlSyncJobOperations.js
  lib/services/automationManagement/lib/operations/testJobOperations.js
  lib/services/automationManagement/lib/operations/testJobStreams.js
  lib/services/automationManagement/lib/operations/variableOperations.js
  lib/services/automationManagement/lib/operations/webhookOperations.js
Labels: RestPRMerged, in progress

#2539 Add iotspaces management library
  codegen_mappings.json
  lib/services/iotspacesManagement/lib/README.md
  lib/services/iotspacesManagement/lib/ioTSpacesClient.d.ts
  lib/services/iotspacesManagement/lib/ioTSpacesClient.js
  lib/services/iotspacesManagement/lib/models/errorDetails.js
  lib/services/iotspacesManagement/lib/models/index.d.ts
  lib/services/iotspacesManagement/lib/models/index.js
  lib/services/iotspacesManagement/lib/models/ioTSpacesDescription.js
  lib/services/iotspacesManagement/lib/models/ioTSpacesDescriptionListResult.js
  lib/services/iotspacesManagement/lib/models/ioTSpacesNameAvailabilityInfo.js
  lib/services/iotspacesManagement/lib/models/ioTSpacesPatchDescription.js
  lib/services/iotspacesManagement/lib/models/ioTSpacesProperties.js
  lib/services/iotspacesManagement/lib/models/ioTSpacesSkuInfo.js
  lib/services/iotspacesManagement/lib/models/operation.js
  lib/services/iotspacesManagement/lib/models/operationDisplay.js
  lib/services/iotspacesManagement/lib/models/operationInputs.js
  lib/services/iotspacesManagement/lib/models/operationListResult.js
  lib/services/iotspacesManagement/lib/models/resource.js
  lib/services/iotspacesManagement/lib/models/storageContainerProperties.js
  lib/services/iotspacesManagement/lib/operations/index.d.ts
  lib/services/iotspacesManagement/lib/operations/index.js
  lib/services/iotspacesManagement/lib/operations/ioTSpaces.js
  lib/services/iotspacesManagement/lib/operations/operations.js
  lib/services/iotspacesManagement/lib/package.json
Labels: in progress

#2546 Generate datacatalog, deviceprovisioningservices, and iotspaces
  codegen_mappings.json
  codegen_mappings.schema.json
  gulpfile.js
  lib/services/datacatalogManagement/lib/LICENSE.txt
  lib/services/datacatalogManagement/lib/README.md
  lib/services/datacatalogManagement/lib/package.json
  lib/services/deviceprovisioningservicesManagement/lib/LICENSE.txt
  lib/services/iotspacesManagement/lib/LICENSE.txt
Labels: in progress

#2538 Add hanaonazure management SDK
  codegen_mappings.json
  lib/services/hanaonazureManagement/lib/LICENSE.txt
  lib/services/hanaonazureManagement/lib/README.md
  lib/services/hanaonazureManagement/lib/hanaManagementClient.d.ts
  lib/services/hanaonazureManagement/lib/hanaManagementClient.js
  lib/services/hanaonazureManagement/lib/models/disk.js
  lib/services/hanaonazureManagement/lib/models/display.js
  lib/services/hanaonazureManagement/lib/models/errorResponse.js
  lib/services/hanaonazureManagement/lib/models/hanaInstance.js
  lib/services/hanaonazureManagement/lib/models/hanaInstancesListResult.js
  lib/services/hanaonazureManagement/lib/models/hardwareProfile.js
  lib/services/hanaonazureManagement/lib/models/index.d.ts
  lib/services/hanaonazureManagement/lib/models/index.js
  lib/services/hanaonazureManagement/lib/models/ipAddress.js
  lib/services/hanaonazureManagement/lib/models/networkProfile.js
  lib/services/hanaonazureManagement/lib/models/oSProfile.js
  lib/services/hanaonazureManagement/lib/models/operation.js
  lib/services/hanaonazureManagement/lib/models/operationList.js
  lib/services/hanaonazureManagement/lib/models/resource.js
  lib/services/hanaonazureManagement/lib/models/storageProfile.js
  lib/services/hanaonazureManagement/lib/operations/hanaInstances.js
  lib/services/hanaonazureManagement/lib/operations/index.d.ts
  lib/services/hanaonazureManagement/lib/operations/index.js
  lib/services/hanaonazureManagement/lib/operations/operations.js
  lib/services/hanaonazureManagement/lib/package.json
Labels: in progress

#2549 Add machinelearningexperimentation SDK
  codegen_mappings.json
  lib/services/machinelearningexperimentationManagement/lib/LICENSE.txt
  lib/services/machinelearningexperimentationManagement/lib/README.md
  lib/services/machinelearningexperimentationManagement/lib/mLTeamAccountManagementClient.d.ts
  lib/services/machinelearningexperimentationManagement/lib/mLTeamAccountManagementClient.js
  lib/services/machinelearningexperimentationManagement/lib/models/account.js
  lib/services/machinelearningexperimentationManagement/lib/models/accountListResult.js
  lib/services/machinelearningexperimentationManagement/lib/models/accountUpdateParameters.js
  lib/services/machinelearningexperimentationManagement/lib/models/errorResponse.js
  lib/services/machinelearningexperimentationManagement/lib/models/index.d.ts
  lib/services/machinelearningexperimentationManagement/lib/models/index.js
  lib/services/machinelearningexperimentationManagement/lib/models/operation.js
  lib/services/machinelearningexperimentationManagement/lib/models/operationDisplay.js
  lib/services/machinelearningexperimentationManagement/lib/models/operationListResult.js
  lib/services/machinelearningexperimentationManagement/lib/models/project.js
  lib/services/machinelearningexperimentationManagement/lib/models/projectListResult.js
  lib/services/machinelearningexperimentationManagement/lib/models/projectUpdateParameters.js
  lib/services/machinelearningexperimentationManagement/lib/models/resource.js
  lib/services/machinelearningexperimentationManagement/lib/models/storageAccountProperties.js
  lib/services/machinelearningexperimentationManagement/lib/models/workspace.js
  lib/services/machinelearningexperimentationManagement/lib/models/workspaceListResult.js
  lib/services/machinelearningexperimentationManagement/lib/models/workspaceUpdateParameters.js
  lib/services/machinelearningexperimentationManagement/lib/operations/accounts.js
  lib/services/machinelearningexperimentationManagement/lib/operations/index.d.ts
  lib/services/machinelearningexperimentationManagement/lib/operations/index.js
  lib/services/machinelearningexperimentationManagement/lib/operations/operations.js
  lib/services/machinelearningexperimentationManagement/lib/operations/projects.js
  lib/services/machinelearningexperimentationManagement/lib/operations/workspaces.js
  lib/services/machinelearningexperimentationManagement/lib/package.json
Labels: in progress

#2550 Add managementgroups SDK
  codegen_mappings.json
  lib/services/managementgroupsManagement/lib/LICENSE.txt
  lib/services/managementgroupsManagement/lib/README.md
  lib/services/managementgroupsManagement/lib/managementGroupsAPI.d.ts
  lib/services/managementgroupsManagement/lib/managementGroupsAPI.js
  lib/services/managementgroupsManagement/lib/models/createManagementGroupRequest.js
  lib/services/managementgroupsManagement/lib/models/errorDetails.js
  lib/services/managementgroupsManagement/lib/models/errorResponse.js
  lib/services/managementgroupsManagement/lib/models/index.d.ts
  lib/services/managementgroupsManagement/lib/models/index.js
  lib/services/managementgroupsManagement/lib/models/managementGroup.js
  lib/services/managementgroupsManagement/lib/models/managementGroupChildInfo.js
  lib/services/managementgroupsManagement/lib/models/managementGroupDetails.js
  lib/services/managementgroupsManagement/lib/models/managementGroupInfo.js
  lib/services/managementgroupsManagement/lib/models/managementGroupListResult.js
  lib/services/managementgroupsManagement/lib/models/operation.js
  lib/services/managementgroupsManagement/lib/models/operationDisplay.js
  lib/services/managementgroupsManagement/lib/models/operationListResult.js
  lib/services/managementgroupsManagement/lib/models/parentGroupInfo.js
  lib/services/managementgroupsManagement/lib/operations/index.d.ts
  lib/services/managementgroupsManagement/lib/operations/index.js
  lib/services/managementgroupsManagement/lib/operations/managementGroupSubscriptions.js
  lib/services/managementgroupsManagement/lib/operations/managementGroups.js
  lib/services/managementgroupsManagement/lib/operations/operations.js
  lib/services/managementgroupsManagement/lib/package.json
Labels: in progress

#2551 Add managementpartner SDK
  codegen_mappings.json
  lib/services/managementpartnerManagement/lib/LICENSE.txt
  lib/services/managementpartnerManagement/lib/README.md
  lib/services/managementpartnerManagement/lib/aCEProvisioningManagementPartnerAPI.d.ts
  lib/services/managementpartnerManagement/lib/aCEProvisioningManagementPartnerAPI.js
  lib/services/managementpartnerManagement/lib/models/errorModel.js
  lib/services/managementpartnerManagement/lib/models/extendedErrorInfo.js
  lib/services/managementpartnerManagement/lib/models/index.d.ts
  lib/services/managementpartnerManagement/lib/models/index.js
  lib/services/managementpartnerManagement/lib/models/operationDisplay.js
  lib/services/managementpartnerManagement/lib/models/operationList.js
  lib/services/managementpartnerManagement/lib/models/operationResponse.js
  lib/services/managementpartnerManagement/lib/models/partnerResponse.js
  lib/services/managementpartnerManagement/lib/operations/index.d.ts
  lib/services/managementpartnerManagement/lib/operations/index.js
  lib/services/managementpartnerManagement/lib/operations/operation.js
  lib/services/managementpartnerManagement/lib/operations/partner.js
  lib/services/managementpartnerManagement/lib/package.json
Labels: in progress

#2552 Add migrate SDK
  codegen_mappings.json
  lib/services/migrateManagement/lib/LICENSE.txt
  lib/services/migrateManagement/lib/README.md
  lib/services/migrateManagement/lib/azureMigrate.d.ts
  lib/services/migrateManagement/lib/azureMigrate.js
  lib/services/migrateManagement/lib/models/assessedDisk.js
  lib/services/migrateManagement/lib/models/assessedMachine.js
  lib/services/migrateManagement/lib/models/assessedMachineResultList.js
  lib/services/migrateManagement/lib/models/assessedNetworkAdapter.js
  lib/services/migrateManagement/lib/models/assessment.js
  lib/services/migrateManagement/lib/models/assessmentResultList.js
  lib/services/migrateManagement/lib/models/disk.js
  lib/services/migrateManagement/lib/models/downloadUrl.js
  lib/services/migrateManagement/lib/models/group.js
  lib/services/migrateManagement/lib/models/groupResultList.js
  lib/services/migrateManagement/lib/models/index.d.ts
  lib/services/migrateManagement/lib/models/index.js
  lib/services/migrateManagement/lib/models/machine.js
  lib/services/migrateManagement/lib/models/machineResultList.js
  lib/services/migrateManagement/lib/models/networkAdapter.js
  lib/services/migrateManagement/lib/models/operation.js
  lib/services/migrateManagement/lib/models/operationDisplay.js
  lib/services/migrateManagement/lib/models/operationResultList.js
  lib/services/migrateManagement/lib/models/project.js
  lib/services/migrateManagement/lib/models/projectKey.js
  lib/services/migrateManagement/lib/models/projectResultList.js
  lib/services/migrateManagement/lib/operations/assessedMachines.js
  lib/services/migrateManagement/lib/operations/assessments.js
  lib/services/migrateManagement/lib/operations/groups.js
  lib/services/migrateManagement/lib/operations/index.d.ts
  lib/services/migrateManagement/lib/operations/index.js
  lib/services/migrateManagement/lib/operations/machines.js
  lib/services/migrateManagement/lib/operations/operations.js
  lib/services/migrateManagement/lib/operations/projects.js
  lib/services/migrateManagement/lib/package.json
Labels: in progress

#2553 Add msi SDK
  codegen_mappings.json
  lib/services/msiManagement/lib/LICENSE.txt
  lib/services/msiManagement/lib/README.md
  lib/services/msiManagement/lib/managedServiceIdentityClient.d.ts
  lib/services/msiManagement/lib/managedServiceIdentityClient.js
  lib/services/msiManagement/lib/models/identity.js
  lib/services/msiManagement/lib/models/index.d.ts
  lib/services/msiManagement/lib/models/index.js
  lib/services/msiManagement/lib/models/operation.js
  lib/services/msiManagement/lib/models/operationDisplay.js
  lib/services/msiManagement/lib/models/operationListResult.js
  lib/services/msiManagement/lib/models/userAssignedIdentitiesListResult.js
  lib/services/msiManagement/lib/operations/index.d.ts
  lib/services/msiManagement/lib/operations/index.js
  lib/services/msiManagement/lib/operations/operations.js
  lib/services/msiManagement/lib/operations/userAssignedIdentities.js
  lib/services/msiManagement/lib/package.json
Labels: in progress

#2510 [AutoPR automation/resource-manager] Adding patch API for Configurations
  lib/services/automationManagement/lib/models/dscConfigurationUpdateParameters.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/operations/dscConfigurationOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#2554 Add policyinsights SDK
  codegen_mappings.json
  lib/services/policyinsightsManagement/lib/LICENSE.txt
  lib/services/policyinsightsManagement/lib/README.md
  lib/services/policyinsightsManagement/lib/models/index.d.ts
  lib/services/policyinsightsManagement/lib/models/index.js
  lib/services/policyinsightsManagement/lib/models/operation.js
  lib/services/policyinsightsManagement/lib/models/operationDisplay.js
  lib/services/policyinsightsManagement/lib/models/operationsListResults.js
  lib/services/policyinsightsManagement/lib/models/policyAssignmentSummary.js
  lib/services/policyinsightsManagement/lib/models/policyDefinitionSummary.js
  lib/services/policyinsightsManagement/lib/models/policyEvent.js
  lib/services/policyinsightsManagement/lib/models/policyEventsQueryResults.js
  lib/services/policyinsightsManagement/lib/models/policyState.js
  lib/services/policyinsightsManagement/lib/models/policyStatesQueryResults.js
  lib/services/policyinsightsManagement/lib/models/queryFailure.js
  lib/services/policyinsightsManagement/lib/models/queryFailureError.js
  lib/services/policyinsightsManagement/lib/models/queryOptions.js
  lib/services/policyinsightsManagement/lib/models/summarizeResults.js
  lib/services/policyinsightsManagement/lib/models/summary.js
  lib/services/policyinsightsManagement/lib/models/summaryResults.js
  lib/services/policyinsightsManagement/lib/operations/index.d.ts
  lib/services/policyinsightsManagement/lib/operations/index.js
  lib/services/policyinsightsManagement/lib/operations/operations.js
  lib/services/policyinsightsManagement/lib/operations/policyEvents.js
  lib/services/policyinsightsManagement/lib/operations/policyStates.js
  lib/services/policyinsightsManagement/lib/package.json
  lib/services/policyinsightsManagement/lib/policyInsightsClient.d.ts
  lib/services/policyinsightsManagement/lib/policyInsightsClient.js
Labels: in progress

#2555 [AutoPR automation/resource-manager] Add new HybridWorkerGroup update example
  lib/services/automationManagement/lib/automationClient.d.ts
  lib/services/automationManagement/lib/automationClient.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/operations/activityOperations.js
  lib/services/automationManagement/lib/operations/agentRegistrationInformation.js
  lib/services/automationManagement/lib/operations/certificateOperations.js
  lib/services/automationManagement/lib/operations/connectionOperations.js
  lib/services/automationManagement/lib/operations/connectionTypeOperations.js
  lib/services/automationManagement/lib/operations/credentialOperations.js
  lib/services/automationManagement/lib/operations/dscCompilationJobOperations.js
  lib/services/automationManagement/lib/operations/dscCompilationJobStream.js
  lib/services/automationManagement/lib/operations/dscConfigurationOperations.js
  lib/services/automationManagement/lib/operations/dscNodeConfigurationOperations.js
  lib/services/automationManagement/lib/operations/dscNodeOperations.js
  lib/services/automationManagement/lib/operations/fields.js
  lib/services/automationManagement/lib/operations/hybridRunbookWorkerGroupOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/jobOperations.js
  lib/services/automationManagement/lib/operations/jobScheduleOperations.js
  lib/services/automationManagement/lib/operations/jobStreamOperations.js
  lib/services/automationManagement/lib/operations/linkedWorkspaceOperations.js
  lib/services/automationManagement/lib/operations/moduleOperations.js
  lib/services/automationManagement/lib/operations/nodeReports.js
  lib/services/automationManagement/lib/operations/objectDataTypes.js
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
  lib/services/automationManagement/lib/operations/runbookOperations.js
  lib/services/automationManagement/lib/operations/scheduleOperations.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationMachineRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
  lib/services/automationManagement/lib/operations/sourceControlOperations.js
  lib/services/automationManagement/lib/operations/sourceControlSyncJobOperations.js
  lib/services/automationManagement/lib/operations/testJobOperations.js
  lib/services/automationManagement/lib/operations/testJobStreams.js
  lib/services/automationManagement/lib/operations/variableOperations.js
  lib/services/automationManagement/lib/operations/webhookOperations.js
Labels: RestPRMerged

#2557 [AutoPR compute/resource-manager] Adding PATCH for virtualMachines/{vmName}/extensions/{extName} and GET for virtualMachines/{vmName}/extensions
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineExtensionUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineExtensionsListResult.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/index.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged

#2559 [AutoPR compute/resource-manager] Update config for Go SDK
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/index.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged

#2563 Update monitor dataplane readme with deprecation explanation
  lib/services/monitor/README.md
  lib/services/monitor/package.json
Labels: in progress

#2562 Add powerbidedicated SDK
  codegen_mappings.json
  lib/services/powerbidedicatedManagement/lib/LICENSE.txt
  lib/services/powerbidedicatedManagement/lib/README.md
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacities.js
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacity.js
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacityAdministrators.js
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacityUpdateParameters.js
  lib/services/powerbidedicatedManagement/lib/models/errorResponse.js
  lib/services/powerbidedicatedManagement/lib/models/index.d.ts
  lib/services/powerbidedicatedManagement/lib/models/index.js
  lib/services/powerbidedicatedManagement/lib/models/operation.js
  lib/services/powerbidedicatedManagement/lib/models/operationDisplay.js
  lib/services/powerbidedicatedManagement/lib/models/operationListResult.js
  lib/services/powerbidedicatedManagement/lib/models/resource.js
  lib/services/powerbidedicatedManagement/lib/models/resourceSku.js
  lib/services/powerbidedicatedManagement/lib/models/skuDetailsForExistingResource.js
  lib/services/powerbidedicatedManagement/lib/models/skuEnumerationForExistingResourceResult.js
  lib/services/powerbidedicatedManagement/lib/models/skuEnumerationForNewResourceResult.js
  lib/services/powerbidedicatedManagement/lib/operations/capacities.js
  lib/services/powerbidedicatedManagement/lib/operations/index.d.ts
  lib/services/powerbidedicatedManagement/lib/operations/index.js
  lib/services/powerbidedicatedManagement/lib/operations/operations.js
  lib/services/powerbidedicatedManagement/lib/package.json
  lib/services/powerbidedicatedManagement/lib/powerBIDedicatedManagementClient.d.ts
  lib/services/powerbidedicatedManagement/lib/powerBIDedicatedManagementClient.js
Labels: in progress

#2567 Add sourceCodeFolderPath to codegen_mappings schema, remove lib from dir
  codegen_mappings.json
  codegen_mappings.schema.json
Labels: in progress

#2566 Add reservations SDK
  codegen_mappings.json
  lib/services/reservationsManagement/lib/LICENSE.txt
  lib/services/reservationsManagement/lib/README.md
  lib/services/reservationsManagement/lib/azureReservationAPI.d.ts
  lib/services/reservationsManagement/lib/azureReservationAPI.js
  lib/services/reservationsManagement/lib/models/appliedReservationList.js
  lib/services/reservationsManagement/lib/models/appliedReservations.js
  lib/services/reservationsManagement/lib/models/catalog.js
  lib/services/reservationsManagement/lib/models/errorModel.js
  lib/services/reservationsManagement/lib/models/extendedErrorInfo.js
  lib/services/reservationsManagement/lib/models/extendedStatusInfo.js
  lib/services/reservationsManagement/lib/models/index.d.ts
  lib/services/reservationsManagement/lib/models/index.js
  lib/services/reservationsManagement/lib/models/mergeRequest.js
  lib/services/reservationsManagement/lib/models/operationDisplay.js
  lib/services/reservationsManagement/lib/models/operationList.js
  lib/services/reservationsManagement/lib/models/operationResponse.js
  lib/services/reservationsManagement/lib/models/patch.js
  lib/services/reservationsManagement/lib/models/reservationList.js
  lib/services/reservationsManagement/lib/models/reservationMergeProperties.js
  lib/services/reservationsManagement/lib/models/reservationOrderList.js
  lib/services/reservationsManagement/lib/models/reservationOrderResponse.js
  lib/services/reservationsManagement/lib/models/reservationProperties.js
  lib/services/reservationsManagement/lib/models/reservationResponse.js
  lib/services/reservationsManagement/lib/models/reservationSplitProperties.js
  lib/services/reservationsManagement/lib/models/skuCapability.js
  lib/services/reservationsManagement/lib/models/skuName.js
  lib/services/reservationsManagement/lib/models/skuRestriction.js
  lib/services/reservationsManagement/lib/models/splitRequest.js
  lib/services/reservationsManagement/lib/operations/index.d.ts
  lib/services/reservationsManagement/lib/operations/index.js
  lib/services/reservationsManagement/lib/operations/operation.js
  lib/services/reservationsManagement/lib/operations/reservation.js
  lib/services/reservationsManagement/lib/operations/reservationOrder.js
  lib/services/reservationsManagement/lib/package.json
Labels: in progress

#2565 Remove monitor dataplane
  lib/services/monitor/LICENSE.txt
  lib/services/monitor/lib/models/errorResponse.js
  lib/services/monitor/lib/models/eventCategoryCollection.js
  lib/services/monitor/lib/models/eventData.js
  lib/services/monitor/lib/models/eventDataCollection.js
  lib/services/monitor/lib/models/httpRequestInfo.js
  lib/services/monitor/lib/models/index.d.ts
  lib/services/monitor/lib/models/index.js
  lib/services/monitor/lib/models/localizableString.js
  lib/services/monitor/lib/models/metadataValue.js
  lib/services/monitor/lib/models/metric.js
  lib/services/monitor/lib/models/metricAvailability.js
  lib/services/monitor/lib/models/metricDefinition.js
  lib/services/monitor/lib/models/metricDefinitionCollection.js
  lib/services/monitor/lib/models/metricValue.js
  lib/services/monitor/lib/models/response.js
  lib/services/monitor/lib/models/senderAuthorization.js
  lib/services/monitor/lib/models/timeSeriesElement.js
  lib/services/monitor/lib/models/usageMetric.js
  lib/services/monitor/lib/models/usageMetricCollection.js
  lib/services/monitor/lib/monitorClient.d.ts
  lib/services/monitor/lib/monitorClient.js
  lib/services/monitor/lib/operations/activityLogs.js
  lib/services/monitor/lib/operations/eventCategories.js
  lib/services/monitor/lib/operations/index.d.ts
  lib/services/monitor/lib/operations/index.js
  lib/services/monitor/lib/operations/metricDefinitions.js
  lib/services/monitor/lib/operations/metrics.js
  lib/services/monitor/lib/operations/tenantActivityLogs.js
  lib/services/monitor/lib/operations/usageMetrics.js
Labels: in progress

#2570 Add subscription SDK (resolves #2525)
  codegen_mappings.json
  lib/services/subscriptionManagement/lib/LICENSE.txt
  lib/services/subscriptionManagement/lib/README.md
  lib/services/subscriptionManagement/lib/models/adPrincipal.js
  lib/services/subscriptionManagement/lib/models/errorResponse.js
  lib/services/subscriptionManagement/lib/models/index.d.ts
  lib/services/subscriptionManagement/lib/models/index.js
  lib/services/subscriptionManagement/lib/models/location.js
  lib/services/subscriptionManagement/lib/models/locationListResult.js
  lib/services/subscriptionManagement/lib/models/operation.js
  lib/services/subscriptionManagement/lib/models/operationDisplay.js
  lib/services/subscriptionManagement/lib/models/operationListResult.js
  lib/services/subscriptionManagement/lib/models/subscription.js
  lib/services/subscriptionManagement/lib/models/subscriptionCreationParameters.js
  lib/services/subscriptionManagement/lib/models/subscriptionCreationResult.js
  lib/services/subscriptionManagement/lib/models/subscriptionListResult.js
  lib/services/subscriptionManagement/lib/models/subscriptionOperation.js
  lib/services/subscriptionManagement/lib/models/subscriptionOperationListResult.js
  lib/services/subscriptionManagement/lib/models/subscriptionPolicies.js
  lib/services/subscriptionManagement/lib/models/tenantIdDescription.js
  lib/services/subscriptionManagement/lib/models/tenantListResult.js
  lib/services/subscriptionManagement/lib/operations/index.d.ts
  lib/services/subscriptionManagement/lib/operations/index.js
  lib/services/subscriptionManagement/lib/operations/operations.js
  lib/services/subscriptionManagement/lib/operations/subscriptionFactory.js
  lib/services/subscriptionManagement/lib/operations/subscriptionOperations.js
  lib/services/subscriptionManagement/lib/operations/subscriptions.js
  lib/services/subscriptionManagement/lib/operations/tenants.js
  lib/services/subscriptionManagement/lib/package.json
  lib/services/subscriptionManagement/lib/subscriptionClient.d.ts
  lib/services/subscriptionManagement/lib/subscriptionClient.js
Labels: in progress

#2571 fixes #2569
  lib/common/package.json
Labels: in progress

#2558 [AutoPR] compute/resource-manager
  codegen_mappings.json
  lib/services/computeManagement2/LICENSE.txt
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineExtensionUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineExtensionsListResult.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/index.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
  lib/services/computeManagement2/package.json
Labels: ServicePR, in progress

#2540 [AutoPR] servicebus/resource-manager
  codegen_mappings.json
  lib/services/serviceBusManagement2/LICENSE.txt
  lib/services/serviceBusManagement2/lib/models/correlationFilter.js
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/rule.js
  lib/services/serviceBusManagement2/lib/models/sBQueue.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/queues.js
  lib/services/serviceBusManagement2/lib/operations/rules.js
  lib/services/serviceBusManagement2/lib/serviceBusManagementClient.d.ts
  lib/services/serviceBusManagement2/lib/serviceBusManagementClient.js
  lib/services/serviceBusManagement2/package.json
Labels: ServicePR, in progress

#2484 [AutoPR] mysql/resource-manager
  codegen_mappings.json
  lib/services/mysqlManagement/LICENSE.txt
  lib/services/mysqlManagement/lib/models/index.d.ts
  lib/services/mysqlManagement/lib/models/index.js
  lib/services/mysqlManagement/lib/models/logFile.js
  lib/services/mysqlManagement/lib/models/nameAvailabilityRequest.js
  lib/services/mysqlManagement/lib/models/performanceTierProperties.js
  lib/services/mysqlManagement/lib/models/performanceTierServiceLevelObjectives.js
  lib/services/mysqlManagement/lib/models/server.js
  lib/services/mysqlManagement/lib/models/serverForCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForDefaultCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForRestore.js
  lib/services/mysqlManagement/lib/models/serverUpdateParameters.js
  lib/services/mysqlManagement/lib/models/sku.js
  lib/services/mysqlManagement/lib/models/storageProfile.js
  lib/services/mysqlManagement/lib/mySQLManagementClient.d.ts
  lib/services/mysqlManagement/lib/mySQLManagementClient.js
  lib/services/mysqlManagement/lib/operations/checkNameAvailability.js
  lib/services/mysqlManagement/lib/operations/index.d.ts
  lib/services/mysqlManagement/lib/operations/index.js
  lib/services/mysqlManagement/lib/operations/servers.js
  lib/services/mysqlManagement/package.json
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_databases_should_create_a_database_correctly.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_databases_should_delete_the_specified_database.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_databases_should_get_the_specified_database.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_databases_should_list_all_the_databases_in_the_server.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_servers_should_create_a_server_correctly.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_servers_should_delete_the_specified_server.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_servers_should_get_the_specified_server.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_servers_should_list_all_the_servers_in_the_resourcegroup.nock.js
  test/recordings/mysqlmanagementservice-tests/MySQL_Management_servers_should_list_all_the_servers_in_the_subscription.nock.js
  test/recordings/mysqlmanagementservice-tests/suite.mysqlmanagementservice-tests.nock.js
  test/services/mysqlManagement/mySQLManagementClient-tests.js
Labels: ServicePR, in progress

#2572 update azure-common dep. version in the rollup package.json
  package-lock.json
  package.json
Labels: in progress

#2505 [AutoPR] apimanagement/resource-manager
  codegen_mappings.json
  lib/services/apimanagement/LICENSE.txt
  lib/services/apimanagement/README.md
  lib/services/apimanagement/lib/apiManagementClient.d.ts
  lib/services/apimanagement/lib/apiManagementClient.js
  lib/services/apimanagement/package.json
Labels: ServicePR, in progress

#2581 Update analysisservices minor version and regenerate
  codegen_mappings.json
  lib/services/analysisServices/LICENSE.txt
  lib/services/analysisServices/lib/analysisServicesManagementClient.d.ts
  lib/services/analysisServices/lib/analysisServicesManagementClient.js
  lib/services/analysisServices/lib/models/analysisServicesServer.js
  lib/services/analysisServices/lib/models/analysisServicesServerUpdateParameters.js
  lib/services/analysisServices/lib/models/checkServerNameAvailabilityParameters.js
  lib/services/analysisServices/lib/models/checkServerNameAvailabilityResult.js
  lib/services/analysisServices/lib/models/index.d.ts
  lib/services/analysisServices/lib/models/index.js
  lib/services/analysisServices/lib/models/operationStatus.js
  lib/services/analysisServices/lib/operations/index.d.ts
  lib/services/analysisServices/lib/operations/servers.js
  lib/services/analysisServices/package.json
Labels: in progress

#2589 Fix datacatalog package folder structure
  codegen_mappings.json
  lib/services/datacatalogManagement/LICENSE.txt
  lib/services/datacatalogManagement/README.md
  lib/services/datacatalogManagement/package.json
Labels: in progress

#2585 [AutoPR apimanagement/resource-manager] Issues resource with Comments and Attachments subresources were added
  lib/services/apimanagement/lib/models/requestReportCollection.js
Labels: RestPRMerged, in progress

#2603 Change the wrong moment version
  lib/services/batch/package.json
Labels: in progress

#2611 [AutoPR cognitiveservices/resource-manager] Make filter a method parameter
  lib/services/cognitiveServicesManagement/lib/LICENSE.txt
  lib/services/cognitiveServicesManagement/lib/lib/cognitiveServicesManagementClient.d.ts
  lib/services/cognitiveServicesManagement/lib/lib/cognitiveServicesManagementClient.js
  lib/services/cognitiveServicesManagement/lib/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/lib/models/checkSkuAvailabilityResultList.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesAccountEnumerateSkusResult.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesAccountKeys.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesAccountListResult.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesAccountUpdateParameters.js
  lib/services/cognitiveServicesManagement/lib/lib/models/cognitiveServicesResourceAndSku.js
  lib/services/cognitiveServicesManagement/lib/lib/models/errorBody.js
  lib/services/cognitiveServicesManagement/lib/lib/models/errorModel.js
  lib/services/cognitiveServicesManagement/lib/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/lib/models/index.js
  lib/services/cognitiveServicesManagement/lib/lib/models/metricName.js
  lib/services/cognitiveServicesManagement/lib/lib/models/operationDisplayInfo.js
  lib/services/cognitiveServicesManagement/lib/lib/models/operationEntity.js
  lib/services/cognitiveServicesManagement/lib/lib/models/operationEntityListResult.js
  lib/services/cognitiveServicesManagement/lib/lib/models/regenerateKeyParameters.js
  lib/services/cognitiveServicesManagement/lib/lib/models/sku.js
  lib/services/cognitiveServicesManagement/lib/lib/models/usage.js
  lib/services/cognitiveServicesManagement/lib/lib/models/usagesResult.js
  lib/services/cognitiveServicesManagement/lib/lib/operations/accounts.js
  lib/services/cognitiveServicesManagement/lib/lib/operations/checkSkuAvailability.js
  lib/services/cognitiveServicesManagement/lib/lib/operations/index.d.ts
  lib/services/cognitiveServicesManagement/lib/lib/operations/index.js
  lib/services/cognitiveServicesManagement/lib/lib/operations/operations.js
  lib/services/cognitiveServicesManagement/lib/package.json
Labels: RestPRMerged, in progress

#2613 [AutoPR monitor/resource-manager] Fix bugs (typos) in the swagger
  lib/services/monitor/lib/lib/operations/metricAlerts.js
  lib/services/monitor/lib/lib/operations/metricAlertsStatus.js
Labels: RestPRMerged, in progress

#2604 [AutoPR containerinstance/resource-manager] Adding April Swagger For GA
  lib/services/containerinstanceManagement/lib/LICENSE.txt
  lib/services/containerinstanceManagement/lib/lib/containerInstanceManagementClient.d.ts
  lib/services/containerinstanceManagement/lib/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/lib/models/azureFileVolume.js
  lib/services/containerinstanceManagement/lib/lib/models/container.js
  lib/services/containerinstanceManagement/lib/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/lib/models/containerExecRequestTerminalSize.js
  lib/services/containerinstanceManagement/lib/lib/models/containerExecResponse.js
  lib/services/containerinstanceManagement/lib/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/lib/models/containerGroupListResult.js
  lib/services/containerinstanceManagement/lib/lib/models/containerGroupPropertiesInstanceView.js
  lib/services/containerinstanceManagement/lib/lib/models/containerPort.js
  lib/services/containerinstanceManagement/lib/lib/models/containerPropertiesInstanceView.js
  lib/services/containerinstanceManagement/lib/lib/models/containerState.js
  lib/services/containerinstanceManagement/lib/lib/models/environmentVariable.js
  lib/services/containerinstanceManagement/lib/lib/models/event.js
  lib/services/containerinstanceManagement/lib/lib/models/gitRepoVolume.js
  lib/services/containerinstanceManagement/lib/lib/models/imageRegistryCredential.js
  lib/services/containerinstanceManagement/lib/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/lib/models/index.js
  lib/services/containerinstanceManagement/lib/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/lib/models/logs.js
  lib/services/containerinstanceManagement/lib/lib/models/operation.js
  lib/services/containerinstanceManagement/lib/lib/models/operationDisplay.js
  lib/services/containerinstanceManagement/lib/lib/models/operationListResult.js
  lib/services/containerinstanceManagement/lib/lib/models/port.js
  lib/services/containerinstanceManagement/lib/lib/models/resource.js
  lib/services/containerinstanceManagement/lib/lib/models/resourceLimits.js
  lib/services/containerinstanceManagement/lib/lib/models/resourceRequests.js
  lib/services/containerinstanceManagement/lib/lib/models/resourceRequirements.js
  lib/services/containerinstanceManagement/lib/lib/models/usage.js
  lib/services/containerinstanceManagement/lib/lib/models/usageListResult.js
  lib/services/containerinstanceManagement/lib/lib/models/usageName.js
  lib/services/containerinstanceManagement/lib/lib/models/volume.js
  lib/services/containerinstanceManagement/lib/lib/models/volumeMount.js
  lib/services/containerinstanceManagement/lib/lib/operations/containerGroupUsage.js
  lib/services/containerinstanceManagement/lib/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/lib/operations/containerLogs.js
  lib/services/containerinstanceManagement/lib/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/lib/operations/index.js
  lib/services/containerinstanceManagement/lib/lib/operations/operations.js
  lib/services/containerinstanceManagement/lib/lib/operations/startContainer.js
  lib/services/containerinstanceManagement/lib/package.json
Labels: RestPRMerged, in progress

#2619 Update README.md
  lib/services/advisorManagement/README.md
Labels: in progress
