Repository Azure/azure-sdk-for-node, pull requests merged in 2018-10, with the labels that each got.

#3724 [AutoPR containerregistry/resource-manager] Add ContextPath and source location URL for encode task and run type, support for pull request based triggers
  lib/services/containerRegistryManagement/lib/models/baseImageTrigger.js
  lib/services/containerRegistryManagement/lib/models/baseImageTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildRequest.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStep.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/fileTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStep.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/run.js
  lib/services/containerRegistryManagement/lib/models/runFilter.js
  lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
  lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/taskStepProperties.js
  lib/services/containerRegistryManagement/lib/models/taskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/triggerProperties.js
  lib/services/containerRegistryManagement/lib/models/triggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/tasks.js
  lib/services/containerRegistryManagement/package.json
Labels: RestPRMerged, in progress

#3736 [AutoPR datafactory/resource-manager] Add Pipeline Variables / Set Variable Activity / Append Variable Activity
  lib/services/datafactoryManagement/lib/models/appendVariableActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/pipelineResource.js
  lib/services/datafactoryManagement/lib/models/setVariableActivity.js
  lib/services/datafactoryManagement/lib/models/variableSpecification.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/pipelines.js
Labels: RestPRMerged, in progress

#3739 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/appendVariableActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/pipelineResource.js
  lib/services/datafactoryManagement/lib/models/setVariableActivity.js
  lib/services/datafactoryManagement/lib/models/variableSpecification.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/pipelines.js
Labels: ServicePR, in progress

#3738 [AutoPR] containerregistry/resource-manager
  lib/services/containerRegistryManagement/lib/models/baseImageTrigger.js
  lib/services/containerRegistryManagement/lib/models/baseImageTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildRequest.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStep.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/fileTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStep.js
  lib/services/containerRegistryManagement/lib/models/fileTaskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/run.js
  lib/services/containerRegistryManagement/lib/models/runFilter.js
  lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
  lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/taskStepProperties.js
  lib/services/containerRegistryManagement/lib/models/taskStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/triggerProperties.js
  lib/services/containerRegistryManagement/lib/models/triggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/tasks.js
  lib/services/containerRegistryManagement/package.json
Labels: ServicePR, in progress

#3740 Restapi auto datafactory/resource manager
  lib/services/datafactoryManagement/package.json
Labels: in progress

#3741 [AutoPR deploymentmanager/resource-manager] DeploymentManager: Fix property name and enhance descriptions
  lib/services/deploymentmanagerManagement/lib/models/artifactSource.js
  lib/services/deploymentmanagerManagement/lib/models/artifactSourcePropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/index.d.ts
  lib/services/deploymentmanagerManagement/lib/models/prePostStep.js
  lib/services/deploymentmanagerManagement/lib/models/rollout.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutPropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutRequest.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutStep.js
  lib/services/deploymentmanagerManagement/lib/models/sasAuthentication.js
  lib/services/deploymentmanagerManagement/lib/models/serviceProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitResource.js
  lib/services/deploymentmanagerManagement/lib/models/step.js
  lib/services/deploymentmanagerManagement/lib/models/stepOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/stepResource.js
  lib/services/deploymentmanagerManagement/lib/operations/artifactSources.js
  lib/services/deploymentmanagerManagement/lib/operations/index.d.ts
  lib/services/deploymentmanagerManagement/lib/operations/rollouts.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceTopologies.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceUnits.js
  lib/services/deploymentmanagerManagement/lib/operations/services.js
  lib/services/deploymentmanagerManagement/lib/operations/steps.js
  lib/services/deploymentmanagerManagement/package.json
Labels: RestPRMerged, in progress

#3743 [AutoPR] deploymentmanager/resource-manager
  lib/services/deploymentmanagerManagement/lib/models/artifactSource.js
  lib/services/deploymentmanagerManagement/lib/models/artifactSourcePropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/index.d.ts
  lib/services/deploymentmanagerManagement/lib/models/prePostStep.js
  lib/services/deploymentmanagerManagement/lib/models/rollout.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutPropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutRequest.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutStep.js
  lib/services/deploymentmanagerManagement/lib/models/sasAuthentication.js
  lib/services/deploymentmanagerManagement/lib/models/serviceProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitResource.js
  lib/services/deploymentmanagerManagement/lib/models/step.js
  lib/services/deploymentmanagerManagement/lib/models/stepOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/stepResource.js
  lib/services/deploymentmanagerManagement/lib/operations/artifactSources.js
  lib/services/deploymentmanagerManagement/lib/operations/index.d.ts
  lib/services/deploymentmanagerManagement/lib/operations/rollouts.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceTopologies.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceUnits.js
  lib/services/deploymentmanagerManagement/lib/operations/services.js
  lib/services/deploymentmanagerManagement/lib/operations/steps.js
  lib/services/deploymentmanagerManagement/package.json
Labels: ServicePR, in progress

#3737 [AutoPR cosmos-db/resource-manager] Adding parameter enableMultipleWriteLocations in Cosmos DB
  lib/services/cosmosdbManagement/lib/models/databaseAccount.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountCreateUpdateParameters.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountListConnectionStringsResult.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountPatchParameters.js
  lib/services/cosmosdbManagement/lib/models/failoverPolicies.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/metric.js
  lib/services/cosmosdbManagement/lib/models/metricDefinition.js
  lib/services/cosmosdbManagement/lib/models/operation.js
  lib/services/cosmosdbManagement/lib/models/percentileMetric.js
  lib/services/cosmosdbManagement/lib/models/usage.js
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
  lib/services/cosmosdbManagement/package.json
Labels: RestPRMerged, in progress

#3751 [AutoPR] cosmos-db/resource-manager
  lib/services/cosmosdbManagement/lib/models/databaseAccount.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountCreateUpdateParameters.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountListConnectionStringsResult.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountPatchParameters.js
  lib/services/cosmosdbManagement/lib/models/failoverPolicies.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/metric.js
  lib/services/cosmosdbManagement/lib/models/metricDefinition.js
  lib/services/cosmosdbManagement/lib/models/operation.js
  lib/services/cosmosdbManagement/lib/models/percentileMetric.js
  lib/services/cosmosdbManagement/lib/models/usage.js
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
  lib/services/cosmosdbManagement/package.json
Labels: ServicePR, in progress

#3750 [AutoPR containerinstance/resource-manager] Container Instance October Swagger
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.d.ts
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/containerGroupIdentity.js
  lib/services/containerinstanceManagement/lib/models/containerGroupIdentityUserAssignedIdentitiesValue.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/index.js
  lib/services/containerinstanceManagement/lib/operations/serviceAssociationLink.js
Labels: RestPRMerged, in progress

#3753 [AutoPR] containerinstance/resource-manager
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.d.ts
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/containerGroupIdentity.js
  lib/services/containerinstanceManagement/lib/models/containerGroupIdentityUserAssignedIdentitiesValue.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/index.js
  lib/services/containerinstanceManagement/lib/operations/serviceAssociationLink.js
  lib/services/containerinstanceManagement/package.json
  package.json
Labels: ServicePR, in progress

#3755 Define msiEndpoint and msiSecret as optional
  runtime/ms-rest-azure/index.d.ts
Labels: customer-reported

#3759 [AutoPR containerregistry/resource-manager] Move ACR C# specific config to C#
  lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
  lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
Labels: RestPRMerged, in progress

#3760 [AutoPR] containerregistry/resource-manager
  lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
  lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3742 [AutoPR storagesync/resource-manager] Swagger Update for Microsoft.StorageSync (2018-07-01)
  lib/services/storagesyncManagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncManagement/lib/models/cloudEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/lib/models/registeredServerCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpoint.js
  lib/services/storagesyncManagement/lib/models/serverEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpointUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceCreateParameters.js
  lib/services/storagesyncManagement/lib/models/syncGroup.js
  lib/services/storagesyncManagement/lib/models/syncGroupCreateParameters.js
  lib/services/storagesyncManagement/lib/models/triggerRolloverRequest.js
  lib/services/storagesyncManagement/lib/models/workflow.js
  lib/services/storagesyncManagement/lib/models/workflowArray.js
  lib/services/storagesyncManagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncManagement/lib/operations/syncGroups.js
  lib/services/storagesyncManagement/lib/operations/workflows.js
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
Labels: RestPRMerged, in progress

#3761 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncManagement/lib/models/cloudEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/lib/models/registeredServerCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpoint.js
  lib/services/storagesyncManagement/lib/models/serverEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpointUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceCreateParameters.js
  lib/services/storagesyncManagement/lib/models/syncGroup.js
  lib/services/storagesyncManagement/lib/models/syncGroupCreateParameters.js
  lib/services/storagesyncManagement/lib/models/triggerRolloverRequest.js
  lib/services/storagesyncManagement/lib/models/workflow.js
  lib/services/storagesyncManagement/lib/models/workflowArray.js
  lib/services/storagesyncManagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncManagement/lib/operations/syncGroups.js
  lib/services/storagesyncManagement/lib/operations/workflows.js
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
  lib/services/storagesyncManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3748 [AutoPR sql/resource-manager] Adding VA support for manged instance - Update readme.md
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/managedInstance.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessmentRuleBaselines.js
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessmentScans.js
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/lib/operations/managedInstances.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
  lib/services/sqlManagement2/package.json
Labels: RestPRMerged, in progress

#3764 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/managedInstance.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessmentRuleBaselines.js
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessmentScans.js
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/lib/operations/managedInstances.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3747 [AutoPR domainservices/resource-manager] DomainServices: Add missing properties, add examples, and fix linting errors
  lib/services/domainservicesManagement/LICENSE.txt
  lib/services/domainservicesManagement/README.md
  lib/services/domainservicesManagement/lib/domainservicesManagementClient.d.ts
  lib/services/domainservicesManagement/lib/domainservicesManagementClient.js
  lib/services/domainservicesManagement/lib/models/domainSecuritySettings.js
  lib/services/domainservicesManagement/lib/models/domainService.js
  lib/services/domainservicesManagement/lib/models/domainServiceListResult.js
  lib/services/domainservicesManagement/lib/models/domainServicePatchProperties.js
  lib/services/domainservicesManagement/lib/models/domainServiceProperties.js
  lib/services/domainservicesManagement/lib/models/healthAlert.js
  lib/services/domainservicesManagement/lib/models/healthMonitor.js
  lib/services/domainservicesManagement/lib/models/index.d.ts
  lib/services/domainservicesManagement/lib/models/index.js
  lib/services/domainservicesManagement/lib/models/notificationSettings.js
  lib/services/domainservicesManagement/lib/models/operationEntity.js
  lib/services/domainservicesManagement/lib/models/operationEntityListResult.js
  lib/services/domainservicesManagement/lib/operations/domainServiceOperations.js
  lib/services/domainservicesManagement/lib/operations/domainServices.js
  lib/services/domainservicesManagement/lib/operations/index.d.ts
  lib/services/domainservicesManagement/package.json
Labels: RestPRMerged, in progress

#3752 [AutoPR datafactory/resource-manager] Add APIs for tumbling window rerun trigger
  lib/services/datafactoryManagement/lib/dataFactoryManagementClient.d.ts
  lib/services/datafactoryManagement/lib/dataFactoryManagementClient.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/rerunTriggerListResponse.js
  lib/services/datafactoryManagement/lib/models/rerunTriggerResource.js
  lib/services/datafactoryManagement/lib/models/rerunTumblingWindowTrigger.js
  lib/services/datafactoryManagement/lib/models/rerunTumblingWindowTriggerActionParameters.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/index.js
  lib/services/datafactoryManagement/lib/operations/rerunTriggers.js
Labels: RestPRMerged, in progress

#3773 [AutoPR keyvault/data-plane] Disabled KV Python DT multi-api script
  lib/services/keyvault/lib/models/certificateBundle.js
  lib/services/keyvault/lib/models/certificateCreateParameters.js
  lib/services/keyvault/lib/models/certificateImportParameters.js
  lib/services/keyvault/lib/models/certificateIssuerSetParameters.js
  lib/services/keyvault/lib/models/certificateIssuerUpdateParameters.js
  lib/services/keyvault/lib/models/certificateItem.js
  lib/services/keyvault/lib/models/certificateMergeParameters.js
  lib/services/keyvault/lib/models/certificateOperation.js
  lib/services/keyvault/lib/models/certificatePolicy.js
  lib/services/keyvault/lib/models/certificateUpdateParameters.js
  lib/services/keyvault/lib/models/contacts.js
  lib/services/keyvault/lib/models/errorModel.js
  lib/services/keyvault/lib/models/issuerBundle.js
  lib/services/keyvault/lib/models/keyBundle.js
  lib/services/keyvault/lib/models/keyCreateParameters.js
  lib/services/keyvault/lib/models/keyImportParameters.js
  lib/services/keyvault/lib/models/keyItem.js
  lib/services/keyvault/lib/models/keyUpdateParameters.js
  lib/services/keyvault/lib/models/keyVaultError.js
  lib/services/keyvault/lib/models/lifetimeAction.js
  lib/services/keyvault/lib/models/organizationDetails.js
  lib/services/keyvault/lib/models/sasDefinitionBundle.js
  lib/services/keyvault/lib/models/sasDefinitionCreateParameters.js
  lib/services/keyvault/lib/models/sasDefinitionItem.js
  lib/services/keyvault/lib/models/sasDefinitionUpdateParameters.js
  lib/services/keyvault/lib/models/secretBundle.js
  lib/services/keyvault/lib/models/secretItem.js
  lib/services/keyvault/lib/models/secretSetParameters.js
  lib/services/keyvault/lib/models/secretUpdateParameters.js
  lib/services/keyvault/lib/models/storageAccountCreateParameters.js
  lib/services/keyvault/lib/models/storageAccountItem.js
  lib/services/keyvault/lib/models/storageAccountUpdateParameters.js
  lib/services/keyvault/lib/models/storageBundle.js
  lib/services/keyvault/lib/models/x509CertificateProperties.js
Labels: RestPRMerged

#3771 [AutoPR] domainservices/resource-manager
  lib/services/domainservicesManagement/LICENSE.txt
  lib/services/domainservicesManagement/README.md
  lib/services/domainservicesManagement/lib/domainservicesManagementClient.d.ts
  lib/services/domainservicesManagement/lib/domainservicesManagementClient.js
  lib/services/domainservicesManagement/lib/models/domainSecuritySettings.js
  lib/services/domainservicesManagement/lib/models/domainService.js
  lib/services/domainservicesManagement/lib/models/domainServiceListResult.js
  lib/services/domainservicesManagement/lib/models/domainServicePatchProperties.js
  lib/services/domainservicesManagement/lib/models/domainServiceProperties.js
  lib/services/domainservicesManagement/lib/models/healthAlert.js
  lib/services/domainservicesManagement/lib/models/healthMonitor.js
  lib/services/domainservicesManagement/lib/models/index.d.ts
  lib/services/domainservicesManagement/lib/models/index.js
  lib/services/domainservicesManagement/lib/models/notificationSettings.js
  lib/services/domainservicesManagement/lib/models/operationEntity.js
  lib/services/domainservicesManagement/lib/models/operationEntityListResult.js
  lib/services/domainservicesManagement/lib/operations/domainServiceOperations.js
  lib/services/domainservicesManagement/lib/operations/domainServices.js
  lib/services/domainservicesManagement/lib/operations/index.d.ts
  lib/services/domainservicesManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3772 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/dataFactoryManagementClient.d.ts
  lib/services/datafactoryManagement/lib/dataFactoryManagementClient.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/rerunTriggerListResponse.js
  lib/services/datafactoryManagement/lib/models/rerunTriggerResource.js
  lib/services/datafactoryManagement/lib/models/rerunTumblingWindowTrigger.js
  lib/services/datafactoryManagement/lib/models/rerunTumblingWindowTriggerActionParameters.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/index.js
  lib/services/datafactoryManagement/lib/operations/rerunTriggers.js
  lib/services/datafactoryManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3780 [AutoPR] containerregistry/resource-manager
  lib/services/containerRegistryManagement/lib/models/importImageParameters.js
  lib/services/containerRegistryManagement/lib/models/importSource.js
  lib/services/containerRegistryManagement/lib/models/importSourceCredentials.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/registry.js
  lib/services/containerRegistryManagement/lib/models/registryIdentity.js
  lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/registries.js
  lib/services/containerRegistryManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3786 [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Add Monitoring Configuration (Missing)
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/registeredServer.js
Labels: RestPRMerged, in progress

#3788 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3810 [AutoPR graphrbac/data-plane] Fix operation named missed in #3947
  lib/services/graphManagement/lib/operations/index.d.ts
  lib/services/graphManagement/lib/operations/oAuth2.js
Labels: RestPRMerged, in progress

#3807 [AutoPR cognitiveservices/data-plane/ComputerVision] Split Ocr out into own Swagger file
  lib/services/computerVision/lib/models/index.d.ts
  lib/services/computerVision/lib/models/index.js
  lib/services/computerVision/package.json
Labels: RestPRMerged, in progress

#3832 [AutoPR graphrbac/data-plane] [GraphRBAC] Add delete owner
  lib/services/graphManagement/lib/operations/applications.js
  lib/services/graphManagement/lib/operations/groups.js
  lib/services/graphManagement/lib/operations/index.d.ts
Labels: RestPRMerged

#3813 [AutoPR hdinsight/resource-manager] [HDInsight] Added support for MSI
  lib/services/hdInsightManagement/lib/models/cluster.js
  lib/services/hdInsightManagement/lib/models/clusterCreateParametersExtended.js
  lib/services/hdInsightManagement/lib/models/clusterIdentity.js
  lib/services/hdInsightManagement/lib/models/clusterIdentityUserAssignedIdentitiesValue.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/index.js
  lib/services/hdInsightManagement/lib/operations/clusters.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3855 [AutoPR] hdinsight/resource-manager
  lib/services/hdInsightManagement/lib/models/cluster.js
  lib/services/hdInsightManagement/lib/models/clusterCreateParametersExtended.js
  lib/services/hdInsightManagement/lib/models/clusterIdentity.js
  lib/services/hdInsightManagement/lib/models/clusterIdentityUserAssignedIdentitiesValue.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/index.js
  lib/services/hdInsightManagement/lib/operations/clusters.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
  lib/services/hdInsightManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3854 [AutoPR containerregistry/resource-manager] Revert the previous change: remove the identity properties
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/registry.js
  lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/registries.js
Labels: RestPRMerged, in progress

#3833 [AutoPR] graphrbac/data-plane
  lib/services/graphManagement/lib/operations/applications.js
  lib/services/graphManagement/lib/operations/groups.js
  lib/services/graphManagement/lib/operations/index.d.ts
  lib/services/graphManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3864 [AutoPR] containerregistry/resource-manager
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/registry.js
  lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/registries.js
  lib/services/containerRegistryManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3822 [AutoPR] cognitiveservices/data-plane/ComputerVision
  lib/services/computerVision/lib/models/index.d.ts
  lib/services/computerVision/lib/models/index.js
  lib/services/computerVision/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3783 [AutoPR network/resource-manager] Add ExpressRoutePort swagger
  lib/services/networkManagement2/lib/models/applicationGateway.js
  lib/services/networkManagement2/lib/models/applicationGatewayCustomError.js
  lib/services/networkManagement2/lib/models/applicationGatewayHttpListener.js
  lib/services/networkManagement2/lib/models/expressRouteCircuit.js
  lib/services/networkManagement2/lib/models/expressRouteLink.js
  lib/services/networkManagement2/lib/models/expressRouteLinkListResult.js
  lib/services/networkManagement2/lib/models/expressRoutePort.js
  lib/services/networkManagement2/lib/models/expressRoutePortListResult.js
  lib/services/networkManagement2/lib/models/expressRoutePortsLocation.js
  lib/services/networkManagement2/lib/models/expressRoutePortsLocationBandwidths.js
  lib/services/networkManagement2/lib/models/expressRoutePortsLocationListResult.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/lib/operations/applicationGateways.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuits.js
  lib/services/networkManagement2/lib/operations/expressRouteLinks.js
  lib/services/networkManagement2/lib/operations/expressRoutePorts.js
  lib/services/networkManagement2/lib/operations/expressRoutePortsLocations.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/index.js
Labels: RestPRMerged, in progress

#3757 [AutoPR consumption/resource-manager] Introducing New Version 2018-10-01 for Consumption API
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/managementGroupAggregatedCostResult.js
  lib/services/consumptionManagement/package.json
Labels: RestPRMerged, in progress

#3868 [AutoPR] consumption/resource-manager
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/managementGroupAggregatedCostResult.js
  lib/services/consumptionManagement/package.json
Labels: Planned-Sprint-125, ServicePR, Started-Sprint-125, in progress

#3866 [AutoPR apimanagement/resource-manager] add openid connect in authentication settings
  lib/services/apimanagement/lib/models/apiContract.js
  lib/services/apimanagement/lib/models/apiCreateOrUpdateParameter.js
  lib/services/apimanagement/lib/models/apiEntityBaseContract.js
  lib/services/apimanagement/lib/models/apiUpdateContract.js
  lib/services/apimanagement/lib/models/authenticationSettingsContract.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/index.js
  lib/services/apimanagement/lib/models/openIdAuthenticationSettingsContract.js
  lib/services/apimanagement/lib/operations/api.js
  lib/services/apimanagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3781 [AutoPR network/resource-manager] Remove error code from swagger
  lib/services/networkManagement2/lib/operations/expressRouteGateways.js
  lib/services/networkManagement2/package.json
Labels: RestPRMerged, in progress

#3815 [AutoPR automation/resource-manager] Swagger change for Update configuration dynamic group
  lib/services/automationManagement/lib/models/azureQueryProperties.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
  lib/services/automationManagement/lib/models/tagSettingsProperties.js
  lib/services/automationManagement/lib/models/targetProperties.js
  lib/services/automationManagement/lib/models/updateConfiguration.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Labels: RestPRMerged, in progress

#3879 [AutoPR applicationinsights/data-plane] [App Insights] Update python output folder
  lib/services/applicationinsights-query/LICENSE.txt
  lib/services/applicationinsights-query/README.md
  lib/services/applicationinsights-query/lib/models/index.d.ts
  lib/services/applicationinsights-query/lib/models/metricsPostBodySchemaParameters.js
  lib/services/applicationinsights-query/lib/models/table.js
  lib/services/applicationinsights-query/lib/operations/metrics.js
Labels: RestPRMerged, in progress

#3882 [AutoPR automation/resource-manager] Updating sync type property from PartialSync to IncrementalSync.
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/sourceControlSyncJob.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
Labels: RestPRMerged, in progress

#3870 [AutoPR resources/resource-manager] added descriptions for filter and expand
  lib/services/resourceManagement/lib/resource/operations/index.d.ts
  lib/services/resourceManagement/lib/resource/operations/resourceGroups.js
  lib/services/resourceManagement/lib/resource/operations/resources.js
Labels: RestPRMerged, in progress

#3886 [AutoPR network/resource-manager] Cherry pick NRP's changes from master to October branch
  lib/services/networkManagement2/lib/operations/expressRouteGateways.js
Labels: RestPRMerged, in progress

#3869 [AutoPR eventgrid/resource-manager] EventGrid: Update README files to include the current new preview api…
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFilter.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/index.js
Labels: RestPRMerged, in progress

#3874 [AutoPR containerservices/resource-manager] Support two apiversion for container service
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/lib/operations/operations.js
Labels: RestPRMerged, in progress

#3881 [AutoPR eventhub/resource-manager] EventHub: moved VNet, IpFilter rules and Kafka from 2018-preview to 2017 API Version
  lib/services/eventHubManagement/lib/models/eHNamespace.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/models/ipFilterRule.js
  lib/services/eventHubManagement/lib/models/ipFilterRuleListResult.js
  lib/services/eventHubManagement/lib/models/virtualNetworkRule.js
  lib/services/eventHubManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#3918 [AutoPR resources/resource-manager] added to description of allowed characters for resource group name
  lib/services/resourceManagement/lib/resource/operations/index.d.ts
  lib/services/resourceManagement/lib/resource/operations/resourceGroups.js
Labels: RestPRMerged, in progress

#3891 [AutoPR eventgrid/data-plane] Added missing discriminator property to MediaJobOutput
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/mediaJobCanceledEventData.js
  lib/services/eventgrid/lib/models/mediaJobErroredEventData.js
  lib/services/eventgrid/lib/models/mediaJobFinishedEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutput.js
  lib/services/eventgrid/lib/models/mediaJobOutputAsset.js
  lib/services/eventgrid/lib/models/mediaJobOutputCanceledEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutputCancelingEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutputErroredEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutputFinishedEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutputProcessingEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutputScheduledEventData.js
  lib/services/eventgrid/lib/models/mediaJobOutputStateChangeEventData.js
Labels: RestPRMerged, in progress

#3922 [AutoPR compute/resource-manager] Adding provisionAfterExtensions property for extension sequencing
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/virtualMachineExtension.js
  lib/services/computeManagement2/lib/models/virtualMachineExtensionUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetExtension.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetExtensions.js
Labels: RestPRMerged, in progress

#3893 [AutoPR monitor/resource-manager] add armRoleReceiver to ActionGroup API and update API version to 2018-09-01
  lib/services/monitorManagement/lib/models/actionGroupResource.js
  lib/services/monitorManagement/lib/models/armRoleReceiver.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/index.js
  lib/services/monitorManagement/lib/operations/actionGroups.js
  lib/services/monitorManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3930 Remove scheduler packages
  lib/services/scheduler/LICENSE.txt
  lib/services/scheduler/README.md
  lib/services/scheduler/lib/scheduler.js
  lib/services/scheduler/lib/schedulerClient.js
  lib/services/scheduler/package.json
  lib/services/schedulerManagement/LICENSE.txt
  lib/services/schedulerManagement/README.md
  lib/services/schedulerManagement/lib/cloudServiceManagementClient.js
  lib/services/schedulerManagement/lib/scheduler.js
  lib/services/schedulerManagement/lib/schedulerManagementClient.js
  lib/services/schedulerManagement/package.json
  lib/services/schedulerManagement2/LICENSE.txt
  lib/services/schedulerManagement2/README.md
  lib/services/schedulerManagement2/lib/models/basicAuthentication.js
  lib/services/schedulerManagement2/lib/models/clientCertAuthentication.js
  lib/services/schedulerManagement2/lib/models/httpAuthentication.js
  lib/services/schedulerManagement2/lib/models/httpRequest.js
  lib/services/schedulerManagement2/lib/models/index.d.ts
  lib/services/schedulerManagement2/lib/models/index.js
  lib/services/schedulerManagement2/lib/models/jobAction.js
  lib/services/schedulerManagement2/lib/models/jobCollectionDefinition.js
  lib/services/schedulerManagement2/lib/models/jobCollectionListResult.js
  lib/services/schedulerManagement2/lib/models/jobCollectionProperties.js
  lib/services/schedulerManagement2/lib/models/jobCollectionQuota.js
  lib/services/schedulerManagement2/lib/models/jobDefinition.js
  lib/services/schedulerManagement2/lib/models/jobErrorAction.js
  lib/services/schedulerManagement2/lib/models/jobHistoryDefinition.js
  lib/services/schedulerManagement2/lib/models/jobHistoryDefinitionProperties.js
  lib/services/schedulerManagement2/lib/models/jobHistoryFilter.js
  lib/services/schedulerManagement2/lib/models/jobHistoryListResult.js
  lib/services/schedulerManagement2/lib/models/jobListResult.js
  lib/services/schedulerManagement2/lib/models/jobMaxRecurrence.js
  lib/services/schedulerManagement2/lib/models/jobProperties.js
  lib/services/schedulerManagement2/lib/models/jobRecurrence.js
  lib/services/schedulerManagement2/lib/models/jobRecurrenceSchedule.js
  lib/services/schedulerManagement2/lib/models/jobRecurrenceScheduleMonthlyOccurrence.js
  lib/services/schedulerManagement2/lib/models/jobStateFilter.js
  lib/services/schedulerManagement2/lib/models/jobStatus.js
  lib/services/schedulerManagement2/lib/models/oAuthAuthentication.js
  lib/services/schedulerManagement2/lib/models/retryPolicy.js
  lib/services/schedulerManagement2/lib/models/serviceBusAuthentication.js
  lib/services/schedulerManagement2/lib/models/serviceBusBrokeredMessageProperties.js
  lib/services/schedulerManagement2/lib/models/serviceBusMessage.js
  lib/services/schedulerManagement2/lib/models/serviceBusQueueMessage.js
  lib/services/schedulerManagement2/lib/models/serviceBusTopicMessage.js
  lib/services/schedulerManagement2/lib/models/sku.js
  lib/services/schedulerManagement2/lib/models/storageQueueMessage.js
  lib/services/schedulerManagement2/lib/operations/index.d.ts
  lib/services/schedulerManagement2/lib/operations/index.js
  lib/services/schedulerManagement2/lib/operations/jobCollections.js
  lib/services/schedulerManagement2/lib/operations/jobs.js
  lib/services/schedulerManagement2/lib/schedulerManagementClient.d.ts
  lib/services/schedulerManagement2/lib/schedulerManagementClient.js
  lib/services/schedulerManagement2/package.json
Labels: Planned-Sprint-125, Started-Sprint-125

#3928 [AutoPR storagesync/resource-manager] StorageSync ResourceProvider : Bug Fix to change parameter name
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/triggerRolloverRequest.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
Labels: RestPRMerged, in progress

#3929 [AutoPR] monitor/resource-manager
  lib/services/monitorManagement/lib/models/actionGroupResource.js
  lib/services/monitorManagement/lib/models/armRoleReceiver.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/index.js
  lib/services/monitorManagement/lib/operations/actionGroups.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3919 [AutoPR] eventhub/resource-manager
  lib/services/eventHubManagement/lib/models/eHNamespace.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/models/ipFilterRule.js
  lib/services/eventHubManagement/lib/models/ipFilterRuleListResult.js
  lib/services/eventHubManagement/lib/models/virtualNetworkRule.js
  lib/services/eventHubManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
  lib/services/eventHubManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3887 [AutoPR] servicebus/resource-manager
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/index.js
  lib/services/serviceBusManagement2/lib/models/ipFilterRule.js
  lib/services/serviceBusManagement2/lib/models/ipFilterRuleListResult.js
  lib/services/serviceBusManagement2/lib/models/virtualNetworkRule.js
  lib/services/serviceBusManagement2/lib/models/virtualNetworkRuleListResult.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/namespaces.js
  lib/services/serviceBusManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3885 [AutoPR] resources/resource-manager
  lib/services/resourceManagement/lib/resource/operations/index.d.ts
  lib/services/resourceManagement/lib/resource/operations/resourceGroups.js
  lib/services/resourceManagement/lib/resource/operations/resources.js
  lib/services/resourceManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3888 [AutoPR servicebus/resource-manager] ServiceBus : Added namespace Migrate API reported in ARMs Fundamental dashboard
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/index.js
  lib/services/serviceBusManagement2/lib/models/sBNamespaceMigrate.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#3924 [AutoPR automation/resource-manager] Reverting change: Replacing PartialSync for IncrementalSync for sync type and updating examples.
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/sourceControlSyncJob.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
Labels: RestPRMerged, in progress

#3883 [AutoPR] applicationinsights/data-plane
  lib/services/applicationinsights-query/LICENSE.txt
  lib/services/applicationinsights-query/README.md
  lib/services/applicationinsights-query/lib/models/index.d.ts
  lib/services/applicationinsights-query/lib/models/metricsPostBodySchemaParameters.js
  lib/services/applicationinsights-query/lib/models/table.js
  lib/services/applicationinsights-query/lib/operations/metrics.js
  lib/services/applicationinsights-query/package.json
Labels: Planned-Sprint-126, ServicePR, in progress

#3876 [AutoPR] automation/resource-manager
  lib/services/automationManagement/lib/models/azureQueryProperties.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
  lib/services/automationManagement/lib/models/tagSettingsProperties.js
  lib/services/automationManagement/lib/models/targetProperties.js
  lib/services/automationManagement/lib/models/updateConfiguration.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
  lib/services/automationManagement/package.json
Labels: Planned-Sprint-126, ServicePR, in progress

#3875 [AutoPR] containerservices/resource-manager
  lib/services/containerservicesManagement/README.md
  lib/services/containerservicesManagement/lib/containerServiceClient.d.ts
  lib/services/containerservicesManagement/lib/containerServiceClient.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/index.js
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/networkProfile.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedCluster.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterAADIdentityProvider.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterAuthProfile.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterBaseIdentityProvider.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterIdentityProvider.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterMasterPoolProfile.js
  lib/services/containerservicesManagement/lib/models/openShiftRouterProfile.js
  lib/services/containerservicesManagement/lib/models/purchasePlan.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/index.js
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
  lib/services/containerservicesManagement/lib/operations/operations.js
  lib/services/containerservicesManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3873 [AutoPR] network/resource-manager
  lib/services/networkManagement2/lib/operations/expressRouteGateways.js
  lib/services/networkManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, in progress

#3872 [AutoPR] apimanagement/resource-manager
  lib/services/apimanagement/lib/models/apiContract.js
  lib/services/apimanagement/lib/models/apiCreateOrUpdateParameter.js
  lib/services/apimanagement/lib/models/apiEntityBaseContract.js
  lib/services/apimanagement/lib/models/apiUpdateContract.js
  lib/services/apimanagement/lib/models/authenticationSettingsContract.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/index.js
  lib/services/apimanagement/lib/models/openIdAuthenticationSettingsContract.js
  lib/services/apimanagement/lib/operations/api.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3936 [AutoPR] servicebus/resource-manager
  lib/services/serviceBusManagement2/lib/models/sBNamespaceMigrate.js
  lib/services/serviceBusManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, in progress

#3931 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/triggerRolloverRequest.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3939 [AutoPR sql/resource-manager] Fixed spelling mistake in SQL documentation
  lib/services/sqlManagement2/lib/models/backupLongTermRetentionPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/operations/backupLongTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3933 [AutoPR datafactory/resource-manager] Revert PR #4258: "Swagger changes for connectors: Google AdWords, Oracle Service Cloud, OData, Rest Service, Dynamics AX and support for wildcardPath."
  lib/services/datafactoryManagement/lib/models/amazonS3Dataset.js
  lib/services/datafactoryManagement/lib/models/azureBlobDataset.js
  lib/services/datafactoryManagement/lib/models/azureDataLakeStoreDataset.js
  lib/services/datafactoryManagement/lib/models/fileShareDataset.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/oDataLinkedService.js
  lib/services/datafactoryManagement/lib/models/storedProcedureParameter.js
Labels: RestPRMerged, in progress

#3945 [AutoPR storagesync/resource-manager] Microsoft.StorageSync Change Host name from swagger spec
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
Labels: RestPRMerged, in progress

#3921 [AutoPR compute/resource-manager] Added Reimage API support for ephemeral os disks in single VM
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineReimageParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetReimageParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMReimageParameters.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#3953 [AutoPR consumption/resource-manager] Introducing Marketplaces at Management Group Level
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/marketplaces.js
Labels: RestPRMerged, in progress

#3938 [AutoPR] automation/resource-manager
  lib/services/automationManagement/lib/models/azureQueryProperties.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/softareUpdateConfigurationRunTaskProperties.js
  lib/services/automationManagement/lib/models/softareUpdateConfigurationRunTasks.js
  lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
  lib/services/automationManagement/lib/models/softwareUpdateConfigurationMachineRun.js
  lib/services/automationManagement/lib/models/softwareUpdateConfigurationRun.js
  lib/services/automationManagement/lib/models/softwareUpdateConfigurationTasks.js
  lib/services/automationManagement/lib/models/taskProperties.js
  lib/services/automationManagement/lib/models/tasksProperties.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
  lib/services/automationManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3941 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/backupLongTermRetentionPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/operations/backupLongTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3947 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
  lib/services/storagesyncManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3949 [AutoPR] compute/resource-manager
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineReimageParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetReimageParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMReimageParameters.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
  lib/services/computeManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3955 [AutoPR] consumption/resource-manager
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/marketplaces.js
  lib/services/consumptionManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3959 Regenerate azure-arm-website
  lib/services/websiteManagement2/package.json
Labels: Planned-Sprint-126, Started-Sprint-126, in progress

#3963 [AutoPR mariadb/resource-manager] Add Vnet resource for Microsoft.DBforMariaDB
  lib/services/mariadbManagement/lib/mariaDBManagementClient.d.ts
  lib/services/mariadbManagement/lib/mariaDBManagementClient.js
  lib/services/mariadbManagement/lib/models/index.d.ts
  lib/services/mariadbManagement/lib/models/index.js
  lib/services/mariadbManagement/lib/models/virtualNetworkRule.js
  lib/services/mariadbManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/mariadbManagement/lib/operations/index.d.ts
  lib/services/mariadbManagement/lib/operations/index.js
  lib/services/mariadbManagement/lib/operations/virtualNetworkRules.js
  lib/services/mariadbManagement/package.json
Labels: RestPRMerged, in progress

#3968 Remove preview version suffix from azure-arm-iotcentral
  lib/services/iotcentralManagement/package.json
Labels: Planned-Sprint-126, Started-Sprint-126, in progress

#3950 [AutoPR eventhub/resource-manager] EventHub : Revert PR 4246 from 2017 and added Kafka enabled
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#3972 [AutoPR signalr/resource-manager] Oct10
  lib/services/signalrManagement/LICENSE.txt
  lib/services/signalrManagement/README.md
  lib/services/signalrManagement/lib/operations/operations.js
  lib/services/signalrManagement/lib/operations/signalR.js
  lib/services/signalrManagement/lib/operations/usages.js
  lib/services/signalrManagement/lib/signalRManagementClient.js
Labels: RestPRMerged, in progress

#3952 [AutoPR servicebus/resource-manager] Service Bus: Revert PR 4245 from 2017
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/index.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#3977 [AutoPR graphrbac/data-plane] Fix #4346 - RequiredResourceAccess missing on GET
  lib/services/graphManagement/lib/models/application.js
  lib/services/graphManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#3970 [AutoPR] eventhub/resource-manager
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
  lib/services/eventHubManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3973 [AutoPR] signalr/resource-manager
  lib/services/signalrManagement/LICENSE.txt
  lib/services/signalrManagement/README.md
  lib/services/signalrManagement/lib/operations/operations.js
  lib/services/signalrManagement/lib/operations/signalR.js
  lib/services/signalrManagement/lib/operations/usages.js
  lib/services/signalrManagement/lib/signalRManagementClient.js
  lib/services/signalrManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3974 [AutoPR] servicebus/resource-manager
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/index.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/namespaces.js
  lib/services/serviceBusManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3978 [AutoPR] graphrbac/data-plane
  lib/services/graphManagement/lib/models/application.js
  lib/services/graphManagement/lib/models/index.d.ts
  lib/services/graphManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3976 [AutoPR storage/resource-manager] Support for SRP BlobServiceProperties API
  lib/services/storageManagement2/lib/models/blobServiceProperties.js
  lib/services/storageManagement2/lib/models/corsRule.js
  lib/services/storageManagement2/lib/models/corsRules.js
  lib/services/storageManagement2/lib/models/deleteRetentionPolicy.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/operations/blobServices.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
Labels: RestPRMerged, in progress

#3979 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/lib/models/blobServiceProperties.js
  lib/services/storageManagement2/lib/models/corsRule.js
  lib/services/storageManagement2/lib/models/corsRules.js
  lib/services/storageManagement2/lib/models/deleteRetentionPolicy.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/operations/blobServices.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
  lib/services/storageManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3966 [AutoPR sql/resource-manager] Update BlobAuditing swaggers to support Azure Monitor audit target
  lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
Labels: RestPRMerged, in progress

#3985 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedDatabaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/extendedServerBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/serverBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedDatabaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/extendedServerBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/serverBlobAuditingPolicies.js
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3991 [AutoPR hdinsight/resource-manager] [HDInsight] Fixed non-existent extra parameter (bug)
  lib/services/hdInsightManagement/lib/models/application.js
  lib/services/hdInsightManagement/lib/models/applicationGetHttpsEndpoint.js
  lib/services/hdInsightManagement/lib/models/applicationProperties.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/operations/applications.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3993 [AutoPR] hdinsight/resource-manager
  lib/services/hdInsightManagement/lib/models/application.js
  lib/services/hdInsightManagement/lib/models/applicationGetHttpsEndpoint.js
  lib/services/hdInsightManagement/lib/models/applicationProperties.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/operations/applications.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
  lib/services/hdInsightManagement/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress

#3994 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/databaseVulnerabilityAssessment.js
  lib/services/sqlManagement2/lib/models/databaseVulnerabilityAssessmentListResult.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/managedDatabaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-126, ServicePR, Started-Sprint-126, in progress
