Repository Azure/azure-sdk-for-node, pull requests merged in 2018-09, with the labels that each got.

#3478 Update swagger_to_sdk_config.json file
  swagger_to_sdk_config.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3437 [AutoPR authorization/resource-manager] Grlin/Adding Principal Type to RA
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/providerOperationsMetadata.js
  lib/services/authorizationManagement/lib/models/resourceType.js
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/models/roleDefinition.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/permissions.js
  lib/services/authorizationManagement/lib/operations/providerOperationsMetadataOperations.js
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
  lib/services/authorizationManagement/lib/operations/roleDefinitions.js
  lib/services/authorizationManagement/package.json
Labels: RestPRMerged, in progress

#3487 Add --whatif parameter to gulpfile
  gulpfile.js
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3486 [AutoPR] authorization/resource-manager
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/permissions.js
  lib/services/authorizationManagement/lib/operations/providerOperationsMetadataOperations.js
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
  lib/services/authorizationManagement/lib/operations/roleDefinitions.js
  lib/services/authorizationManagement/package-lock.json
  lib/services/authorizationManagement/package.json
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_assign_Key_Vault_the_operator_role_on_a_storage_account.nock.js
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3488 Regenerate azure-arm-analysisservices and update version to 2.2.2-pre…
  lib/services/analysisServices/lib/analysisServicesManagementClient.d.ts
  lib/services/analysisServices/lib/analysisServicesManagementClient.js
  lib/services/analysisServices/lib/models/analysisServicesServerUpdateParameters.js
  lib/services/analysisServices/lib/models/gatewayListStatusError.js
  lib/services/analysisServices/lib/models/iPv4FirewallSettings.js
  lib/services/analysisServices/lib/models/operation.js
  lib/services/analysisServices/lib/models/operationStatus.js
  lib/services/analysisServices/lib/models/skuDetailsForExistingResource.js
  lib/services/analysisServices/lib/models/skuEnumerationForExistingResourceResult.js
  lib/services/analysisServices/lib/models/skuEnumerationForNewResourceResult.js
  lib/services/analysisServices/package-lock.json
  lib/services/analysisServices/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3491 Generate azure-arm-databricks
  lib/services/databricksManagement/LICENSE.txt
  lib/services/databricksManagement/README.md
  lib/services/databricksManagement/lib/databricksClient.d.ts
  lib/services/databricksManagement/lib/databricksClient.js
  lib/services/databricksManagement/lib/models/errorDetail.js
  lib/services/databricksManagement/lib/models/errorInfo.js
  lib/services/databricksManagement/lib/models/errorResponse.js
  lib/services/databricksManagement/lib/models/index.d.ts
  lib/services/databricksManagement/lib/models/index.js
  lib/services/databricksManagement/lib/models/operation.js
  lib/services/databricksManagement/lib/models/operationDisplay.js
  lib/services/databricksManagement/lib/models/operationListResult.js
  lib/services/databricksManagement/lib/models/resource.js
  lib/services/databricksManagement/lib/models/sku.js
  lib/services/databricksManagement/lib/models/trackedResource.js
  lib/services/databricksManagement/lib/models/workspace.js
  lib/services/databricksManagement/lib/models/workspaceListResult.js
  lib/services/databricksManagement/lib/models/workspaceProviderAuthorization.js
  lib/services/databricksManagement/lib/models/workspaceUpdate.js
  lib/services/databricksManagement/lib/operations/index.d.ts
  lib/services/databricksManagement/lib/operations/index.js
  lib/services/databricksManagement/lib/operations/operations.js
  lib/services/databricksManagement/lib/operations/workspaces.js
  lib/services/databricksManagement/package-lock.json
  lib/services/databricksManagement/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3496 Generate azure-arm-maps
  lib/services/mapsManagement/LICENSE.txt
  lib/services/mapsManagement/README.md
  lib/services/mapsManagement/lib/mapsManagementClient.d.ts
  lib/services/mapsManagement/lib/mapsManagementClient.js
  lib/services/mapsManagement/lib/models/errorDetailsItem.js
  lib/services/mapsManagement/lib/models/errorModel.js
  lib/services/mapsManagement/lib/models/index.d.ts
  lib/services/mapsManagement/lib/models/index.js
  lib/services/mapsManagement/lib/models/mapsAccount.js
  lib/services/mapsManagement/lib/models/mapsAccountCreateParameters.js
  lib/services/mapsManagement/lib/models/mapsAccountKeys.js
  lib/services/mapsManagement/lib/models/mapsAccountUpdateParameters.js
  lib/services/mapsManagement/lib/models/mapsAccounts.js
  lib/services/mapsManagement/lib/models/mapsAccountsMoveRequest.js
  lib/services/mapsManagement/lib/models/mapsKeySpecification.js
  lib/services/mapsManagement/lib/models/mapsOperations.js
  lib/services/mapsManagement/lib/models/mapsOperationsValueItem.js
  lib/services/mapsManagement/lib/models/mapsOperationsValueItemDisplay.js
  lib/services/mapsManagement/lib/models/resource.js
  lib/services/mapsManagement/lib/models/sku.js
  lib/services/mapsManagement/lib/operations/accounts.js
  lib/services/mapsManagement/lib/operations/index.d.ts
  lib/services/mapsManagement/lib/operations/index.js
  lib/services/mapsManagement/package-lock.json
  lib/services/mapsManagement/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3498 Generate azure-arm-reservations and update version to 2.0.0-preview
  lib/services/reservationsManagement/LICENSE.txt
  lib/services/reservationsManagement/README.md
  lib/services/reservationsManagement/lib/azureReservationAPI.d.ts
  lib/services/reservationsManagement/lib/azureReservationAPI.js
  lib/services/reservationsManagement/lib/models/appliedReservations.js
  lib/services/reservationsManagement/lib/models/catalog.js
  lib/services/reservationsManagement/lib/models/errorModel.js
  lib/services/reservationsManagement/lib/models/extendedErrorInfo.js
  lib/services/reservationsManagement/lib/models/index.d.ts
  lib/services/reservationsManagement/lib/models/index.js
  lib/services/reservationsManagement/lib/models/operationResponse.js
  lib/services/reservationsManagement/lib/models/patch.js
  lib/services/reservationsManagement/lib/models/reservationOrderResponse.js
  lib/services/reservationsManagement/lib/models/reservationProperties.js
  lib/services/reservationsManagement/lib/models/reservationResponse.js
  lib/services/reservationsManagement/lib/models/skuProperty.js
  lib/services/reservationsManagement/lib/operations/index.d.ts
  lib/services/reservationsManagement/lib/operations/reservation.js
  lib/services/reservationsManagement/package-lock.json
  lib/services/reservationsManagement/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3471 [AutoPR dns/resource-manager] Dev dns microsoft.network 2018 05 01
  lib/services/dnsManagement/lib/dnsManagementClient.d.ts
  lib/services/dnsManagement/lib/dnsManagementClient.js
  lib/services/dnsManagement/lib/models/dnsResourceReference.js
  lib/services/dnsManagement/lib/models/dnsResourceReferenceRequest.js
  lib/services/dnsManagement/lib/models/dnsResourceReferenceResult.js
  lib/services/dnsManagement/lib/models/index.d.ts
  lib/services/dnsManagement/lib/models/index.js
  lib/services/dnsManagement/lib/models/recordSet.js
  lib/services/dnsManagement/lib/models/recordSetUpdateParameters.js
  lib/services/dnsManagement/lib/models/resource.js
  lib/services/dnsManagement/lib/models/zone.js
  lib/services/dnsManagement/lib/operations/dnsResourceReferenceOperations.js
  lib/services/dnsManagement/lib/operations/index.d.ts
  lib/services/dnsManagement/lib/operations/index.js
  lib/services/dnsManagement/lib/operations/recordSets.js
  lib/services/dnsManagement/lib/operations/zones.js
  lib/services/dnsManagement/package.json
Labels: RestPRMerged, in progress

#3499 Generate azure-arm-timeseriesinsights
  lib/services/timeseriesinsightsManagement/LICENSE.txt
  lib/services/timeseriesinsightsManagement/README.md
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyResource.js
  lib/services/timeseriesinsightsManagement/lib/models/accessPolicyUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/azureEventSourceProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/createOrUpdateTrackedResourceProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentResource.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentStateDetails.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentStatus.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceCommonProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceResource.js
  lib/services/timeseriesinsightsManagement/lib/models/eventHubEventSourceUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceCommonProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceMutableProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceResource.js
  lib/services/timeseriesinsightsManagement/lib/models/eventSourceUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/index.d.ts
  lib/services/timeseriesinsightsManagement/lib/models/index.js
  lib/services/timeseriesinsightsManagement/lib/models/ingressEnvironmentStatus.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceCommonProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceResource.js
  lib/services/timeseriesinsightsManagement/lib/models/ioTHubEventSourceUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/localTimestamp.js
  lib/services/timeseriesinsightsManagement/lib/models/localTimestampTimeZoneOffset.js
  lib/services/timeseriesinsightsManagement/lib/models/operation.js
  lib/services/timeseriesinsightsManagement/lib/models/operationDisplay.js
  lib/services/timeseriesinsightsManagement/lib/models/operationListResult.js
  lib/services/timeseriesinsightsManagement/lib/models/partitionKeyProperty.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetCreateOrUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetKeyProperty.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetListResponse.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetResource.js
  lib/services/timeseriesinsightsManagement/lib/models/referenceDataSetUpdateParameters.js
  lib/services/timeseriesinsightsManagement/lib/models/resource.js
  lib/services/timeseriesinsightsManagement/lib/models/resourceProperties.js
  lib/services/timeseriesinsightsManagement/lib/models/sku.js
  lib/services/timeseriesinsightsManagement/lib/models/trackedResource.js
  lib/services/timeseriesinsightsManagement/lib/operations/accessPolicies.js
  lib/services/timeseriesinsightsManagement/lib/operations/environments.js
  lib/services/timeseriesinsightsManagement/lib/operations/eventSources.js
  lib/services/timeseriesinsightsManagement/lib/operations/index.d.ts
  lib/services/timeseriesinsightsManagement/lib/operations/index.js
  lib/services/timeseriesinsightsManagement/lib/operations/operations.js
  lib/services/timeseriesinsightsManagement/lib/operations/referenceDataSets.js
  lib/services/timeseriesinsightsManagement/lib/timeSeriesInsightsClient.d.ts
  lib/services/timeseriesinsightsManagement/lib/timeSeriesInsightsClient.js
  lib/services/timeseriesinsightsManagement/package-lock.json
  lib/services/timeseriesinsightsManagement/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3503 [AutoPR] dns/resource-manager
  lib/services/dnsManagement/lib/models/dnsResourceReference.js
  lib/services/dnsManagement/lib/models/dnsResourceReferenceRequest.js
  lib/services/dnsManagement/lib/models/dnsResourceReferenceResult.js
  lib/services/dnsManagement/lib/operations/dnsResourceReferenceOperations.js
  lib/services/dnsManagement/package-lock.json
  lib/services/dnsManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3500 Update generator version to 2.1.99
  swagger_to_sdk_config.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3493 [AutoPR containerinstance/resource-manager] Container Instance: Adding September Update
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/containerGroupDiagnostics.js
  lib/services/containerinstanceManagement/lib/models/containerGroupNetworkProfile.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/logAnalytics.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: RestPRMerged, in progress

#3509 [AutoPR] containerinstance/resource-manager
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/containerGroupDiagnostics.js
  lib/services/containerinstanceManagement/lib/models/containerGroupNetworkProfile.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/logAnalytics.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package-lock.json
  lib/services/containerinstanceManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3514 Update publish script to use npm-auth env variable and set access to …
  gulpfile.js
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3516 Fix npm authentication during CI publish
  gulpfile.js
Labels: Planned-Sprint-123, Started-Sprint-123, in progress

#3521 [AutoPR] monitor/resource-manager
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/index.js
  lib/services/monitorManagement/lib/models/metricNamespace.js
  lib/services/monitorManagement/lib/models/metricNamespaceCollection.js
  lib/services/monitorManagement/lib/models/metricNamespaceName.js
  lib/services/monitorManagement/lib/monitorManagementClient.d.ts
  lib/services/monitorManagement/lib/monitorManagementClient.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/lib/operations/index.js
  lib/services/monitorManagement/lib/operations/metricNamespaces.js
  lib/services/monitorManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3462 [AutoPR eventgrid/resource-manager] EventGrid management APIs: Swagger for new Preview API version
  lib/services/eventgridManagement/package.json
Labels: RestPRMerged, in progress

#3522 [AutoPR] eventgrid/resource-manager
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/operation.js
  lib/services/eventgridManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3523 [AutoPR containerinstance/resource-manager] Container Instance: Add Private for Ip Address Enum
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: RestPRMerged, in progress

#3525 [AutoPR containerregistry/resource-manager] ACR conf for 2018-09 and Python
  lib/services/containerRegistryManagement/lib/models/eventContent.js
  lib/services/containerRegistryManagement/lib/models/eventRequestMessage.js
  lib/services/containerRegistryManagement/lib/models/imageUpdateTrigger.js
  lib/services/containerRegistryManagement/lib/models/importImageParameters.js
  lib/services/containerRegistryManagement/lib/models/operationDefinition.js
  lib/services/containerRegistryManagement/lib/models/operationServiceSpecificationDefinition.js
  lib/services/containerRegistryManagement/lib/models/registryListCredentialsResult.js
  lib/services/containerRegistryManagement/lib/models/registryPolicies.js
  lib/services/containerRegistryManagement/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/registryUsageListResult.js
  lib/services/containerRegistryManagement/lib/models/sourceProperties.js
  lib/services/containerRegistryManagement/lib/models/sourceTrigger.js
  lib/services/containerRegistryManagement/lib/models/sourceTriggerUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/sourceUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/taskStepProperties.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/triggerProperties.js
  lib/services/containerRegistryManagement/lib/models/triggerUpdateParameters.js
  lib/services/containerRegistryManagement/package.json
Labels: RestPRMerged

#3524 [AutoPR] containerinstance/resource-manager
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3539 [AutoPR containerservices/resource-manager] [AKS] note that only one agent pool is currently supported
  lib/services/containerservicesManagement/lib/models/containerServiceDiagnosticsProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceLinuxProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceServicePrincipalProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceSshConfiguration.js
  lib/services/containerservicesManagement/lib/models/credentialResults.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/models/managedClusterUpgradeProfile.js
  lib/services/containerservicesManagement/lib/models/orchestratorVersionProfile.js
  lib/services/containerservicesManagement/lib/models/orchestratorVersionProfileListResult.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/package.json
Labels: RestPRMerged

#3540 [AutoPR] containerservices/resource-manager
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3546 [AutoPR network/resource-manager] vtapswaggerupdate
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/networkInterface.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkInterfaces.js
Labels: RestPRMerged

#3550 [AutoPR resources/resource-manager] Fix ARMViolation Error for Microsoft.Authorization
  lib/services/resourceManagement/lib/lock/managementLockClient.d.ts
  lib/services/resourceManagement/lib/lock/managementLockClient.js
  lib/services/resourceManagement/lib/lock/models/index.d.ts
  lib/services/resourceManagement/lib/lock/models/index.js
  lib/services/resourceManagement/lib/lock/models/managementLockObject.js
  lib/services/resourceManagement/lib/lock/models/operation.js
  lib/services/resourceManagement/lib/lock/models/operationDisplay.js
  lib/services/resourceManagement/lib/lock/models/operationListResult.js
  lib/services/resourceManagement/lib/lock/operations/index.d.ts
  lib/services/resourceManagement/lib/lock/operations/managementLocks.js
Labels: RestPRMerged, in progress

#3543 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/azureDatabricksLinkedService.js
  lib/services/datafactoryManagement/lib/models/gitHubAccessTokenRequest.js
  lib/services/datafactoryManagement/lib/models/gitHubAccessTokenResponse.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/operations/factories.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3553 [AutoPR] resources/resource-manager
  lib/services/resourceManagement/lib/lock/managementLockClient.d.ts
  lib/services/resourceManagement/lib/lock/managementLockClient.js
  lib/services/resourceManagement/lib/lock/models/index.d.ts
  lib/services/resourceManagement/lib/lock/models/index.js
  lib/services/resourceManagement/lib/lock/models/managementLockObject.js
  lib/services/resourceManagement/lib/lock/models/operation.js
  lib/services/resourceManagement/lib/lock/models/operationDisplay.js
  lib/services/resourceManagement/lib/lock/models/operationListResult.js
  lib/services/resourceManagement/lib/lock/operations/index.d.ts
  lib/services/resourceManagement/lib/lock/operations/managementLocks.js
  lib/services/resourceManagement/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3470 [AutoPR logic/resource-manager] Change some string Microsoft.Logic modeled enums back into enums
  lib/services/logicManagement/lib/models/edifactDelimiterOverride.js
  lib/services/logicManagement/lib/models/edifactFramingSettings.js
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/index.js
  lib/services/logicManagement/lib/models/integrationAccountAgreement.js
  lib/services/logicManagement/lib/models/integrationAccountAgreementFilter.js
  lib/services/logicManagement/lib/models/recurrenceSchedule.js
  lib/services/logicManagement/lib/models/recurrenceScheduleOccurrence.js
  lib/services/logicManagement/lib/models/trackingEvent.js
  lib/services/logicManagement/lib/models/x12DelimiterOverrides.js
  lib/services/logicManagement/lib/models/x12FramingSettings.js
  lib/services/logicManagement/lib/operations/integrationAccountSessions.js
  lib/services/logicManagement/package.json
Labels: RestPRMerged, in progress

#3556 [AutoPR] logic/resource-manager
  lib/services/logicManagement/lib/models/edifactDelimiterOverride.js
  lib/services/logicManagement/lib/models/edifactFramingSettings.js
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/index.js
  lib/services/logicManagement/lib/models/integrationAccountAgreement.js
  lib/services/logicManagement/lib/models/integrationAccountAgreementFilter.js
  lib/services/logicManagement/lib/models/recurrenceSchedule.js
  lib/services/logicManagement/lib/models/recurrenceScheduleOccurrence.js
  lib/services/logicManagement/lib/models/trackingEvent.js
  lib/services/logicManagement/lib/models/x12DelimiterOverrides.js
  lib/services/logicManagement/lib/models/x12FramingSettings.js
  lib/services/logicManagement/lib/operations/integrationAccountSessions.js
  lib/services/logicManagement/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3554 [AutoPR authorization/resource-manager] Grlin/updatingReqsforRA
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
  lib/services/authorizationManagement/package.json
Labels: RestPRMerged, in progress

#3504 [AutoPR web/resource-manager] Add new OsType parameters for Microsoft.Web/availablestacks
  lib/services/websiteManagement2/LICENSE.txt
  lib/services/websiteManagement2/README.md
  lib/services/websiteManagement2/lib/models/abnormalTimePeriod.js
  lib/services/websiteManagement2/lib/models/addressResponse.js
  lib/services/websiteManagement2/lib/models/analysisData.js
  lib/services/websiteManagement2/lib/models/appServiceEnvironment.js
  lib/services/websiteManagement2/lib/models/applicationLogsConfig.js
  lib/services/websiteManagement2/lib/models/applicationStack.js
  lib/services/websiteManagement2/lib/models/autoHealActions.js
  lib/services/websiteManagement2/lib/models/autoHealRules.js
  lib/services/websiteManagement2/lib/models/autoHealTriggers.js
  lib/services/websiteManagement2/lib/models/contact.js
  lib/services/websiteManagement2/lib/models/csmOperationDescription.js
  lib/services/websiteManagement2/lib/models/csmOperationDescriptionProperties.js
  lib/services/websiteManagement2/lib/models/csmUsageQuota.js
  lib/services/websiteManagement2/lib/models/dataSource.js
  lib/services/websiteManagement2/lib/models/dataTableResponseObject.js
  lib/services/websiteManagement2/lib/models/defaultErrorResponse.js
  lib/services/websiteManagement2/lib/models/defaultErrorResponseError.js
  lib/services/websiteManagement2/lib/models/deploymentLocations.js
  lib/services/websiteManagement2/lib/models/detectorAbnormalTimePeriod.js
  lib/services/websiteManagement2/lib/models/diagnosticData.js
  lib/services/websiteManagement2/lib/models/diagnosticMetricSet.js
  lib/services/websiteManagement2/lib/models/errorEntity.js
  lib/services/websiteManagement2/lib/models/experiments.js
  lib/services/websiteManagement2/lib/models/globalCsmSkuDescription.js
  lib/services/websiteManagement2/lib/models/httpLogsConfig.js
  lib/services/websiteManagement2/lib/models/metricSpecification.js
  lib/services/websiteManagement2/lib/models/operation.js
  lib/services/websiteManagement2/lib/models/perfMonResponse.js
  lib/services/websiteManagement2/lib/models/perfMonSet.js
  lib/services/websiteManagement2/lib/models/privateAccessVirtualNetwork.js
  lib/services/websiteManagement2/lib/models/resourceMetric.js
  lib/services/websiteManagement2/lib/models/resourceMetricValue.js
  lib/services/websiteManagement2/lib/models/responseMetaData.js
  lib/services/websiteManagement2/lib/models/serviceSpecification.js
  lib/services/websiteManagement2/lib/models/siteCloneability.js
  lib/services/websiteManagement2/lib/models/siteConfig.js
  lib/services/websiteManagement2/lib/models/skuDescription.js
  lib/services/websiteManagement2/lib/models/skuInfo.js
  lib/services/websiteManagement2/lib/models/skuInfos.js
  lib/services/websiteManagement2/lib/models/solution.js
  lib/services/websiteManagement2/lib/models/stackMajorVersion.js
  lib/services/websiteManagement2/lib/models/validateResponse.js
  lib/services/websiteManagement2/lib/models/virtualApplication.js
  lib/services/websiteManagement2/lib/operations/index.d.ts
  lib/services/websiteManagement2/lib/operations/provider.js
  lib/services/websiteManagement2/package.json
Labels: RestPRMerged, in progress

#3537 [AutoPR sql/resource-manager] Remove sensitivityLabels from sql readme.md
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
  lib/services/sqlManagement2/package.json
Labels: RestPRMerged, in progress

#3558 [AutoPR] authorization/resource-manager
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
  lib/services/authorizationManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3560 [AutoPR] web/resource-manager
  lib/services/websiteManagement2/LICENSE.txt
  lib/services/websiteManagement2/README.md
  lib/services/websiteManagement2/lib/operations/index.d.ts
  lib/services/websiteManagement2/lib/operations/provider.js
  lib/services/websiteManagement2/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3561 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3562 [AutoPR network/resource-manager] changes to swagger in interface endpoints and subnet delegation
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/interfaceEndpoint.js
  lib/services/networkManagement2/lib/models/networkInterface.js
  lib/services/networkManagement2/lib/models/subnet.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/interfaceEndpoints.js
  lib/services/networkManagement2/lib/operations/networkInterfaceTapConfigurations.js
  lib/services/networkManagement2/lib/operations/networkInterfaces.js
  lib/services/networkManagement2/lib/operations/subnets.js
  lib/services/networkManagement2/lib/operations/virtualNetworkTaps.js
Labels: RestPRMerged

#3569 [AutoPR network/resource-manager] Local september branch merge to master
  lib/services/networkManagement2/package.json
Labels: RestPRMerged

#3573 [AutoPR monitor/resource-manager] Fix Go SDK generation
  lib/services/monitorManagement/package.json
Labels: RestPRMerged, in progress

#3587 Update generator version in swagger_to_sdk_config.json
  swagger_to_sdk_config.json
Labels: Started-Sprint-124, Unplanned-Sprint-124, in progress

#3574 [AutoPR] eventgrid/resource-manager
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/advancedFilter.js
  lib/services/eventgridManagement/lib/models/boolEqualsAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/domain.js
  lib/services/eventgridManagement/lib/models/domainRegenerateKeyRequest.js
  lib/services/eventgridManagement/lib/models/domainSharedAccessKeys.js
  lib/services/eventgridManagement/lib/models/domainTopic.js
  lib/services/eventgridManagement/lib/models/domainTopicsListResult.js
  lib/services/eventgridManagement/lib/models/domainUpdateParameters.js
  lib/services/eventgridManagement/lib/models/domainsListResult.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFilter.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/models/numberGreaterThanAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/numberGreaterThanOrEqualsAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/numberInAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/numberLessThanAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/numberLessThanOrEqualsAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/numberNotInAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/stringBeginsWithAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/stringContainsAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/stringEndsWithAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/stringInAdvancedFilter.js
  lib/services/eventgridManagement/lib/models/stringNotInAdvancedFilter.js
  lib/services/eventgridManagement/lib/operations/domainTopics.js
  lib/services/eventgridManagement/lib/operations/domains.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/index.js
  lib/services/eventgridManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3593 [AutoPR mariadb/resource-manager] Fix Go SDK codegen for mariadb
  lib/services/mariadbManagement/README.md
  lib/services/mariadbManagement/package.json
Labels: RestPRMerged

#3589 [AutoPR] mariadb/resource-manager
  lib/services/mariadbManagement/LICENSE.txt
  lib/services/mariadbManagement/README.md
  lib/services/mariadbManagement/lib/mariaDBManagementClient.d.ts
  lib/services/mariadbManagement/lib/mariaDBManagementClient.js
  lib/services/mariadbManagement/lib/models/configuration.js
  lib/services/mariadbManagement/lib/models/configurationListResult.js
  lib/services/mariadbManagement/lib/models/database.js
  lib/services/mariadbManagement/lib/models/databaseListResult.js
  lib/services/mariadbManagement/lib/models/firewallRule.js
  lib/services/mariadbManagement/lib/models/firewallRuleListResult.js
  lib/services/mariadbManagement/lib/models/index.d.ts
  lib/services/mariadbManagement/lib/models/index.js
  lib/services/mariadbManagement/lib/models/logFile.js
  lib/services/mariadbManagement/lib/models/logFileListResult.js
  lib/services/mariadbManagement/lib/models/nameAvailability.js
  lib/services/mariadbManagement/lib/models/nameAvailabilityRequest.js
  lib/services/mariadbManagement/lib/models/operation.js
  lib/services/mariadbManagement/lib/models/operationDisplay.js
  lib/services/mariadbManagement/lib/models/operationListResult.js
  lib/services/mariadbManagement/lib/models/performanceTierListResult.js
  lib/services/mariadbManagement/lib/models/performanceTierProperties.js
  lib/services/mariadbManagement/lib/models/performanceTierServiceLevelObjectives.js
  lib/services/mariadbManagement/lib/models/proxyResource.js
  lib/services/mariadbManagement/lib/models/server.js
  lib/services/mariadbManagement/lib/models/serverForCreate.js
  lib/services/mariadbManagement/lib/models/serverListResult.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForDefaultCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForGeoRestore.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForRestore.js
  lib/services/mariadbManagement/lib/models/serverSecurityAlertPolicy.js
  lib/services/mariadbManagement/lib/models/serverUpdateParameters.js
  lib/services/mariadbManagement/lib/models/sku.js
  lib/services/mariadbManagement/lib/models/storageProfile.js
  lib/services/mariadbManagement/lib/models/trackedResource.js
  lib/services/mariadbManagement/lib/operations/checkNameAvailability.js
  lib/services/mariadbManagement/lib/operations/configurations.js
  lib/services/mariadbManagement/lib/operations/databases.js
  lib/services/mariadbManagement/lib/operations/firewallRules.js
  lib/services/mariadbManagement/lib/operations/index.d.ts
  lib/services/mariadbManagement/lib/operations/index.js
  lib/services/mariadbManagement/lib/operations/locationBasedPerformanceTier.js
  lib/services/mariadbManagement/lib/operations/logFiles.js
  lib/services/mariadbManagement/lib/operations/operations.js
  lib/services/mariadbManagement/lib/operations/serverSecurityAlertPolicies.js
  lib/services/mariadbManagement/lib/operations/servers.js
  lib/services/mariadbManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3579 [AutoPR sql/resource-manager] [DO NOT MERGE] Added list support to VA policies
  lib/services/sqlManagement2/package.json
Labels: RestPRMerged, in progress

#3597 [AutoPR automation/resource-manager] Fix to version in examples and in runbook.json
  lib/services/automationManagement/package.json
Labels: RestPRMerged, in progress

#3602 [AutoPR network/resource-manager] Add 202 response code as expected for network profile deletion
  lib/services/networkManagement2/package.json
Labels: RestPRMerged, in progress

#3605 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/sku.js
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/operations/blobContainers.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/managementPolicies.js
  lib/services/storageManagement2/lib/operations/operations.js
  lib/services/storageManagement2/lib/operations/skus.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usageOperations.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
  lib/services/storageManagement2/package.json
  test/recordings/datalakeAnalyticsManagement-tests/Data_Lake_Analytics_Clients_Account_Job_and_Catalog_Data_Lake_Analytics_Account_adding_and_removing_blob_storage_accounts_to_the_account_should_work.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_assign_Key_Vault_the_operator_role_on_a_storage_account.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_check_the_name_availability_for_a_storage_account_that_already_exists.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_check_the_name_availability_for_a_storage_account_that_does_not_exist.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_StorageV2.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_cool.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_encryption.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_https_only.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_with_vnet_rule_set_correctly.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_delete_the_specified_storage_account.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_get_properties_of_the_specified_storage_account.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_all_the_storage_account_keys.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_all_the_storage_accounts_in_the_resourcegroup.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_all_the_storage_accounts_in_the_subscription.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_the_skus_for_subscription.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_the_storage_account_SAS.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_the_storage_service_SAS.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_regenerate_storage_account_keys.nock.js
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3572 [AutoPR logic/resource-manager] Remove default response from Sessions
  lib/services/logicManagement/lib/operations/integrationAccountSessions.js
  lib/services/logicManagement/package.json
Labels: RestPRMerged, in progress

#3608 [AutoPR automation/resource-manager] New tag for 2018-06 APIs for Automation
  lib/services/automationManagement/lib/automationClient.d.ts
  lib/services/automationManagement/lib/automationClient.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/runbookDraftUndoEditResult.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/index.js
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
  lib/services/automationManagement/lib/operations/runbookOperations.js
  lib/services/automationManagement/lib/operations/testJobOperations.js
  lib/services/automationManagement/lib/operations/testJobStreams.js
  lib/services/automationManagement/package.json
Labels: RestPRMerged

#3585 [AutoPR monitor/resource-manager] Add specifications for dynanic threshold GA api
  lib/services/monitorManagement/package.json
Labels: RestPRMerged, in progress

#3609 [AutoPR] automation/resource-manager
  lib/services/automationManagement/lib/automationClient.d.ts
  lib/services/automationManagement/lib/automationClient.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/runbookDraftUndoEditResult.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/index.js
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
  lib/services/automationManagement/lib/operations/runbookOperations.js
  lib/services/automationManagement/lib/operations/testJobOperations.js
  lib/services/automationManagement/lib/operations/testJobStreams.js
  lib/services/automationManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3577 [AutoPR sql/resource-manager] Add algorithm types to threat detection disabled alerts description
  lib/services/sqlManagement2/lib/models/databaseSecurityAlertPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/serverSecurityAlertPolicy.js
  lib/services/sqlManagement2/lib/operations/databaseThreatDetectionPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/serverSecurityAlertPolicies.js
  lib/services/sqlManagement2/package.json
Labels: RestPRMerged, in progress

#3607 [AutoPR] logic/resource-manager
  lib/services/logicManagement/lib/operations/integrationAccountSessions.js
  lib/services/logicManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3616 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/databaseSecurityAlertPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/serverSecurityAlertPolicy.js
  lib/services/sqlManagement2/lib/operations/databaseThreatDetectionPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/serverSecurityAlertPolicies.js
  lib/services/sqlManagement2/package.json
Labels: ServicePR, in progress

#3622 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncManagement/lib/models/cloudEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/recallActionParameters.js
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/lib/models/registeredServerCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncApiError.js
  lib/services/storagesyncManagement/lib/models/storageSyncError.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceCreateParameters.js
  lib/services/storagesyncManagement/lib/models/syncGroupCreateParameters.js
  lib/services/storagesyncManagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncManagement/lib/operations/syncGroups.js
  lib/services/storagesyncManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3625 [AutoPR storagesync/resource-manager] StorageSync : Clone existing ApiVersion 2018-04-02 for creating a new version 2018-07-01
  lib/services/storagesyncManagement/package.json
Labels: RestPRMerged, in progress

#3629 Specify the name of the folder that our repo will be cloned to for sw…
  swagger_to_sdk_config.json
Labels: Started-Sprint-124, Unplanned-Sprint-124, in progress

#3623 [AutoPR eventgrid/resource-manager] EventGrid: README.md changes: Updated default tag for global settings and updates to multi-api settings.
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFilter.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/index.js
  lib/services/eventgridManagement/package.json
Labels: RestPRMerged, in progress

#3634 [AutoPR storSimple1200Series/resource-manager] Fixed GetOperations route to not have subId
  lib/services/storSimple1200SeriesManagement/LICENSE.txt
  lib/services/storSimple1200SeriesManagement/README.md
  lib/services/storSimple1200SeriesManagement/lib/operations/availableProviderOperationsOperations.js
Labels: RestPRMerged, in progress

#3620 [AutoPR monitor/resource-manager] Add missing enum for aggregation type
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/metricTrigger.js
  lib/services/monitorManagement/lib/models/scaleRule.js
  lib/services/monitorManagement/package.json
Labels: RestPRMerged, in progress

#3631 [AutoPR] eventgrid/resource-manager
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFilter.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/index.js
  lib/services/eventgridManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3640 [AutoPR] monitor/resource-manager
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/metricTrigger.js
  lib/services/monitorManagement/lib/models/scaleRule.js
  lib/services/monitorManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3643 [AutoPR] resources/resource-manager
  lib/services/resourceManagement/lib/feature/featureClient.d.ts
  lib/services/resourceManagement/lib/feature/featureClient.js
  lib/services/resourceManagement/lib/feature/models/index.d.ts
  lib/services/resourceManagement/lib/feature/models/index.js
  lib/services/resourceManagement/lib/feature/models/operation.js
  lib/services/resourceManagement/lib/feature/models/operationDisplay.js
  lib/services/resourceManagement/lib/feature/models/operationListResult.js
  lib/services/resourceManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3617 [AutoPR datafactory/resource-manager] [Datafactory] Add SecureInput property to Activity. Add recursive option to cancel API
  lib/services/datafactoryManagement/lib/models/activityPolicy.js
  lib/services/datafactoryManagement/lib/models/executionActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/pipelineRuns.js
  lib/services/datafactoryManagement/package.json
Labels: RestPRMerged, in progress

#3644 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/activityPolicy.js
  lib/services/datafactoryManagement/lib/models/executionActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/pipelineRuns.js
  lib/services/datafactoryManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3646 [AutoPR resources/resource-manager] Fix typo, the provider should be Microsoft.Authorization
  lib/services/resourceManagement/lib/lock/managementLockClient.js
Labels: RestPRMerged, in progress

#3651 Regenerate azure-arm-signalr
  lib/services/signalrManagement/lib/models/dimension.js
  lib/services/signalrManagement/lib/models/index.d.ts
  lib/services/signalrManagement/lib/models/index.js
  lib/services/signalrManagement/lib/models/metricSpecification.js
  lib/services/signalrManagement/lib/models/operation.js
  lib/services/signalrManagement/lib/models/operationProperties.js
  lib/services/signalrManagement/lib/models/resourceSku.js
  lib/services/signalrManagement/lib/models/serviceSpecification.js
  lib/services/signalrManagement/lib/models/signalRKeys.js
  lib/services/signalrManagement/lib/models/signalRResource.js
  lib/services/signalrManagement/lib/models/signalRUpdateParameters.js
  lib/services/signalrManagement/lib/models/signalRUsage.js
  lib/services/signalrManagement/lib/models/signalRUsageList.js
  lib/services/signalrManagement/lib/models/signalRUsageName.js
  lib/services/signalrManagement/lib/operations/index.d.ts
  lib/services/signalrManagement/lib/operations/index.js
  lib/services/signalrManagement/lib/operations/signalR.js
  lib/services/signalrManagement/lib/operations/usages.js
  lib/services/signalrManagement/lib/signalRManagementClient.d.ts
  lib/services/signalrManagement/lib/signalRManagementClient.js
  lib/services/signalrManagement/package.json
Labels: Planned-Sprint-124, Started-Sprint-124, in progress

#3647 [AutoPR] resources/resource-manager
  lib/services/resourceManagement/lib/lock/managementLockClient.js
  lib/services/resourceManagement/lib/managedApplicationClient.d.ts
  lib/services/resourceManagement/lib/managedApplicationClient.js
  lib/services/resourceManagement/lib/models/appliance.js
  lib/services/resourceManagement/lib/models/index.d.ts
  lib/services/resourceManagement/lib/models/index.js
  lib/services/resourceManagement/lib/models/operation.js
  lib/services/resourceManagement/lib/models/operationDisplay.js
  lib/services/resourceManagement/lib/models/operationListResult.js
  lib/services/resourceManagement/lib/operations/appliances.js
  lib/services/resourceManagement/lib/operations/index.d.ts
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3653 Update azure-arm-resource to 5.1.1
  lib/services/resourceManagement/package.json
Labels: Planned-Sprint-124, Started-Sprint-124, in progress

#3654 [AutoPR resources/resource-manager] Change operationId of Microsoft.Authorization
  lib/services/resourceManagement/lib/lock/managementLockClient.d.ts
  lib/services/resourceManagement/lib/lock/managementLockClient.js
  lib/services/resourceManagement/lib/lock/operations/authorizationOperations.js
  lib/services/resourceManagement/lib/lock/operations/index.d.ts
  lib/services/resourceManagement/lib/lock/operations/index.js
Labels: RestPRMerged

#3656 Update autorest.nodejs generator version in swaggerToSDK config
  swagger_to_sdk_config.json
Labels: Planned-Sprint-124, Started-Sprint-124, in progress

#3655 [AutoPR] resources/resource-manager
  lib/services/resourceManagement/lib/lock/managementLockClient.d.ts
  lib/services/resourceManagement/lib/lock/managementLockClient.js
  lib/services/resourceManagement/lib/lock/operations/authorizationOperations.js
  lib/services/resourceManagement/lib/lock/operations/index.d.ts
  lib/services/resourceManagement/lib/lock/operations/index.js
  lib/services/resourceManagement/package.json
Labels: Planned-Sprint-124, ServicePR, Started-Sprint-124, in progress

#3660 [AutoPR recoveryservicesbackup/resource-manager] Move Go SDK config for back to its own config file
  lib/services/recoveryServicesBackupManagement/lib/models/azureIaaSVMJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureStorageJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadContainerExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSQLRecoveryPointExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBase.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupManagementUsage.js
  lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryForProperties.js
  lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryForServiceSpecification.js
  lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryValueForSingleApi.js
  lib/services/recoveryServicesBackupManagement/lib/models/dailyRetentionFormat.js
  lib/services/recoveryServicesBackupManagement/lib/models/dailyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/lib/models/distributedNodesInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/dpmJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/genericContainerExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/inquiryInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/inquiryValidation.js
  lib/services/recoveryServicesBackupManagement/lib/models/instantItemRecoveryTarget.js
  lib/services/recoveryServicesBackupManagement/lib/models/keyAndSecretDetails.js
  lib/services/recoveryServicesBackupManagement/lib/models/mabJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/monthlyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/lib/models/operationStatus.js
  lib/services/recoveryServicesBackupManagement/lib/models/subProtectionPolicy.js
  lib/services/recoveryServicesBackupManagement/lib/models/validateOperationResponse.js
  lib/services/recoveryServicesBackupManagement/lib/models/validateOperationsResponse.js
  lib/services/recoveryServicesBackupManagement/lib/models/weeklyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/lib/models/workloadInquiryDetails.js
  lib/services/recoveryServicesBackupManagement/lib/models/yearlyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/package.json
Labels: RestPRMerged, in progress

#3659 [AutoPR automation/resource-manager] Quick fix to response type of runbookdraftcontent get
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
  lib/services/automationManagement/package.json
Labels: RestPRMerged, in progress

#3661 [AutoPR] recoveryservicesbackup/resource-manager
  lib/services/recoveryServicesBackupManagement/lib/models/azureIaaSVMJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureStorageJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadContainerExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSQLRecoveryPointExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBase.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupManagementUsage.js
  lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryForProperties.js
  lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryForServiceSpecification.js
  lib/services/recoveryServicesBackupManagement/lib/models/clientDiscoveryValueForSingleApi.js
  lib/services/recoveryServicesBackupManagement/lib/models/dailyRetentionFormat.js
  lib/services/recoveryServicesBackupManagement/lib/models/dailyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/lib/models/distributedNodesInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/dpmJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/genericContainerExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/inquiryInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/inquiryValidation.js
  lib/services/recoveryServicesBackupManagement/lib/models/instantItemRecoveryTarget.js
  lib/services/recoveryServicesBackupManagement/lib/models/keyAndSecretDetails.js
  lib/services/recoveryServicesBackupManagement/lib/models/mabJobExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/monthlyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/lib/models/operationStatus.js
  lib/services/recoveryServicesBackupManagement/lib/models/subProtectionPolicy.js
  lib/services/recoveryServicesBackupManagement/lib/models/validateOperationResponse.js
  lib/services/recoveryServicesBackupManagement/lib/models/validateOperationsResponse.js
  lib/services/recoveryServicesBackupManagement/lib/models/weeklyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/lib/models/workloadInquiryDetails.js
  lib/services/recoveryServicesBackupManagement/lib/models/yearlyRetentionSchedule.js
  lib/services/recoveryServicesBackupManagement/package.json
Labels: ServicePR, in progress

#3662 [AutoPR] automation/resource-manager
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
  lib/services/automationManagement/package.json
Labels: ServicePR, in progress

#3664 [AutoPR deploymentmanager/resource-manager] DeploymentManager: API Spec, examples - private preview
  lib/services/deploymentmanagerManagement/LICENSE.txt
  lib/services/deploymentmanagerManagement/README.md
  lib/services/deploymentmanagerManagement/lib/azureDeploymentManager.d.ts
  lib/services/deploymentmanagerManagement/lib/azureDeploymentManager.js
  lib/services/deploymentmanagerManagement/lib/models/artifactSource.js
  lib/services/deploymentmanagerManagement/lib/models/artifactSourcePropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/authentication.js
  lib/services/deploymentmanagerManagement/lib/models/azureEntityResource.js
  lib/services/deploymentmanagerManagement/lib/models/cloudErrorBody.js
  lib/services/deploymentmanagerManagement/lib/models/identity.js
  lib/services/deploymentmanagerManagement/lib/models/index.d.ts
  lib/services/deploymentmanagerManagement/lib/models/index.js
  lib/services/deploymentmanagerManagement/lib/models/message.js
  lib/services/deploymentmanagerManagement/lib/models/operation.js
  lib/services/deploymentmanagerManagement/lib/models/operationDetail.js
  lib/services/deploymentmanagerManagement/lib/models/prePostStep.js
  lib/services/deploymentmanagerManagement/lib/models/proxyResource.js
  lib/services/deploymentmanagerManagement/lib/models/resource.js
  lib/services/deploymentmanagerManagement/lib/models/resourceOperation.js
  lib/services/deploymentmanagerManagement/lib/models/rollout.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutPropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutRequest.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutStep.js
  lib/services/deploymentmanagerManagement/lib/models/sasAuthentication.js
  lib/services/deploymentmanagerManagement/lib/models/service.js
  lib/services/deploymentmanagerManagement/lib/models/serviceProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnit.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitArtifacts.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitResource.js
  lib/services/deploymentmanagerManagement/lib/models/step.js
  lib/services/deploymentmanagerManagement/lib/models/stepOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/stepProperties.js
  lib/services/deploymentmanagerManagement/lib/models/stepResource.js
  lib/services/deploymentmanagerManagement/lib/models/trackedResource.js
  lib/services/deploymentmanagerManagement/lib/models/waitStepAttributes.js
  lib/services/deploymentmanagerManagement/lib/models/waitStepProperties.js
  lib/services/deploymentmanagerManagement/lib/operations/artifactSources.js
  lib/services/deploymentmanagerManagement/lib/operations/index.d.ts
  lib/services/deploymentmanagerManagement/lib/operations/index.js
  lib/services/deploymentmanagerManagement/lib/operations/operations.js
  lib/services/deploymentmanagerManagement/lib/operations/rollouts.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceTopologies.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceUnits.js
  lib/services/deploymentmanagerManagement/lib/operations/services.js
  lib/services/deploymentmanagerManagement/lib/operations/steps.js
  lib/services/deploymentmanagerManagement/package.json
Labels: RestPRMerged, in progress

#3678 [AutoPR compute/resource-manager] Swagger changes for adding diffdisksettings property for the Ephemeral OS Disks
  lib/services/computeManagement2/lib/models/diffDiskSettings.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#3630 [AutoPR graphrbac/data-plane] Rename Post to Grants
  lib/services/graphManagement/package.json
Labels: RestPRMerged, in progress

#3675 [AutoPR] deploymentmanager/resource-manager
  lib/services/deploymentmanagerManagement/LICENSE.txt
  lib/services/deploymentmanagerManagement/README.md
  lib/services/deploymentmanagerManagement/lib/azureDeploymentManager.d.ts
  lib/services/deploymentmanagerManagement/lib/azureDeploymentManager.js
  lib/services/deploymentmanagerManagement/lib/models/artifactSource.js
  lib/services/deploymentmanagerManagement/lib/models/artifactSourcePropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/authentication.js
  lib/services/deploymentmanagerManagement/lib/models/azureEntityResource.js
  lib/services/deploymentmanagerManagement/lib/models/cloudErrorBody.js
  lib/services/deploymentmanagerManagement/lib/models/identity.js
  lib/services/deploymentmanagerManagement/lib/models/index.d.ts
  lib/services/deploymentmanagerManagement/lib/models/index.js
  lib/services/deploymentmanagerManagement/lib/models/message.js
  lib/services/deploymentmanagerManagement/lib/models/operation.js
  lib/services/deploymentmanagerManagement/lib/models/operationDetail.js
  lib/services/deploymentmanagerManagement/lib/models/prePostStep.js
  lib/services/deploymentmanagerManagement/lib/models/proxyResource.js
  lib/services/deploymentmanagerManagement/lib/models/resource.js
  lib/services/deploymentmanagerManagement/lib/models/resourceOperation.js
  lib/services/deploymentmanagerManagement/lib/models/rollout.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutPropertiesModel.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutRequest.js
  lib/services/deploymentmanagerManagement/lib/models/rolloutStep.js
  lib/services/deploymentmanagerManagement/lib/models/sasAuthentication.js
  lib/services/deploymentmanagerManagement/lib/models/service.js
  lib/services/deploymentmanagerManagement/lib/models/serviceProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceTopologyResource.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnit.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitArtifacts.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitProperties.js
  lib/services/deploymentmanagerManagement/lib/models/serviceUnitResource.js
  lib/services/deploymentmanagerManagement/lib/models/step.js
  lib/services/deploymentmanagerManagement/lib/models/stepOperationInfo.js
  lib/services/deploymentmanagerManagement/lib/models/stepProperties.js
  lib/services/deploymentmanagerManagement/lib/models/stepResource.js
  lib/services/deploymentmanagerManagement/lib/models/trackedResource.js
  lib/services/deploymentmanagerManagement/lib/models/waitStepAttributes.js
  lib/services/deploymentmanagerManagement/lib/models/waitStepProperties.js
  lib/services/deploymentmanagerManagement/lib/operations/artifactSources.js
  lib/services/deploymentmanagerManagement/lib/operations/index.d.ts
  lib/services/deploymentmanagerManagement/lib/operations/index.js
  lib/services/deploymentmanagerManagement/lib/operations/operations.js
  lib/services/deploymentmanagerManagement/lib/operations/rollouts.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceTopologies.js
  lib/services/deploymentmanagerManagement/lib/operations/serviceUnits.js
  lib/services/deploymentmanagerManagement/lib/operations/services.js
  lib/services/deploymentmanagerManagement/lib/operations/steps.js
  lib/services/deploymentmanagerManagement/package.json
Labels: ServicePR, in progress

#3681 [AutoPR] compute/resource-manager
  lib/services/computeManagement2/lib/models/diffDiskSettings.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
  lib/services/computeManagement2/package.json
Labels: ServicePR, in progress

#3685 [AutoPR] compute/resource-manager
  lib/services/computeManagement2/lib/models/bootDiagnostics.js
  lib/services/computeManagement2/lib/models/bootDiagnosticsInstanceView.js
  lib/services/computeManagement2/lib/models/diagnosticsProfile.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineInstanceView.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMInstanceView.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
  lib/services/computeManagement2/package.json
Labels: ServicePR, in progress

#3690 [AutoPR trafficmanager/resource-manager] Remove readOnly attribute for ID field of Resource.
  lib/services/trafficManagerManagement2/lib/models/endpoint.js
  lib/services/trafficManagerManagement2/lib/models/heatMapModel.js
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/profile.js
  lib/services/trafficManagerManagement2/lib/models/proxyResource.js
  lib/services/trafficManagerManagement2/lib/models/resource.js
  lib/services/trafficManagerManagement2/lib/models/trackedResource.js
  lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js
  lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
  lib/services/trafficManagerManagement2/package.json
Labels: RestPRMerged, in progress

#3693 [AutoPR] trafficmanager/resource-manager
  lib/services/trafficManagerManagement2/lib/models/endpoint.js
  lib/services/trafficManagerManagement2/lib/models/heatMapModel.js
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/profile.js
  lib/services/trafficManagerManagement2/lib/models/proxyResource.js
  lib/services/trafficManagerManagement2/lib/models/resource.js
  lib/services/trafficManagerManagement2/lib/models/trackedResource.js
  lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js
  lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
  lib/services/trafficManagerManagement2/package.json
Labels: ServicePR, in progress

#3689 [AutoPR] applicationinsights/resource-manager
  lib/services/applicationinsights/lib/models/annotationError.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentAnalyticsItem.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentAvailableFeatures.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentBillingFeatures.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentFeature.js
  lib/services/applicationinsights/lib/models/componentPurgeBody.js
  lib/services/applicationinsights/lib/models/operation.js
  lib/services/applicationinsights/lib/models/workItemConfigurationError.js
  lib/services/applicationinsights/lib/models/workbookError.js
  lib/services/applicationinsights/package.json
Labels: ServicePR, in progress

#3694 [AutoPR compute/resource-manager] Set location for the final state option of the POST long running disk…
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/index.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#3696 [AutoPR] compute/resource-manager
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/index.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
  lib/services/computeManagement2/package.json
Labels: ServicePR, in progress

#3699 [AutoPR servicebus/resource-manager] ServiceBus: Added read-only property migrationState to MigrationConfig
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js
  lib/services/serviceBusManagement2/package.json
Labels: RestPRMerged, in progress

#3697 [AutoPR web/resource-manager] Updated the AppService Swagger to include ElasticPremium and ElasticIsolated Skus, and a new MaximumElasticWorkerCount parameter.
  lib/services/websiteManagement2/lib/models/appServicePlan.js
  lib/services/websiteManagement2/lib/models/appServicePlanPatchResource.js
  lib/services/websiteManagement2/lib/models/index.d.ts
  lib/services/websiteManagement2/lib/operations/appServicePlans.js
  lib/services/websiteManagement2/lib/operations/index.d.ts
  lib/services/websiteManagement2/lib/webSiteManagementClient.d.ts
  lib/services/websiteManagement2/lib/webSiteManagementClient.js
  lib/services/websiteManagement2/package.json
Labels: RestPRMerged, in progress

#3701 [AutoPR] compute/resource-manager
  lib/services/computeManagement2/lib/models/creationData.js
  lib/services/computeManagement2/lib/models/disk.js
  lib/services/computeManagement2/lib/models/imageDiskReference.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/snapshot.js
  lib/services/computeManagement2/lib/operations/disks.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/snapshots.js
  lib/services/computeManagement2/package.json
Labels: ServicePR, in progress

#3703 [AutoPR] frontdoor/resource-manager
  lib/services/frontdoorManagement/LICENSE.txt
  lib/services/frontdoorManagement/README.md
  lib/services/frontdoorManagement/lib/operations/backendPools.js
  lib/services/frontdoorManagement/lib/operations/endpoints.js
  lib/services/frontdoorManagement/lib/operations/frontDoors.js
  lib/services/frontdoorManagement/lib/operations/frontendEndpoints.js
  lib/services/frontdoorManagement/lib/operations/healthProbeSettings.js
  lib/services/frontdoorManagement/lib/operations/loadBalancingSettings.js
  lib/services/frontdoorManagement/lib/operations/routingRules.js
  lib/services/frontdoorManagement/package.json
Labels: ServicePR, in progress

#3698 [AutoPR trafficmanager/resource-manager] Do not omit type and name while serializing the resource object.
  lib/services/trafficManagerManagement2/lib/models/endpoint.js
  lib/services/trafficManagerManagement2/lib/models/heatMapModel.js
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/profile.js
  lib/services/trafficManagerManagement2/lib/models/proxyResource.js
  lib/services/trafficManagerManagement2/lib/models/resource.js
  lib/services/trafficManagerManagement2/lib/models/trackedResource.js
  lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js
  lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
Labels: RestPRMerged, in progress

#3702 [AutoPR] web/resource-manager
  lib/services/websiteManagement2/lib/models/appServicePlan.js
  lib/services/websiteManagement2/lib/models/appServicePlanPatchResource.js
  lib/services/websiteManagement2/lib/models/index.d.ts
  lib/services/websiteManagement2/lib/operations/appServicePlans.js
  lib/services/websiteManagement2/lib/operations/index.d.ts
  lib/services/websiteManagement2/lib/webSiteManagementClient.d.ts
  lib/services/websiteManagement2/lib/webSiteManagementClient.js
  lib/services/websiteManagement2/package.json
Labels: ServicePR, in progress

#3709 update runtime packages to be in sync with request version dependency.
  runtime/ms-rest-azure/Changelog.md
  runtime/ms-rest-azure/lib/credentials/msiAppServiceTokenCredentials.js
  runtime/ms-rest-azure/lib/credentials/msiVmTokenCredentials.js
  runtime/ms-rest-azure/package.json
  runtime/ms-rest/Changelog.md
  runtime/ms-rest/package.json
Labels: in progress

#3708 [AutoPR] trafficmanager/resource-manager
  lib/services/trafficManagerManagement2/lib/models/endpoint.js
  lib/services/trafficManagerManagement2/lib/models/heatMapModel.js
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/profile.js
  lib/services/trafficManagerManagement2/lib/models/proxyResource.js
  lib/services/trafficManagerManagement2/lib/models/resource.js
  lib/services/trafficManagerManagement2/lib/models/trackedResource.js
  lib/services/trafficManagerManagement2/lib/models/trafficManagerGeographicHierarchy.js
  lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
  lib/services/trafficManagerManagement2/package.json
Labels: ServicePR, in progress

#3710 [AutoPR] web/resource-manager
  lib/services/websiteManagement2/lib/webSiteManagementClient.d.ts
  lib/services/websiteManagement2/lib/webSiteManagementClient.js
  lib/services/websiteManagement2/package.json
Labels: ServicePR, in progress

#3718 [AutoPR storage/resource-manager] Add Java support for storage 2018-07-01
  lib/services/storageManagement2/LICENSE.txt
  lib/services/storageManagement2/package.json
Labels: RestPRMerged, in progress

#3719 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/LICENSE.txt
Labels: ServicePR, in progress

#3722 [AutoPR datafactory/resource-manager] [Datafactory] Adding script actions support for HDI on demand linked service
  lib/services/datafactoryManagement/lib/models/hDInsightOnDemandLinkedService.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/scriptAction.js
Labels: RestPRMerged, in progress

#3721 [AutoPR] frontdoor/resource-manager
  lib/services/frontdoorManagement/LICENSE.txt
  lib/services/frontdoorManagement/README.md
  lib/services/frontdoorManagement/lib/frontDoorManagementClient.d.ts
  lib/services/frontdoorManagement/lib/frontDoorManagementClient.js
  lib/services/frontdoorManagement/lib/operations/backendPools.js
  lib/services/frontdoorManagement/lib/operations/endpoints.js
  lib/services/frontdoorManagement/lib/operations/frontDoors.js
  lib/services/frontdoorManagement/lib/operations/frontendEndpoints.js
  lib/services/frontdoorManagement/lib/operations/healthProbeSettings.js
  lib/services/frontdoorManagement/lib/operations/index.d.ts
  lib/services/frontdoorManagement/lib/operations/loadBalancingSettings.js
  lib/services/frontdoorManagement/lib/operations/policies.js
  lib/services/frontdoorManagement/lib/operations/routingRules.js
  lib/services/frontdoorManagement/package.json
Labels: ServicePR, in progress

#3726 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/hDInsightOnDemandLinkedService.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/scriptAction.js
  lib/services/datafactoryManagement/package.json
Labels: ServicePR, in progress

#3723 [AutoPR] monitor/resource-manager
  lib/services/monitorManagement/lib/models/criteria.js
  lib/services/monitorManagement/lib/models/dimension.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/index.js
  lib/services/monitorManagement/lib/models/logSearchRuleResource.js
  lib/services/monitorManagement/lib/models/logToMetricAction.js
  lib/services/monitorManagement/lib/models/source.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/lib/operations/scheduledQueryRules.js
  lib/services/monitorManagement/package.json
Labels: ServicePR, in progress

#3727 [AutoPR compute/resource-manager] Add AutomaticOSUpgradeProperties in GET VMImageVersion API
  lib/services/computeManagement2/lib/models/automaticOSUpgradeProperties.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineImage.js
Labels: RestPRMerged, in progress

#3705 [AutoPR hdinsight/resource-manager] [HDInsight] Added additional parameters for security profile
  lib/services/hdInsightManagement/lib/models/cluster.js
  lib/services/hdInsightManagement/lib/models/clusterCreateParametersExtended.js
  lib/services/hdInsightManagement/lib/models/clusterCreateProperties.js
  lib/services/hdInsightManagement/lib/models/clusterGetProperties.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/securityProfile.js
  lib/services/hdInsightManagement/lib/operations/clusters.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
  lib/services/hdInsightManagement/package.json
Labels: RestPRMerged, in progress

#3728 [AutoPR] compute/resource-manager
  lib/services/computeManagement2/lib/models/automaticOSUpgradeProperties.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineImage.js
  lib/services/computeManagement2/package.json
Labels: ServicePR, in progress

#3731 [AutoPR] hdinsight/resource-manager
  lib/services/hdInsightManagement/lib/models/cluster.js
  lib/services/hdInsightManagement/lib/models/clusterCreateParametersExtended.js
  lib/services/hdInsightManagement/lib/models/clusterCreateProperties.js
  lib/services/hdInsightManagement/lib/models/clusterGetProperties.js
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/securityProfile.js
  lib/services/hdInsightManagement/lib/operations/clusters.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
  lib/services/hdInsightManagement/package.json
Labels: ServicePR, in progress
