Repository Azure/azure-sdk-for-node, pull requests merged in 2018-04, with the labels that each got.

#2616 [AutoPR iothub/resource-manager] Add package-2018-01 to Go SDK build
  lib/services/iothub/lib/LICENSE.txt
  lib/services/iothub/lib/lib/iotHubClient.d.ts
  lib/services/iothub/lib/lib/iotHubClient.js
  lib/services/iothub/lib/lib/models/certificateBodyDescription.js
  lib/services/iothub/lib/lib/models/certificateDescription.js
  lib/services/iothub/lib/lib/models/certificateListDescription.js
  lib/services/iothub/lib/lib/models/certificateProperties.js
  lib/services/iothub/lib/lib/models/certificatePropertiesWithNonce.js
  lib/services/iothub/lib/lib/models/certificateVerificationDescription.js
  lib/services/iothub/lib/lib/models/certificateWithNonceDescription.js
  lib/services/iothub/lib/lib/models/cloudToDeviceProperties.js
  lib/services/iothub/lib/lib/models/errorDetails.js
  lib/services/iothub/lib/lib/models/eventHubConsumerGroupInfo.js
  lib/services/iothub/lib/lib/models/eventHubConsumerGroupsListResult.js
  lib/services/iothub/lib/lib/models/eventHubProperties.js
  lib/services/iothub/lib/lib/models/exportDevicesRequest.js
  lib/services/iothub/lib/lib/models/fallbackRouteProperties.js
  lib/services/iothub/lib/lib/models/feedbackProperties.js
  lib/services/iothub/lib/lib/models/importDevicesRequest.js
  lib/services/iothub/lib/lib/models/index.d.ts
  lib/services/iothub/lib/lib/models/index.js
  lib/services/iothub/lib/lib/models/iotHubCapacity.js
  lib/services/iothub/lib/lib/models/iotHubDescription.js
  lib/services/iothub/lib/lib/models/iotHubDescriptionListResult.js
  lib/services/iothub/lib/lib/models/iotHubNameAvailabilityInfo.js
  lib/services/iothub/lib/lib/models/iotHubProperties.js
  lib/services/iothub/lib/lib/models/iotHubQuotaMetricInfo.js
  lib/services/iothub/lib/lib/models/iotHubQuotaMetricInfoListResult.js
  lib/services/iothub/lib/lib/models/iotHubSkuDescription.js
  lib/services/iothub/lib/lib/models/iotHubSkuDescriptionListResult.js
  lib/services/iothub/lib/lib/models/iotHubSkuInfo.js
  lib/services/iothub/lib/lib/models/ipFilterRule.js
  lib/services/iothub/lib/lib/models/jobResponse.js
  lib/services/iothub/lib/lib/models/jobResponseListResult.js
  lib/services/iothub/lib/lib/models/messagingEndpointProperties.js
  lib/services/iothub/lib/lib/models/operation.js
  lib/services/iothub/lib/lib/models/operationDisplay.js
  lib/services/iothub/lib/lib/models/operationInputs.js
  lib/services/iothub/lib/lib/models/operationListResult.js
  lib/services/iothub/lib/lib/models/operationsMonitoringProperties.js
  lib/services/iothub/lib/lib/models/registryStatistics.js
  lib/services/iothub/lib/lib/models/resource.js
  lib/services/iothub/lib/lib/models/routeProperties.js
  lib/services/iothub/lib/lib/models/routingEndpoints.js
  lib/services/iothub/lib/lib/models/routingEventHubProperties.js
  lib/services/iothub/lib/lib/models/routingProperties.js
  lib/services/iothub/lib/lib/models/routingServiceBusQueueEndpointProperties.js
  lib/services/iothub/lib/lib/models/routingServiceBusTopicEndpointProperties.js
  lib/services/iothub/lib/lib/models/routingStorageContainerProperties.js
  lib/services/iothub/lib/lib/models/sharedAccessSignatureAuthorizationRule.js
  lib/services/iothub/lib/lib/models/sharedAccessSignatureAuthorizationRuleListResult.js
  lib/services/iothub/lib/lib/models/storageEndpointProperties.js
  lib/services/iothub/lib/lib/models/tagsResource.js
  lib/services/iothub/lib/lib/operations/certificates.js
  lib/services/iothub/lib/lib/operations/index.d.ts
  lib/services/iothub/lib/lib/operations/index.js
  lib/services/iothub/lib/lib/operations/iotHubResource.js
  lib/services/iothub/lib/lib/operations/operations.js
  lib/services/iothub/lib/package.json
Labels: RestPRMerged, in progress

#2617 Remove codegen_mappings.json, update gulpfile tasks
  codegen_mappings.json
  codegen_mappings.schema.json
  gulpfile.js
  lib/services/monitor/README.md
  lib/services/monitor/package.json
  package_service_mapping.json
Labels: in progress

#2635 Add docs header and fix ms-rest version for apimanagement
  lib/services/apimanagement/README.md
  lib/services/apimanagement/package.json
Labels: in progress

#2634 Fix ms-rest version reference for analysisServices
  lib/services/analysisServices/package.json
Labels: in progress

#2637 Regenerate authorization package and increment major version
  lib/services/authorizationManagement/LICENSE.txt
  lib/services/authorizationManagement/README.md
  lib/services/authorizationManagement/lib/authorizationManagementClient.d.ts
  lib/services/authorizationManagement/lib/authorizationManagementClient.js
  lib/services/authorizationManagement/lib/models/classicAdministrator.js
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/index.js
  lib/services/authorizationManagement/lib/models/permission.js
  lib/services/authorizationManagement/lib/models/providerOperation.js
  lib/services/authorizationManagement/lib/models/roleAssignment.js
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/models/roleAssignmentFilter.js
  lib/services/authorizationManagement/lib/models/roleDefinition.js
  lib/services/authorizationManagement/lib/models/roleDefinitionFilter.js
  lib/services/authorizationManagement/lib/operations/classicAdministrators.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/index.js
  lib/services/authorizationManagement/lib/operations/permissions.js
  lib/services/authorizationManagement/lib/operations/providerOperationsMetadataOperations.js
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
  lib/services/authorizationManagement/lib/operations/roleDefinitions.js
  lib/services/authorizationManagement/package.json
Labels: in progress

#2636 Add docs header and fix ms-rest version for applicationinsights
  lib/services/applicationinsights/README.md
  lib/services/applicationinsights/package.json
Labels: in progress

#2639 Regenerate batch and add docs readme header
  lib/services/batch/LICENSE.txt
  lib/services/batch/README.md
  lib/services/batch/lib/batchServiceClient.d.ts
  lib/services/batch/lib/batchServiceClient.js
  lib/services/batch/package.json
Labels: in progress

#2640 Regenerate batchManagement and fix ms-rest version
  lib/services/batchManagement/LICENSE.txt
  lib/services/batchManagement/README.md
  lib/services/batchManagement/lib/batchManagementClient.d.ts
  lib/services/batchManagement/lib/batchManagementClient.js
  lib/services/batchManagement/lib/models/fixedScaleSettings.js
  lib/services/batchManagement/lib/models/index.d.ts
  lib/services/batchManagement/lib/models/pool.js
  lib/services/batchManagement/lib/models/scaleSettings.js
  lib/services/batchManagement/lib/operations/certificateOperations.js
  lib/services/batchManagement/lib/operations/index.d.ts
  lib/services/batchManagement/lib/operations/poolOperations.js
  lib/services/batchManagement/package.json
Labels: in progress

#2641 Regenerate batchaiManagement
  lib/services/batchaiManagement/LICENSE.txt
  lib/services/batchaiManagement/README.md
  lib/services/batchaiManagement/package.json
Labels: in progress

#2644 Regenerate networkManagement2
  lib/services/networkManagement2/lib/models/connectionMonitorQueryResult.js
  lib/services/networkManagement2/lib/models/connectivityParameters.js
  lib/services/networkManagement2/lib/models/hTTPConfiguration.js
  lib/services/networkManagement2/lib/models/hTTPHeader.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/protocolConfiguration.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkWatchers.js
  lib/services/networkManagement2/package.json
Labels: in progress

#2647 Regenerate cognitiveServiceManagement
  lib/services/cognitiveServicesManagement/LICENSE.txt
  lib/services/cognitiveServicesManagement/README.md
  lib/services/cognitiveServicesManagement/lib/cognitiveServicesManagementClient.d.ts
  lib/services/cognitiveServicesManagement/lib/cognitiveServicesManagementClient.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/index.js
  lib/services/cognitiveServicesManagement/lib/models/metricName.js
  lib/services/cognitiveServicesManagement/lib/models/usage.js
  lib/services/cognitiveServicesManagement/lib/models/usagesResult.js
  lib/services/cognitiveServicesManagement/lib/operations/accounts.js
  lib/services/cognitiveServicesManagement/lib/operations/checkSkuAvailability.js
  lib/services/cognitiveServicesManagement/lib/operations/index.d.ts
  lib/services/cognitiveServicesManagement/package.json
Labels: in progress

#2648 Regenerate commerce
  lib/services/commerce/LICENSE.txt
  lib/services/commerce/README.md
  lib/services/commerce/lib/models/index.d.ts
  lib/services/commerce/lib/models/monetaryCommitment.js
  lib/services/commerce/lib/models/monetaryCredit.js
  lib/services/commerce/lib/models/offerTermInfo.js
  lib/services/commerce/lib/models/recurringCharge.js
  lib/services/commerce/lib/models/usageAggregation.js
  lib/services/commerce/lib/usageManagementClient.d.ts
  lib/services/commerce/lib/usageManagementClient.js
  lib/services/commerce/package.json
Labels: in progress

#2620 [AutoPR apimanagement/resource-manager] Support for Non Xml Encoded policies
  lib/services/apimanagement/LICENSE.txt
  lib/services/apimanagement/README.md
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/policyContract.js
  lib/services/apimanagement/lib/operations/apiOperationPolicy.js
  lib/services/apimanagement/lib/operations/apiPolicy.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/policy.js
  lib/services/apimanagement/lib/operations/productPolicy.js
Labels: RestPRMerged, in progress

#2656 [AutoPR eventhub/resource-manager] EventHub: removed messaging plan from namespace
  lib/services/eventHubManagement/LICENSE.txt
  lib/services/eventHubManagement/README.md
  lib/services/eventHubManagement/lib/eventHubManagementClient.d.ts
  lib/services/eventHubManagement/lib/eventHubManagementClient.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/models/messagingRegions.js
  lib/services/eventHubManagement/lib/models/messagingRegionsListResult.js
  lib/services/eventHubManagement/lib/models/messagingRegionsProperties.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/index.js
  lib/services/eventHubManagement/lib/operations/regions.js
  lib/services/eventHubManagement/package.json
Labels: RestPRMerged, in progress

#2659 Regenerate computer vision and change version to 1.0.1
  lib/services/computerVision/LICENSE.txt
  lib/services/computerVision/lib/computerVisionAPIClient.d.ts
  lib/services/computerVision/lib/computerVisionAPIClient.js
  lib/services/computerVision/package.json
Labels: in progress

#2661 Regenerate containerRegistryManagement and change version to 2.2.0
  lib/services/containerRegistryManagement/LICENSE.txt
  lib/services/containerRegistryManagement/README.md
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.d.ts
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.js
  lib/services/containerRegistryManagement/package.json
Labels: in progress

#2662 Regenerate containerinstanceManagement and change version to 2.0.0
  lib/services/containerinstanceManagement/LICENSE.txt
  lib/services/containerinstanceManagement/README.md
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.d.ts
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequestTerminalSize.js
  lib/services/containerinstanceManagement/lib/models/containerExecResponse.js
  lib/services/containerinstanceManagement/lib/models/containerState.js
  lib/services/containerinstanceManagement/lib/models/event.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/logs.js
  lib/services/containerinstanceManagement/lib/models/operation.js
  lib/services/containerinstanceManagement/lib/models/operationDisplay.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/index.js
  lib/services/containerinstanceManagement/lib/operations/startContainer.js
  lib/services/containerinstanceManagement/package.json
Labels: in progress

#2664 Regenerate contentModerator and change version to 2.0.0
  lib/services/contentModerator/LICENSE.txt
  lib/services/contentModerator/lib/contentModeratorAPIClient.d.ts
  lib/services/contentModerator/lib/contentModeratorAPIClient.js
  lib/services/contentModerator/lib/models/classification.js
  lib/services/contentModerator/lib/models/classificationCategory1.js
  lib/services/contentModerator/lib/models/classificationCategory2.js
  lib/services/contentModerator/lib/models/classificationCategory3.js
  lib/services/contentModerator/lib/models/index.d.ts
  lib/services/contentModerator/lib/models/index.js
  lib/services/contentModerator/lib/models/screen.js
  lib/services/contentModerator/package.json
Labels: in progress

#2665 Regenerate cosmosdbManagement and change version to 1.1.2
  lib/services/cosmosdbManagement/LICENSE.txt
  lib/services/cosmosdbManagement/README.md
  lib/services/cosmosdbManagement/package.json
Labels: in progress

#2668 Regenerate customerInsightsManagement and change version to 3.0.0
  lib/services/customerInsightsManagement/LICENSE.txt
  lib/services/customerInsightsManagement/README.md
  lib/services/customerInsightsManagement/lib/customerInsightsManagementClient.d.ts
  lib/services/customerInsightsManagement/lib/customerInsightsManagementClient.js
  lib/services/customerInsightsManagement/lib/models/index.d.ts
  lib/services/customerInsightsManagement/lib/models/index.js
  lib/services/customerInsightsManagement/lib/models/operation.js
  lib/services/customerInsightsManagement/lib/models/operationDisplay.js
  lib/services/customerInsightsManagement/lib/models/operationListResult.js
  lib/services/customerInsightsManagement/lib/models/predictionMappings.js
  lib/services/customerInsightsManagement/lib/operations/hubs.js
  lib/services/customerInsightsManagement/lib/operations/index.d.ts
  lib/services/customerInsightsManagement/lib/operations/index.js
  lib/services/customerInsightsManagement/lib/operations/operations.js
  lib/services/customerInsightsManagement/lib/operations/predictions.js
  lib/services/customerInsightsManagement/lib/operations/relationshipLinks.js
  lib/services/customerInsightsManagement/lib/operations/relationships.js
  lib/services/customerInsightsManagement/package.json
Labels: in progress

#2669 Regenerate datacatalogManagement and change version to 1.0.1
  lib/services/datacatalogManagement/README.md
  lib/services/datacatalogManagement/package.json
Labels: in progress

#2670 Regenerate datafactoryManagement and change version to 2.0.1
  lib/services/datafactoryManagement/README.md
  lib/services/datafactoryManagement/package.json
Labels: in progress

#2673 Regenerate devTestLabs and change version to 2.1.1
  lib/services/devTestLabs/README.md
  lib/services/devTestLabs/package.json
Labels: in progress

#2675 Regenerate deviceprovisioningservicesManagement and change version to…
  lib/services/deviceprovisioningservicesManagement/README.md
  lib/services/deviceprovisioningservicesManagement/lib/iotDpsClient.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/iotDpsClient.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/dpsCertificate.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/index.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/operations/index.js
  lib/services/deviceprovisioningservicesManagement/package.json
Labels: in progress

#2676 Regenerate dnsManagement and change version to 2.1.0
  lib/services/dnsManagement/LICENSE.txt
  lib/services/dnsManagement/README.md
  lib/services/dnsManagement/lib/dnsManagementClient.d.ts
  lib/services/dnsManagement/lib/dnsManagementClient.js
  lib/services/dnsManagement/lib/models/index.d.ts
  lib/services/dnsManagement/lib/models/index.js
  lib/services/dnsManagement/lib/models/subResource.js
  lib/services/dnsManagement/lib/models/zone.js
  lib/services/dnsManagement/lib/models/zoneUpdate.js
  lib/services/dnsManagement/lib/operations/index.d.ts
  lib/services/dnsManagement/lib/operations/recordSets.js
  lib/services/dnsManagement/lib/operations/zones.js
  lib/services/dnsManagement/package.json
Labels: in progress

#2679 Regenerate eventHubManagement and change version to 1.3.0
  lib/services/eventHubManagement/LICENSE.txt
  lib/services/eventHubManagement/README.md
  lib/services/eventHubManagement/lib/eventHubManagementClient.d.ts
  lib/services/eventHubManagement/lib/eventHubManagementClient.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/models/messagingPlan.js
  lib/services/eventHubManagement/lib/models/messagingRegions.js
  lib/services/eventHubManagement/lib/models/messagingRegionsListResult.js
  lib/services/eventHubManagement/lib/models/messagingRegionsProperties.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/index.js
  lib/services/eventHubManagement/lib/operations/messagingPlanOperations.js
  lib/services/eventHubManagement/lib/operations/regions.js
  lib/services/eventHubManagement/package.json
Labels: in progress

#2680 Run 'npm install' after generating and before publishing
  gulpfile.js
Labels: in progress

#2677 Regenerate domainservicesManagement and change version to 1.1.0
  lib/services/domainservicesManagement/LICENSE.txt
  lib/services/domainservicesManagement/README.md
  lib/services/domainservicesManagement/lib/domainservicesManagementClient.d.ts
  lib/services/domainservicesManagement/lib/domainservicesManagementClient.js
  lib/services/domainservicesManagement/package.json
Labels: in progress

#2678 Regenerate entitySeach and change version to 1.1.0
  lib/services/entitySearch/LICENSE.txt
  lib/services/entitySearch/lib/entitySearchAPIClient.d.ts
  lib/services/entitySearch/lib/entitySearchAPIClient.js
  lib/services/entitySearch/lib/models/airport.js
  lib/services/entitySearch/lib/models/answer.js
  lib/services/entitySearch/lib/models/civicStructure.js
  lib/services/entitySearch/lib/models/contractualRulesAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesContractualRule.js
  lib/services/entitySearch/lib/models/contractualRulesLicenseAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesLinkAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesMediaAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesTextAttribution.js
  lib/services/entitySearch/lib/models/creativeWork.js
  lib/services/entitySearch/lib/models/entertainmentBusiness.js
  lib/services/entitySearch/lib/models/entities.js
  lib/services/entitySearch/lib/models/errorResponse.js
  lib/services/entitySearch/lib/models/foodEstablishment.js
  lib/services/entitySearch/lib/models/hotel.js
  lib/services/entitySearch/lib/models/identifiable.js
  lib/services/entitySearch/lib/models/imageObject.js
  lib/services/entitySearch/lib/models/intangible.js
  lib/services/entitySearch/lib/models/license.js
  lib/services/entitySearch/lib/models/localBusiness.js
  lib/services/entitySearch/lib/models/lodgingBusiness.js
  lib/services/entitySearch/lib/models/mediaObject.js
  lib/services/entitySearch/lib/models/movieTheater.js
  lib/services/entitySearch/lib/models/organization.js
  lib/services/entitySearch/lib/models/place.js
  lib/services/entitySearch/lib/models/places.js
  lib/services/entitySearch/lib/models/postalAddress.js
  lib/services/entitySearch/lib/models/response.js
  lib/services/entitySearch/lib/models/responseBase.js
  lib/services/entitySearch/lib/models/restaurant.js
  lib/services/entitySearch/lib/models/searchResponse.js
  lib/services/entitySearch/lib/models/searchResultsAnswer.js
  lib/services/entitySearch/lib/models/structuredValue.js
  lib/services/entitySearch/lib/models/thing.js
  lib/services/entitySearch/lib/models/touristAttraction.js
  lib/services/entitySearch/package.json
Labels: in progress

#2683 Regenerate trafficmanagerManagement2 and change version to 3.0.0
  lib/services/trafficManagerManagement2/LICENSE.txt
  lib/services/trafficManagerManagement2/README.md
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/index.js
  lib/services/trafficManagerManagement2/lib/models/queryExperience.js
  lib/services/trafficManagerManagement2/lib/models/trafficManagerUserMetricsKeyModel.js
  lib/services/trafficManagerManagement2/lib/operations/endpoints.js
  lib/services/trafficManagerManagement2/lib/operations/geographicHierarchies.js
  lib/services/trafficManagerManagement2/lib/operations/heatMap.js
  lib/services/trafficManagerManagement2/lib/operations/index.d.ts
  lib/services/trafficManagerManagement2/lib/operations/index.js
  lib/services/trafficManagerManagement2/lib/operations/profiles.js
  lib/services/trafficManagerManagement2/lib/operations/trafficManagerUserMetricsKeys.js
  lib/services/trafficManagerManagement2/lib/trafficManagerManagementClient.d.ts
  lib/services/trafficManagerManagement2/lib/trafficManagerManagementClient.js
  lib/services/trafficManagerManagement2/package-lock.json
  lib/services/trafficManagerManagement2/package.json
Labels: in progress

#2682 Remove extra search for readme.nodejs.md files in codegen task of gul…
  gulpfile.js
Labels: in progress

#2666 [AutoPR cognitiveservices/data-plane/ContentModerator] Add SSN parameter
  lib/services/contentModerator/LICENSE.txt
  lib/services/contentModerator/lib/contentModeratorAPIClient.d.ts
  lib/services/contentModerator/lib/contentModeratorAPIClient.js
  lib/services/contentModerator/lib/models/classification.js
  lib/services/contentModerator/lib/models/classificationCategory1.js
  lib/services/contentModerator/lib/models/classificationCategory2.js
  lib/services/contentModerator/lib/models/classificationCategory3.js
  lib/services/contentModerator/lib/models/index.d.ts
  lib/services/contentModerator/lib/models/index.js
  lib/services/contentModerator/lib/models/pII.js
  lib/services/contentModerator/lib/models/sSN.js
  lib/services/contentModerator/lib/models/screen.js
  lib/services/contentModerator/lib/operations/index.d.ts
  lib/services/contentModerator/lib/operations/textModeration.js
  lib/services/contentModerator/package.json
Labels: RestPRMerged, in progress

#2693 Bump ms-rest version to 2.3.3 to solve azure package reference problems
  runtime/ms-rest/Changelog.md
  runtime/ms-rest/package-lock.json
  runtime/ms-rest/package.json
Labels: in progress

#2587 [AutoPR cognitiveservices/resource-manager] [Cognitive Services] Add Microsoft.CognitiveServices/skus operation
  lib/services/cognitiveServicesManagement/lib/cognitiveServicesManagementClient.d.ts
  lib/services/cognitiveServicesManagement/lib/cognitiveServicesManagementClient.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/index.js
  lib/services/cognitiveServicesManagement/lib/models/metricName.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSku.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictionInfo.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictions.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkusResult.js
  lib/services/cognitiveServicesManagement/lib/models/usage.js
  lib/services/cognitiveServicesManagement/lib/models/usagesResult.js
  lib/services/cognitiveServicesManagement/lib/operations/accounts.js
  lib/services/cognitiveServicesManagement/lib/operations/checkSkuAvailability.js
  lib/services/cognitiveServicesManagement/lib/operations/index.d.ts
  lib/services/cognitiveServicesManagement/lib/operations/index.js
  lib/services/cognitiveServicesManagement/lib/operations/resourceSkus.js
Labels: RestPRMerged

#2690 Regenerate hdInsightManagement and change version to 0.3.1
  lib/services/hdInsightManagement/README.md
  lib/services/hdInsightManagement/package-lock.json
  lib/services/hdInsightManagement/package.json
Labels: in progress

#2689 Regenerate hanaonazureManagement and change version to 1.0.1
  lib/services/hanaonazureManagement/README.md
  lib/services/hanaonazureManagement/package-lock.json
  lib/services/hanaonazureManagement/package.json
Labels: in progress

#2686 Regenerate eventgridManagement and change version to 1.2.0
  lib/services/eventgridManagement/LICENSE.txt
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/package-lock.json
  lib/services/eventgridManagement/package.json
Labels: in progress

#2685 Regenerate eventgrid and change version to 1.1.0
  lib/services/eventgrid/LICENSE.txt
  lib/services/eventgrid/lib/eventGridClient.d.ts
  lib/services/eventgrid/lib/eventGridClient.js
  lib/services/eventgrid/lib/models/containerRegistryEventActor.js
  lib/services/eventgrid/lib/models/containerRegistryEventData.js
  lib/services/eventgrid/lib/models/containerRegistryEventRequest.js
  lib/services/eventgrid/lib/models/containerRegistryEventSource.js
  lib/services/eventgrid/lib/models/containerRegistryEventTarget.js
  lib/services/eventgrid/lib/models/containerRegistryImageDeletedEventData.js
  lib/services/eventgrid/lib/models/containerRegistryImagePushedEventData.js
  lib/services/eventgrid/lib/models/deviceLifeCycleEventProperties.js
  lib/services/eventgrid/lib/models/deviceTwinInfo.js
  lib/services/eventgrid/lib/models/deviceTwinInfoProperties.js
  lib/services/eventgrid/lib/models/deviceTwinInfoX509Thumbprint.js
  lib/services/eventgrid/lib/models/deviceTwinMetadata.js
  lib/services/eventgrid/lib/models/deviceTwinProperties.js
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/iotHubDeviceCreatedEventData.js
  lib/services/eventgrid/lib/models/iotHubDeviceDeletedEventData.js
  lib/services/eventgrid/package-lock.json
  lib/services/eventgrid/package.json
Labels: in progress

#2630 [AutoPR eventgrid/resource-manager] EventGrid: Initial placeholder for a new preview API version based on previous stable API version
  lib/services/eventgridManagement/LICENSE.txt
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/package.json
Labels: RestPRMerged, in progress

#2697 [AutoPR analysisservices/resource-manager] Change analysisservices nodejs package version to 2.2.0
  lib/services/analysisServices/LICENSE.txt
  lib/services/analysisServices/package.json
Labels: RestPRMerged, in progress

#2684 [AutoPR network/resource-manager] Copy App Gateway Examples from 2018-01-01 to 2018-02-01
  lib/services/networkManagement2/package.json
Labels: RestPRMerged, in progress

#2705 [AutoPR compute/resource-manager] Added Eviction Policy Property for VirtualMachineScaleSetVMProfile for version 2017-12-01
  lib/services/computeManagement2/LICENSE.txt
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/package.json
Labels: RestPRMerged, in progress

#2711 [AutoPR monitor/resource-manager] fix documentation bug: max length of Group Short Name should be 12
  lib/services/monitorManagement/lib/models/actionGroupResource.js
Labels: RestPRMerged, in progress

#2704 [AutoPR sql/resource-manager] Updating swagger with missing 2014-04-01 advisor server api.
  lib/services/sqlManagement2/LICENSE.txt
  lib/services/sqlManagement2/README.md
  lib/services/sqlManagement2/package.json
Labels: RestPRMerged, in progress

#2717 [AutoPR eventhub/resource-manager] EventHub: Revert removing of messaging plan and updated with examples
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/models/messagingPlan.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#2716 update AKV management plane sdk
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.d.ts
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.js
  lib/services/keyVaultManagement/lib/models/iPRule.js
  lib/services/keyVaultManagement/lib/models/index.d.ts
  lib/services/keyVaultManagement/lib/models/index.js
  lib/services/keyVaultManagement/lib/models/networkRuleSet.js
  lib/services/keyVaultManagement/lib/models/vault.js
  lib/services/keyVaultManagement/lib/models/vaultCreateOrUpdateParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchProperties.js
  lib/services/keyVaultManagement/lib/models/vaultProperties.js
  lib/services/keyVaultManagement/lib/models/virtualNetworkRule.js
  lib/services/keyVaultManagement/lib/operations/index.d.ts
  lib/services/keyVaultManagement/lib/operations/vaults.js
  lib/services/keyVaultManagement/package.json
Labels: in progress

#2671 [AutoPR cosmos-db/resource-manager] Add VNet related properties to CosmosDB
  lib/services/cosmosdbManagement/LICENSE.txt
  lib/services/cosmosdbManagement/README.md
  lib/services/cosmosdbManagement/lib/models/databaseAccount.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountCreateUpdateParameters.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/index.js
  lib/services/cosmosdbManagement/lib/models/virtualNetworkRule.js
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
  lib/services/cosmosdbManagement/package.json
Labels: RestPRMerged, in progress

#2723 [AutoPR cognitiveservices/data-plane/SpellCheck] Change C# SDK namespace
  lib/services/spellCheck/LICENSE.txt
  lib/services/spellCheck/lib/spellCheckAPIClient.d.ts
  lib/services/spellCheck/lib/spellCheckAPIClient.js
  lib/services/spellCheck/package.json
Labels: RestPRMerged, in progress

#2729 [AutoPR resourcehealth/resource-manager] Fix swagger violation for resource health operations definitions
  lib/services/resourceHealthManagement/LICENSE.txt
  lib/services/resourceHealthManagement/README.md
  lib/services/resourceHealthManagement/lib/microsoftResourceHealth.d.ts
  lib/services/resourceHealthManagement/lib/microsoftResourceHealth.js
  lib/services/resourceHealthManagement/lib/models/index.d.ts
  lib/services/resourceHealthManagement/lib/models/operation.js
  lib/services/resourceHealthManagement/lib/models/operationDisplay.js
  lib/services/resourceHealthManagement/package.json
Labels: RestPRMerged, in progress

#2727 [AutoPR consumption/resource-manager] Renamed cost allocation tags to cost tags and added schema for get list of all available tag keys
  lib/services/consumptionManagement/LICENSE.txt
  lib/services/consumptionManagement/README.md
  lib/services/consumptionManagement/lib/consumptionManagementClient.d.ts
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/costTag.js
  lib/services/consumptionManagement/lib/models/costTags.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/index.js
  lib/services/consumptionManagement/lib/models/tag.js
  lib/services/consumptionManagement/lib/models/tags.js
  lib/services/consumptionManagement/lib/operations/costTagsOperations.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/index.js
  lib/services/consumptionManagement/lib/operations/tagsOperations.js
  lib/services/consumptionManagement/package.json
Labels: RestPRMerged, in progress

#2734 [AutoPR automation/resource-manager] Correcting the NodeConfiguration Model and Example
  lib/services/automationManagement/lib/models/dscNodeConfigurationCreateOrUpdateParameters.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/operations/dscNodeConfigurationOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#2742 Regenerate eventgrid
  lib/services/eventgrid/package-lock.json
  lib/services/eventgrid/package.json
Labels: in progress

#2744 [AutoPR apimanagement/resource-manager] add readonly property private ip address in addtional location
  lib/services/apimanagement/lib/models/additionalLocation.js
  lib/services/apimanagement/lib/models/apiManagementServiceBaseProperties.js
  lib/services/apimanagement/lib/models/apiManagementServiceResource.js
  lib/services/apimanagement/lib/models/apiManagementServiceUpdateParameters.js
  lib/services/apimanagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#2746 Add --package parameter to gulp publish task
  gulpfile.js
Labels: in progress

#2730 [AutoPR compute/resource-manager] Fix minor typos in compute.
  lib/services/computeManagement2/lib/models/availabilitySetUpdate.js
  lib/services/computeManagement2/lib/models/imageUpdate.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoricalStatusInfo.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoricalStatusInfoProperties.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoryStatus.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetListOSUpgradeHistory.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
Labels: RestPRMerged, in progress

#2747 [AutoPR cognitiveservices/data-plane/ContentModerator] Set language parameter as a non-required field for Screen Text API
  lib/services/contentModerator/lib/operations/index.d.ts
  lib/services/contentModerator/lib/operations/textModeration.js
Labels: RestPRMerged, in progress

#2753 [AutoPR sql/resource-manager] Fixing readme error the was merged in PR 2706.
  lib/services/sqlManagement2/lib/models/completeDatabaseRestoreDefinition.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/instanceFailoverGroup.js
  lib/services/sqlManagement2/lib/models/instanceFailoverGroupListResult.js
  lib/services/sqlManagement2/lib/models/instanceFailoverGroupReadOnlyEndpoint.js
  lib/services/sqlManagement2/lib/models/instanceFailoverGroupReadWriteEndpoint.js
  lib/services/sqlManagement2/lib/models/managedDatabase.js
  lib/services/sqlManagement2/lib/models/managedDatabaseListResult.js
  lib/services/sqlManagement2/lib/models/managedDatabaseUpdate.js
  lib/services/sqlManagement2/lib/models/managedInstance.js
  lib/services/sqlManagement2/lib/models/managedInstanceListResult.js
  lib/services/sqlManagement2/lib/models/managedInstancePairInfo.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/models/partnerRegionInfo.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/instanceFailoverGroups.js
  lib/services/sqlManagement2/lib/operations/managedDatabases.js
  lib/services/sqlManagement2/lib/operations/managedInstances.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged, in progress

#2751 [AutoPR apimanagement/resource-manager] ApiIssue HEAD operation name consistent across the spec
  lib/services/apimanagement/lib/operations/apiIssue.js
  lib/services/apimanagement/lib/operations/apiIssueAttachment.js
  lib/services/apimanagement/lib/operations/apiIssueComment.js
  lib/services/apimanagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#2748 [AutoPR batch/data-plane] Update documentation of Batch data plane swagger.
  lib/services/batch/LICENSE.txt
  lib/services/batch/lib/models/autoPoolSpecification.js
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudJobSchedule.js
  lib/services/batch/lib/models/cloudPool.js
  lib/services/batch/lib/models/cloudTask.js
  lib/services/batch/lib/models/computeNode.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/jobAddParameter.js
  lib/services/batch/lib/models/jobManagerTask.js
  lib/services/batch/lib/models/jobPatchParameter.js
  lib/services/batch/lib/models/jobPreparationTask.js
  lib/services/batch/lib/models/jobReleaseTask.js
  lib/services/batch/lib/models/jobScheduleAddParameter.js
  lib/services/batch/lib/models/jobSchedulePatchParameter.js
  lib/services/batch/lib/models/jobScheduleUpdateParameter.js
  lib/services/batch/lib/models/jobSpecification.js
  lib/services/batch/lib/models/jobUpdateParameter.js
  lib/services/batch/lib/models/nodeCounts.js
  lib/services/batch/lib/models/poolAddParameter.js
  lib/services/batch/lib/models/poolInformation.js
  lib/services/batch/lib/models/poolNodeCounts.js
  lib/services/batch/lib/models/poolPatchParameter.js
  lib/services/batch/lib/models/poolSpecification.js
  lib/services/batch/lib/models/poolUpdatePropertiesParameter.js
  lib/services/batch/lib/models/startTask.js
  lib/services/batch/lib/models/taskAddParameter.js
  lib/services/batch/lib/models/taskConstraints.js
  lib/services/batch/lib/models/taskUpdateParameter.js
  lib/services/batch/lib/models/userIdentity.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
  lib/services/batch/lib/operations/task.js
Labels: RestPRMerged, in progress

#2769 [AutoPR sql/resource-manager] Add Swagger for Short Term Retention Policies
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/shortTermRetentionPolicy.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/shortTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged, in progress

#2702 [AutoPR datafactory/resource-manager] Change connection-string to be object and support making severname, d…
  lib/services/datafactoryManagement/LICENSE.txt
  lib/services/datafactoryManagement/README.md
  lib/services/datafactoryManagement/lib/models/azureMySqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/azurePostgreSqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureSqlDWLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureSqlDatabaseLinkedService.js
  lib/services/datafactoryManagement/lib/models/azureStorageLinkedService.js
  lib/services/datafactoryManagement/lib/models/cosmosDbLinkedService.js
  lib/services/datafactoryManagement/lib/models/couchbaseLinkedService.js
  lib/services/datafactoryManagement/lib/models/drillLinkedService.js
  lib/services/datafactoryManagement/lib/models/executeSSISPackageActivity.js
  lib/services/datafactoryManagement/lib/models/greenplumLinkedService.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/mariaDBLinkedService.js
  lib/services/datafactoryManagement/lib/models/netezzaLinkedService.js
  lib/services/datafactoryManagement/lib/models/odbcLinkedService.js
  lib/services/datafactoryManagement/lib/models/oracleLinkedService.js
  lib/services/datafactoryManagement/lib/models/sSISExecutionParameter.js
  lib/services/datafactoryManagement/lib/models/sSISPropertyOverride.js
  lib/services/datafactoryManagement/lib/models/sqlServerLinkedService.js
  lib/services/datafactoryManagement/lib/models/verticaLinkedService.js
  lib/services/datafactoryManagement/package.json
Labels: RestPRMerged, in progress

#2761 [AutoPR automation/resource-manager] Changing enum to free string for Provisioning State
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/job.js
  lib/services/automationManagement/lib/models/jobCollectionItem.js
Labels: RestPRMerged, in progress

#2719 [AutoPR servicebus/resource-manager] Service Bus: added Standard to Premium namespace migration API [DO NOT MERGE]
  lib/services/serviceBusManagement2/LICENSE.txt
  lib/services/serviceBusManagement2/README.md
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/index.js
  lib/services/serviceBusManagement2/lib/models/migrationConfigListResult.js
  lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/index.js
  lib/services/serviceBusManagement2/lib/operations/migrationConfig.js
  lib/services/serviceBusManagement2/lib/operations/migrationConfigs.js
  lib/services/serviceBusManagement2/lib/operations/migrationConfigurations.js
  lib/services/serviceBusManagement2/lib/serviceBusManagementClient.d.ts
  lib/services/serviceBusManagement2/lib/serviceBusManagementClient.js
  lib/services/serviceBusManagement2/package.json
Labels: RestPRMerged, in progress

#2778 Update comments based on updated swagger spec
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudJobSchedule.js
  lib/services/batch/lib/models/cloudPool.js
  lib/services/batch/lib/models/cloudTask.js
  lib/services/batch/lib/models/computeNode.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/jobAddParameter.js
  lib/services/batch/lib/models/jobManagerTask.js
  lib/services/batch/lib/models/jobPatchParameter.js
  lib/services/batch/lib/models/jobPreparationTask.js
  lib/services/batch/lib/models/jobReleaseTask.js
  lib/services/batch/lib/models/jobScheduleAddParameter.js
  lib/services/batch/lib/models/jobSchedulePatchParameter.js
  lib/services/batch/lib/models/jobScheduleUpdateParameter.js
  lib/services/batch/lib/models/jobSpecification.js
  lib/services/batch/lib/models/nodeCounts.js
  lib/services/batch/lib/models/poolAddParameter.js
  lib/services/batch/lib/models/poolInformation.js
  lib/services/batch/lib/models/poolNodeCounts.js
  lib/services/batch/lib/models/poolPatchParameter.js
  lib/services/batch/lib/models/poolSpecification.js
  lib/services/batch/lib/models/poolUpdatePropertiesParameter.js
  lib/services/batch/lib/models/startTask.js
  lib/services/batch/lib/models/taskAddParameter.js
  lib/services/batch/lib/models/taskConstraints.js
  lib/services/batch/lib/models/taskUpdateParameter.js
  lib/services/batch/lib/models/userIdentity.js
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
  lib/services/batch/lib/operations/task.js
  lib/services/batch/package-lock.json
  lib/services/batch/package.json
  test/recordings/batchservice-tests/Batch_Service_operations_should_get_pool_node_counts_successfully.nock.js
Labels: Batch, RestPRMerged

#2783 [AutoPR batch/data-plane] Batch API: Fix the wrong statement in description
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
Labels: RestPRMerged, in progress

#2785 [AutoPR network/resource-manager] Network Watcher: Suppressing a validation message
  lib/services/networkManagement2/lib/models/expressRouteCrossConnection.js
  lib/services/networkManagement2/lib/models/expressRouteCrossConnectionPeering.js
  lib/services/networkManagement2/lib/models/httpConfiguration.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/operations/expressRouteCrossConnectionPeerings.js
  lib/services/networkManagement2/lib/operations/expressRouteCrossConnections.js
  lib/services/networkManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#2791 [AutoPR web/resource-manager] Fix ASE instance metrics url
  lib/services/websiteManagement2/lib/models/dataTableResponseColumn.js
  lib/services/websiteManagement2/lib/models/dataTableResponseObject.js
  lib/services/websiteManagement2/lib/models/detectorInfo.js
  lib/services/websiteManagement2/lib/models/detectorResponse.js
  lib/services/websiteManagement2/lib/models/detectorResponseCollection.js
  lib/services/websiteManagement2/lib/models/diagnosticData.js
  lib/services/websiteManagement2/lib/models/index.d.ts
  lib/services/websiteManagement2/lib/models/index.js
  lib/services/websiteManagement2/lib/models/rendering.js
  lib/services/websiteManagement2/lib/operations/appServiceEnvironments.js
  lib/services/websiteManagement2/lib/operations/diagnostics.js
  lib/services/websiteManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#2797 [AutoPR servicebus/resource-manager] Service Bus: added $skip and $top to list calls
  lib/services/serviceBusManagement2/lib/operations/index.d.ts
  lib/services/serviceBusManagement2/lib/operations/queues.js
  lib/services/serviceBusManagement2/lib/operations/rules.js
  lib/services/serviceBusManagement2/lib/operations/subscriptions.js
  lib/services/serviceBusManagement2/lib/operations/topics.js
Labels: RestPRMerged, in progress

#2799 [AutoPR eventgrid/data-plane] EventGrid Py conf to 1.0.0
  lib/services/eventgrid/LICENSE.txt
  lib/services/eventgrid/package.json
Labels: RestPRMerged

#2801 [AutoPR eventgrid/resource-manager] EventGrid Py conf to 1.0.0
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/topic.js
  lib/services/eventgridManagement/lib/models/trackedResource.js
Labels: RestPRMerged

#2811 [AutoPR compute/resource-manager] Update OS Upgrade History API
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/rollbackStatusInfo.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoricalStatusInfo.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoricalStatusInfoProperties.js
Labels: RestPRMerged
