Repository Azure/azure-sdk-for-node, pull requests merged in 2018-07, with the labels that each got.

#3096 [AutoPR automation/resource-manager] Module and activity data enrichment
  lib/services/automationManagement/lib/models/activityParameter.js
  lib/services/automationManagement/lib/models/activityParameterValidationSet.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/module.js
Labels: RestPRMerged, in progress

#3097 [AutoPR compute/resource-manager] User identities in a new dictionary property
  lib/services/computeManagement2/lib/models/availabilitySetListResult.js
  lib/services/computeManagement2/lib/models/dataDisk.js
  lib/services/computeManagement2/lib/models/disk.js
  lib/services/computeManagement2/lib/models/diskSku.js
  lib/services/computeManagement2/lib/models/diskUpdate.js
  lib/services/computeManagement2/lib/models/image.js
  lib/services/computeManagement2/lib/models/imageDataDisk.js
  lib/services/computeManagement2/lib/models/imageOSDisk.js
  lib/services/computeManagement2/lib/models/imageStorageProfile.js
  lib/services/computeManagement2/lib/models/imageUpdate.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/managedDiskParameters.js
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetDataDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetManagedDiskParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/availabilitySets.js
  lib/services/computeManagement2/lib/operations/disks.js
  lib/services/computeManagement2/lib/operations/images.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged

#3098 [AutoPR compute/resource-manager] Added listing all availability sets in a subscription and StandardSSD…
  lib/services/computeManagement2/lib/models/availabilitySetListResult.js
  lib/services/computeManagement2/lib/models/dataDisk.js
  lib/services/computeManagement2/lib/models/disk.js
  lib/services/computeManagement2/lib/models/diskSku.js
  lib/services/computeManagement2/lib/models/diskUpdate.js
  lib/services/computeManagement2/lib/models/image.js
  lib/services/computeManagement2/lib/models/imageDataDisk.js
  lib/services/computeManagement2/lib/models/imageOSDisk.js
  lib/services/computeManagement2/lib/models/imageStorageProfile.js
  lib/services/computeManagement2/lib/models/imageUpdate.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/managedDiskParameters.js
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetDataDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetManagedDiskParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/availabilitySets.js
  lib/services/computeManagement2/lib/operations/disks.js
  lib/services/computeManagement2/lib/operations/images.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#3107 [AutoPR network/resource-manager] Fixed typos. Fixes issue 1770 in .NET SDK
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/vpnConnections.js
Labels: RestPRMerged, in progress

#3116 [AutoPR postgresql/resource-manager] Add support for PG 10
  lib/services/postgresqlManagement/LICENSE.txt
  lib/services/postgresqlManagement/lib/models/index.d.ts
  lib/services/postgresqlManagement/lib/models/index.js
  lib/services/postgresqlManagement/lib/models/server.js
  lib/services/postgresqlManagement/lib/models/serverForCreate.js
  lib/services/postgresqlManagement/lib/models/serverPropertiesForCreate.js
  lib/services/postgresqlManagement/lib/models/serverSecurityAlertPolicy.js
  lib/services/postgresqlManagement/lib/models/serverUpdateParameters.js
  lib/services/postgresqlManagement/lib/models/virtualNetworkRule.js
  lib/services/postgresqlManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/postgresqlManagement/lib/operations/index.d.ts
  lib/services/postgresqlManagement/lib/operations/index.js
  lib/services/postgresqlManagement/lib/operations/serverSecurityAlertPolicies.js
  lib/services/postgresqlManagement/lib/operations/servers.js
  lib/services/postgresqlManagement/lib/operations/virtualNetworkRules.js
  lib/services/postgresqlManagement/lib/postgreSQLManagementClient.d.ts
  lib/services/postgresqlManagement/lib/postgreSQLManagementClient.js
  lib/services/postgresqlManagement/package.json
Labels: RestPRMerged

#3119 Generating mediaservices for 2018-06-01-preview.
  lib/services/mediaServicesManagement/README.md
  lib/services/mediaServicesManagement/lib/azureMediaServices.js
  lib/services/mediaServicesManagement/lib/models/apiError.js
  lib/services/mediaServicesManagement/lib/models/cbcsDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/cencDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCbcs.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCenc.js
  lib/services/mediaServicesManagement/lib/models/defaultKey.js
  lib/services/mediaServicesManagement/lib/models/enabledProtocols.js
  lib/services/mediaServicesManagement/lib/models/envelopeEncryption.js
  lib/services/mediaServicesManagement/lib/models/index.d.ts
  lib/services/mediaServicesManagement/lib/models/index.js
  lib/services/mediaServicesManagement/lib/models/job.js
  lib/services/mediaServicesManagement/lib/models/liveEvent.js
  lib/services/mediaServicesManagement/lib/models/liveEventPreview.js
  lib/services/mediaServicesManagement/lib/models/noEncryption.js
  lib/services/mediaServicesManagement/lib/models/streamingLocator.js
  lib/services/mediaServicesManagement/lib/models/streamingLocatorContentKey.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicy.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyContentKey.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyContentKeys.js
  lib/services/mediaServicesManagement/lib/models/trackPropertyCondition.js
  lib/services/mediaServicesManagement/lib/operations/index.d.ts
  lib/services/mediaServicesManagement/lib/operations/jobs.js
  lib/services/mediaServicesManagement/lib/operations/liveEvents.js
  lib/services/mediaServicesManagement/lib/operations/streamingLocators.js
  lib/services/mediaServicesManagement/lib/operations/streamingPolicies.js
  lib/services/mediaServicesManagement/package-lock.json
  lib/services/mediaServicesManagement/package.json
Labels: in progress

#3083 [AutoPR batch/data-plane] Update documentation of possible errors and size limits for Batch
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudJobSchedule.js
  lib/services/batch/lib/models/cloudTask.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/jobAddParameter.js
  lib/services/batch/lib/models/jobManagerTask.js
  lib/services/batch/lib/models/jobPreparationTask.js
  lib/services/batch/lib/models/jobReleaseTask.js
  lib/services/batch/lib/models/jobScheduleAddParameter.js
  lib/services/batch/lib/models/jobSchedulePatchParameter.js
  lib/services/batch/lib/models/jobScheduleUpdateParameter.js
  lib/services/batch/lib/models/jobSpecification.js
  lib/services/batch/lib/models/multiInstanceSettings.js
  lib/services/batch/lib/models/startTask.js
  lib/services/batch/lib/models/taskAddCollectionParameter.js
  lib/services/batch/lib/models/taskAddParameter.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
  lib/services/batch/lib/operations/task.js
Labels: RestPRMerged, in progress

#3123 [AutoPR cognitiveservices/data-plane/CustomVision/Training] Custom vision 2.1 updates
  lib/services/customVision/training/lib/models/exportModel.js
  lib/services/customVision/training/lib/models/index.d.ts
  lib/services/customVision/training/lib/models/iteration.js
  lib/services/customVision/training/lib/models/project.js
  lib/services/customVision/training/lib/models/projectSettings.js
  lib/services/customVision/training/lib/trainingAPIClient.d.ts
  lib/services/customVision/training/lib/trainingAPIClient.js
Labels: RestPRMerged, in progress

#3133 [AutoPR batch/resource-manager] Fixed a typo
  lib/services/batchManagement/LICENSE.txt
  lib/services/batchManagement/README.md
  lib/services/batchManagement/lib/models/index.d.ts
  lib/services/batchManagement/lib/models/virtualMachineConfiguration.js
  lib/services/batchManagement/lib/operations/index.d.ts
  lib/services/batchManagement/lib/operations/poolOperations.js
  lib/services/batchManagement/package.json
Labels: RestPRMerged, in progress

#3135 [AutoPR network/resource-manager] Renaming ConnectionBandwidthInMbps to ConnectionBandwidth
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/vpnConnection.js
Labels: RestPRMerged, in progress

#3040 [AutoPR resources/resource-manager] Add userAssignedIdentities
  lib/services/resourceManagement/lib/resource/models/genericResource.js
  lib/services/resourceManagement/lib/resource/models/identity.js
  lib/services/resourceManagement/lib/resource/models/identityUserAssignedIdentitiesValue.js
  lib/services/resourceManagement/lib/resource/models/index.d.ts
  lib/services/resourceManagement/lib/resource/models/index.js
  lib/services/resourceManagement/lib/resource/operations/index.d.ts
  lib/services/resourceManagement/lib/resource/operations/resources.js
Labels: RestPRMerged, in progress

#3125 [AutoPR compute/resource-manager] Update RunCommand operation output as valid json object
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/runCommandResult.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#3130 [AutoPR] cognitiveservices/data-plane/CustomVision/Training
  lib/services/customVision/training/lib/models/exportModel.js
  lib/services/customVision/training/lib/models/index.d.ts
  lib/services/customVision/training/lib/models/iteration.js
  lib/services/customVision/training/lib/models/project.js
  lib/services/customVision/training/lib/models/projectSettings.js
  lib/services/customVision/training/lib/trainingAPIClient.d.ts
  lib/services/customVision/training/lib/trainingAPIClient.js
  lib/services/customVision/training/package-lock.json
  lib/services/customVision/training/package.json
Labels: ServicePR, in progress

#3134 [AutoPR] batch/resource-manager
  lib/services/batchManagement/LICENSE.txt
  lib/services/batchManagement/README.md
  lib/services/batchManagement/lib/models/index.d.ts
  lib/services/batchManagement/lib/models/virtualMachineConfiguration.js
  lib/services/batchManagement/lib/operations/index.d.ts
  lib/services/batchManagement/lib/operations/poolOperations.js
  lib/services/batchManagement/package.json
Labels: ServicePR, in progress

#3148 Revert customVision package version to 1.0.0-preview
  lib/services/customVision/training/package-lock.json
  lib/services/customVision/training/package.json
Labels: in progress

#3145 [AutoPR search/resource-manager] Azure Search: Add resource identity (MSI) support
  lib/services/searchManagement/LICENSE.txt
  lib/services/searchManagement/README.md
  lib/services/searchManagement/lib/models/identity.js
  lib/services/searchManagement/lib/models/index.d.ts
  lib/services/searchManagement/lib/models/index.js
  lib/services/searchManagement/lib/models/operation.js
  lib/services/searchManagement/lib/models/operationDisplay.js
  lib/services/searchManagement/lib/models/operationListResult.js
  lib/services/searchManagement/lib/models/resource.js
  lib/services/searchManagement/lib/models/searchService.js
  lib/services/searchManagement/lib/operations/index.d.ts
  lib/services/searchManagement/lib/operations/index.js
  lib/services/searchManagement/lib/operations/operations.js
  lib/services/searchManagement/lib/operations/services.js
  lib/services/searchManagement/lib/searchManagementClient.d.ts
  lib/services/searchManagement/lib/searchManagementClient.js
  lib/services/searchManagement/package.json
Labels: RestPRMerged, in progress

#3157 [AutoPR compute/resource-manager] Update VMSS planned maintenance description to refer to best practices doc
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
Labels: RestPRMerged, in progress

#3149 [AutoPR] search/resource-manager
  lib/services/searchManagement/LICENSE.txt
  lib/services/searchManagement/README.md
  lib/services/searchManagement/lib/models/identity.js
  lib/services/searchManagement/lib/models/index.d.ts
  lib/services/searchManagement/lib/models/index.js
  lib/services/searchManagement/lib/models/operation.js
  lib/services/searchManagement/lib/models/operationDisplay.js
  lib/services/searchManagement/lib/models/operationListResult.js
  lib/services/searchManagement/lib/models/resource.js
  lib/services/searchManagement/lib/models/searchService.js
  lib/services/searchManagement/lib/operations/index.d.ts
  lib/services/searchManagement/lib/operations/index.js
  lib/services/searchManagement/lib/operations/operations.js
  lib/services/searchManagement/lib/operations/services.js
  lib/services/searchManagement/lib/searchManagementClient.d.ts
  lib/services/searchManagement/lib/searchManagementClient.js
  lib/services/searchManagement/package.json
Labels: ServicePR, Started-Sprint-121, Unplanned-Sprint-121, in progress

#3153 [AutoPR datafactory/resource-manager] Remove sharedWithFactories property from SelfHostedIntegrationRuntime…
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/selfHostedIntegrationRuntimeStatus.js
Labels: RestPRMerged, in progress

#3160 Regenerate custom vision prediction package
  lib/services/customVision/prediction/lib/models/boundingBox.js
  lib/services/customVision/prediction/lib/models/imagePrediction.js
  lib/services/customVision/prediction/lib/models/imageUrl.js
  lib/services/customVision/prediction/lib/models/prediction.js
  lib/services/customVision/prediction/lib/predictionAPIClient.js
  lib/services/customVision/prediction/package-lock.json
  lib/services/customVision/prediction/package.json
Labels: Started-Sprint-121, Unplanned-Sprint-121, in progress

#3127 [AutoPR network/resource-manager] Port fixes from 04-01 (master) to 06-01
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/vpnConnections.js
Labels: RestPRMerged, in progress

#3144 [AutoPR hdinsight/resource-manager] [HDInsight] Added support for ADLS type Gen 2
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/storageAccount.js
Labels: RestPRMerged, in progress

#3163 [AutoPR automation/resource-manager] Add x-ms-parameter-location property
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
Labels: RestPRMerged, in progress

#3117 [AutoPR] postgresql/resource-manager
  lib/services/postgresqlManagement/LICENSE.txt
  lib/services/postgresqlManagement/lib/models/index.d.ts
  lib/services/postgresqlManagement/lib/models/server.js
  lib/services/postgresqlManagement/lib/models/serverForCreate.js
  lib/services/postgresqlManagement/lib/models/serverPropertiesForCreate.js
  lib/services/postgresqlManagement/lib/models/serverUpdateParameters.js
  lib/services/postgresqlManagement/lib/operations/index.d.ts
  lib/services/postgresqlManagement/lib/operations/servers.js
  lib/services/postgresqlManagement/lib/postgreSQLManagementClient.d.ts
  lib/services/postgresqlManagement/lib/postgreSQLManagementClient.js
  lib/services/postgresqlManagement/package-lock.json
  lib/services/postgresqlManagement/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3168 Generate azure-arm-devspaces
  lib/services/devspacesManagement/LICENSE.txt
  lib/services/devspacesManagement/README.md
  lib/services/devspacesManagement/lib/devSpacesManagementClient.d.ts
  lib/services/devspacesManagement/lib/devSpacesManagementClient.js
  lib/services/devspacesManagement/lib/models/controller.js
  lib/services/devspacesManagement/lib/models/controllerConnectionDetails.js
  lib/services/devspacesManagement/lib/models/controllerConnectionDetailsList.js
  lib/services/devspacesManagement/lib/models/controllerList.js
  lib/services/devspacesManagement/lib/models/controllerUpdateParameters.js
  lib/services/devspacesManagement/lib/models/errorDetails.js
  lib/services/devspacesManagement/lib/models/errorResponse.js
  lib/services/devspacesManagement/lib/models/index.d.ts
  lib/services/devspacesManagement/lib/models/index.js
  lib/services/devspacesManagement/lib/models/kubernetesConnectionDetails.js
  lib/services/devspacesManagement/lib/models/orchestratorSpecificConnectionDetails.js
  lib/services/devspacesManagement/lib/models/resource.js
  lib/services/devspacesManagement/lib/models/resourceProviderOperationDefinition.js
  lib/services/devspacesManagement/lib/models/resourceProviderOperationDisplay.js
  lib/services/devspacesManagement/lib/models/resourceProviderOperationList.js
  lib/services/devspacesManagement/lib/models/sku.js
  lib/services/devspacesManagement/lib/models/trackedResource.js
  lib/services/devspacesManagement/lib/operations/controllers.js
  lib/services/devspacesManagement/lib/operations/index.d.ts
  lib/services/devspacesManagement/lib/operations/index.js
  lib/services/devspacesManagement/lib/operations/operations.js
  lib/services/devspacesManagement/package-lock.json
  lib/services/devspacesManagement/package.json
Labels: Started-Sprint-121, Unplanned-Sprint-121, in progress

#3165 [AutoPR compute/resource-manager] Add missing ScaleSet properties
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetDataDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
Labels: RestPRMerged, in progress

#3111 [AutoPR] containerregistry/resource-manager
  lib/services/containerRegistryManagement/lib/LICENSE.txt
  lib/services/containerRegistryManagement/lib/lib/containerRegistryManagementClient.d.ts
  lib/services/containerRegistryManagement/lib/lib/containerRegistryManagementClient.js
  lib/services/containerRegistryManagement/lib/lib/models/actor.js
  lib/services/containerRegistryManagement/lib/lib/models/callbackConfig.js
  lib/services/containerRegistryManagement/lib/lib/models/event.js
  lib/services/containerRegistryManagement/lib/lib/models/eventContent.js
  lib/services/containerRegistryManagement/lib/lib/models/eventInfo.js
  lib/services/containerRegistryManagement/lib/lib/models/eventListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/eventRequestMessage.js
  lib/services/containerRegistryManagement/lib/lib/models/eventResponseMessage.js
  lib/services/containerRegistryManagement/lib/lib/models/importImageParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/importSource.js
  lib/services/containerRegistryManagement/lib/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/lib/models/index.js
  lib/services/containerRegistryManagement/lib/lib/models/operationDefinition.js
  lib/services/containerRegistryManagement/lib/lib/models/operationDisplayDefinition.js
  lib/services/containerRegistryManagement/lib/lib/models/operationListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/regenerateCredentialParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/registry.js
  lib/services/containerRegistryManagement/lib/lib/models/registryListCredentialsResult.js
  lib/services/containerRegistryManagement/lib/lib/models/registryListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/registryNameCheckRequest.js
  lib/services/containerRegistryManagement/lib/lib/models/registryNameStatus.js
  lib/services/containerRegistryManagement/lib/lib/models/registryPassword.js
  lib/services/containerRegistryManagement/lib/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/registryUsage.js
  lib/services/containerRegistryManagement/lib/lib/models/registryUsageListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/replication.js
  lib/services/containerRegistryManagement/lib/lib/models/replicationListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/replicationUpdateParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/request.js
  lib/services/containerRegistryManagement/lib/lib/models/resource.js
  lib/services/containerRegistryManagement/lib/lib/models/sku.js
  lib/services/containerRegistryManagement/lib/lib/models/source.js
  lib/services/containerRegistryManagement/lib/lib/models/status.js
  lib/services/containerRegistryManagement/lib/lib/models/storageAccountProperties.js
  lib/services/containerRegistryManagement/lib/lib/models/target.js
  lib/services/containerRegistryManagement/lib/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/webhookListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/lib/operations/index.js
  lib/services/containerRegistryManagement/lib/lib/operations/operations.js
  lib/services/containerRegistryManagement/lib/lib/operations/registries.js
  lib/services/containerRegistryManagement/lib/lib/operations/replications.js
  lib/services/containerRegistryManagement/lib/lib/operations/webhooks.js
  lib/services/containerRegistryManagement/lib/models/imageCopyFromModel.js
  lib/services/containerRegistryManagement/lib/package.json
Labels: ServicePR, in progress

#3177 Regenerate containerregistry package
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.d.ts
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/operationDefinition.js
  lib/services/containerRegistryManagement/lib/models/operationMetricSpecificationDefinition.js
  lib/services/containerRegistryManagement/lib/models/operationServiceSpecificationDefinition.js
  lib/services/containerRegistryManagement/lib/models/quarantinePolicy.js
  lib/services/containerRegistryManagement/lib/models/registryPolicies.js
  lib/services/containerRegistryManagement/lib/models/trustPolicy.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/registries.js
  lib/services/containerRegistryManagement/package-lock.json
  lib/services/containerRegistryManagement/package.json
Labels: Planned-Sprint-121, Started-Sprint-121, in progress

#3181 [AutoPR automation/resource-manager] Changing schema from string to file
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/runbookDraftOperations.js
Labels: RestPRMerged, in progress

#2625 [AutoPR] iothub/resource-manager
  lib/services/iothub/lib/iotHubClient.d.ts
  lib/services/iothub/lib/iotHubClient.js
  lib/services/iothub/lib/models/operationsMonitoringProperties.js
  lib/services/iothub/package-lock.json
  lib/services/iothub/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3194 [AutoPR containerservices/resource-manager] [AKS] added PATCH endpoint for updating tags
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/index.js
  lib/services/containerservicesManagement/lib/models/tagsObject.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
Labels: RestPRMerged, in progress

#2715 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/sensitivityLabel.js
  lib/services/sqlManagement2/lib/models/sensitivityLabelListResult.js
  lib/services/sqlManagement2/lib/models/shortTermRetentionPolicy.js
  lib/services/sqlManagement2/lib/models/tdeCertificate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/managedInstanceTdeCertificates.js
  lib/services/sqlManagement2/lib/operations/sensitivityLabels.js
  lib/services/sqlManagement2/lib/operations/shortTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/tdeCertificates.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
  lib/services/sqlManagement2/package-lock.json
  lib/services/sqlManagement2/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3205 [AutoPR compute/resource-manager] Fixing instance view object definition in VMSSVMProperties
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
Labels: RestPRMerged, in progress

#3210 [AutoPR monitor/resource-manager] updated description of recurrent frequency
  lib/services/monitorManagement/lib/models/autoscaleProfile.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/recurrence.js
Labels: RestPRMerged, in progress

#3208 Generate AutoSuggest data-plane library
  lib/services/cognitiveServicesAutoSuggest/LICENSE.txt
  lib/services/cognitiveServicesAutoSuggest/README.md
  lib/services/cognitiveServicesAutoSuggest/lib/autoSuggestAPIClient.d.ts
  lib/services/cognitiveServicesAutoSuggest/lib/autoSuggestAPIClient.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/action.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/answer.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/creativeWork.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/errorModel.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/errorResponse.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/identifiable.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/index.d.ts
  lib/services/cognitiveServicesAutoSuggest/lib/models/index.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/queryContext.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/response.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/responseBase.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/searchAction.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/suggestions.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/suggestionsSuggestionGroup.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/thing.js
  lib/services/cognitiveServicesAutoSuggest/package-lock.json
  lib/services/cognitiveServicesAutoSuggest/package.json
Labels: Started-Sprint-121, Unplanned-Sprint-121, in progress

#2849 [AutoPR] cognitiveservices/data-plane/CustomImageSearch
  lib/services/cognitiveServicesCustomImageSearch/LICENSE.txt
  lib/services/cognitiveServicesCustomImageSearch/README.md
  lib/services/cognitiveServicesCustomImageSearch/lib/customImageSearchAPIClient.d.ts
  lib/services/cognitiveServicesCustomImageSearch/lib/customImageSearchAPIClient.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/answer.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/imageObject.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/images.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesCustomImageSearch/lib/models/index.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/mediaObject.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/query.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/response.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/thing.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/webPage.js
  lib/services/cognitiveServicesCustomImageSearch/lib/operations/customInstance.js
  lib/services/cognitiveServicesCustomImageSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesCustomImageSearch/lib/operations/index.js
  lib/services/cognitiveServicesCustomImageSearch/package-lock.json
  lib/services/cognitiveServicesCustomImageSearch/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3193 [AutoPR cognitiveservices/data-plane/ComputerVision] Enable Computer Vision Client to customize endpoint.
  lib/services/computerVision/lib/computerVisionClient.d.ts
  lib/services/computerVision/lib/computerVisionClient.js
  lib/services/computerVision/package.json
Labels: RestPRMerged, in progress

#2796 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/lib/models/azureResource.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/restriction.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
  lib/services/storageManagement2/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3231 [AutoPR datafactory/resource-manager] [Datafactory] Bringing back additionalProperties in Activity removed by mistake
  lib/services/datafactoryManagement/lib/models/activity.js
  lib/services/datafactoryManagement/lib/models/forEachActivity.js
  lib/services/datafactoryManagement/lib/models/ifConditionActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/pipelineResource.js
  lib/services/datafactoryManagement/lib/models/untilActivity.js
Labels: RestPRMerged, in progress

#3230 [AutoPR cognitiveservices/data-plane/TextAnalytics] [Cognitive Services] Update endpoint URL template for TextAnalytics.
  lib/services/textAnalytics/lib/textAnalyticsClient.d.ts
  lib/services/textAnalytics/lib/textAnalyticsClient.js
  lib/services/textAnalytics/package.json
Labels: RestPRMerged, in progress

#3174 [AutoPR keyvault/resource-manager] KV multiapi Readme
  lib/services/keyVaultManagement/LICENSE.txt
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.d.ts
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.js
  lib/services/keyVaultManagement/lib/models/iPRule.js
  lib/services/keyVaultManagement/lib/models/index.d.ts
  lib/services/keyVaultManagement/lib/models/index.js
  lib/services/keyVaultManagement/lib/models/networkRuleSet.js
  lib/services/keyVaultManagement/lib/models/vault.js
  lib/services/keyVaultManagement/lib/models/vaultCreateOrUpdateParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchProperties.js
  lib/services/keyVaultManagement/lib/models/vaultProperties.js
  lib/services/keyVaultManagement/lib/models/virtualNetworkRule.js
  lib/services/keyVaultManagement/lib/operations/index.d.ts
  lib/services/keyVaultManagement/lib/operations/vaults.js
  lib/services/keyVaultManagement/package.json
Labels: RestPRMerged, in progress

#2728 [AutoPR] cosmos-db/resource-manager
  lib/services/cosmosdbManagement/lib/cosmosDBManagementClient.d.ts
  lib/services/cosmosdbManagement/lib/cosmosDBManagementClient.js
  lib/services/cosmosdbManagement/package-lock.json
  lib/services/cosmosdbManagement/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3228 [AutoPR containerservices/resource-manager] [AKS] remove "KeyVaultSecretRef" and rename to "ManagedClusterServicePrincipalProfile"
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/index.js
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/models/managedClusterServicePrincipalProfile.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
Labels: RestPRMerged, in progress

#2615 [AutoPR] cognitiveservices/resource-manager
  lib/services/cognitiveServicesManagement/README.md
  lib/services/cognitiveServicesManagement/lib/cognitiveServicesManagementClient.d.ts
  lib/services/cognitiveServicesManagement/lib/cognitiveServicesManagementClient.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/index.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSku.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictionInfo.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictions.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkusResult.js
  lib/services/cognitiveServicesManagement/lib/operations/index.d.ts
  lib/services/cognitiveServicesManagement/lib/operations/index.js
  lib/services/cognitiveServicesManagement/lib/operations/resourceSkus.js
  lib/services/cognitiveServicesManagement/package-lock.json
  lib/services/cognitiveServicesManagement/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#3251 [AutoPR network/resource-manager] add package-2018-06 to Go SDK
  lib/services/networkManagement2/lib/models/applicationGatewayAvailableSslOptions.js
  lib/services/networkManagement2/lib/models/applicationGatewaySslPolicy.js
  lib/services/networkManagement2/lib/models/applicationGatewaySslPredefinedPolicy.js
  lib/services/networkManagement2/lib/models/azureFirewallNetworkRule.js
  lib/services/networkManagement2/lib/models/packetCaptureQueryStatusResult.js
  lib/services/networkManagement2/lib/models/vpnClientConfiguration.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/package.json
Labels: RestPRMerged, in progress

#3226 [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision: bug fixes for /describe and /analyze [breaking]
  lib/services/computerVision/lib/computerVisionClient.d.ts
  lib/services/computerVision/lib/computerVisionClient.js
Labels: RestPRMerged, in progress

#2848 [AutoPR] containerservices/resource-manager
  lib/services/containerservicesManagement/LICENSE.txt
  lib/services/containerservicesManagement/README.md
  lib/services/containerservicesManagement/lib/containerServiceClient.d.ts
  lib/services/containerservicesManagement/lib/containerServiceClient.js
  lib/services/containerservicesManagement/lib/models/computeOperationListResult.js
  lib/services/containerservicesManagement/lib/models/computeOperationValue.js
  lib/services/containerservicesManagement/lib/models/credentialResult.js
  lib/services/containerservicesManagement/lib/models/credentialResults.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/index.js
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/managedClusterServicePrincipalProfile.js
  lib/services/containerservicesManagement/lib/models/tagsObject.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/package-lock.json
  lib/services/containerservicesManagement/package.json
Labels: Planned-Sprint-121, ServicePR, Started-Sprint-121, in progress

#2698 [AutoPR] eventgrid/resource-manager
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/package-lock.json
  lib/services/eventgridManagement/package.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#2733 [AutoPR] cognitiveservices/data-plane/SpellCheck
  lib/services/spellCheck/LICENSE.txt
  lib/services/spellCheck/package-lock.json
  lib/services/spellCheck/package.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#3270 [AutoPR containerinstance/resource-manager] Add Contaienr Group Stop and Restart API
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package.json
Labels: RestPRMerged, in progress
