Repository Azure/azure-sdk-for-node, pull requests merged in 2018-05, with the labels that each got.

#2815 [AutoPR automation/resource-manager] Added x-mx-odata properties for some resources
  lib/services/automationManagement/lib/models/hybridRunbookWorker.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/jobCollectionItem.js
  lib/services/automationManagement/lib/models/linuxProperties.js
  lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
  lib/services/automationManagement/lib/models/updateConfiguration.js
  lib/services/automationManagement/lib/models/webhook.js
  lib/services/automationManagement/lib/models/windowsProperties.js
  lib/services/automationManagement/lib/operations/hybridRunbookWorkerGroupOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/jobScheduleOperations.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Labels: RestPRMerged, in progress

#2820 [AutoPR eventgrid/resource-manager] Reverting back x-ms-azure-resource from TrackedResource definition as it is already part of the base class Resource.
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/topic.js
  lib/services/eventgridManagement/lib/models/trackedResource.js
Labels: RestPRMerged, in progress

#2817 [AutoPR compute/resource-manager] fixed formatting
  lib/services/computeManagement2/lib/models/dataDisk.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#2821 [AutoPR eventgrid/resource-manager] Added tag corresponding to new preview API version 2018-05-01-preview
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/deadLetterDestination.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/hybridConnectionEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/models/inputSchemaMapping.js
  lib/services/eventgridManagement/lib/models/jsonField.js
  lib/services/eventgridManagement/lib/models/jsonFieldWithDefault.js
  lib/services/eventgridManagement/lib/models/jsonInputSchemaMapping.js
  lib/services/eventgridManagement/lib/models/retryPolicy.js
  lib/services/eventgridManagement/lib/models/storageBlobDeadLetterDestination.js
  lib/services/eventgridManagement/lib/models/storageQueueEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/topic.js
  lib/services/eventgridManagement/lib/models/topicRegenerateKeyRequest.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/topics.js
Labels: RestPRMerged, in progress

#2826 [AutoPR cognitiveservices/data-plane/WebSearch] Plug WebSearch for the automation
  lib/services/webSearch/LICENSE.txt
  lib/services/webSearch/package.json
Labels: RestPRMerged

#2818 [AutoPR cognitiveservices/data-plane/TextAnalytics] Update CognitiveServices/Text-Analytics Swagger with new /entities endpoint
  lib/services/textAnalytics/LICENSE.txt
  lib/services/textAnalytics/lib/models/entitiesBatchResult.js
  lib/services/textAnalytics/lib/models/entitiesBatchResultItem.js
  lib/services/textAnalytics/lib/models/entityRecord.js
  lib/services/textAnalytics/lib/models/index.d.ts
  lib/services/textAnalytics/lib/models/index.js
  lib/services/textAnalytics/lib/models/matchRecord.js
  lib/services/textAnalytics/lib/textAnalyticsAPIClient.d.ts
  lib/services/textAnalytics/lib/textAnalyticsAPIClient.js
  lib/services/textAnalytics/package.json
Labels: RestPRMerged, in progress

#2824 [AutoPR monitor/resource-manager] Minor Updates - description text
  lib/services/monitorManagement/lib/models/actionGroupResource.js
  lib/services/monitorManagement/lib/models/alertingAction.js
  lib/services/monitorManagement/lib/models/azNsActionGroup.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/logSearchRuleResource.js
  lib/services/monitorManagement/lib/models/source.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/lib/operations/scheduledQueryRules.js
Labels: RestPRMerged, in progress

#2837 [AutoPR recoveryservicessiterecovery/resource-manager] BugFixes: Representing enums as string and moving away from complex odata fields.
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2AContainerMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2APolicyCreationInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2AProtectionContainerMappingDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2ARecoveryPointDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2AReplicationDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2AUpdateContainerMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/createRecoveryPlanInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/disableProtectionInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/healthErrorSummary.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/hyperVVirtualMachineDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/identityInformation.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageAgentVersionDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageAzureV2PolicyInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageFailoverProviderInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMagePolicyInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/index.d.ts
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/index.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/jobQueryParameter.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/protectableItemQueryParameter.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/protectedItemsQueryParameter.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/rcmAzureMigrationPolicyDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanA2AFailoverInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanAction.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanAutomationRunbookActionDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanGroup.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanHyperVReplicaAzureFailbackInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanHyperVReplicaAzureFailoverInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanInMageAzureV2FailoverInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanInMageFailoverInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanPlannedFailoverInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanScriptActionDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanTestFailoverInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/recoveryPlanUnplannedFailoverInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/updateReplicationProtectedItemInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/versionDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vmmVirtualMachineDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/index.d.ts
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/replicationJobs.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/replicationProtectableItems.js
Labels: RestPRMerged, in progress

#2833 [AutoPR automation/resource-manager] Edit property names for SourceControlSyncJob
  lib/services/automationManagement/lib/models/dscConfiguration.js
  lib/services/automationManagement/lib/models/dscConfigurationListResult.js
  lib/services/automationManagement/lib/models/dscNode.js
  lib/services/automationManagement/lib/models/dscNodeConfigurationListResult.js
  lib/services/automationManagement/lib/models/dscNodeListResult.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/linuxProperties.js
  lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
  lib/services/automationManagement/lib/models/sourceControlSyncJob.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
  lib/services/automationManagement/lib/models/updateConfiguration.js
  lib/services/automationManagement/lib/models/windowsProperties.js
  lib/services/automationManagement/lib/operations/dscConfigurationOperations.js
  lib/services/automationManagement/lib/operations/dscNodeConfigurationOperations.js
  lib/services/automationManagement/lib/operations/dscNodeOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Labels: RestPRMerged, in progress

#2840 Regenerate CognitiveServices VisualSearch data-plane SDK
  lib/services/visualSearch/lib/models/filters.js
  lib/services/visualSearch/lib/models/imageInfo.js
  lib/services/visualSearch/lib/models/index.d.ts
  lib/services/visualSearch/lib/models/index.js
  lib/services/visualSearch/lib/models/knowledgeRequest.js
  lib/services/visualSearch/lib/models/visualSearchRequest.js
  lib/services/visualSearch/package-lock.json
  lib/services/visualSearch/package.json
  package-lock.json
Labels: in progress

#2843 Generate SignalR management SDK
  lib/services/signalrManagement/LICENSE.txt
  lib/services/signalrManagement/README.md
  lib/services/signalrManagement/lib/models/index.d.ts
  lib/services/signalrManagement/lib/models/index.js
  lib/services/signalrManagement/lib/models/metricSpecification.js
  lib/services/signalrManagement/lib/models/nameAvailability.js
  lib/services/signalrManagement/lib/models/nameAvailabilityParameters.js
  lib/services/signalrManagement/lib/models/operation.js
  lib/services/signalrManagement/lib/models/operationDisplay.js
  lib/services/signalrManagement/lib/models/operationList.js
  lib/services/signalrManagement/lib/models/operationProperties.js
  lib/services/signalrManagement/lib/models/regenerateKeyParameters.js
  lib/services/signalrManagement/lib/models/resource.js
  lib/services/signalrManagement/lib/models/resourceSku.js
  lib/services/signalrManagement/lib/models/serviceSpecification.js
  lib/services/signalrManagement/lib/models/signalRCreateOrUpdateProperties.js
  lib/services/signalrManagement/lib/models/signalRCreateParameters.js
  lib/services/signalrManagement/lib/models/signalRKeys.js
  lib/services/signalrManagement/lib/models/signalRResource.js
  lib/services/signalrManagement/lib/models/signalRResourceList.js
  lib/services/signalrManagement/lib/models/signalRUpdateParameters.js
  lib/services/signalrManagement/lib/models/trackedResource.js
  lib/services/signalrManagement/lib/operations/index.d.ts
  lib/services/signalrManagement/lib/operations/index.js
  lib/services/signalrManagement/lib/operations/operations.js
  lib/services/signalrManagement/lib/operations/signalR.js
  lib/services/signalrManagement/lib/signalRManagementClient.d.ts
  lib/services/signalrManagement/lib/signalRManagementClient.js
  lib/services/signalrManagement/package-lock.json
  lib/services/signalrManagement/package.json
Labels: in progress

#2819 [AutoPR compute/resource-manager] added autoOSUpgradePolicy to UpgradePolicy
  lib/services/computeManagement2/lib/models/autoOSUpgradePolicy.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/upgradePolicy.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/package.json
Labels: RestPRMerged, in progress

#2847 [AutoPR containerservices/resource-manager] [AKS] remove unsupported VM types
  lib/services/containerservicesManagement/LICENSE.txt
  lib/services/containerservicesManagement/README.md
  lib/services/containerservicesManagement/lib/models/containerService.js
  lib/services/containerservicesManagement/lib/models/containerServiceAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceMasterProfile.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/operations/containerServices.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/package.json
Labels: RestPRMerged

#2806 [AutoPR cosmos-db/resource-manager] Swagger changes to introduce REST APIs for offline and online region for the Cosmos DB account
  lib/services/cosmosdbManagement/lib/models/errorResponse.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/index.js
  lib/services/cosmosdbManagement/lib/models/regionForOnlineOffline.js
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
  lib/services/cosmosdbManagement/package.json
Labels: RestPRMerged, in progress

#2851 add tests + test recordings for vault creation w network acls
  runtime/ms-rest/package-lock.json
  test/recordings/keyvaultmanagement-tests/Key_Vault_Management_Key_Vaults_should_create_a_key_vault_with_vnet_rule_set_correctly.nock.js
  test/recordings/keyvaultmanagement-tests/suite.keyvaultmanagement-tests.nock.js
  test/services/keyVaultManagement/keyVaultManagement-tests.js
  test/testlistarm.txt
Labels: in progress

#2858 [AutoPR batchai/resource-manager] BatchAI. Several fixes
  lib/services/batchaiManagement/lib/models/index.d.ts
  lib/services/batchaiManagement/lib/models/jobCreateParameters.js
  lib/services/batchaiManagement/lib/operations/experiments.js
  lib/services/batchaiManagement/lib/operations/index.d.ts
  lib/services/batchaiManagement/lib/operations/jobs.js
  lib/services/batchaiManagement/package.json
Labels: RestPRMerged

#2861 generating from 2018-05-01-preview version of the swagger spec.
  lib/services/eventgridManagement/LICENSE.txt
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/deadLetterDestination.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/hybridConnectionEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/models/inputSchemaMapping.js
  lib/services/eventgridManagement/lib/models/jsonField.js
  lib/services/eventgridManagement/lib/models/jsonFieldWithDefault.js
  lib/services/eventgridManagement/lib/models/jsonInputSchemaMapping.js
  lib/services/eventgridManagement/lib/models/retryPolicy.js
  lib/services/eventgridManagement/lib/models/storageBlobDeadLetterDestination.js
  lib/services/eventgridManagement/lib/models/storageQueueEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/topic.js
  lib/services/eventgridManagement/lib/models/topicRegenerateKeyRequest.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/topics.js
  lib/services/eventgridManagement/package-lock.json
  lib/services/eventgridManagement/package.json
Labels: in progress

#2862 [AutoPR eventgrid/data-plane] EventGrid Dataplane: Added schemas corresponding to SubscriptionValidationEvent/Response and SubscriptionDeletedEvent
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/serviceBusActiveMessagesAvailableWithNoListenersEventData.js
  lib/services/eventgrid/lib/models/serviceBusDeadletterMessagesAvailableWithNoListenersEventData.js
  lib/services/eventgrid/lib/models/subscriptionDeletedEventData.js
  lib/services/eventgrid/lib/models/subscriptionValidationEventData.js
  lib/services/eventgrid/lib/models/subscriptionValidationResponse.js
  lib/services/eventgrid/package.json
Labels: RestPRMerged

#2832 [AutoPR datafactory/resource-manager] [DataFactory] blob events trigger
  lib/services/datafactoryManagement/lib/models/blobEventsTrigger.js
  lib/services/datafactoryManagement/lib/models/db2LinkedService.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/mySqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/postgreSqlLinkedService.js
  lib/services/datafactoryManagement/lib/models/teradataLinkedService.js
  lib/services/datafactoryManagement/package.json
Labels: RestPRMerged, in progress

#2873 [AutoPR web/resource-manager] Update CommonDefinitions.json
  lib/services/websiteManagement2/package.json
Labels: RestPRMerged

#2880 [AutoPR eventgrid/data-plane] Adding Media Services Event Grid schema
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/mediaJobStateChangeEventData.js
Labels: RestPRMerged, in progress

#2884 [AutoPR monitor/resource-manager] Add "autoMitigate" to Metric Alert API spec for 2018-03-01
  lib/services/monitorManagement/lib/models/alertingAction.js
  lib/services/monitorManagement/lib/models/azNsActionGroup.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/logSearchRuleResource.js
  lib/services/monitorManagement/lib/models/metricAlertResource.js
  lib/services/monitorManagement/lib/models/metricAlertResourcePatch.js
  lib/services/monitorManagement/lib/models/source.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/lib/operations/metricAlerts.js
  lib/services/monitorManagement/lib/operations/scheduledQueryRules.js
  lib/services/monitorManagement/package.json
Labels: RestPRMerged

#2869 [AutoPR cognitiveservices/data-plane/CustomWebSearch] renaming custom search to custom web search
  lib/services/customSearch/LICENSE.txt
  lib/services/customSearch/lib/customSearchAPIClient.d.ts
  lib/services/customSearch/lib/customSearchAPIClient.js
  lib/services/customSearch/lib/operations/customInstance.js
  lib/services/customSearch/lib/operations/index.d.ts
  lib/services/customSearch/package.json
Labels: RestPRMerged, in progress

#2872 [AutoPR compute/resource-manager] Upgrade Compute API version and Fix the response of POST response
  lib/services/computeManagement2/lib/models/accessUri.js
  lib/services/computeManagement2/lib/models/dataDisk.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/logAnalyticsOperationResult.js
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/runCommandResult.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineCaptureResult.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/availabilitySets.js
  lib/services/computeManagement2/lib/operations/disks.js
  lib/services/computeManagement2/lib/operations/images.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/logAnalytics.js
  lib/services/computeManagement2/lib/operations/operations.js
  lib/services/computeManagement2/lib/operations/snapshots.js
  lib/services/computeManagement2/lib/operations/usageOperations.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensionImages.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachineImages.js
  lib/services/computeManagement2/lib/operations/virtualMachineRunCommands.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetRollingUpgrades.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachineSizes.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#2876 [AutoPR containerservices/resource-manager] [AKS] add POST endpoint for fetching accessProfiles
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
Labels: RestPRMerged

#2896 [AutoPR notificationhubs/resource-manager] Add suppressions for linting errors. Approved by Gaurav
  lib/services/notificationHubsManagement/LICENSE.txt
  lib/services/notificationHubsManagement/lib/models/checkAvailabilityResult.js
  lib/services/notificationHubsManagement/lib/models/errorResponse.js
  lib/services/notificationHubsManagement/lib/models/index.d.ts
  lib/services/notificationHubsManagement/lib/models/index.js
  lib/services/notificationHubsManagement/lib/models/namespaceCreateOrUpdateParameters.js
  lib/services/notificationHubsManagement/lib/models/namespaceResource.js
  lib/services/notificationHubsManagement/lib/models/notificationHubCreateOrUpdateParameters.js
  lib/services/notificationHubsManagement/lib/models/notificationHubResource.js
  lib/services/notificationHubsManagement/lib/models/operation.js
  lib/services/notificationHubsManagement/lib/models/operationDisplay.js
  lib/services/notificationHubsManagement/lib/models/operationListResult.js
  lib/services/notificationHubsManagement/lib/models/pnsCredentialsResource.js
  lib/services/notificationHubsManagement/lib/models/resource.js
  lib/services/notificationHubsManagement/lib/models/sharedAccessAuthorizationRuleCreateOrUpdateParameters.js
  lib/services/notificationHubsManagement/lib/models/sharedAccessAuthorizationRuleProperties.js
  lib/services/notificationHubsManagement/lib/models/sharedAccessAuthorizationRuleResource.js
  lib/services/notificationHubsManagement/lib/notificationHubsManagementClient.d.ts
  lib/services/notificationHubsManagement/lib/notificationHubsManagementClient.js
  lib/services/notificationHubsManagement/lib/operations/index.d.ts
  lib/services/notificationHubsManagement/lib/operations/index.js
  lib/services/notificationHubsManagement/lib/operations/namespaces.js
  lib/services/notificationHubsManagement/lib/operations/notificationHubs.js
  lib/services/notificationHubsManagement/lib/operations/operations.js
  lib/services/notificationHubsManagement/package.json
Labels: RestPRMerged

#2893 [AutoPR sql/resource-manager] Rename resource "ShortTermRetentionPolicy"->"BackupShortTermRetentionPolicy" to align with "BackupLongTermRetentionPolicy"
  lib/services/sqlManagement2/lib/models/backupShortTermRetentionPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/operations/backupShortTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged

#2900 [AutoPR applicationinsights/resource-manager] [AppInsights] Added webtests-by-component API to 2015-05-01
  lib/services/applicationinsights/lib/operations/index.d.ts
  lib/services/applicationinsights/lib/operations/webTests.js
  lib/services/applicationinsights/package.json
Labels: RestPRMerged, in progress

#2902 [AutoPR monitor/resource-manager] [Monitor] Deconflict "Action" name in MetricAlert
  lib/services/monitorManagement/lib/models/action.js
  lib/services/monitorManagement/lib/models/alertingAction.js
  lib/services/monitorManagement/lib/models/azNsActionGroup.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/index.js
  lib/services/monitorManagement/lib/models/logSearchRuleResource.js
  lib/services/monitorManagement/lib/models/metricAlertAction.js
  lib/services/monitorManagement/lib/models/metricAlertResource.js
  lib/services/monitorManagement/lib/models/metricAlertResourcePatch.js
  lib/services/monitorManagement/lib/models/source.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/lib/operations/scheduledQueryRules.js
Labels: RestPRMerged

#2908 [AutoPR sql/resource-manager] Use common Resource & Sku definitions in all Sql specs
  lib/services/sqlManagement2/lib/models/database.js
  lib/services/sqlManagement2/lib/models/databaseUpdate.js
  lib/services/sqlManagement2/lib/models/databaseVulnerabilityAssessment.js
  lib/services/sqlManagement2/lib/models/elasticPool.js
  lib/services/sqlManagement2/lib/models/elasticPoolPerformanceLevelCapability.js
  lib/services/sqlManagement2/lib/models/elasticPoolUpdate.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/jobAgent.js
  lib/services/sqlManagement2/lib/models/managedDatabase.js
  lib/services/sqlManagement2/lib/models/managedInstance.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/models/server.js
  lib/services/sqlManagement2/lib/models/serviceObjectiveCapability.js
  lib/services/sqlManagement2/lib/models/sku.js
  lib/services/sqlManagement2/lib/models/trackedResource.js
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessmentScans.js
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/lib/operations/databases.js
  lib/services/sqlManagement2/lib/operations/elasticPools.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/jobAgents.js
  lib/services/sqlManagement2/lib/operations/managedDatabases.js
  lib/services/sqlManagement2/lib/operations/managedInstances.js
  lib/services/sqlManagement2/lib/operations/servers.js
Labels: RestPRMerged

#2911 [AutoPR servermanagement/resource-manager] Fix Python conf of servermanager
  lib/services/servermanagement/LICENSE.txt
  lib/services/servermanagement/README.md
  lib/services/servermanagement/lib/serverManagement.d.ts
  lib/services/servermanagement/lib/serverManagement.js
  lib/services/servermanagement/package.json
Labels: RestPRMerged

#2913 [AutoPR operationalinsights/resource-manager] Plug SwaggerToSdk to LogAnalyticsMgmt
  lib/services/operationalInsightsManagement/package.json
Labels: RestPRMerged, in progress

#2915 [AutoPR storage/resource-manager] [Storage] Support Management policy on new api version 2018-03-01-preview
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/managementPoliciesRulesSetParameter.js
  lib/services/storageManagement2/lib/models/storageAccountManagementPolicies.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
Labels: RestPRMerged

#2916 [AutoPR keyvault/data-plane] RSA key size examples, ECC descriptions
  lib/services/keyvault/lib/keyVaultClient.d.ts
  lib/services/keyvault/lib/keyVaultClient.js
  lib/services/keyvault/lib/models/certificateBundle.js
  lib/services/keyvault/lib/models/certificateCreateParameters.js
  lib/services/keyvault/lib/models/certificateImportParameters.js
  lib/services/keyvault/lib/models/certificatePolicy.js
  lib/services/keyvault/lib/models/certificateUpdateParameters.js
  lib/services/keyvault/lib/models/index.d.ts
  lib/services/keyvault/lib/models/keyCreateParameters.js
  lib/services/keyvault/lib/models/keyProperties.js
  lib/services/keyvault/package.json
Labels: RestPRMerged

#2903 [AutoPR automation/resource-manager] Added GroupType property in HybridWorkerGroup
  lib/services/automationManagement/lib/models/hybridRunbookWorkerGroup.js
  lib/services/automationManagement/lib/models/index.d.ts
Labels: RestPRMerged

#2894 Regenerated EventGrid DataPlane SDK (based on latest Swagger) to include new event types.
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/mediaJobStateChangeEventData.js
  lib/services/eventgrid/lib/models/serviceBusActiveMessagesAvailableWithNoListenersEventData.js
  lib/services/eventgrid/lib/models/serviceBusDeadletterMessagesAvailableWithNoListenersEventData.js
  lib/services/eventgrid/lib/models/subscriptionDeletedEventData.js
  lib/services/eventgrid/lib/models/subscriptionValidationEventData.js
  lib/services/eventgrid/lib/models/subscriptionValidationResponse.js
  lib/services/eventgrid/package.json
Labels: in progress

#2920 Regenerate storage and update major version number
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/managementPoliciesRulesSetParameter.js
  lib/services/storageManagement2/lib/models/storageAccountManagementPolicies.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
  lib/services/storageManagement2/package-lock.json
  lib/services/storageManagement2/package.json
  test/recordings/datalakeAnalyticsManagement-tests/Data_Lake_Analytics_Clients_Account_Job_and_Catalog_Data_Lake_Analytics_Account_adding_and_removing_blob_storage_accounts_to_the_account_should_work.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_check_the_name_availability_for_a_storage_account_that_already_exists.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_check_the_name_availability_for_a_storage_account_that_does_not_exist.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_StorageV2.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_cool.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_encryption.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_correctly_with_https_only.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_create_an_account_with_vnet_rule_set_correctly.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_delete_the_specified_storage_account.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_get_properties_of_the_specified_storage_account.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_all_the_storage_account_keys.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_all_the_storage_accounts_in_the_resourcegroup.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_all_the_storage_accounts_in_the_subscription.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_the_skus_for_subscription.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_the_storage_account_SAS.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_list_the_storage_service_SAS.nock.js
  test/recordings/storagemanagementservice-tests/Storage_Management_storage_accounts_should_regenerate_storage_account_keys.nock.js
Labels: in progress

#2922 [AutoPR network/resource-manager] Fix foir Azure Networking swagger
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/lib/operations/applicationGateways.js
  lib/services/networkManagement2/lib/operations/applicationSecurityGroups.js
  lib/services/networkManagement2/lib/operations/availableEndpointServices.js
  lib/services/networkManagement2/lib/operations/bgpServiceCommunities.js
  lib/services/networkManagement2/lib/operations/connectionMonitors.js
  lib/services/networkManagement2/lib/operations/ddosProtectionPlans.js
  lib/services/networkManagement2/lib/operations/defaultSecurityRules.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuitAuthorizations.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuitConnections.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuitPeerings.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuits.js
  lib/services/networkManagement2/lib/operations/expressRouteCrossConnectionPeerings.js
  lib/services/networkManagement2/lib/operations/expressRouteCrossConnections.js
  lib/services/networkManagement2/lib/operations/expressRouteServiceProviders.js
  lib/services/networkManagement2/lib/operations/inboundNatRules.js
  lib/services/networkManagement2/lib/operations/loadBalancerBackendAddressPools.js
  lib/services/networkManagement2/lib/operations/loadBalancerFrontendIPConfigurations.js
  lib/services/networkManagement2/lib/operations/loadBalancerLoadBalancingRules.js
  lib/services/networkManagement2/lib/operations/loadBalancerNetworkInterfaces.js
  lib/services/networkManagement2/lib/operations/loadBalancerProbes.js
  lib/services/networkManagement2/lib/operations/loadBalancers.js
  lib/services/networkManagement2/lib/operations/localNetworkGateways.js
  lib/services/networkManagement2/lib/operations/networkInterfaceIPConfigurations.js
  lib/services/networkManagement2/lib/operations/networkInterfaceLoadBalancers.js
  lib/services/networkManagement2/lib/operations/networkInterfaces.js
  lib/services/networkManagement2/lib/operations/networkSecurityGroups.js
  lib/services/networkManagement2/lib/operations/networkWatchers.js
  lib/services/networkManagement2/lib/operations/operations.js
  lib/services/networkManagement2/lib/operations/packetCaptures.js
  lib/services/networkManagement2/lib/operations/publicIPAddresses.js
  lib/services/networkManagement2/lib/operations/routeFilterRules.js
  lib/services/networkManagement2/lib/operations/routeFilters.js
  lib/services/networkManagement2/lib/operations/routeTables.js
  lib/services/networkManagement2/lib/operations/routes.js
  lib/services/networkManagement2/lib/operations/securityRules.js
  lib/services/networkManagement2/lib/operations/subnets.js
  lib/services/networkManagement2/lib/operations/usages.js
  lib/services/networkManagement2/lib/operations/virtualNetworkGatewayConnections.js
  lib/services/networkManagement2/lib/operations/virtualNetworkGateways.js
  lib/services/networkManagement2/lib/operations/virtualNetworkPeerings.js
  lib/services/networkManagement2/lib/operations/virtualNetworks.js
Labels: RestPRMerged

#2889 [AutoPR automation/resource-manager] Refactoring Job Definitions
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/job.js
  lib/services/automationManagement/lib/models/jobCreateParameters.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/jobOperations.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationMachineRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurationRuns.js
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Labels: RestPRMerged

#2928 [AutoPR network/resource-manager] reverted methods removal
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/virtualNetworkGateways.js
Labels: RestPRMerged, in progress

#2925 [AutoPR compute/resource-manager] [Disk swagger] Removing resourceUpdate, adding contents to diskupdate and snapshotupdate
  lib/services/computeManagement2/lib/models/diskUpdate.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/snapshotUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/snapshots.js
Labels: RestPRMerged

#2930 [AutoPR iotcentral/resource-manager] Add specs for Microsoft.IoTCentral RP
  lib/services/iotcentral/LICENSE.txt
  lib/services/iotcentral/README.md
  lib/services/iotcentral/lib/iotCentralClient.d.ts
  lib/services/iotcentral/lib/iotCentralClient.js
  lib/services/iotcentral/lib/models/app.js
  lib/services/iotcentral/lib/models/appListResult.js
  lib/services/iotcentral/lib/models/appNameAvailabilityInfo.js
  lib/services/iotcentral/lib/models/appPatch.js
  lib/services/iotcentral/lib/models/appSkuInfo.js
  lib/services/iotcentral/lib/models/errorDetails.js
  lib/services/iotcentral/lib/models/index.d.ts
  lib/services/iotcentral/lib/models/index.js
  lib/services/iotcentral/lib/models/operation.js
  lib/services/iotcentral/lib/models/operationDisplay.js
  lib/services/iotcentral/lib/models/operationInputs.js
  lib/services/iotcentral/lib/models/operationListResult.js
  lib/services/iotcentral/lib/models/resource.js
  lib/services/iotcentral/lib/operations/apps.js
  lib/services/iotcentral/lib/operations/index.d.ts
  lib/services/iotcentral/lib/operations/index.js
  lib/services/iotcentral/lib/operations/operations.js
  lib/services/iotcentral/package.json
Labels: RestPRMerged
