Repository Azure/azure-sdk-for-node, pull requests merged in 2018-12, with the labels that each got.

#4236 Remove component governance
  .azure-pipelines/client.yml
Labels: in progress

#4235 Add status badge for client libraries
  README.md
Labels: in progress

#4239 [AutoPR compute/resource-manager] updated Reimage API documentation in compute json for ephemeral os disks
  lib/services/computeManagement2/lib/models/diffDiskSettings.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineReimageParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged

#4259 [AutoPR datamigration/resource-manager] typo: Microsoft.DataMigration
  lib/services/datamigrationManagement/lib/models/connectToSourceSqlServerTaskOutputAgentJobLevel.js
  lib/services/datamigrationManagement/lib/models/connectToSourceSqlServerTaskOutputLoginLevel.js
  lib/services/datamigrationManagement/lib/models/index.d.ts
  lib/services/datamigrationManagement/lib/models/projectFile.js
  lib/services/datamigrationManagement/lib/models/projectFileProperties.js
  lib/services/datamigrationManagement/lib/models/resourceSkuCapabilities.js
  lib/services/datamigrationManagement/lib/models/selectedCertificateInput.js
  lib/services/datamigrationManagement/lib/operations/files.js
  lib/services/datamigrationManagement/lib/operations/index.d.ts
  lib/services/datamigrationManagement/lib/operations/tasks.js
Labels: RestPRMerged, in progress

#4256 [AutoPR databox/resource-manager] typo: Microsoft.DataBox
  lib/services/databoxManagement/lib/models/dataBoxHeavyAccountCopyLogDetails.js
  lib/services/databoxManagement/lib/models/dataBoxHeavyJobDetails.js
  lib/services/databoxManagement/lib/models/dataBoxHeavyJobSecrets.js
  lib/services/databoxManagement/lib/models/dataBoxHeavySecret.js
  lib/services/databoxManagement/lib/models/dataBoxJobDetails.js
  lib/services/databoxManagement/lib/models/databoxJobSecrets.js
  lib/services/databoxManagement/lib/models/index.d.ts
  lib/services/databoxManagement/lib/models/jobDetails.js
  lib/services/databoxManagement/lib/models/jobResource.js
  lib/services/databoxManagement/lib/operations/index.d.ts
  lib/services/databoxManagement/lib/operations/jobs.js
Labels: RestPRMerged, in progress

#4250 [AutoPR compute/resource-manager] typo: Microsoft.ContainerService
  lib/services/computeManagement2/lib/models/containerService.js
  lib/services/computeManagement2/lib/models/containerServiceAgentPoolProfile.js
  lib/services/computeManagement2/lib/models/containerServiceMasterProfile.js
  lib/services/computeManagement2/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4242 [AutoPR cognitiveservices/data-plane/ContentModerator] typo: ContentModerator
  lib/services/cognitiveServicesContentModerator/LICENSE.txt
  lib/services/cognitiveServicesContentModerator/lib/models/evaluate.js
  lib/services/cognitiveServicesContentModerator/lib/models/index.d.ts
  lib/services/cognitiveServicesContentModerator/package.json
Labels: RestPRMerged, in progress

#4290 [AutoPR operationalinsights/resource-manager] typo: operationalinsights/resource-manager/Microsoft.OperationalInsights
  lib/services/operationalInsightsManagement/README.md
  lib/services/operationalInsightsManagement/lib/models/dataSource.js
  lib/services/operationalInsightsManagement/lib/models/dataSourceFilter.js
  lib/services/operationalInsightsManagement/lib/models/dataSourceListResult.js
  lib/services/operationalInsightsManagement/lib/models/index.d.ts
  lib/services/operationalInsightsManagement/lib/models/intelligencePack.js
  lib/services/operationalInsightsManagement/lib/models/linkedService.js
  lib/services/operationalInsightsManagement/lib/models/managementGroup.js
  lib/services/operationalInsightsManagement/lib/models/metricName.js
  lib/services/operationalInsightsManagement/lib/models/operation.js
  lib/services/operationalInsightsManagement/lib/models/operationDisplay.js
  lib/services/operationalInsightsManagement/lib/models/operationListResult.js
  lib/services/operationalInsightsManagement/lib/models/proxyResource.js
  lib/services/operationalInsightsManagement/lib/models/resource.js
  lib/services/operationalInsightsManagement/lib/models/sharedKeys.js
  lib/services/operationalInsightsManagement/lib/models/sku.js
  lib/services/operationalInsightsManagement/lib/models/usageMetric.js
  lib/services/operationalInsightsManagement/lib/models/workspace.js
  lib/services/operationalInsightsManagement/lib/models/workspaceListManagementGroupsResult.js
  lib/services/operationalInsightsManagement/package.json
Labels: RestPRMerged, in progress

#4278 [AutoPR marketplaceordering/resource-manager] typo: marketplaceordering/resource-manager/Microsoft.MarketplaceOrdering
  lib/services/marketplaceorderingManagement/LICENSE.txt
  lib/services/marketplaceorderingManagement/README.md
  lib/services/marketplaceorderingManagement/lib/marketplaceOrderingAgreements.d.ts
  lib/services/marketplaceorderingManagement/lib/marketplaceOrderingAgreements.js
  lib/services/marketplaceorderingManagement/lib/models/agreementTerms.js
  lib/services/marketplaceorderingManagement/lib/models/errorResponse.js
  lib/services/marketplaceorderingManagement/lib/models/errorResponseError.js
  lib/services/marketplaceorderingManagement/lib/models/index.d.ts
  lib/services/marketplaceorderingManagement/lib/models/operation.js
  lib/services/marketplaceorderingManagement/lib/models/operationDisplay.js
  lib/services/marketplaceorderingManagement/lib/models/operationListResult.js
  lib/services/marketplaceorderingManagement/lib/models/resource.js
  lib/services/marketplaceorderingManagement/package.json
Labels: RestPRMerged, in progress

#4272 [AutoPR keyvault/resource-manager] typo: resource-manager/Microsoft.KeyVault
  lib/services/keyVaultManagement/LICENSE.txt
  lib/services/keyVaultManagement/lib/models/accessPolicyEntry.js
  lib/services/keyVaultManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/keyVaultManagement/lib/models/deletedVault.js
  lib/services/keyVaultManagement/lib/models/deletedVaultListResult.js
  lib/services/keyVaultManagement/lib/models/deletedVaultProperties.js
  lib/services/keyVaultManagement/lib/models/iPRule.js
  lib/services/keyVaultManagement/lib/models/index.d.ts
  lib/services/keyVaultManagement/lib/models/logSpecification.js
  lib/services/keyVaultManagement/lib/models/networkRuleSet.js
  lib/services/keyVaultManagement/lib/models/operation.js
  lib/services/keyVaultManagement/lib/models/operationDisplay.js
  lib/services/keyVaultManagement/lib/models/operationListResult.js
  lib/services/keyVaultManagement/lib/models/permissions.js
  lib/services/keyVaultManagement/lib/models/resource.js
  lib/services/keyVaultManagement/lib/models/resourceListResult.js
  lib/services/keyVaultManagement/lib/models/serviceSpecification.js
  lib/services/keyVaultManagement/lib/models/sku.js
  lib/services/keyVaultManagement/lib/models/vault.js
  lib/services/keyVaultManagement/lib/models/vaultAccessPolicyParameters.js
  lib/services/keyVaultManagement/lib/models/vaultAccessPolicyProperties.js
  lib/services/keyVaultManagement/lib/models/vaultCheckNameAvailabilityParameters.js
  lib/services/keyVaultManagement/lib/models/vaultCreateOrUpdateParameters.js
  lib/services/keyVaultManagement/lib/models/vaultListResult.js
  lib/services/keyVaultManagement/lib/models/vaultPatchParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchProperties.js
  lib/services/keyVaultManagement/lib/models/vaultProperties.js
  lib/services/keyVaultManagement/lib/models/virtualNetworkRule.js
  lib/services/keyVaultManagement/package.json
Labels: RestPRMerged

#4267 [AutoPR graphrbac/data-plane] typo: graphrbac
  lib/services/graphManagement/lib/models/index.d.ts
  lib/services/graphManagement/lib/models/requiredResourceAccess.js
  lib/services/graphManagement/lib/operations/index.d.ts
  lib/services/graphManagement/lib/operations/oAuth2.js
Labels: RestPRMerged, in progress

#4255 [AutoPR cosmos-db/resource-manager] typo: Microsoft.DocumentDB
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4296 [AutoPR powerbiembedded/resource-manager] typo: powerbiembedded/resource-manager/Microsoft.PowerBI
  lib/services/powerbiembedded/LICENSE.txt
  lib/services/powerbiembedded/lib/models/checkNameRequest.js
  lib/services/powerbiembedded/lib/models/checkNameResponse.js
  lib/services/powerbiembedded/lib/models/createWorkspaceCollectionRequest.js
  lib/services/powerbiembedded/lib/models/display.js
  lib/services/powerbiembedded/lib/models/errorDetail.js
  lib/services/powerbiembedded/lib/models/errorModel.js
  lib/services/powerbiembedded/lib/models/index.d.ts
  lib/services/powerbiembedded/lib/models/migrateWorkspaceCollectionRequest.js
  lib/services/powerbiembedded/lib/models/operation.js
  lib/services/powerbiembedded/lib/models/operationList.js
  lib/services/powerbiembedded/lib/models/updateWorkspaceCollectionRequest.js
  lib/services/powerbiembedded/lib/models/workspace.js
  lib/services/powerbiembedded/lib/models/workspaceCollection.js
  lib/services/powerbiembedded/lib/models/workspaceCollectionAccessKey.js
  lib/services/powerbiembedded/lib/models/workspaceCollectionAccessKeys.js
  lib/services/powerbiembedded/lib/powerBIEmbeddedManagementClient.d.ts
  lib/services/powerbiembedded/lib/powerBIEmbeddedManagementClient.js
  lib/services/powerbiembedded/package.json
Labels: RestPRMerged, in progress

#4293 [AutoPR policyinsights/resource-manager] typo: policyinsights/resource-manager/Microsoft.PolicyInsights
  lib/services/policyinsightsManagement/lib/models/index.d.ts
  lib/services/policyinsightsManagement/lib/models/remediation.js
  lib/services/policyinsightsManagement/lib/models/remediationDeploymentSummary.js
  lib/services/policyinsightsManagement/lib/operations/index.d.ts
  lib/services/policyinsightsManagement/lib/operations/remediations.js
Labels: RestPRMerged, in progress

#4262 [AutoPR devtestlabs/resource-manager] typo: Microsoft.DevTestLab
  lib/services/devTestLabs/lib/models/attachNewDataDiskOptions.js
  lib/services/devTestLabs/lib/models/attachNewDataDiskOptionsFragment.js
  lib/services/devTestLabs/lib/models/dataDiskProperties.js
  lib/services/devTestLabs/lib/models/dataDiskPropertiesFragment.js
  lib/services/devTestLabs/lib/models/disk.js
  lib/services/devTestLabs/lib/models/diskFragment.js
  lib/services/devTestLabs/lib/models/index.d.ts
  lib/services/devTestLabs/lib/operations/disks.js
  lib/services/devTestLabs/lib/operations/index.d.ts
  lib/services/devTestLabs/lib/operations/notificationChannels.js
  lib/services/devTestLabs/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#4257 [AutoPR datacatalog/resource-manager] typo: Microsoft.DataCatalog
  lib/services/datacatalogManagement/LICENSE.txt
  lib/services/datacatalogManagement/README.md
  lib/services/datacatalogManagement/lib/dataCatalogRestClient.d.ts
  lib/services/datacatalogManagement/lib/dataCatalogRestClient.js
  lib/services/datacatalogManagement/lib/models/aDCCatalog.js
  lib/services/datacatalogManagement/lib/models/aDCCatalogsListResult.js
  lib/services/datacatalogManagement/lib/models/index.d.ts
  lib/services/datacatalogManagement/lib/models/operationDisplayInfo.js
  lib/services/datacatalogManagement/lib/models/operationEntity.js
  lib/services/datacatalogManagement/lib/models/operationEntityListResult.js
  lib/services/datacatalogManagement/lib/models/principals.js
  lib/services/datacatalogManagement/lib/models/resource.js
  lib/services/datacatalogManagement/package.json
Labels: RestPRMerged, in progress

#4251 [AutoPR consumption/resource-manager] typo: Microsoft.Consumption
  lib/services/consumptionManagement/lib/models/budget.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/proxyResource.js
  lib/services/consumptionManagement/lib/models/reservationDetail.js
  lib/services/consumptionManagement/lib/models/reservationRecommendation.js
  lib/services/consumptionManagement/lib/models/reservationSummary.js
  lib/services/consumptionManagement/lib/operations/budgets.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/marketplaces.js
  lib/services/consumptionManagement/lib/operations/reservationRecommendations.js
Labels: RestPRMerged, in progress

#4243 [AutoPR cognitiveservices/data-plane/EntitySearch] typo: cognitiveservices/data-plane/EntitySearch
  lib/services/entitySearch/LICENSE.txt
  lib/services/entitySearch/lib/entitySearchAPIClient.d.ts
  lib/services/entitySearch/lib/entitySearchAPIClient.js
  lib/services/entitySearch/lib/models/airport.js
  lib/services/entitySearch/lib/models/contractualRulesAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesContractualRule.js
  lib/services/entitySearch/lib/models/contractualRulesLicenseAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesLinkAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesMediaAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesTextAttribution.js
  lib/services/entitySearch/lib/models/creativeWork.js
  lib/services/entitySearch/lib/models/entities.js
  lib/services/entitySearch/lib/models/entitiesEntityPresentationInfo.js
  lib/services/entitySearch/lib/models/errorModel.js
  lib/services/entitySearch/lib/models/errorResponse.js
  lib/services/entitySearch/lib/models/hotel.js
  lib/services/entitySearch/lib/models/identifiable.js
  lib/services/entitySearch/lib/models/imageObject.js
  lib/services/entitySearch/lib/models/index.d.ts
  lib/services/entitySearch/lib/models/localBusiness.js
  lib/services/entitySearch/lib/models/mediaObject.js
  lib/services/entitySearch/lib/models/movieTheater.js
  lib/services/entitySearch/lib/models/place.js
  lib/services/entitySearch/lib/models/places.js
  lib/services/entitySearch/lib/models/postalAddress.js
  lib/services/entitySearch/lib/models/queryContext.js
  lib/services/entitySearch/lib/models/response.js
  lib/services/entitySearch/lib/models/responseBase.js
  lib/services/entitySearch/lib/models/restaurant.js
  lib/services/entitySearch/lib/models/searchResponse.js
  lib/services/entitySearch/lib/models/searchResultsAnswer.js
  lib/services/entitySearch/lib/models/thing.js
  lib/services/entitySearch/lib/operations/entitiesOperations.js
  lib/services/entitySearch/package.json
Labels: RestPRMerged, in progress

#4228 [AutoPR billing/resource-manager] typo: Microsoft.Billing
  lib/services/billingManagement/lib/models/index.d.ts
  lib/services/billingManagement/lib/models/invoice.js
Labels: RestPRMerged, in progress

#4237 Parameterize source and test paths in pipeline
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
Labels: in progress

#4244 [AutoPR cognitiveservices/data-plane/ImageSearch] typo: cognitiveservices/data-plane/ImageSearch
  lib/services/imageSearch/LICENSE.txt
  lib/services/imageSearch/lib/imageSearchAPIClient.d.ts
  lib/services/imageSearch/lib/imageSearchAPIClient.js
  lib/services/imageSearch/lib/models/aggregateOffer.js
  lib/services/imageSearch/lib/models/aggregateRating.js
  lib/services/imageSearch/lib/models/creativeWork.js
  lib/services/imageSearch/lib/models/errorModel.js
  lib/services/imageSearch/lib/models/errorResponse.js
  lib/services/imageSearch/lib/models/identifiable.js
  lib/services/imageSearch/lib/models/imageGallery.js
  lib/services/imageSearch/lib/models/imageInsights.js
  lib/services/imageSearch/lib/models/imageInsightsImageCaption.js
  lib/services/imageSearch/lib/models/imageObject.js
  lib/services/imageSearch/lib/models/imageTagsModule.js
  lib/services/imageSearch/lib/models/images.js
  lib/services/imageSearch/lib/models/imagesImageMetadata.js
  lib/services/imageSearch/lib/models/imagesModule.js
  lib/services/imageSearch/lib/models/index.d.ts
  lib/services/imageSearch/lib/models/insightsTag.js
  lib/services/imageSearch/lib/models/mediaObject.js
  lib/services/imageSearch/lib/models/normalizedRectangle.js
  lib/services/imageSearch/lib/models/offer.js
  lib/services/imageSearch/lib/models/person.js
  lib/services/imageSearch/lib/models/pivotSuggestions.js
  lib/services/imageSearch/lib/models/propertiesItem.js
  lib/services/imageSearch/lib/models/query.js
  lib/services/imageSearch/lib/models/rating.js
  lib/services/imageSearch/lib/models/recipe.js
  lib/services/imageSearch/lib/models/recipesModule.js
  lib/services/imageSearch/lib/models/recognizedEntitiesModule.js
  lib/services/imageSearch/lib/models/recognizedEntity.js
  lib/services/imageSearch/lib/models/recognizedEntityGroup.js
  lib/services/imageSearch/lib/models/recognizedEntityRegion.js
  lib/services/imageSearch/lib/models/relatedCollectionsModule.js
  lib/services/imageSearch/lib/models/relatedSearchesModule.js
  lib/services/imageSearch/lib/models/response.js
  lib/services/imageSearch/lib/models/responseBase.js
  lib/services/imageSearch/lib/models/searchResultsAnswer.js
  lib/services/imageSearch/lib/models/thing.js
  lib/services/imageSearch/lib/models/trendingImages.js
  lib/services/imageSearch/lib/models/trendingImagesCategory.js
  lib/services/imageSearch/lib/models/trendingImagesTile.js
  lib/services/imageSearch/lib/operations/imagesOperations.js
  lib/services/imageSearch/package.json
Labels: RestPRMerged, in progress

#4270 [AutoPR iothub/resource-manager] typo: iothub/Microsoft.Devices
  lib/services/iothub/lib/models/index.d.ts
  lib/services/iothub/lib/models/iotHubDescription.js
  lib/services/iothub/lib/models/iotHubProperties.js
  lib/services/iothub/lib/models/routingStorageContainerProperties.js
  lib/services/iothub/lib/models/storageEndpointProperties.js
Labels: RestPRMerged, in progress

#4280 [AutoPR migrate/resource-manager] typo: migrate/resource-manager/Microsoft.Migrate
  lib/services/migrateManagement/LICENSE.txt
  lib/services/migrateManagement/README.md
  lib/services/migrateManagement/lib/azureMigrate.d.ts
  lib/services/migrateManagement/lib/azureMigrate.js
  lib/services/migrateManagement/lib/models/assessedDisk.js
  lib/services/migrateManagement/lib/models/assessedMachine.js
  lib/services/migrateManagement/lib/models/assessedNetworkAdapter.js
  lib/services/migrateManagement/lib/models/assessment.js
  lib/services/migrateManagement/lib/models/assessmentOptionsResultList.js
  lib/services/migrateManagement/lib/models/checkNameAvailabilityParameters.js
  lib/services/migrateManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/migrateManagement/lib/models/disk.js
  lib/services/migrateManagement/lib/models/downloadUrl.js
  lib/services/migrateManagement/lib/models/group.js
  lib/services/migrateManagement/lib/models/index.d.ts
  lib/services/migrateManagement/lib/models/index.js
  lib/services/migrateManagement/lib/models/machine.js
  lib/services/migrateManagement/lib/models/networkAdapter.js
  lib/services/migrateManagement/lib/models/operation.js
  lib/services/migrateManagement/lib/models/operationDisplay.js
  lib/services/migrateManagement/lib/models/project.js
  lib/services/migrateManagement/lib/models/projectKey.js
  lib/services/migrateManagement/lib/models/vmFamily.js
  lib/services/migrateManagement/lib/operations/assessedMachines.js
  lib/services/migrateManagement/lib/operations/assessmentOptions.js
  lib/services/migrateManagement/lib/operations/assessments.js
  lib/services/migrateManagement/lib/operations/groups.js
  lib/services/migrateManagement/lib/operations/index.d.ts
  lib/services/migrateManagement/lib/operations/index.js
  lib/services/migrateManagement/lib/operations/location.js
  lib/services/migrateManagement/lib/operations/machines.js
  lib/services/migrateManagement/lib/operations/projects.js
  lib/services/migrateManagement/package.json
Labels: RestPRMerged, in progress

#4263 [AutoPR dns/resource-manager] typo: dns/Microsoft.Network
  lib/services/dnsManagement/README.md
  lib/services/dnsManagement/lib/dnsManagementClient.d.ts
  lib/services/dnsManagement/lib/dnsManagementClient.js
  lib/services/dnsManagement/lib/models/aRecord.js
  lib/services/dnsManagement/lib/models/aaaaRecord.js
  lib/services/dnsManagement/lib/models/caaRecord.js
  lib/services/dnsManagement/lib/models/cnameRecord.js
  lib/services/dnsManagement/lib/models/dnsResourceReference.js
  lib/services/dnsManagement/lib/models/dnsResourceReferenceRequest.js
  lib/services/dnsManagement/lib/models/dnsResourceReferenceResult.js
  lib/services/dnsManagement/lib/models/index.d.ts
  lib/services/dnsManagement/lib/models/index.js
  lib/services/dnsManagement/lib/models/mxRecord.js
  lib/services/dnsManagement/lib/models/nsRecord.js
  lib/services/dnsManagement/lib/models/ptrRecord.js
  lib/services/dnsManagement/lib/models/recordSet.js
  lib/services/dnsManagement/lib/models/recordSetListResult.js
  lib/services/dnsManagement/lib/models/recordSetUpdateParameters.js
  lib/services/dnsManagement/lib/models/resource.js
  lib/services/dnsManagement/lib/models/soaRecord.js
  lib/services/dnsManagement/lib/models/srvRecord.js
  lib/services/dnsManagement/lib/models/subResource.js
  lib/services/dnsManagement/lib/models/txtRecord.js
  lib/services/dnsManagement/lib/models/zone.js
  lib/services/dnsManagement/lib/models/zoneListResult.js
  lib/services/dnsManagement/lib/models/zoneUpdate.js
  lib/services/dnsManagement/lib/operations/index.d.ts
  lib/services/dnsManagement/lib/operations/index.js
  lib/services/dnsManagement/lib/operations/recordSets.js
  lib/services/dnsManagement/lib/operations/zones.js
  lib/services/dnsManagement/package.json
Labels: RestPRMerged, in progress

#4292 [AutoPR operationsmanagement/resource-manager] typo: operationsmanagement/resource-manager/Microsoft.OperationsManagement
  lib/services/operationsManagement/README.md
  lib/services/operationsManagement/lib/models/armTemplateParameter.js
  lib/services/operationsManagement/lib/models/codeMessageError.js
  lib/services/operationsManagement/lib/models/codeMessageErrorError.js
  lib/services/operationsManagement/lib/models/index.d.ts
  lib/services/operationsManagement/lib/models/managementAssociation.js
  lib/services/operationsManagement/lib/models/managementAssociationProperties.js
  lib/services/operationsManagement/lib/models/managementAssociationPropertiesList.js
  lib/services/operationsManagement/lib/models/managementConfiguration.js
  lib/services/operationsManagement/lib/models/managementConfigurationProperties.js
  lib/services/operationsManagement/lib/models/managementConfigurationPropertiesList.js
  lib/services/operationsManagement/lib/models/operation.js
  lib/services/operationsManagement/lib/models/operationDisplay.js
  lib/services/operationsManagement/lib/models/solution.js
  lib/services/operationsManagement/lib/models/solutionPlan.js
  lib/services/operationsManagement/lib/models/solutionProperties.js
  lib/services/operationsManagement/lib/models/solutionPropertiesList.js
  lib/services/operationsManagement/lib/operations/index.d.ts
  lib/services/operationsManagement/lib/operations/managementAssociations.js
  lib/services/operationsManagement/package.json
Labels: RestPRMerged, in progress

#4245 [AutoPR cognitiveservices/data-plane/QnAMaker] typo: cognitiveservices/data-plane/QnAMaker
  lib/services/cognitiveServices/qnamaker/lib/models/index.d.ts
  lib/services/cognitiveServices/qnamaker/lib/models/updateMetadataDTO.js
Labels: RestPRMerged, in progress

#4252 [AutoPR containerinstance/resource-manager] typo: Microsoft.ConainterInstance
  lib/services/containerinstanceManagement/README.md
  lib/services/containerinstanceManagement/lib/models/azureFileVolume.js
  lib/services/containerinstanceManagement/lib/models/container.js
  lib/services/containerinstanceManagement/lib/models/containerExec.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequestTerminalSize.js
  lib/services/containerinstanceManagement/lib/models/containerExecResponse.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/containerGroupDiagnostics.js
  lib/services/containerinstanceManagement/lib/models/containerGroupIdentity.js
  lib/services/containerinstanceManagement/lib/models/containerGroupIdentityUserAssignedIdentitiesValue.js
  lib/services/containerinstanceManagement/lib/models/containerGroupListResult.js
  lib/services/containerinstanceManagement/lib/models/containerGroupNetworkProfile.js
  lib/services/containerinstanceManagement/lib/models/containerGroupPropertiesInstanceView.js
  lib/services/containerinstanceManagement/lib/models/containerHttpGet.js
  lib/services/containerinstanceManagement/lib/models/containerPort.js
  lib/services/containerinstanceManagement/lib/models/containerProbe.js
  lib/services/containerinstanceManagement/lib/models/containerPropertiesInstanceView.js
  lib/services/containerinstanceManagement/lib/models/containerState.js
  lib/services/containerinstanceManagement/lib/models/dnsConfiguration.js
  lib/services/containerinstanceManagement/lib/models/environmentVariable.js
  lib/services/containerinstanceManagement/lib/models/event.js
  lib/services/containerinstanceManagement/lib/models/gitRepoVolume.js
  lib/services/containerinstanceManagement/lib/models/gpuResource.js
  lib/services/containerinstanceManagement/lib/models/imageRegistryCredential.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/models/logAnalytics.js
  lib/services/containerinstanceManagement/lib/models/logs.js
  lib/services/containerinstanceManagement/lib/models/operation.js
  lib/services/containerinstanceManagement/lib/models/operationDisplay.js
  lib/services/containerinstanceManagement/lib/models/operationListResult.js
  lib/services/containerinstanceManagement/lib/models/port.js
  lib/services/containerinstanceManagement/lib/models/resource.js
  lib/services/containerinstanceManagement/lib/models/resourceLimits.js
  lib/services/containerinstanceManagement/lib/models/resourceRequests.js
  lib/services/containerinstanceManagement/lib/models/resourceRequirements.js
  lib/services/containerinstanceManagement/lib/models/usage.js
  lib/services/containerinstanceManagement/lib/models/usageListResult.js
  lib/services/containerinstanceManagement/lib/models/usageName.js
  lib/services/containerinstanceManagement/lib/models/volume.js
  lib/services/containerinstanceManagement/lib/models/volumeMount.js
Labels: RestPRMerged, in progress

#4264 [AutoPR eventgrid/data-plane] typo: Microsoft.Media
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/mediaLiveEventIncomingDataChunkDroppedEventData.js
  lib/services/eventgrid/lib/models/mediaLiveEventIngestHeartbeatEventData.js
Labels: RestPRMerged, in progress

#4277 [AutoPR mariadb/resource-manager] typo: mariadb/resource-manager/Microsoft.DBforMariaDB
  lib/services/mariadbManagement/README.md
  lib/services/mariadbManagement/lib/models/configuration.js
  lib/services/mariadbManagement/lib/models/database.js
  lib/services/mariadbManagement/lib/models/firewallRule.js
  lib/services/mariadbManagement/lib/models/index.d.ts
  lib/services/mariadbManagement/lib/models/logFile.js
  lib/services/mariadbManagement/lib/models/nameAvailability.js
  lib/services/mariadbManagement/lib/models/nameAvailabilityRequest.js
  lib/services/mariadbManagement/lib/models/operation.js
  lib/services/mariadbManagement/lib/models/operationDisplay.js
  lib/services/mariadbManagement/lib/models/operationListResult.js
  lib/services/mariadbManagement/lib/models/performanceTierProperties.js
  lib/services/mariadbManagement/lib/models/performanceTierServiceLevelObjectives.js
  lib/services/mariadbManagement/lib/models/proxyResource.js
  lib/services/mariadbManagement/lib/models/server.js
  lib/services/mariadbManagement/lib/models/serverForCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForDefaultCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForGeoRestore.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForRestore.js
  lib/services/mariadbManagement/lib/models/serverSecurityAlertPolicy.js
  lib/services/mariadbManagement/lib/models/serverUpdateParameters.js
  lib/services/mariadbManagement/lib/models/sku.js
  lib/services/mariadbManagement/lib/models/storageProfile.js
  lib/services/mariadbManagement/lib/models/trackedResource.js
  lib/services/mariadbManagement/lib/models/virtualNetworkRule.js
  lib/services/mariadbManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/mariadbManagement/package.json
Labels: RestPRMerged, in progress

#4248 [AutoPR cognitiveservices/resource-manager] typo: Microsoft.CognitiveServices
  lib/services/cognitiveServicesManagement/README.md
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResultList.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountEnumerateSkusResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountKeys.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountListResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js
  lib/services/cognitiveServicesManagement/lib/models/errorBody.js
  lib/services/cognitiveServicesManagement/lib/models/errorModel.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/metricName.js
  lib/services/cognitiveServicesManagement/lib/models/operationDisplayInfo.js
  lib/services/cognitiveServicesManagement/lib/models/operationEntity.js
  lib/services/cognitiveServicesManagement/lib/models/operationEntityListResult.js
  lib/services/cognitiveServicesManagement/lib/models/regenerateKeyParameters.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSku.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictionInfo.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkuRestrictions.js
  lib/services/cognitiveServicesManagement/lib/models/resourceSkusResult.js
  lib/services/cognitiveServicesManagement/lib/models/sku.js
  lib/services/cognitiveServicesManagement/lib/models/usage.js
  lib/services/cognitiveServicesManagement/lib/models/usagesResult.js
Labels: RestPRMerged, in progress

#4288 [AutoPR notificationhubs/resource-manager] typo: notificationhubs/resource-manager/Microsoft.NotificationHubs
  lib/services/notificationHubsManagement/lib/models/apnsCredential.js
  lib/services/notificationHubsManagement/lib/models/checkAvailabilityResult.js
  lib/services/notificationHubsManagement/lib/models/errorResponse.js
  lib/services/notificationHubsManagement/lib/models/index.d.ts
  lib/services/notificationHubsManagement/lib/models/mpnsCredential.js
  lib/services/notificationHubsManagement/lib/models/notificationHubCreateOrUpdateParameters.js
  lib/services/notificationHubsManagement/lib/models/notificationHubPatchParameters.js
  lib/services/notificationHubsManagement/lib/models/notificationHubResource.js
  lib/services/notificationHubsManagement/lib/models/pnsCredentialsResource.js
  lib/services/notificationHubsManagement/lib/operations/index.d.ts
  lib/services/notificationHubsManagement/lib/operations/namespaces.js
  lib/services/notificationHubsManagement/lib/operations/notificationHubs.js
  lib/services/notificationHubsManagement/package.json
Labels: RestPRMerged, in progress

#4258 [AutoPR datalake-store/data-plane] typo: Microsoft.DataLakeStore
  lib/services/datalake.Store/lib/filesystem/operations/fileSystem.js
  lib/services/datalake.Store/lib/filesystem/operations/index.d.ts
Labels: RestPRMerged, in progress

#4246 [AutoPR cognitiveservices/data-plane/NewsSearch] typo: cognitiveservices/data-plane/NewsSearch
  lib/services/newsSearch/LICENSE.txt
  lib/services/newsSearch/lib/models/answer.js
  lib/services/newsSearch/lib/models/article.js
  lib/services/newsSearch/lib/models/creativeWork.js
  lib/services/newsSearch/lib/models/errorModel.js
  lib/services/newsSearch/lib/models/errorResponse.js
  lib/services/newsSearch/lib/models/identifiable.js
  lib/services/newsSearch/lib/models/imageObject.js
  lib/services/newsSearch/lib/models/index.d.ts
  lib/services/newsSearch/lib/models/mediaObject.js
  lib/services/newsSearch/lib/models/news.js
  lib/services/newsSearch/lib/models/newsArticle.js
  lib/services/newsSearch/lib/models/newsTopic.js
  lib/services/newsSearch/lib/models/query.js
  lib/services/newsSearch/lib/models/response.js
  lib/services/newsSearch/lib/models/responseBase.js
  lib/services/newsSearch/lib/models/searchResultsAnswer.js
  lib/services/newsSearch/lib/models/thing.js
  lib/services/newsSearch/lib/models/trendingTopics.js
  lib/services/newsSearch/lib/models/videoObject.js
  lib/services/newsSearch/lib/newsSearchAPIClient.d.ts
  lib/services/newsSearch/lib/newsSearchAPIClient.js
  lib/services/newsSearch/lib/operations/index.d.ts
  lib/services/newsSearch/lib/operations/newsOperations.js
  lib/services/newsSearch/package.json
Labels: RestPRMerged, in progress

#4334 [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Resources
  lib/services/resourceManagement/lib/link/operations/index.d.ts
  lib/services/resourceManagement/lib/link/operations/resourceLinks.js
  lib/services/resourceManagement/lib/resource/models/deploymentExtended.js
  lib/services/resourceManagement/lib/resource/models/deploymentPropertiesExtended.js
  lib/services/resourceManagement/lib/resource/models/deploymentValidateResult.js
  lib/services/resourceManagement/lib/resource/models/index.d.ts
  lib/services/resourceManagement/lib/resource/models/parametersLink.js
Labels: RestPRMerged, in progress

#4336 [AutoPR search/resource-manager] typo: search/resource-manager/Microsoft.Search
  lib/services/searchManagement/README.md
  lib/services/searchManagement/lib/models/adminKeyResult.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityInput.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityOutput.js
  lib/services/searchManagement/lib/models/identity.js
  lib/services/searchManagement/lib/models/index.d.ts
  lib/services/searchManagement/lib/models/operation.js
  lib/services/searchManagement/lib/models/operationDisplay.js
  lib/services/searchManagement/lib/models/operationListResult.js
  lib/services/searchManagement/lib/models/queryKey.js
  lib/services/searchManagement/lib/models/resource.js
  lib/services/searchManagement/lib/models/searchManagementRequestOptions.js
  lib/services/searchManagement/lib/models/searchService.js
  lib/services/searchManagement/lib/models/sku.js
  lib/services/searchManagement/lib/searchManagementClient.d.ts
  lib/services/searchManagement/lib/searchManagementClient.js
  lib/services/searchManagement/package.json
Labels: RestPRMerged, in progress

#4282 [AutoPR mysql/resource-manager] typo: mysql/resource-manager/Microsoft.DBforMySQL
  lib/services/mysqlManagement/lib/models/index.d.ts
  lib/services/mysqlManagement/lib/models/index.js
  lib/services/mysqlManagement/lib/models/server.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForReplica.js
  lib/services/mysqlManagement/lib/models/serverUpdateParameters.js
  lib/services/mysqlManagement/lib/mySQLManagementClient.d.ts
  lib/services/mysqlManagement/lib/mySQLManagementClient.js
  lib/services/mysqlManagement/lib/operations/index.d.ts
  lib/services/mysqlManagement/lib/operations/index.js
  lib/services/mysqlManagement/lib/operations/replicas.js
  lib/services/mysqlManagement/lib/operations/servers.js
  lib/services/mysqlManagement/package.json
Labels: RestPRMerged

#4294 [AutoPR postgresql/resource-manager] typo: postgresql/resource-manager/Microsoft.DBforPostgreSQL
  lib/services/postgresqlManagement/lib/models/index.d.ts
  lib/services/postgresqlManagement/lib/models/operation.js
  lib/services/postgresqlManagement/lib/models/operationListResult.js
  lib/services/postgresqlManagement/lib/models/performanceTierProperties.js
  lib/services/postgresqlManagement/lib/models/serverForCreate.js
  lib/services/postgresqlManagement/lib/models/serverPropertiesForCreate.js
  lib/services/postgresqlManagement/lib/models/serverUpdateParameters.js
  lib/services/postgresqlManagement/package.json
Labels: RestPRMerged

#4268 [AutoPR hanaonazure/resource-manager] typo: Microsoft.HanaOnAzure
  lib/services/hanaonazureManagement/LICENSE.txt
  lib/services/hanaonazureManagement/README.md
  lib/services/hanaonazureManagement/lib/models/disk.js
  lib/services/hanaonazureManagement/lib/models/display.js
  lib/services/hanaonazureManagement/lib/models/errorResponse.js
  lib/services/hanaonazureManagement/lib/models/hanaInstance.js
  lib/services/hanaonazureManagement/lib/models/hanaInstancesListResult.js
  lib/services/hanaonazureManagement/lib/models/hardwareProfile.js
  lib/services/hanaonazureManagement/lib/models/index.d.ts
  lib/services/hanaonazureManagement/lib/models/ipAddress.js
  lib/services/hanaonazureManagement/lib/models/networkProfile.js
  lib/services/hanaonazureManagement/lib/models/oSProfile.js
  lib/services/hanaonazureManagement/lib/models/operation.js
  lib/services/hanaonazureManagement/lib/models/resource.js
  lib/services/hanaonazureManagement/lib/models/storageProfile.js
  lib/services/hanaonazureManagement/package.json
Labels: RestPRMerged

#4329 [AutoPR recoveryservicessiterecovery/resource-manager] typo: recoveryservicessiterecovery/resource-manager/Microsoft.RecoveryServices
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/alertProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/azureToAzureCreateNetworkMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/consistencyCheckTaskDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/currentJobDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/dataStore.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/diskDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/event.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/eventProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageAzureV2ReplicationDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageEnableProtectionInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageReplicationDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/inMageReprotectInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/index.d.ts
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/jobQueryParameter.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/networkMapping.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/protectionContainer.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/protectionContainerFabricSpecificDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/protectionContainerProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/resourceHealthSummary.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/storageClassification.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/storageClassificationMapping.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/updateRecoveryPlanInputProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/updateVCenterRequest.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/updateVCenterRequestProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vCenter.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vCenterProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vMNicDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vMNicInputDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vMwareCbtEnableMigrationInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vMwareCbtMigrationDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vaultHealthDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vaultHealthProperties.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vmmToAzureCreateNetworkMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vmmToAzureUpdateNetworkMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vmmToVmmCreateNetworkMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/vmmToVmmUpdateNetworkMappingInput.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/index.d.ts
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/replicationJobs.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/replicationStorageClassificationMappings.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/operations/replicationvCenters.js
Labels: RestPRMerged, in progress

#4266 [AutoPR frontdoor/resource-manager] typo: frontdoor/Microsoft.Network
  lib/services/frontdoorManagement/LICENSE.txt
  lib/services/frontdoorManagement/README.md
  lib/services/frontdoorManagement/lib/models/azureAsyncOperationResult.js
  lib/services/frontdoorManagement/lib/models/azureManagedOverrideRuleGroup.js
  lib/services/frontdoorManagement/lib/models/azureManagedRuleSet.js
  lib/services/frontdoorManagement/lib/models/backend.js
  lib/services/frontdoorManagement/lib/models/backendPool.js
  lib/services/frontdoorManagement/lib/models/backendPoolListResult.js
  lib/services/frontdoorManagement/lib/models/backendPoolUpdateParameters.js
  lib/services/frontdoorManagement/lib/models/cacheConfiguration.js
  lib/services/frontdoorManagement/lib/models/checkNameAvailabilityInput.js
  lib/services/frontdoorManagement/lib/models/checkNameAvailabilityOutput.js
  lib/services/frontdoorManagement/lib/models/customHttpsConfiguration.js
  lib/services/frontdoorManagement/lib/models/customRule.js
  lib/services/frontdoorManagement/lib/models/customRules.js
  lib/services/frontdoorManagement/lib/models/errorDetails.js
  lib/services/frontdoorManagement/lib/models/errorModel.js
  lib/services/frontdoorManagement/lib/models/errorResponse.js
  lib/services/frontdoorManagement/lib/models/frontDoor.js
  lib/services/frontdoorManagement/lib/models/frontDoorListResult.js
  lib/services/frontdoorManagement/lib/models/frontDoorUpdateParameters.js
  lib/services/frontdoorManagement/lib/models/frontendEndpoint.js
  lib/services/frontdoorManagement/lib/models/frontendEndpointUpdateParameters.js
  lib/services/frontdoorManagement/lib/models/frontendEndpointUpdateParametersWebApplicationFirewallPolicyLink.js
  lib/services/frontdoorManagement/lib/models/frontendEndpointsListResult.js
  lib/services/frontdoorManagement/lib/models/healthProbeSettingsListResult.js
  lib/services/frontdoorManagement/lib/models/healthProbeSettingsModel.js
  lib/services/frontdoorManagement/lib/models/healthProbeSettingsUpdateParameters.js
  lib/services/frontdoorManagement/lib/models/index.d.ts
  lib/services/frontdoorManagement/lib/models/keyVaultCertificateSourceParametersVault.js
  lib/services/frontdoorManagement/lib/models/loadBalancingSettingsListResult.js
  lib/services/frontdoorManagement/lib/models/loadBalancingSettingsModel.js
  lib/services/frontdoorManagement/lib/models/loadBalancingSettingsUpdateParameters.js
  lib/services/frontdoorManagement/lib/models/managedRuleSet.js
  lib/services/frontdoorManagement/lib/models/managedRuleSets.js
  lib/services/frontdoorManagement/lib/models/matchCondition1.js
  lib/services/frontdoorManagement/lib/models/policySettings.js
  lib/services/frontdoorManagement/lib/models/purgeParameters.js
  lib/services/frontdoorManagement/lib/models/resource.js
  lib/services/frontdoorManagement/lib/models/routingRule.js
  lib/services/frontdoorManagement/lib/models/routingRuleListResult.js
  lib/services/frontdoorManagement/lib/models/routingRuleUpdateParameters.js
  lib/services/frontdoorManagement/lib/models/subResource.js
  lib/services/frontdoorManagement/lib/models/tagsObject.js
  lib/services/frontdoorManagement/lib/models/validateCustomDomainInput.js
  lib/services/frontdoorManagement/lib/models/validateCustomDomainOutput.js
  lib/services/frontdoorManagement/lib/models/webApplicationFirewallPolicy1.js
  lib/services/frontdoorManagement/lib/models/webApplicationFirewallPolicyListResult.js
  lib/services/frontdoorManagement/lib/operations/index.d.ts
  lib/services/frontdoorManagement/lib/operations/policies.js
  lib/services/frontdoorManagement/package.json
Labels: RestPRMerged, in progress

#4261 [AutoPR deviceprovisioningservices/resource-manager] typo: Microsoft.Devices
  lib/services/deviceprovisioningservicesManagement/LICENSE.txt
  lib/services/deviceprovisioningservicesManagement/README.md
  lib/services/deviceprovisioningservicesManagement/lib/iotDpsClient.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/iotDpsClient.js
  lib/services/deviceprovisioningservicesManagement/lib/models/asyncOperationResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateBodyDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateListDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateProperties.js
  lib/services/deviceprovisioningservicesManagement/lib/models/certificateResponse.js
  lib/services/deviceprovisioningservicesManagement/lib/models/errorDetails.js
  lib/services/deviceprovisioningservicesManagement/lib/models/errorMesssage.js
  lib/services/deviceprovisioningservicesManagement/lib/models/index.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsPropertiesDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsSkuDefinition.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsSkuDefinitionListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotDpsSkuInfo.js
  lib/services/deviceprovisioningservicesManagement/lib/models/iotHubDefinitionDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/nameAvailabilityInfo.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operation.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operationDisplay.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operationInputs.js
  lib/services/deviceprovisioningservicesManagement/lib/models/operationListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/provisioningServiceDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/provisioningServiceDescriptionListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/resource.js
  lib/services/deviceprovisioningservicesManagement/lib/models/sharedAccessSignatureAuthorizationRuleAccessRightsDescription.js
  lib/services/deviceprovisioningservicesManagement/lib/models/sharedAccessSignatureAuthorizationRuleListResult.js
  lib/services/deviceprovisioningservicesManagement/lib/models/tagsResource.js
  lib/services/deviceprovisioningservicesManagement/lib/models/verificationCodeRequest.js
  lib/services/deviceprovisioningservicesManagement/lib/models/verificationCodeResponse.js
  lib/services/deviceprovisioningservicesManagement/lib/models/verificationCodeResponseProperties.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/dpsCertificate.js
  lib/services/deviceprovisioningservicesManagement/lib/operations/index.d.ts
  lib/services/deviceprovisioningservicesManagement/lib/operations/iotDpsResource.js
  lib/services/deviceprovisioningservicesManagement/package.json
Labels: RestPRMerged, in progress

#4351 Generate azure-arm-sqlvirtualmachine
  lib/services/sqlvirtualmachineManagement/LICENSE.txt
  lib/services/sqlvirtualmachineManagement/README.md
  lib/services/sqlvirtualmachineManagement/lib/models/additionalFeaturesServerConfigurations.js
  lib/services/sqlvirtualmachineManagement/lib/models/autoBackupSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/autoPatchingSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/availabilityGroupListener.js
  lib/services/sqlvirtualmachineManagement/lib/models/availabilityGroupListenerListResult.js
  lib/services/sqlvirtualmachineManagement/lib/models/index.d.ts
  lib/services/sqlvirtualmachineManagement/lib/models/index.js
  lib/services/sqlvirtualmachineManagement/lib/models/keyVaultCredentialSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/loadBalancerConfiguration.js
  lib/services/sqlvirtualmachineManagement/lib/models/operation.js
  lib/services/sqlvirtualmachineManagement/lib/models/operationDisplay.js
  lib/services/sqlvirtualmachineManagement/lib/models/operationListResult.js
  lib/services/sqlvirtualmachineManagement/lib/models/privateIPAddress.js
  lib/services/sqlvirtualmachineManagement/lib/models/proxyResource.js
  lib/services/sqlvirtualmachineManagement/lib/models/resource.js
  lib/services/sqlvirtualmachineManagement/lib/models/resourceIdentity.js
  lib/services/sqlvirtualmachineManagement/lib/models/serverConfigurationsManagementSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlConnectivityUpdateSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlStorageUpdateSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachine.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachineGroup.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachineGroupListResult.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachineGroupUpdate.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachineListResult.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachineUpdate.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlWorkloadTypeUpdateSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/trackedResource.js
  lib/services/sqlvirtualmachineManagement/lib/models/wsfcDomainCredentials.js
  lib/services/sqlvirtualmachineManagement/lib/models/wsfcDomainProfile.js
  lib/services/sqlvirtualmachineManagement/lib/operations/availabilityGroupListeners.js
  lib/services/sqlvirtualmachineManagement/lib/operations/index.d.ts
  lib/services/sqlvirtualmachineManagement/lib/operations/index.js
  lib/services/sqlvirtualmachineManagement/lib/operations/operations.js
  lib/services/sqlvirtualmachineManagement/lib/operations/sqlVirtualMachineGroups.js
  lib/services/sqlvirtualmachineManagement/lib/operations/sqlVirtualMachines.js
  lib/services/sqlvirtualmachineManagement/lib/sqlVirtualMachineManagementClient.d.ts
  lib/services/sqlvirtualmachineManagement/lib/sqlVirtualMachineManagementClient.js
  lib/services/sqlvirtualmachineManagement/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4352 Regenerate azure-cognitiveservices-luis-runtime
  lib/services/luis/runtime/README.md
  lib/services/luis/runtime/lib/models/aPIError.js
  lib/services/luis/runtime/lib/models/compositeChildModel.js
  lib/services/luis/runtime/lib/models/compositeEntityModel.js
  lib/services/luis/runtime/lib/models/entityModel.js
  lib/services/luis/runtime/lib/models/entityWithResolution.js
  lib/services/luis/runtime/lib/models/entityWithScore.js
  lib/services/luis/runtime/lib/models/index.d.ts
  lib/services/luis/runtime/lib/models/intentModel.js
  lib/services/luis/runtime/lib/models/luisResult.js
  lib/services/luis/runtime/lib/models/sentiment.js
  lib/services/luis/runtime/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4366 [AutoPR signalr/resource-manager] typo: signalr/resource-manager/Microsoft.SignalRService
  lib/services/signalrManagement/lib/models/index.d.ts
  lib/services/signalrManagement/lib/models/resource.js
  lib/services/signalrManagement/lib/models/signalRUsage.js
  lib/services/signalrManagement/lib/models/signalRUsageName.js
Labels: RestPRMerged, in progress

#4361 Regenerate azure-cognitiveservices-customvision-prediction
  lib/services/customVision/prediction/README.md
  lib/services/customVision/prediction/lib/models/boundingBox.js
  lib/services/customVision/prediction/lib/models/imagePrediction.js
  lib/services/customVision/prediction/lib/models/imageUrl.js
  lib/services/customVision/prediction/lib/models/index.d.ts
  lib/services/customVision/prediction/lib/models/prediction.js
  lib/services/customVision/prediction/lib/predictionAPIClient.d.ts
  lib/services/customVision/prediction/lib/predictionAPIClient.js
  lib/services/customVision/prediction/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4360 Regenerate azure-cognitiveservices-customvision-training
  lib/services/customVision/training/README.md
  lib/services/customVision/training/lib/models/boundingBox.js
  lib/services/customVision/training/lib/models/domain.js
  lib/services/customVision/training/lib/models/exportModel.js
  lib/services/customVision/training/lib/models/image.js
  lib/services/customVision/training/lib/models/imageCreateResult.js
  lib/services/customVision/training/lib/models/imageCreateSummary.js
  lib/services/customVision/training/lib/models/imageFileCreateBatch.js
  lib/services/customVision/training/lib/models/imageFileCreateEntry.js
  lib/services/customVision/training/lib/models/imageIdCreateBatch.js
  lib/services/customVision/training/lib/models/imageIdCreateEntry.js
  lib/services/customVision/training/lib/models/imagePerformance.js
  lib/services/customVision/training/lib/models/imagePrediction.js
  lib/services/customVision/training/lib/models/imageRegion.js
  lib/services/customVision/training/lib/models/imageRegionCreateBatch.js
  lib/services/customVision/training/lib/models/imageRegionCreateEntry.js
  lib/services/customVision/training/lib/models/imageRegionCreateResult.js
  lib/services/customVision/training/lib/models/imageRegionCreateSummary.js
  lib/services/customVision/training/lib/models/imageRegionProposal.js
  lib/services/customVision/training/lib/models/imageTag.js
  lib/services/customVision/training/lib/models/imageTagCreateBatch.js
  lib/services/customVision/training/lib/models/imageTagCreateEntry.js
  lib/services/customVision/training/lib/models/imageTagCreateSummary.js
  lib/services/customVision/training/lib/models/imageUrl.js
  lib/services/customVision/training/lib/models/imageUrlCreateBatch.js
  lib/services/customVision/training/lib/models/imageUrlCreateEntry.js
  lib/services/customVision/training/lib/models/index.d.ts
  lib/services/customVision/training/lib/models/index.js
  lib/services/customVision/training/lib/models/iteration.js
  lib/services/customVision/training/lib/models/iterationPerformance.js
  lib/services/customVision/training/lib/models/prediction.js
  lib/services/customVision/training/lib/models/predictionQueryResult.js
  lib/services/customVision/training/lib/models/predictionQueryTag.js
  lib/services/customVision/training/lib/models/predictionQueryToken.js
  lib/services/customVision/training/lib/models/project.js
  lib/services/customVision/training/lib/models/projectSettings.js
  lib/services/customVision/training/lib/models/region.js
  lib/services/customVision/training/lib/models/regionProposal.js
  lib/services/customVision/training/lib/models/storedImagePrediction.js
  lib/services/customVision/training/lib/models/tag.js
  lib/services/customVision/training/lib/models/tagPerformance.js
  lib/services/customVision/training/lib/trainingAPIClient.d.ts
  lib/services/customVision/training/lib/trainingAPIClient.js
  lib/services/customVision/training/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4368 [AutoPR storagesync/resource-manager] typo: storagesync/resource-manager/Microsoft.StorageSync
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
Labels: RestPRMerged, in progress

#4338 [AutoPR security/resource-manager] typo: security/resource-manager/Microsoft.Security
  lib/services/securityManagement/lib/models/externalSecuritySolution.js
  lib/services/securityManagement/lib/models/index.d.ts
  lib/services/securityManagement/lib/operations/alerts.js
  lib/services/securityManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4356 [AutoPR hanaonazure/resource-manager] Update HanaOnAzure Swagger to support new SKU: S96
  lib/services/hanaonazureManagement/lib/models/hanaInstance.js
  lib/services/hanaonazureManagement/lib/models/hardwareProfile.js
  lib/services/hanaonazureManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4316 [AutoPR applicationinsights/resource-manager] chore: Rename microsoft.insights to Microsoft.Insights
  lib/services/applicationinsights/lib/models/aPIKeyRequest.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentAPIKey.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentExportConfiguration.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentListResult.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentProactiveDetectionConfiguration.js
  lib/services/applicationinsights/lib/models/applicationInsightsComponentProactiveDetectionConfigurationRuleDefinitions.js
  lib/services/applicationinsights/lib/models/errorResponse.js
  lib/services/applicationinsights/lib/models/index.d.ts
  lib/services/applicationinsights/lib/models/workItemCreateConfiguration.js
  lib/services/applicationinsights/lib/operations/index.d.ts
  lib/services/applicationinsights/lib/operations/proactiveDetectionConfigurations.js
  lib/services/applicationinsights/lib/operations/webTests.js
  lib/services/applicationinsights/lib/operations/workItemConfigurations.js
Labels: RestPRMerged, in progress

#4364 [AutoPR servicefabricmesh/resource-manager] typo: servicefabricmesh/resource-manager/Microsoft.ServiceFabricMesh
  lib/services/serviceFabricMeshManagement/lib/models/containerCodePackageProperties.js
  lib/services/serviceFabricMeshManagement/lib/models/httpHostConfig.js
  lib/services/serviceFabricMeshManagement/lib/models/index.d.ts
  lib/services/serviceFabricMeshManagement/lib/models/secretValueResourceDescriptionList.js
  lib/services/serviceFabricMeshManagement/lib/operations/index.d.ts
  lib/services/serviceFabricMeshManagement/lib/operations/secretValueOperations.js
Labels: RestPRMerged, in progress

#4315 Add ComponentGovernance
  .azure-pipelines/client.yml
Labels: in progress

#4328 [AutoPR datafactory/resource-manager] Refactor delete activity payload
  lib/services/datafactoryManagement/lib/models/deleteActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/logStorageSettings.js
Labels: RestPRMerged, in progress

#4383 [AutoPR timeseriesinsights/resource-manager] typo: timeseriesinsights/resource-manager/Microsoft.TimeSeriesInsights
  lib/services/timeseriesinsightsManagement/lib/models/environmentResource.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentStateDetails.js
  lib/services/timeseriesinsightsManagement/lib/models/environmentStatus.js
  lib/services/timeseriesinsightsManagement/lib/models/index.d.ts
  lib/services/timeseriesinsightsManagement/lib/models/ingressEnvironmentStatus.js
Labels: RestPRMerged, in progress

#4375 [AutoPR labservices/resource-manager] [LabServices] Fix typo, remove required from optional param
  lib/services/labservicesManagement/lib/models/index.d.ts
  lib/services/labservicesManagement/lib/models/index.js
  lib/services/labservicesManagement/lib/models/personalPreferencesOperationsPayload.js
  lib/services/labservicesManagement/lib/operations/globalUsers.js
  lib/services/labservicesManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4392 Regenerate azure-cognitiveservices-autosuggest
  lib/services/cognitiveServicesAutoSuggest/lib/autoSuggestClient.d.ts
  lib/services/cognitiveServicesAutoSuggest/lib/autoSuggestClient.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/action.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/creativeWork.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/errorModel.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/errorResponse.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/identifiable.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/index.d.ts
  lib/services/cognitiveServicesAutoSuggest/lib/models/queryContext.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/response.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/responseBase.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/searchAction.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/suggestions.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/suggestionsSuggestionGroup.js
  lib/services/cognitiveServicesAutoSuggest/lib/models/thing.js
  lib/services/cognitiveServicesAutoSuggest/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4393 Regenerate azure-cognitiveservices-customimagesearch
  lib/services/cognitiveServicesCustomImageSearch/lib/customImageSearchClient.d.ts
  lib/services/cognitiveServicesCustomImageSearch/lib/customImageSearchClient.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/imageObject.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/images.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesCustomImageSearch/lib/models/mediaObject.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/query.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/response.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesCustomImageSearch/lib/models/thing.js
  lib/services/cognitiveServicesCustomImageSearch/lib/operations/customInstance.js
  lib/services/cognitiveServicesCustomImageSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesCustomImageSearch/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4396 Regenerate azure-cognitiveservices-imagesearch
  lib/services/imageSearch/lib/imageSearchClient.d.ts
  lib/services/imageSearch/lib/imageSearchClient.js
  lib/services/imageSearch/lib/models/aggregateOffer.js
  lib/services/imageSearch/lib/models/aggregateRating.js
  lib/services/imageSearch/lib/models/creativeWork.js
  lib/services/imageSearch/lib/models/errorModel.js
  lib/services/imageSearch/lib/models/errorResponse.js
  lib/services/imageSearch/lib/models/identifiable.js
  lib/services/imageSearch/lib/models/imageGallery.js
  lib/services/imageSearch/lib/models/imageInsights.js
  lib/services/imageSearch/lib/models/imageInsightsImageCaption.js
  lib/services/imageSearch/lib/models/imageObject.js
  lib/services/imageSearch/lib/models/imageTagsModule.js
  lib/services/imageSearch/lib/models/images.js
  lib/services/imageSearch/lib/models/imagesImageMetadata.js
  lib/services/imageSearch/lib/models/imagesModule.js
  lib/services/imageSearch/lib/models/index.d.ts
  lib/services/imageSearch/lib/models/insightsTag.js
  lib/services/imageSearch/lib/models/mediaObject.js
  lib/services/imageSearch/lib/models/normalizedRectangle.js
  lib/services/imageSearch/lib/models/offer.js
  lib/services/imageSearch/lib/models/person.js
  lib/services/imageSearch/lib/models/pivotSuggestions.js
  lib/services/imageSearch/lib/models/propertiesItem.js
  lib/services/imageSearch/lib/models/query.js
  lib/services/imageSearch/lib/models/rating.js
  lib/services/imageSearch/lib/models/recipe.js
  lib/services/imageSearch/lib/models/recipesModule.js
  lib/services/imageSearch/lib/models/recognizedEntitiesModule.js
  lib/services/imageSearch/lib/models/recognizedEntity.js
  lib/services/imageSearch/lib/models/recognizedEntityGroup.js
  lib/services/imageSearch/lib/models/recognizedEntityRegion.js
  lib/services/imageSearch/lib/models/relatedCollectionsModule.js
  lib/services/imageSearch/lib/models/relatedSearchesModule.js
  lib/services/imageSearch/lib/models/response.js
  lib/services/imageSearch/lib/models/responseBase.js
  lib/services/imageSearch/lib/models/searchResultsAnswer.js
  lib/services/imageSearch/lib/models/thing.js
  lib/services/imageSearch/lib/models/trendingImages.js
  lib/services/imageSearch/lib/models/trendingImagesCategory.js
  lib/services/imageSearch/lib/models/trendingImagesTile.js
  lib/services/imageSearch/lib/operations/imagesOperations.js
  lib/services/imageSearch/lib/operations/index.d.ts
  lib/services/imageSearch/package.json
  test/services/cognitiveServicesSearch/imageSearch-tests.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4395 Regenerate azure-cognitiveservices-entitysearch
  lib/services/entitySearch/lib/entitySearchClient.d.ts
  lib/services/entitySearch/lib/entitySearchClient.js
  lib/services/entitySearch/lib/models/airport.js
  lib/services/entitySearch/lib/models/contractualRulesAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesContractualRule.js
  lib/services/entitySearch/lib/models/contractualRulesLicenseAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesLinkAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesMediaAttribution.js
  lib/services/entitySearch/lib/models/contractualRulesTextAttribution.js
  lib/services/entitySearch/lib/models/creativeWork.js
  lib/services/entitySearch/lib/models/entities.js
  lib/services/entitySearch/lib/models/entitiesEntityPresentationInfo.js
  lib/services/entitySearch/lib/models/errorModel.js
  lib/services/entitySearch/lib/models/errorResponse.js
  lib/services/entitySearch/lib/models/hotel.js
  lib/services/entitySearch/lib/models/identifiable.js
  lib/services/entitySearch/lib/models/imageObject.js
  lib/services/entitySearch/lib/models/index.d.ts
  lib/services/entitySearch/lib/models/localBusiness.js
  lib/services/entitySearch/lib/models/mediaObject.js
  lib/services/entitySearch/lib/models/movieTheater.js
  lib/services/entitySearch/lib/models/place.js
  lib/services/entitySearch/lib/models/places.js
  lib/services/entitySearch/lib/models/postalAddress.js
  lib/services/entitySearch/lib/models/queryContext.js
  lib/services/entitySearch/lib/models/response.js
  lib/services/entitySearch/lib/models/responseBase.js
  lib/services/entitySearch/lib/models/restaurant.js
  lib/services/entitySearch/lib/models/searchResponse.js
  lib/services/entitySearch/lib/models/searchResultsAnswer.js
  lib/services/entitySearch/lib/models/thing.js
  lib/services/entitySearch/lib/operations/entitiesOperations.js
  lib/services/entitySearch/lib/operations/index.d.ts
  lib/services/entitySearch/package.json
  test/services/cognitiveServicesSearch/entitySearch-tests.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4398 Regenerate azure-cognitiveservices-spellcheck
  lib/services/spellCheck/lib/models/errorModel.js
  lib/services/spellCheck/lib/models/errorResponse.js
  lib/services/spellCheck/lib/models/identifiable.js
  lib/services/spellCheck/lib/models/index.d.ts
  lib/services/spellCheck/lib/models/responseBase.js
  lib/services/spellCheck/lib/models/spellCheck.js
  lib/services/spellCheck/lib/models/spellingFlaggedToken.js
  lib/services/spellCheck/lib/models/spellingTokenSuggestion.js
  lib/services/spellCheck/lib/spellCheckClient.d.ts
  lib/services/spellCheck/lib/spellCheckClient.js
  lib/services/spellCheck/package.json
  test/services/cognitiveServicesLanguage/spellCheckAPIClient-tests.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4399 Regenerate azure-cognitiveservices-visualsearch
  lib/services/visualSearch/lib/models/action.js
  lib/services/visualSearch/lib/models/aggregateOffer.js
  lib/services/visualSearch/lib/models/aggregateRating.js
  lib/services/visualSearch/lib/models/creativeWork.js
  lib/services/visualSearch/lib/models/cropArea.js
  lib/services/visualSearch/lib/models/errorModel.js
  lib/services/visualSearch/lib/models/errorResponse.js
  lib/services/visualSearch/lib/models/filters.js
  lib/services/visualSearch/lib/models/identifiable.js
  lib/services/visualSearch/lib/models/imageAction.js
  lib/services/visualSearch/lib/models/imageInfo.js
  lib/services/visualSearch/lib/models/imageKnowledge.js
  lib/services/visualSearch/lib/models/imageModuleAction.js
  lib/services/visualSearch/lib/models/imageObject.js
  lib/services/visualSearch/lib/models/imageRecipesAction.js
  lib/services/visualSearch/lib/models/imageRelatedSearchesAction.js
  lib/services/visualSearch/lib/models/imageShoppingSourcesAction.js
  lib/services/visualSearch/lib/models/imageTag.js
  lib/services/visualSearch/lib/models/imageTagRegion.js
  lib/services/visualSearch/lib/models/imagesImageMetadata.js
  lib/services/visualSearch/lib/models/imagesModule.js
  lib/services/visualSearch/lib/models/index.d.ts
  lib/services/visualSearch/lib/models/knowledgeRequest.js
  lib/services/visualSearch/lib/models/mediaObject.js
  lib/services/visualSearch/lib/models/normalizedQuadrilateral.js
  lib/services/visualSearch/lib/models/offer.js
  lib/services/visualSearch/lib/models/person.js
  lib/services/visualSearch/lib/models/point2D.js
  lib/services/visualSearch/lib/models/propertiesItem.js
  lib/services/visualSearch/lib/models/query.js
  lib/services/visualSearch/lib/models/rating.js
  lib/services/visualSearch/lib/models/recipe.js
  lib/services/visualSearch/lib/models/recipesModule.js
  lib/services/visualSearch/lib/models/relatedSearchesModule.js
  lib/services/visualSearch/lib/models/response.js
  lib/services/visualSearch/lib/models/responseBase.js
  lib/services/visualSearch/lib/models/thing.js
  lib/services/visualSearch/lib/models/visualSearchRequest.js
  lib/services/visualSearch/lib/operations/images.js
  lib/services/visualSearch/lib/operations/index.d.ts
  lib/services/visualSearch/lib/visualSearchClient.d.ts
  lib/services/visualSearch/lib/visualSearchClient.js
  lib/services/visualSearch/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4347 [AutoPR compute/resource-manager] [Please do not merge] Adding provisionAfterExtensions property for ex…
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetExtension.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetExtensions.js
Labels: RestPRMerged, in progress

#4400 Regenerate azure-cognitiveservices-websearch
  lib/services/cognitiveServicesWebSearch/lib/models/answer.js
  lib/services/cognitiveServicesWebSearch/lib/models/article.js
  lib/services/cognitiveServicesWebSearch/lib/models/computation.js
  lib/services/cognitiveServicesWebSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesWebSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesWebSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesWebSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesWebSearch/lib/models/imageObject.js
  lib/services/cognitiveServicesWebSearch/lib/models/images.js
  lib/services/cognitiveServicesWebSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesWebSearch/lib/models/mediaObject.js
  lib/services/cognitiveServicesWebSearch/lib/models/news.js
  lib/services/cognitiveServicesWebSearch/lib/models/places.js
  lib/services/cognitiveServicesWebSearch/lib/models/query.js
  lib/services/cognitiveServicesWebSearch/lib/models/queryContext.js
  lib/services/cognitiveServicesWebSearch/lib/models/rankingRankingGroup.js
  lib/services/cognitiveServicesWebSearch/lib/models/rankingRankingItem.js
  lib/services/cognitiveServicesWebSearch/lib/models/rankingRankingResponse.js
  lib/services/cognitiveServicesWebSearch/lib/models/relatedSearchesRelatedSearchAnswer.js
  lib/services/cognitiveServicesWebSearch/lib/models/response.js
  lib/services/cognitiveServicesWebSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesWebSearch/lib/models/searchResponse.js
  lib/services/cognitiveServicesWebSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesWebSearch/lib/models/spellSuggestions.js
  lib/services/cognitiveServicesWebSearch/lib/models/thing.js
  lib/services/cognitiveServicesWebSearch/lib/models/timeZone.js
  lib/services/cognitiveServicesWebSearch/lib/models/timeZoneTimeZoneInformation.js
  lib/services/cognitiveServicesWebSearch/lib/models/videoObject.js
  lib/services/cognitiveServicesWebSearch/lib/models/videos.js
  lib/services/cognitiveServicesWebSearch/lib/models/webMetaTag.js
  lib/services/cognitiveServicesWebSearch/lib/models/webPage.js
  lib/services/cognitiveServicesWebSearch/lib/models/webWebAnswer.js
  lib/services/cognitiveServicesWebSearch/lib/models/webWebGrouping.js
  lib/services/cognitiveServicesWebSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesWebSearch/lib/operations/web.js
  lib/services/cognitiveServicesWebSearch/lib/webSearchClient.d.ts
  lib/services/cognitiveServicesWebSearch/lib/webSearchClient.js
  lib/services/cognitiveServicesWebSearch/package.json
  test/services/cognitiveServicesSearch/webSearch-tests.js
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4346 [AutoPR logic/resource-manager] Bugfix for swagger/sdk not matching the underlying service API
  lib/services/logicManagement/lib/models/agreementContent.js
  lib/services/logicManagement/lib/models/edifactAgreementContent.js
  lib/services/logicManagement/lib/models/edifactOneWayAgreement.js
  lib/services/logicManagement/lib/models/edifactProtocolSettings.js
  lib/services/logicManagement/lib/models/edifactValidationOverride.js
  lib/services/logicManagement/lib/models/edifactValidationSettings.js
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/integrationAccountAgreement.js
  lib/services/logicManagement/lib/models/x12AgreementContent.js
  lib/services/logicManagement/lib/models/x12OneWayAgreement.js
  lib/services/logicManagement/lib/models/x12ProtocolSettings.js
  lib/services/logicManagement/lib/models/x12ValidationOverride.js
  lib/services/logicManagement/lib/models/x12ValidationSettings.js
  lib/services/logicManagement/lib/operations/index.d.ts
  lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
Labels: RestPRMerged, in progress

#4404 Regenerate azure-arm-sqlvirtualmachine
  lib/services/sqlvirtualmachineManagement/lib/models/additionalFeaturesServerConfigurations.js
  lib/services/sqlvirtualmachineManagement/lib/models/index.d.ts
  lib/services/sqlvirtualmachineManagement/lib/models/loadBalancerConfiguration.js
  lib/services/sqlvirtualmachineManagement/lib/models/serverConfigurationsManagementSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlStorageUpdateSettings.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachine.js
  lib/services/sqlvirtualmachineManagement/lib/models/sqlVirtualMachineGroup.js
  lib/services/sqlvirtualmachineManagement/lib/operations/index.d.ts
  lib/services/sqlvirtualmachineManagement/lib/operations/sqlVirtualMachineGroups.js
  lib/services/sqlvirtualmachineManagement/lib/operations/sqlVirtualMachines.js
  lib/services/sqlvirtualmachineManagement/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4405 Regenerate azure-cognitiveservices-contentmoderator
  lib/services/cognitiveServicesContentModerator/lib/models/aPIError.js
  lib/services/cognitiveServicesContentModerator/lib/models/address.js
  lib/services/cognitiveServicesContentModerator/lib/models/body.js
  lib/services/cognitiveServicesContentModerator/lib/models/bodyModel.js
  lib/services/cognitiveServicesContentModerator/lib/models/candidate.js
  lib/services/cognitiveServicesContentModerator/lib/models/classification.js
  lib/services/cognitiveServicesContentModerator/lib/models/classificationCategory1.js
  lib/services/cognitiveServicesContentModerator/lib/models/classificationCategory2.js
  lib/services/cognitiveServicesContentModerator/lib/models/classificationCategory3.js
  lib/services/cognitiveServicesContentModerator/lib/models/content.js
  lib/services/cognitiveServicesContentModerator/lib/models/createReviewBodyItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/createReviewBodyItemMetadataItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/createVideoReviewsBodyItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/createVideoReviewsBodyItemMetadataItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/createVideoReviewsBodyItemVideoFramesItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/createVideoReviewsBodyItemVideoFramesItemMetadataItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/createVideoReviewsBodyItemVideoFramesItemReviewerResultTagsItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/detectedLanguage.js
  lib/services/cognitiveServicesContentModerator/lib/models/detectedTerms.js
  lib/services/cognitiveServicesContentModerator/lib/models/email.js
  lib/services/cognitiveServicesContentModerator/lib/models/errorModel.js
  lib/services/cognitiveServicesContentModerator/lib/models/evaluate.js
  lib/services/cognitiveServicesContentModerator/lib/models/face.js
  lib/services/cognitiveServicesContentModerator/lib/models/foundFaces.js
  lib/services/cognitiveServicesContentModerator/lib/models/frame.js
  lib/services/cognitiveServicesContentModerator/lib/models/frames.js
  lib/services/cognitiveServicesContentModerator/lib/models/iPA.js
  lib/services/cognitiveServicesContentModerator/lib/models/image.js
  lib/services/cognitiveServicesContentModerator/lib/models/imageAdditionalInfoItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/imageIds.js
  lib/services/cognitiveServicesContentModerator/lib/models/imageList.js
  lib/services/cognitiveServicesContentModerator/lib/models/index.d.ts
  lib/services/cognitiveServicesContentModerator/lib/models/job.js
  lib/services/cognitiveServicesContentModerator/lib/models/jobExecutionReportDetails.js
  lib/services/cognitiveServicesContentModerator/lib/models/jobId.js
  lib/services/cognitiveServicesContentModerator/lib/models/jobListResult.js
  lib/services/cognitiveServicesContentModerator/lib/models/keyValuePair.js
  lib/services/cognitiveServicesContentModerator/lib/models/match.js
  lib/services/cognitiveServicesContentModerator/lib/models/matchResponse.js
  lib/services/cognitiveServicesContentModerator/lib/models/oCR.js
  lib/services/cognitiveServicesContentModerator/lib/models/pII.js
  lib/services/cognitiveServicesContentModerator/lib/models/phone.js
  lib/services/cognitiveServicesContentModerator/lib/models/refreshIndex.js
  lib/services/cognitiveServicesContentModerator/lib/models/review.js
  lib/services/cognitiveServicesContentModerator/lib/models/sSN.js
  lib/services/cognitiveServicesContentModerator/lib/models/screen.js
  lib/services/cognitiveServicesContentModerator/lib/models/status.js
  lib/services/cognitiveServicesContentModerator/lib/models/tag.js
  lib/services/cognitiveServicesContentModerator/lib/models/termList.js
  lib/services/cognitiveServicesContentModerator/lib/models/terms.js
  lib/services/cognitiveServicesContentModerator/lib/models/termsData.js
  lib/services/cognitiveServicesContentModerator/lib/models/termsInList.js
  lib/services/cognitiveServicesContentModerator/lib/models/termsPaging.js
  lib/services/cognitiveServicesContentModerator/lib/models/transcriptModerationBodyItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/transcriptModerationBodyItemTermsItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/videoFrameBodyItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/videoFrameBodyItemMetadataItem.js
  lib/services/cognitiveServicesContentModerator/lib/models/videoFrameBodyItemReviewerResultTagsItem.js
  lib/services/cognitiveServicesContentModerator/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4409 [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face
  lib/services/cognitiveServicesFace/README.md
  lib/services/cognitiveServicesFace/lib/models/faceList.js
  lib/services/cognitiveServicesFace/lib/models/findSimilarRequest.js
  lib/services/cognitiveServicesFace/lib/models/identifyRequest.js
  lib/services/cognitiveServicesFace/lib/models/index.d.ts
  lib/services/cognitiveServicesFace/lib/models/largeFaceList.js
  lib/services/cognitiveServicesFace/lib/models/largePersonGroup.js
  lib/services/cognitiveServicesFace/lib/models/personGroup.js
  lib/services/cognitiveServicesFace/lib/models/verifyFaceToPersonRequest.js
  lib/services/cognitiveServicesFace/lib/operations/faceListOperations.js
  lib/services/cognitiveServicesFace/lib/operations/index.d.ts
  lib/services/cognitiveServicesFace/lib/operations/largeFaceListOperations.js
Labels: RestPRMerged, in progress

#4411 [AutoPR resourcehealth/resource-manager] typo: resourcehealth/resource-manager/Microsoft.ResourceHealth
  lib/services/resourceHealthManagement/lib/models/availabilityStatus.js
  lib/services/resourceHealthManagement/lib/models/availabilityStatusProperties.js
  lib/services/resourceHealthManagement/lib/models/operation.js
  lib/services/resourceHealthManagement/lib/models/operationListResult.js
  lib/services/resourceHealthManagement/lib/models/serviceImpactingEvent.js
  lib/services/resourceHealthManagement/package.json
Labels: RestPRMerged, in progress

#4412 [AutoPR resources/resource-manager] typo: resources/resource-manager/Microsoft.Authorization
  lib/services/resourceManagement/lib/policy/models/errorResponse.js
  lib/services/resourceManagement/lib/policy/models/index.d.ts
Labels: RestPRMerged, in progress

#4421 Generate azure-cognitiveservices-localsearch
  lib/services/cognitiveServicesLocalSearch/LICENSE.txt
  lib/services/cognitiveServicesLocalSearch/README.md
  lib/services/cognitiveServicesLocalSearch/lib/localSearchClient.d.ts
  lib/services/cognitiveServicesLocalSearch/lib/localSearchClient.js
  lib/services/cognitiveServicesLocalSearch/lib/models/action.js
  lib/services/cognitiveServicesLocalSearch/lib/models/answer.js
  lib/services/cognitiveServicesLocalSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesLocalSearch/lib/models/entitiesEntityPresentationInfo.js
  lib/services/cognitiveServicesLocalSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesLocalSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesLocalSearch/lib/models/geoCoordinates.js
  lib/services/cognitiveServicesLocalSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesLocalSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesLocalSearch/lib/models/index.js
  lib/services/cognitiveServicesLocalSearch/lib/models/intangible.js
  lib/services/cognitiveServicesLocalSearch/lib/models/place.js
  lib/services/cognitiveServicesLocalSearch/lib/models/places.js
  lib/services/cognitiveServicesLocalSearch/lib/models/postalAddress.js
  lib/services/cognitiveServicesLocalSearch/lib/models/queryContext.js
  lib/services/cognitiveServicesLocalSearch/lib/models/response.js
  lib/services/cognitiveServicesLocalSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesLocalSearch/lib/models/searchAction.js
  lib/services/cognitiveServicesLocalSearch/lib/models/searchResponse.js
  lib/services/cognitiveServicesLocalSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesLocalSearch/lib/models/structuredValue.js
  lib/services/cognitiveServicesLocalSearch/lib/models/thing.js
  lib/services/cognitiveServicesLocalSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesLocalSearch/lib/operations/index.js
  lib/services/cognitiveServicesLocalSearch/lib/operations/local.js
  lib/services/cognitiveServicesLocalSearch/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4414 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric
  lib/services/serviceFabric/lib/models/backupInfo.js
  lib/services/serviceFabric/lib/models/backupProgressInfo.js
  lib/services/serviceFabric/lib/models/chaos.js
  lib/services/serviceFabric/lib/models/chaosParameters.js
  lib/services/serviceFabric/lib/models/chaosParametersDictionaryItem.js
  lib/services/serviceFabric/lib/models/chaosTargetFilter.js
  lib/services/serviceFabric/lib/models/containerCodePackageProperties.js
  lib/services/serviceFabric/lib/models/epoch.js
  lib/services/serviceFabric/lib/models/fabricError.js
  lib/services/serviceFabric/lib/models/fabricErrorError.js
  lib/services/serviceFabric/lib/models/httpHostConfig.js
  lib/services/serviceFabric/lib/models/index.d.ts
  lib/services/serviceFabric/lib/models/partitionBackupConfigurationInfo.js
  lib/services/serviceFabric/lib/models/partitionBackupEntity.js
  lib/services/serviceFabric/lib/models/restoreProgressInfo.js
  lib/services/serviceFabric/lib/models/startedChaosEvent.js
  lib/services/serviceFabric/lib/models/statefulServicePartitionInfo.js
  lib/services/serviceFabric/lib/operations/index.d.ts
  lib/services/serviceFabric/lib/operations/meshSecretValue.js
  lib/services/serviceFabric/lib/serviceFabricClient.d.ts
  lib/services/serviceFabric/lib/serviceFabricClient.js
Labels: RestPRMerged, in progress

#4387 [AutoPR cognitiveservices/data-plane/CustomVision/Training] typo: CustomVision/Training
  lib/services/customVision/training/README.md
  lib/services/customVision/training/lib/models/index.d.ts
  lib/services/customVision/training/lib/models/project.js
  lib/services/customVision/training/lib/trainingAPIClient.d.ts
  lib/services/customVision/training/lib/trainingAPIClient.js
Labels: RestPRMerged, in progress

#4295 [AutoPR powerbidedicated/resource-manager] typo: powerbidedicated/resource-manager/Microsoft.PowerBIdedicated
  lib/services/powerbidedicatedManagement/LICENSE.txt
  lib/services/powerbidedicatedManagement/README.md
  lib/services/powerbidedicatedManagement/lib/models/checkCapacityNameAvailabilityParameters.js
  lib/services/powerbidedicatedManagement/lib/models/checkCapacityNameAvailabilityResult.js
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacity.js
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacityAdministrators.js
  lib/services/powerbidedicatedManagement/lib/models/dedicatedCapacityUpdateParameters.js
  lib/services/powerbidedicatedManagement/lib/models/errorResponse.js
  lib/services/powerbidedicatedManagement/lib/models/index.d.ts
  lib/services/powerbidedicatedManagement/lib/models/index.js
  lib/services/powerbidedicatedManagement/lib/models/operation.js
  lib/services/powerbidedicatedManagement/lib/models/operationDisplay.js
  lib/services/powerbidedicatedManagement/lib/models/operationListResult.js
  lib/services/powerbidedicatedManagement/lib/models/resource.js
  lib/services/powerbidedicatedManagement/lib/models/resourceSku.js
  lib/services/powerbidedicatedManagement/lib/models/skuDetailsForExistingResource.js
  lib/services/powerbidedicatedManagement/lib/models/skuEnumerationForExistingResourceResult.js
  lib/services/powerbidedicatedManagement/lib/models/skuEnumerationForNewResourceResult.js
  lib/services/powerbidedicatedManagement/lib/operations/capacities.js
  lib/services/powerbidedicatedManagement/lib/operations/index.d.ts
  lib/services/powerbidedicatedManagement/lib/powerBIDedicatedManagementClient.d.ts
  lib/services/powerbidedicatedManagement/lib/powerBIDedicatedManagementClient.js
  lib/services/powerbidedicatedManagement/package.json
Labels: RestPRMerged, in progress

#4326 Change keyVault version to 3.0.4
  lib/services/keyVault/package.json
Labels: in progress

#4410 [AutoPR cognitiveservices/data-plane/VisualSearch] typo: cognitiveservices/data-plane/VisualSearch
  lib/services/visualSearch/lib/models/imageKnowledge.js
  lib/services/visualSearch/lib/models/imageObject.js
  lib/services/visualSearch/lib/models/index.d.ts
  lib/services/visualSearch/lib/models/query.js
  lib/services/visualSearch/lib/models/thing.js
Labels: RestPRMerged, in progress

#4432 [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch
  lib/services/batch/lib/batchServiceClient.d.ts
  lib/services/batch/lib/batchServiceClient.js
  lib/services/batch/lib/models/autoPoolSpecification.js
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudJobSchedule.js
  lib/services/batch/lib/models/cloudPool.js
  lib/services/batch/lib/models/cloudServiceConfiguration.js
  lib/services/batch/lib/models/cloudTask.js
  lib/services/batch/lib/models/computeNode.js
  lib/services/batch/lib/models/exitCodeMapping.js
  lib/services/batch/lib/models/exitCodeRangeMapping.js
  lib/services/batch/lib/models/exitConditions.js
  lib/services/batch/lib/models/exitOptions.js
  lib/services/batch/lib/models/imageReference.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/index.js
  lib/services/batch/lib/models/jobAddParameter.js
  lib/services/batch/lib/models/jobManagerTask.js
  lib/services/batch/lib/models/jobNetworkConfiguration.js
  lib/services/batch/lib/models/jobPatchParameter.js
  lib/services/batch/lib/models/jobPreparationTask.js
  lib/services/batch/lib/models/jobReleaseTask.js
  lib/services/batch/lib/models/jobScheduleAddParameter.js
  lib/services/batch/lib/models/jobSchedulePatchParameter.js
  lib/services/batch/lib/models/jobScheduleUpdateParameter.js
  lib/services/batch/lib/models/jobSpecification.js
  lib/services/batch/lib/models/jobUpdateParameter.js
  lib/services/batch/lib/models/networkConfiguration.js
  lib/services/batch/lib/models/poolAddParameter.js
  lib/services/batch/lib/models/poolInformation.js
  lib/services/batch/lib/models/poolSpecification.js
  lib/services/batch/lib/models/poolUsageMetrics.js
  lib/services/batch/lib/models/resourceFile.js
  lib/services/batch/lib/models/taskAddParameter.js
  lib/services/batch/lib/models/taskConstraints.js
  lib/services/batch/lib/models/taskUpdateParameter.js
  lib/services/batch/lib/models/userAccount.js
  lib/services/batch/lib/models/userIdentity.js
  lib/services/batch/lib/models/virtualMachineConfiguration.js
  lib/services/batch/lib/models/windowsUserConfiguration.js
  lib/services/batch/lib/operations/account.js
  lib/services/batch/lib/operations/application.js
  lib/services/batch/lib/operations/certificateOperations.js
  lib/services/batch/lib/operations/computeNodeOperations.js
  lib/services/batch/lib/operations/file.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
  lib/services/batch/lib/operations/task.js
Labels: RestPRMerged, in progress

#4436 [AutoPR containerservices/resource-manager] ContainerServices - OpenShift - Add new routes and update
  lib/services/containerservicesManagement/README.md
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/index.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedCluster.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterListResult.js
  lib/services/containerservicesManagement/lib/models/openShiftManagedClusterMasterPoolProfile.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Labels: RestPRMerged, in progress

#4434 [AutoPR commerce/resource-manager] typo: commerce/resource-manager/Microsoft.Commerce
  lib/services/commerce/LICENSE.txt
  lib/services/commerce/README.md
  lib/services/commerce/lib/models/errorResponse.js
  lib/services/commerce/lib/models/index.d.ts
  lib/services/commerce/lib/models/infoField.js
  lib/services/commerce/lib/models/meterInfo.js
  lib/services/commerce/lib/models/monetaryCommitment.js
  lib/services/commerce/lib/models/monetaryCredit.js
  lib/services/commerce/lib/models/offerTermInfo.js
  lib/services/commerce/lib/models/rateCardQueryParameters.js
  lib/services/commerce/lib/models/recurringCharge.js
  lib/services/commerce/lib/models/resourceRateCardInfo.js
  lib/services/commerce/lib/models/usageAggregation.js
  lib/services/commerce/lib/models/usageAggregationListResult.js
  lib/services/commerce/lib/usageManagementClient.d.ts
  lib/services/commerce/lib/usageManagementClient.js
  lib/services/commerce/package.json
Labels: RestPRMerged, in progress

#4450 [AutoPR sql/resource-manager] Updating managed database swagger
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/managedDatabase.js
  lib/services/sqlManagement2/lib/models/managedDatabaseUpdate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/managedDatabases.js
Labels: RestPRMerged

#4433 [AutoPR authorization/resource-manager] typo: authorization/resource-manager/Microsoft.Authorization
  lib/services/authorizationManagement/lib/models/index.d.ts
  lib/services/authorizationManagement/lib/models/roleAssignment.js
  lib/services/authorizationManagement/lib/models/roleAssignmentCreateParameters.js
  lib/services/authorizationManagement/lib/models/roleAssignmentFilter.js
  lib/services/authorizationManagement/lib/operations/index.d.ts
  lib/services/authorizationManagement/lib/operations/roleAssignments.js
Labels: RestPRMerged, in progress

#4384 [AutoPR trafficmanager/resource-manager] typo: trafficmanager/resource-manager/Microsoft.Network
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/resource.js
Labels: RestPRMerged, in progress

#4457 [AutoPR cognitiveservices/resource-manager] Change Kind and SKU name to string (from enum).
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/sku.js
  lib/services/cognitiveServicesManagement/lib/operations/accounts.js
  lib/services/cognitiveServicesManagement/lib/operations/checkSkuAvailability.js
  lib/services/cognitiveServicesManagement/lib/operations/index.d.ts
Labels: RestPRMerged

#4461 [AutoPR containerservices/resource-manager] [DO NOT MERGE] [AKS] add C# config to readme.md
  lib/services/containerservicesManagement/lib/models/containerService.js
  lib/services/containerservicesManagement/lib/models/containerServiceAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceMasterProfile.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
  lib/services/containerservicesManagement/lib/models/openShiftRouterProfile.js
  lib/services/containerservicesManagement/lib/operations/containerServices.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Labels: RestPRMerged, in progress

#4466 [AutoPR datafactory/resource-manager] typo: datafactory/resource-manager/Microsoft.DataFactory
  lib/services/datafactoryManagement/lib/models/hDInsightHiveActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4467 [AutoPR labservices/resource-manager] typo: labservices/resource-manager/Microsoft.LabServices
  lib/services/labservicesManagement/lib/models/index.d.ts
  lib/services/labservicesManagement/lib/models/listEnvironmentsResponse.js
Labels: RestPRMerged, in progress

#4468 [AutoPR servicefabric/data-plane] typo: servicefabric/data-plane/Microsoft.ServiceFabric
  lib/services/serviceFabric/lib/models/chaos.js
  lib/services/serviceFabric/lib/models/chaosParameters.js
  lib/services/serviceFabric/lib/models/chaosParametersDictionaryItem.js
  lib/services/serviceFabric/lib/models/chaosTargetFilter.js
  lib/services/serviceFabric/lib/models/index.d.ts
  lib/services/serviceFabric/lib/models/startedChaosEvent.js
  lib/services/serviceFabric/lib/serviceFabricClient.d.ts
  lib/services/serviceFabric/lib/serviceFabricClient.js
Labels: RestPRMerged, in progress

#4463 [AutoPR batch/data-plane] typo: batch/data-plane/Microsoft.Batch
  lib/services/batch/lib/models/computeNode.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/virtualMachineConfiguration.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
Labels: RestPRMerged, in progress

#4445 [AutoPR eventgrid/resource-manager] Event Grid 2019-01-01 API Version: Swagger and related test examples
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFilter.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/models/storageBlobDeadLetterDestination.js
  lib/services/eventgridManagement/lib/models/topic.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/index.js
  lib/services/eventgridManagement/lib/operations/topics.js
Labels: RestPRMerged, in progress

#4471 [AutoPR cognitiveservices/data-plane/QnAMaker] QnQMaker py conf
  lib/services/cognitiveServicesQnAMaker/LICENSE.txt
  lib/services/cognitiveServicesQnAMaker/README.md
  lib/services/cognitiveServicesQnAMaker/lib/models/alterationsDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/createKbDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/createKbInputDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/deleteKbContentsDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/endpointKeysDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/errorModel.js
  lib/services/cognitiveServicesQnAMaker/lib/models/errorResponse.js
  lib/services/cognitiveServicesQnAMaker/lib/models/errorResponseError.js
  lib/services/cognitiveServicesQnAMaker/lib/models/fileDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/index.d.ts
  lib/services/cognitiveServicesQnAMaker/lib/models/index.js
  lib/services/cognitiveServicesQnAMaker/lib/models/innerErrorModel.js
  lib/services/cognitiveServicesQnAMaker/lib/models/knowledgebaseDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/knowledgebasesDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/metadataDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/operation.js
  lib/services/cognitiveServicesQnAMaker/lib/models/qnADTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/qnADocumentsDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/replaceKbDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateKbContentsDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateKbOperationDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateKbOperationDTOAdd.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateKbOperationDTODelete.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateKbOperationDTOUpdate.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateMetadataDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateQnaDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateQnaDTOMetadata.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateQnaDTOQuestions.js
  lib/services/cognitiveServicesQnAMaker/lib/models/updateQuestionsDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/models/wordAlterationsDTO.js
  lib/services/cognitiveServicesQnAMaker/lib/operations/alterations.js
  lib/services/cognitiveServicesQnAMaker/lib/operations/endpointKeys.js
  lib/services/cognitiveServicesQnAMaker/lib/operations/index.d.ts
  lib/services/cognitiveServicesQnAMaker/lib/operations/index.js
  lib/services/cognitiveServicesQnAMaker/lib/operations/knowledgebase.js
  lib/services/cognitiveServicesQnAMaker/lib/operations/operations.js
  lib/services/cognitiveServicesQnAMaker/lib/qnAMakerClient.d.ts
  lib/services/cognitiveServicesQnAMaker/lib/qnAMakerClient.js
  lib/services/cognitiveServicesQnAMaker/package.json
Labels: RestPRMerged, in progress

#4477 Regenerate azure-arm-cognitiveservices
  lib/services/cognitiveServicesManagement/README.md
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityParameter.js
  lib/services/cognitiveServicesManagement/lib/models/checkSkuAvailabilityResult.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountCreateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccountUpdateParameters.js
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesResourceAndSku.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
  lib/services/cognitiveServicesManagement/lib/models/sku.js
  lib/services/cognitiveServicesManagement/lib/operations/accounts.js
  lib/services/cognitiveServicesManagement/lib/operations/checkSkuAvailability.js
  lib/services/cognitiveServicesManagement/lib/operations/index.d.ts
  lib/services/cognitiveServicesManagement/package.json
Labels: Planned-Sprint-128, Started-Sprint-128, in progress

#4472 [AutoPR containerservices/resource-manager] [AKS]: SP/AAD update operation for 2018-03-31 and 2018-08-01-preview
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
Labels: RestPRMerged, in progress

#4485 [AutoPR network/resource-manager] Exposing PATCH for Application Security Group (ASG)
  lib/services/networkManagement2/lib/operations/applicationSecurityGroups.js
  lib/services/networkManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4473 [AutoPR storage/resource-manager] [Storage] Fix the UseSubDomainName
  lib/services/storageManagement2/lib/models/customDomain.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
Labels: RestPRMerged, in progress

#4483 [AutoPR hanaonazure/resource-manager] Add PATCH API example to hanaonazure
  lib/services/hanaonazureManagement/lib/models/index.d.ts
  lib/services/hanaonazureManagement/lib/models/index.js
  lib/services/hanaonazureManagement/lib/models/tags.js
  lib/services/hanaonazureManagement/lib/operations/hanaInstances.js
  lib/services/hanaonazureManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4492 [AutoPR automation/resource-manager] Swagger change for Update configuration dynamic group Saved Search Query
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/nonAzureQueryProperties.js
  lib/services/automationManagement/lib/models/softwareUpdateConfiguration.js
  lib/services/automationManagement/lib/models/targetProperties.js
  lib/services/automationManagement/lib/models/updateConfiguration.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/softwareUpdateConfigurations.js
Labels: RestPRMerged, in progress
