Repository Azure/azure-sdk-for-node, pull requests merged in 2018-08, with the labels that each got.

#3277 [AutoPR datafactory/resource-manager] [Datafactory] Remove readOnly flag on github hostName property
  lib/services/datafactoryManagement/lib/dataFactoryManagementClient.d.ts
  lib/services/datafactoryManagement/lib/dataFactoryManagementClient.js
  lib/services/datafactoryManagement/lib/models/activityDependency.js
  lib/services/datafactoryManagement/lib/models/blobEventsTrigger.js
  lib/services/datafactoryManagement/lib/models/factoryGitHubConfiguration.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/package.json
Labels: RestPRMerged, in progress

#3282 [AutoPR hdinsight/resource-manager] [HDInsight] Fixed PUT application parameter
  lib/services/hdInsightManagement/lib/operations/applications.js
  lib/services/hdInsightManagement/lib/operations/index.d.ts
  lib/services/hdInsightManagement/package.json
Labels: RestPRMerged, in progress

#3284 [AutoPR network/resource-manager] Publicipprefixaugust
  lib/services/networkManagement2/lib/models/applicationGatewayBackendHealthServer.js
  lib/services/networkManagement2/lib/models/frontendIPConfiguration.js
  lib/services/networkManagement2/lib/models/iPConfiguration.js
  lib/services/networkManagement2/lib/models/inboundNatRule.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/networkInterfaceIPConfiguration.js
  lib/services/networkManagement2/lib/models/publicIPAddress.js
  lib/services/networkManagement2/lib/models/publicIPPrefix.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/publicIPAddresses.js
  lib/services/networkManagement2/lib/operations/publicIPPrefixes.js
Labels: RestPRMerged, in progress

#3289 [AutoPR automation/resource-manager] Updating PUT operation requirements for SourceControls and SourceControlSyncJobs, updating streams’ value property, and updating examples.
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/sourceControl.js
  lib/services/automationManagement/lib/models/sourceControlCreateOrUpdateParameters.js
  lib/services/automationManagement/lib/models/sourceControlListResult.js
  lib/services/automationManagement/lib/models/sourceControlSecurityTokenProperties.js
  lib/services/automationManagement/lib/models/sourceControlSyncJob.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobCreateParameters.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobListResult.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobStream.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobStreamById.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobStreamsListBySyncJob.js
  lib/services/automationManagement/lib/models/sourceControlUpdateParameters.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/sourceControlOperations.js
  lib/services/automationManagement/lib/operations/sourceControlSyncJobOperations.js
  lib/services/automationManagement/package.json
Labels: RestPRMerged, in progress

#3288 [AutoPR sql/resource-manager] fix SQL VA command copy paste typo
  lib/services/sqlManagement2/lib/models/databaseVulnerabilityAssessment.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/package.json
Labels: RestPRMerged, in progress

#3295 [AutoPR monitor/resource-manager] [Monitor] Fix issue #3585: revert previous commit since it is a brealing change
  lib/services/monitorManagement/lib/models/autoscaleProfile.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/recurrence.js
  lib/services/monitorManagement/package.json
Labels: RestPRMerged, in progress

#3301 [AutoPR network/resource-manager] add x-ms-long-running-operation-options to query packet capture status
  lib/services/networkManagement2/lib/models/applicationGatewayAvailableSslOptions.js
  lib/services/networkManagement2/lib/models/applicationGatewaySslPolicy.js
  lib/services/networkManagement2/lib/models/applicationGatewaySslPredefinedPolicy.js
  lib/services/networkManagement2/lib/models/azureFirewallNetworkRule.js
  lib/services/networkManagement2/lib/models/packetCaptureQueryStatusResult.js
  lib/services/networkManagement2/lib/models/vpnClientConfiguration.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/package.json
Labels: RestPRMerged, in progress

#3303 [AutoPR containerservices/resource-manager] [AKS] regex bug fix for LinuxProfile.AdminUser
  lib/services/containerservicesManagement/lib/models/containerServiceLinuxProfile.js
  lib/services/containerservicesManagement/package.json
Labels: RestPRMerged, in progress

#3307 [AutoPR containerservices/resource-manager] [AKS]modify credentialResults keyName to kubeconfigs
  lib/services/containerservicesManagement/lib/models/credentialResults.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#3309 [AutoPR apimanagement/resource-manager] Bug fix on readonly property
  lib/services/apimanagement/lib/models/certificateConfiguration.js
  lib/services/apimanagement/lib/models/groupContract.js
  lib/services/apimanagement/lib/models/groupContractProperties.js
  lib/services/apimanagement/lib/models/groupCreateParameters.js
  lib/services/apimanagement/lib/models/groupUpdateParameters.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/operations/group.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/package.json
Labels: RestPRMerged, in progress

#3313 [AutoPR containerservices/resource-manager] [AKS] fix CredentialResult value format
  lib/services/containerservicesManagement/lib/models/credentialResult.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#3305 [AutoPR consumption/resource-manager] Introducing UsageDetails and Aggregated Cost by Managment Group Scope. Also updated some existing examples to include missing billingperiod in billingPeriodId Property.
  lib/services/consumptionManagement/lib/consumptionManagementClient.d.ts
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/index.js
  lib/services/consumptionManagement/lib/models/managementGroupAggregatedCostResult.js
  lib/services/consumptionManagement/lib/operations/aggregatedCost.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/index.js
  lib/services/consumptionManagement/lib/operations/usageDetails.js
  lib/services/consumptionManagement/package.json
Labels: RestPRMerged, in progress

#3317 [AutoPR logic/resource-manager] Fix for extra / on the end of the triggers endpoint
  lib/services/logicManagement/lib/operations/workflowTriggers.js
  lib/services/logicManagement/package.json
Labels: RestPRMerged, in progress

#3326 [AutoPR automation/resource-manager] Updating SourceControlSyncJobs and SourceControlSyncJobStreams properties and examples.
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/sourceControlSyncJob.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobById.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobStream.js
  lib/services/automationManagement/lib/models/sourceControlSyncJobStreamById.js
Labels: RestPRMerged, in progress

#3223 [AutoPR] iotcentral/resource-manager
  lib/services/iotcentralManagement/LICENSE.txt
  lib/services/iotcentralManagement/README.md
  lib/services/iotcentralManagement/lib/iotCentralClient.js
  lib/services/iotcentralManagement/package.json
Labels: ServicePR, in progress

#3334 regenerate acr in the correct folder
  lib/services/containerRegistryManagement/lib/LICENSE.txt
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.d.ts
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.js
  lib/services/containerRegistryManagement/lib/lib/containerRegistryManagementClient.d.ts
  lib/services/containerRegistryManagement/lib/lib/containerRegistryManagementClient.js
  lib/services/containerRegistryManagement/lib/lib/models/actor.js
  lib/services/containerRegistryManagement/lib/lib/models/callbackConfig.js
  lib/services/containerRegistryManagement/lib/lib/models/event.js
  lib/services/containerRegistryManagement/lib/lib/models/eventContent.js
  lib/services/containerRegistryManagement/lib/lib/models/eventInfo.js
  lib/services/containerRegistryManagement/lib/lib/models/eventListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/eventRequestMessage.js
  lib/services/containerRegistryManagement/lib/lib/models/eventResponseMessage.js
  lib/services/containerRegistryManagement/lib/lib/models/importImageParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/importSource.js
  lib/services/containerRegistryManagement/lib/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/lib/models/index.js
  lib/services/containerRegistryManagement/lib/lib/models/operationDefinition.js
  lib/services/containerRegistryManagement/lib/lib/models/operationDisplayDefinition.js
  lib/services/containerRegistryManagement/lib/lib/models/operationListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/regenerateCredentialParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/registry.js
  lib/services/containerRegistryManagement/lib/lib/models/registryListCredentialsResult.js
  lib/services/containerRegistryManagement/lib/lib/models/registryListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/registryNameCheckRequest.js
  lib/services/containerRegistryManagement/lib/lib/models/registryNameStatus.js
  lib/services/containerRegistryManagement/lib/lib/models/registryPassword.js
  lib/services/containerRegistryManagement/lib/lib/models/registryUpdateParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/registryUsage.js
  lib/services/containerRegistryManagement/lib/lib/models/registryUsageListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/replication.js
  lib/services/containerRegistryManagement/lib/lib/models/replicationListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/replicationUpdateParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/request.js
  lib/services/containerRegistryManagement/lib/lib/models/resource.js
  lib/services/containerRegistryManagement/lib/lib/models/sku.js
  lib/services/containerRegistryManagement/lib/lib/models/source.js
  lib/services/containerRegistryManagement/lib/lib/models/status.js
  lib/services/containerRegistryManagement/lib/lib/models/storageAccountProperties.js
  lib/services/containerRegistryManagement/lib/lib/models/target.js
  lib/services/containerRegistryManagement/lib/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/lib/models/webhookListResult.js
  lib/services/containerRegistryManagement/lib/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/lib/operations/index.js
  lib/services/containerRegistryManagement/lib/lib/operations/operations.js
  lib/services/containerRegistryManagement/lib/lib/operations/registries.js
  lib/services/containerRegistryManagement/lib/lib/operations/replications.js
  lib/services/containerRegistryManagement/lib/lib/operations/webhooks.js
  lib/services/containerRegistryManagement/lib/models/imageCopyFromModel.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/package.json
  lib/services/containerRegistryManagement/package-lock.json
  lib/services/containerRegistryManagement/package.json
Labels: in progress

#3333 [AutoPR apimanagement/resource-manager] Make 2018-01-01 as default for all clients
  lib/services/apimanagement/lib/apiManagementClient.d.ts
  lib/services/apimanagement/lib/apiManagementClient.js
  lib/services/apimanagement/lib/models/diagnosticContract.js
  lib/services/apimanagement/lib/models/groupContract.js
  lib/services/apimanagement/lib/models/groupContractProperties.js
  lib/services/apimanagement/lib/models/groupCreateParameters.js
  lib/services/apimanagement/lib/models/groupUpdateParameters.js
  lib/services/apimanagement/lib/models/hostnameConfiguration.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/index.js
  lib/services/apimanagement/lib/models/loggerContract.js
  lib/services/apimanagement/lib/models/productContract.js
  lib/services/apimanagement/lib/models/productEntityBaseParameters.js
  lib/services/apimanagement/lib/models/productUpdateParameters.js
  lib/services/apimanagement/lib/operations/apiDiagnostic.js
  lib/services/apimanagement/lib/operations/diagnostic.js
  lib/services/apimanagement/lib/operations/group.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/index.js
  lib/services/apimanagement/lib/operations/logger.js
  lib/services/apimanagement/lib/operations/product.js
Labels: RestPRMerged, in progress

#3330 [AutoPR iotcentral/resource-manager] move stable iotcentral Go SDK package out of preview directory
  lib/services/iotcentralManagement/README.md
  lib/services/iotcentralManagement/lib/iotCentralClient.d.ts
  lib/services/iotcentralManagement/lib/iotCentralClient.js
  lib/services/iotcentralManagement/package.json
Labels: RestPRMerged, in progress

#3323 [AutoPR containerregistry/resource-manager] add option to import images from public registries
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.d.ts
  lib/services/containerRegistryManagement/lib/containerRegistryManagementClient.js
  lib/services/containerRegistryManagement/lib/models/importImageParameters.js
  lib/services/containerRegistryManagement/lib/models/importSource.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/operationDefinition.js
  lib/services/containerRegistryManagement/lib/models/operationMetricSpecificationDefinition.js
  lib/services/containerRegistryManagement/lib/models/operationServiceSpecificationDefinition.js
  lib/services/containerRegistryManagement/lib/models/quarantinePolicy.js
  lib/services/containerRegistryManagement/lib/models/registryPolicies.js
  lib/services/containerRegistryManagement/lib/models/trustPolicy.js
  lib/services/containerRegistryManagement/lib/models/webhook.js
  lib/services/containerRegistryManagement/lib/models/webhookCreateParameters.js
  lib/services/containerRegistryManagement/lib/models/webhookUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/registries.js
  lib/services/containerRegistryManagement/package.json
Labels: RestPRMerged, in progress

#3302 [AutoPR network/resource-manager] Added NetworkConfigurationDiagnostic rest API + example
  lib/services/networkManagement2/lib/models/connectionMonitorsQueryResultItem.js
  lib/services/networkManagement2/lib/models/connectionStateSnapshot.js
  lib/services/networkManagement2/lib/models/errorResponse.js
  lib/services/networkManagement2/lib/models/evaluatedNetworkSecurityGroup.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/matchedRule.js
  lib/services/networkManagement2/lib/models/networkConfigurationDiagnosticParameters.js
  lib/services/networkManagement2/lib/models/networkConfigurationDiagnosticResponse.js
  lib/services/networkManagement2/lib/models/networkConfigurationDiagnosticResult.js
  lib/services/networkManagement2/lib/models/networkSecurityGroupResult.js
  lib/services/networkManagement2/lib/models/networkSecurityRulesEvaluationResult.js
  lib/services/networkManagement2/lib/models/queryConnectionMonitorsParameters.js
  lib/services/networkManagement2/lib/models/queryConnectionMonitorsResponse.js
  lib/services/networkManagement2/lib/models/trafficQuery.js
  lib/services/networkManagement2/lib/operations/connectionMonitors.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkWatchers.js
  lib/services/networkManagement2/lib/operations/packetCaptures.js
Labels: RestPRMerged, in progress

#3344 [AutoPR network/resource-manager] Added new API to networkwatcher.json and examples
  lib/services/networkManagement2/lib/models/connectionMonitorsQueryResultItem.js
  lib/services/networkManagement2/lib/models/connectionStateSnapshot.js
  lib/services/networkManagement2/lib/models/errorResponse.js
  lib/services/networkManagement2/lib/models/evaluatedNetworkSecurityGroup.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/matchedRule.js
  lib/services/networkManagement2/lib/models/networkConfigurationDiagnosticParameters.js
  lib/services/networkManagement2/lib/models/networkConfigurationDiagnosticResponse.js
  lib/services/networkManagement2/lib/models/networkConfigurationDiagnosticResult.js
  lib/services/networkManagement2/lib/models/networkSecurityGroupResult.js
  lib/services/networkManagement2/lib/models/networkSecurityRulesEvaluationResult.js
  lib/services/networkManagement2/lib/models/queryConnectionMonitorsParameters.js
  lib/services/networkManagement2/lib/models/queryConnectionMonitorsResponse.js
  lib/services/networkManagement2/lib/models/trafficQuery.js
  lib/services/networkManagement2/lib/operations/connectionMonitors.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkWatchers.js
  lib/services/networkManagement2/lib/operations/packetCaptures.js
Labels: RestPRMerged, in progress

#2994 Add additionalInfo to CloudError
  runtime/ms-rest-azure/lib/cloudError.js
  runtime/ms-rest-azure/ms-rest-azure.njsproj
  runtime/ms-rest-azure/test/cloudErrorTest.js
  runtime/ms-rest-azure/test/data/TestClient/lib/models/index.js
  runtime/ms-rest-azure/test/data/TestClient/lib/testClient.js
  runtime/ms-rest-azure/test/testlist.txt
Labels: in progress

#2736 [AutoPR] resourcehealth/resource-manager
  lib/services/resourceHealthManagement/LICENSE.txt
  lib/services/resourceHealthManagement/README.md
  lib/services/resourceHealthManagement/lib/microsoftResourceHealth.d.ts
  lib/services/resourceHealthManagement/lib/microsoftResourceHealth.js
  lib/services/resourceHealthManagement/lib/models/index.d.ts
  lib/services/resourceHealthManagement/lib/models/operation.js
  lib/services/resourceHealthManagement/lib/models/operationDisplay.js
  lib/services/resourceHealthManagement/package-lock.json
  lib/services/resourceHealthManagement/package.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#3327 [AutoPR sql/resource-manager] [DO NOT MERGE]
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/sensitivityLabels.js
Labels: RestPRMerged, in progress

#3351 [AutoPR network/resource-manager] Fix name from ServiceEndpointDefinition to ServiceEndpointDefinitions…
  lib/services/networkManagement2/lib/operations/serviceEndpointPolicyDefinitions.js
Labels: RestPRMerged, in progress

#3356 [AutoPR network/resource-manager] Removed QueryConnectionMonitors API
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/networkWatchers.js
Labels: RestPRMerged, in progress

#3357 [AutoPR network/resource-manager] Removed QueryConnectionMOnitors API
  lib/services/networkManagement2/lib/models/backendAddressPool.js
  lib/services/networkManagement2/lib/models/frontendIPConfiguration.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/loadBalancer.js
  lib/services/networkManagement2/lib/models/outboundRule.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/loadBalancers.js
  lib/services/networkManagement2/lib/operations/networkWatchers.js
Labels: RestPRMerged

#3345 [AutoPR batch/resource-manager] Adding suppressions for Microsoft.Batch RP API
  lib/services/batchManagement/lib/batchManagementClient.d.ts
  lib/services/batchManagement/lib/batchManagementClient.js
  lib/services/batchManagement/lib/models/batchAccount.js
  lib/services/batchManagement/lib/models/certificate.js
  lib/services/batchManagement/lib/models/certificateBaseProperties.js
  lib/services/batchManagement/lib/models/certificateCreateOrUpdateParameters.js
  lib/services/batchManagement/package.json
Labels: RestPRMerged, in progress

#2809 [AutoPR] batchai/resource-manager
  lib/services/batchaiManagement/LICENSE.txt
  lib/services/batchaiManagement/README.md
  lib/services/batchaiManagement/lib/batchAIManagementClient.d.ts
  lib/services/batchaiManagement/lib/batchAIManagementClient.js
  lib/services/batchaiManagement/lib/models/appInsightsReference.js
  lib/services/batchaiManagement/lib/models/autoScaleSettings.js
  lib/services/batchaiManagement/lib/models/azureBlobFileSystemReference.js
  lib/services/batchaiManagement/lib/models/azureFileShareReference.js
  lib/services/batchaiManagement/lib/models/azureStorageCredentialsInfo.js
  lib/services/batchaiManagement/lib/models/batchAIError.js
  lib/services/batchaiManagement/lib/models/cluster.js
  lib/services/batchaiManagement/lib/models/clusterCreateParameters.js
  lib/services/batchaiManagement/lib/models/clusterUpdateParameters.js
  lib/services/batchaiManagement/lib/models/clustersListByResourceGroupOptions.js
  lib/services/batchaiManagement/lib/models/containerSettings.js
  lib/services/batchaiManagement/lib/models/environmentVariableWithSecretValue.js
  lib/services/batchaiManagement/lib/models/experiment.js
  lib/services/batchaiManagement/lib/models/fileServer.js
  lib/services/batchaiManagement/lib/models/fileServerCreateParameters.js
  lib/services/batchaiManagement/lib/models/fileServerReference.js
  lib/services/batchaiManagement/lib/models/fileServersListByResourceGroupOptions.js
  lib/services/batchaiManagement/lib/models/imageSourceRegistry.js
  lib/services/batchaiManagement/lib/models/index.d.ts
  lib/services/batchaiManagement/lib/models/job.js
  lib/services/batchaiManagement/lib/models/jobBasePropertiesConstraints.js
  lib/services/batchaiManagement/lib/models/jobCreateParameters.js
  lib/services/batchaiManagement/lib/models/jobPropertiesConstraints.js
  lib/services/batchaiManagement/lib/models/jobPropertiesExecutionInfo.js
  lib/services/batchaiManagement/lib/models/keyVaultSecretReference.js
  lib/services/batchaiManagement/lib/models/mountVolumes.js
  lib/services/batchaiManagement/lib/models/nodeSetup.js
  lib/services/batchaiManagement/lib/models/operation.js
  lib/services/batchaiManagement/lib/models/performanceCountersSettings.js
  lib/services/batchaiManagement/lib/models/privateRegistryCredentials.js
  lib/services/batchaiManagement/lib/models/scaleSettings.js
  lib/services/batchaiManagement/lib/models/setupTask.js
  lib/services/batchaiManagement/lib/models/sshConfiguration.js
  lib/services/batchaiManagement/lib/models/usage.js
  lib/services/batchaiManagement/lib/models/virtualMachineConfiguration.js
  lib/services/batchaiManagement/lib/models/workspace.js
  lib/services/batchaiManagement/lib/operations/jobs.js
  lib/services/batchaiManagement/package-lock.json
  lib/services/batchaiManagement/package.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#2983 [AutoPR] authorization/resource-manager
  lib/services/authorizationManagement/LICENSE.txt
  lib/services/authorizationManagement/README.md
  lib/services/authorizationManagement/lib/authorizationManagementClient.d.ts
  lib/services/authorizationManagement/lib/authorizationManagementClient.js
  lib/services/authorizationManagement/lib/models/providerOperationsMetadata.js
  lib/services/authorizationManagement/lib/models/resourceType.js
  lib/services/authorizationManagement/lib/models/roleDefinition.js
  lib/services/authorizationManagement/package-lock.json
  lib/services/authorizationManagement/package.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#2985 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/LICENSE.txt
  lib/services/storagesyncManagement/README.md
  lib/services/storagesyncManagement/lib/models/backupRequest.js
  lib/services/storagesyncManagement/lib/models/checkNameAvailabilityParameters.js
  lib/services/storagesyncManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/storagesyncManagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncManagement/lib/models/cloudEndpointArray.js
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/operationDisplayInfo.js
  lib/services/storagesyncManagement/lib/models/operationDisplayResource.js
  lib/services/storagesyncManagement/lib/models/operationEntity.js
  lib/services/storagesyncManagement/lib/models/operationEntityListResult.js
  lib/services/storagesyncManagement/lib/models/postBackupResponse.js
  lib/services/storagesyncManagement/lib/models/postRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/preRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/lib/models/registeredServerArray.js
  lib/services/storagesyncManagement/lib/models/resource.js
  lib/services/storagesyncManagement/lib/models/resourcesMoveInfo.js
  lib/services/storagesyncManagement/lib/models/restoreFileSpec.js
  lib/services/storagesyncManagement/lib/models/serverEndpoint.js
  lib/services/storagesyncManagement/lib/models/serverEndpointArray.js
  lib/services/storagesyncManagement/lib/models/storageSyncError.js
  lib/services/storagesyncManagement/lib/models/storageSyncErrorDetails.js
  lib/services/storagesyncManagement/lib/models/storageSyncService.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceArray.js
  lib/services/storagesyncManagement/lib/models/subscriptionState.js
  lib/services/storagesyncManagement/lib/models/syncGroup.js
  lib/services/storagesyncManagement/lib/models/syncGroupArray.js
  lib/services/storagesyncManagement/lib/models/trackedResource.js
  lib/services/storagesyncManagement/lib/models/workflow.js
  lib/services/storagesyncManagement/lib/models/workflowArray.js
  lib/services/storagesyncManagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/index.js
  lib/services/storagesyncManagement/lib/operations/operations.js
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncManagement/lib/operations/syncGroups.js
  lib/services/storagesyncManagement/lib/operations/workflows.js
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.d.ts
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
  lib/services/storagesyncManagement/package-lock.json
  lib/services/storagesyncManagement/package.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#3266 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/lib/models/encryption.js
  lib/services/storageManagement2/lib/models/encryptionServices.js
  lib/services/storageManagement2/lib/models/immutabilityPolicyProperties.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/legalHoldProperties.js
  lib/services/storageManagement2/lib/models/listContainerItems.js
  lib/services/storageManagement2/lib/models/metricSpecification.js
  lib/services/storageManagement2/lib/models/networkRuleSet.js
  lib/services/storageManagement2/lib/models/operation.js
  lib/services/storageManagement2/lib/models/operationDisplay.js
  lib/services/storageManagement2/lib/models/serviceSasParameters.js
  lib/services/storageManagement2/lib/models/serviceSpecification.js
  lib/services/storageManagement2/lib/models/sku.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountListKeysResult.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/models/usage.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/package-lock.json
Labels: Planned-Sprint-122, ServicePR, Started-Sprint-122, in progress

#3354 [AutoPR batch/data-plane] New Batch data plane API version 2018-08-01.7.0
  lib/services/batch/lib/batchServiceClient.d.ts
  lib/services/batch/lib/batchServiceClient.js
  lib/services/batch/lib/models/accountListPoolNodeCountsOptions.js
  lib/services/batch/lib/models/autoPoolSpecification.js
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudJobSchedule.js
  lib/services/batch/lib/models/cloudPool.js
  lib/services/batch/lib/models/computeNode.js
  lib/services/batch/lib/models/containerConfiguration.js
  lib/services/batch/lib/models/dataDisk.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/index.js
  lib/services/batch/lib/models/jobAddParameter.js
  lib/services/batch/lib/models/jobPatchParameter.js
  lib/services/batch/lib/models/jobScheduleAddParameter.js
  lib/services/batch/lib/models/jobSchedulePatchParameter.js
  lib/services/batch/lib/models/jobScheduleUpdateParameter.js
  lib/services/batch/lib/models/jobSpecification.js
  lib/services/batch/lib/models/jobUpdateParameter.js
  lib/services/batch/lib/models/nodeAgentInformation.js
  lib/services/batch/lib/models/oSDisk.js
  lib/services/batch/lib/models/poolAddParameter.js
  lib/services/batch/lib/models/poolInformation.js
  lib/services/batch/lib/models/poolSpecification.js
  lib/services/batch/lib/models/poolUsageMetrics.js
  lib/services/batch/lib/models/taskAddCollectionParameter.js
  lib/services/batch/lib/models/taskCounts.js
  lib/services/batch/lib/models/virtualMachineConfiguration.js
  lib/services/batch/lib/operations/account.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
  lib/services/batch/lib/operations/task.js
Labels: RestPRMerged, in progress

#3381 Regenerate azure-arm-storage
  lib/services/storageManagement2/LICENSE.txt
  lib/services/storageManagement2/package-lock.json
  lib/services/storageManagement2/package.json
Labels: Planned-Sprint-122, Started-Sprint-122, in progress

#3339 [AutoPR compute/resource-manager] [Compute] add zone and rolling upgrade.
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/accessUri.js
  lib/services/computeManagement2/package.json
Labels: RestPRMerged, in progress

#3388 Remove extra autosuggest folder
  lib/services/autosuggest/LICENSE.txt
  lib/services/autosuggest/lib/autoSuggestAPIClient.d.ts
  lib/services/autosuggest/lib/autoSuggestAPIClient.js
  lib/services/autosuggest/lib/models/action.js
  lib/services/autosuggest/lib/models/answer.js
  lib/services/autosuggest/lib/models/autoSuggest.js
  lib/services/autosuggest/lib/models/creativeWork.js
  lib/services/autosuggest/lib/models/errorModel.js
  lib/services/autosuggest/lib/models/errorResponse.js
  lib/services/autosuggest/lib/models/identifiable.js
  lib/services/autosuggest/lib/models/index.d.ts
  lib/services/autosuggest/lib/models/index.js
  lib/services/autosuggest/lib/models/queryContext.js
  lib/services/autosuggest/lib/models/response.js
  lib/services/autosuggest/lib/models/responseBase.js
  lib/services/autosuggest/lib/models/searchAction.js
  lib/services/autosuggest/lib/models/searchResultsAnswer.js
  lib/services/autosuggest/lib/models/suggestions.js
  lib/services/autosuggest/lib/models/suggestionsSuggestionGroup.js
  lib/services/autosuggest/lib/models/thing.js
  lib/services/autosuggest/package.json
Labels: Planned-Sprint-123, Started-Sprint-123, in progress

#3281 [AutoPR graphrbac/data-plane] Added OAuth2 GET and POST to GraphRBAC.json spec
  lib/services/graphManagement/LICENSE.txt
  lib/services/graphManagement/lib/graphRbacManagementClient.d.ts
  lib/services/graphManagement/lib/graphRbacManagementClient.js
  lib/services/graphManagement/lib/models/index.d.ts
  lib/services/graphManagement/lib/models/index.js
  lib/services/graphManagement/lib/models/oAuth2.js
  lib/services/graphManagement/lib/models/permissions.js
  lib/services/graphManagement/lib/operations/index.d.ts
  lib/services/graphManagement/lib/operations/index.js
  lib/services/graphManagement/lib/operations/oAuth2.js
  lib/services/graphManagement/lib/operations/oAuth2Operations.js
  lib/services/graphManagement/lib/operations/servicePrincipals.js
  lib/services/graphManagement/package.json
Labels: RestPRMerged, in progress

#3360 [AutoPR datafactory/resource-manager] Add two API-s to integration runtime
  lib/services/datafactoryManagement/lib/models/createLinkedIntegrationRuntimeRequest.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/selfHostedIntegrationRuntimeNode.js
  lib/services/datafactoryManagement/lib/models/selfHostedIntegrationRuntimeStatus.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/integrationRuntimeNodes.js
  lib/services/datafactoryManagement/lib/operations/integrationRuntimes.js
  lib/services/datafactoryManagement/package.json
Labels: RestPRMerged, in progress

#3026 [AutoPR] operationalinsights/data-plane
  lib/services/loganalytics/lib/models/errorInfo.js
  lib/services/loganalytics/lib/models/errorResponse.js
  lib/services/loganalytics/lib/models/queryResults.js
  lib/services/loganalytics/lib/models/table.js
  lib/services/loganalytics/package-lock.json
  lib/services/loganalytics/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3340 [AutoPR mysql/resource-manager] Add serverSecurityAlertPolicies APIs for MySQL servers
  lib/services/mysqlManagement/LICENSE.txt
  lib/services/mysqlManagement/lib/models/index.d.ts
  lib/services/mysqlManagement/lib/models/index.js
  lib/services/mysqlManagement/lib/models/serverSecurityAlertPolicy.js
  lib/services/mysqlManagement/lib/mySQLManagementClient.d.ts
  lib/services/mysqlManagement/lib/mySQLManagementClient.js
  lib/services/mysqlManagement/lib/operations/index.d.ts
  lib/services/mysqlManagement/lib/operations/index.js
  lib/services/mysqlManagement/lib/operations/serverSecurityAlertPolicies.js
  lib/services/mysqlManagement/package.json
Labels: RestPRMerged, in progress

#3400 [AutoPR batch/data-plane] Update Batch docs
  lib/services/batch/lib/models/autoPoolSpecification.js
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudJobSchedule.js
  lib/services/batch/lib/models/cloudPool.js
  lib/services/batch/lib/models/cloudServiceConfiguration.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/jobAddParameter.js
  lib/services/batch/lib/models/jobPatchParameter.js
  lib/services/batch/lib/models/jobScheduleAddParameter.js
  lib/services/batch/lib/models/jobSchedulePatchParameter.js
  lib/services/batch/lib/models/jobScheduleUpdateParameter.js
  lib/services/batch/lib/models/jobSpecification.js
  lib/services/batch/lib/models/jobUpdateParameter.js
  lib/services/batch/lib/models/poolAddParameter.js
  lib/services/batch/lib/models/poolInformation.js
  lib/services/batch/lib/models/poolSpecification.js
  lib/services/batch/lib/models/userAccount.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
Labels: RestPRMerged, in progress

#3329 [AutoPR cdn/resource-manager] adding standard_microsoft in pricing tier
  lib/services/cdnManagement/LICENSE.txt
  lib/services/cdnManagement/lib/cdnManagementClient.d.ts
  lib/services/cdnManagement/lib/cdnManagementClient.js
  lib/services/cdnManagement/lib/models/cacheExpirationActionParameters.js
  lib/services/cdnManagement/lib/models/index.d.ts
  lib/services/cdnManagement/lib/models/profile.js
  lib/services/cdnManagement/lib/models/sku.js
  lib/services/cdnManagement/lib/models/supportedOptimizationTypesListResult.js
  lib/services/cdnManagement/lib/operations/index.d.ts
  lib/services/cdnManagement/lib/operations/profiles.js
  lib/services/cdnManagement/package.json
Labels: RestPRMerged, in progress

#3406 [AutoPR] resources/resource-manager
  lib/services/resourceManagement/LICENSE.txt
  lib/services/resourceManagement/lib/policy/models/identity.js
  lib/services/resourceManagement/lib/policy/models/index.d.ts
  lib/services/resourceManagement/lib/policy/models/index.js
  lib/services/resourceManagement/lib/policy/models/policyAssignment.js
  lib/services/resourceManagement/lib/policy/operations/index.d.ts
  lib/services/resourceManagement/lib/policy/operations/policyAssignments.js
  lib/services/resourceManagement/lib/policy/policyClient.js
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3404 [AutoPR compute/resource-manager] [Compute] Update default generation version for compute and runcommand
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/linuxConfiguration.js
  lib/services/computeManagement2/lib/models/oSProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineIdentity.js
  lib/services/computeManagement2/lib/models/virtualMachineIdentityUserAssignedIdentitiesValue.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetIPConfiguration.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetIdentity.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetIdentityUserAssignedIdentitiesValue.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetPublicIPAddressConfiguration.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateIPConfiguration.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateOSProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/availabilitySets.js
  lib/services/computeManagement2/lib/operations/images.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/logAnalytics.js
  lib/services/computeManagement2/lib/operations/operations.js
  lib/services/computeManagement2/lib/operations/usageOperations.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensionImages.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachineImages.js
  lib/services/computeManagement2/lib/operations/virtualMachineRunCommands.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetRollingUpgrades.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachineSizes.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#3415 [AutoPR network/resource-manager] Added AddressPrefixes on Subnet properties
  lib/services/networkManagement2/lib/models/applicationGatewayBackendHealthServer.js
  lib/services/networkManagement2/lib/models/frontendIPConfiguration.js
  lib/services/networkManagement2/lib/models/iPConfiguration.js
  lib/services/networkManagement2/lib/models/inboundNatRule.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/networkInterfaceIPConfiguration.js
  lib/services/networkManagement2/lib/models/publicIPAddress.js
  lib/services/networkManagement2/lib/models/subnet.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/subnets.js
Labels: RestPRMerged, in progress

#3399 [AutoPR] mysql/resource-manager
  lib/services/mysqlManagement/LICENSE.txt
  lib/services/mysqlManagement/lib/models/index.d.ts
  lib/services/mysqlManagement/lib/models/index.js
  lib/services/mysqlManagement/lib/models/operation.js
  lib/services/mysqlManagement/lib/models/operationListResult.js
  lib/services/mysqlManagement/lib/models/performanceTierProperties.js
  lib/services/mysqlManagement/lib/models/serverForCreate.js
  lib/services/mysqlManagement/lib/models/serverPropertiesForCreate.js
  lib/services/mysqlManagement/lib/models/serverSecurityAlertPolicy.js
  lib/services/mysqlManagement/lib/models/serverUpdateParameters.js
  lib/services/mysqlManagement/lib/mySQLManagementClient.d.ts
  lib/services/mysqlManagement/lib/mySQLManagementClient.js
  lib/services/mysqlManagement/lib/operations/index.d.ts
  lib/services/mysqlManagement/lib/operations/index.js
  lib/services/mysqlManagement/lib/operations/serverSecurityAlertPolicies.js
  lib/services/mysqlManagement/package-lock.json
  lib/services/mysqlManagement/package.json
Labels: Planned-Sprint-123, ServicePR, Started-Sprint-123, in progress

#3396 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/activity.js
  lib/services/datafactoryManagement/lib/models/activityRunsQueryResponse.js
  lib/services/datafactoryManagement/lib/models/azureMLWebServiceFile.js
  lib/services/datafactoryManagement/lib/models/createLinkedIntegrationRuntimeRequest.js
  lib/services/datafactoryManagement/lib/models/customActivityReferenceObject.js
  lib/services/datafactoryManagement/lib/models/dataset.js
  lib/services/datafactoryManagement/lib/models/factoryRepoUpdate.js
  lib/services/datafactoryManagement/lib/models/factoryUpdateParameters.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeComputeProperties.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeCustomSetupScriptProperties.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeMonitoringData.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeSsisCatalogInfo.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeSsisProperties.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeStatusListResponse.js
  lib/services/datafactoryManagement/lib/models/integrationRuntimeStatusResponse.js
  lib/services/datafactoryManagement/lib/models/linkedService.js
  lib/services/datafactoryManagement/lib/models/managedIntegrationRuntimeNode.js
  lib/services/datafactoryManagement/lib/models/operation.js
  lib/services/datafactoryManagement/lib/models/operationMetricSpecification.js
  lib/services/datafactoryManagement/lib/models/operationServiceSpecification.js
  lib/services/datafactoryManagement/lib/models/pipelineRun.js
  lib/services/datafactoryManagement/lib/models/pipelineRunsQueryResponse.js
  lib/services/datafactoryManagement/lib/models/recurrenceSchedule.js
  lib/services/datafactoryManagement/lib/models/redshiftUnloadSettings.js
  lib/services/datafactoryManagement/lib/models/runFilterParameters.js
  lib/services/datafactoryManagement/lib/models/scheduleTriggerRecurrence.js
  lib/services/datafactoryManagement/lib/models/selfHostedIntegrationRuntimeNode.js
  lib/services/datafactoryManagement/lib/models/selfHostedIntegrationRuntimeStatus.js
  lib/services/datafactoryManagement/lib/models/stagingSettings.js
  lib/services/datafactoryManagement/lib/models/triggerPipelineReference.js
  lib/services/datafactoryManagement/lib/models/triggerRunsQueryResponse.js
  lib/services/datafactoryManagement/lib/models/webActivityAuthentication.js
  lib/services/datafactoryManagement/lib/operations/index.d.ts
  lib/services/datafactoryManagement/lib/operations/integrationRuntimeNodes.js
  lib/services/datafactoryManagement/lib/operations/integrationRuntimes.js
  lib/services/datafactoryManagement/package-lock.json
  lib/services/datafactoryManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3420 [AutoPR compute/resource-manager] RDBug 13056055 - Update description to deprecated.
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineSizes.js
Labels: RestPRMerged, in progress

#3395 [AutoPR] graphrbac/data-plane
  lib/services/graphManagement/LICENSE.txt
  lib/services/graphManagement/lib/graphRbacManagementClient.d.ts
  lib/services/graphManagement/lib/graphRbacManagementClient.js
  lib/services/graphManagement/lib/models/applicationCreateParameters.js
  lib/services/graphManagement/lib/models/applicationUpdateParameters.js
  lib/services/graphManagement/lib/models/index.d.ts
  lib/services/graphManagement/lib/models/index.js
  lib/services/graphManagement/lib/models/keyCredentialsUpdateParameters.js
  lib/services/graphManagement/lib/models/oAuth2.js
  lib/services/graphManagement/lib/models/passwordCredentialsUpdateParameters.js
  lib/services/graphManagement/lib/models/permissions.js
  lib/services/graphManagement/lib/models/requiredResourceAccess.js
  lib/services/graphManagement/lib/models/servicePrincipalCreateParameters.js
  lib/services/graphManagement/lib/operations/index.d.ts
  lib/services/graphManagement/lib/operations/index.js
  lib/services/graphManagement/lib/operations/oAuth2.js
  lib/services/graphManagement/lib/operations/oAuth2Operations.js
  lib/services/graphManagement/lib/operations/servicePrincipals.js
  lib/services/graphManagement/package-lock.json
  lib/services/graphManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3358 [AutoPR] batch/resource-manager
  lib/services/batchManagement/lib/batchManagementClient.d.ts
  lib/services/batchManagement/lib/batchManagementClient.js
  lib/services/batchManagement/lib/models/batchAccount.js
  lib/services/batchManagement/lib/models/certificate.js
  lib/services/batchManagement/lib/models/certificateBaseProperties.js
  lib/services/batchManagement/lib/models/certificateCreateOrUpdateParameters.js
  lib/services/batchManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3429 Restapi auto batch/resource manager
  lib/services/batchManagement/lib/models/application.js
  lib/services/batchManagement/lib/models/autoScaleRun.js
  lib/services/batchManagement/lib/models/autoScaleRunError.js
  lib/services/batchManagement/lib/models/batchAccountCreateParameters.js
  lib/services/batchManagement/lib/models/batchAccountUpdateParameters.js
  lib/services/batchManagement/lib/models/deleteCertificateError.js
  lib/services/batchManagement/lib/models/deploymentConfiguration.js
  lib/services/batchManagement/lib/models/inboundNatPool.js
  lib/services/batchManagement/lib/models/networkConfiguration.js
  lib/services/batchManagement/lib/models/operation.js
  lib/services/batchManagement/lib/models/poolEndpointConfiguration.js
  lib/services/batchManagement/lib/models/resizeError.js
  lib/services/batchManagement/lib/models/resizeOperationStatus.js
  lib/services/batchManagement/lib/models/scaleSettings.js
  lib/services/batchManagement/lib/models/startTask.js
  lib/services/batchManagement/lib/models/userAccount.js
  lib/services/batchManagement/lib/models/userIdentity.js
  lib/services/batchManagement/lib/models/virtualMachineConfiguration.js
  lib/services/batchManagement/package-lock.json
  lib/services/batchManagement/package.json
Labels: in progress

#3424 [AutoPR network/resource-manager] Changes to include required properties for outbound rule
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/outboundRule.js
Labels: RestPRMerged, in progress

#3421 [AutoPR storagesync/resource-manager] Remove TrackedResource from Swagger spec in Microsoft.StorageSync Resource Provider
  lib/services/storagesyncManagement/LICENSE.txt
  lib/services/storagesyncManagement/README.md
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/operationEntity.js
  lib/services/storagesyncManagement/lib/models/postRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/preRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/serverEndpointUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncError.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/trackedResource.js
  lib/services/storagesyncManagement/lib/models/workflowArray.js
  lib/services/storagesyncManagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/operations.js
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncManagement/lib/operations/syncGroups.js
  lib/services/storagesyncManagement/lib/operations/workflows.js
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.d.ts
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
  lib/services/storagesyncManagement/package.json
Labels: RestPRMerged, in progress

#3434 [AutoPR iothub/resource-manager] IoTHub conf py
  lib/services/iothub/package.json
Labels: RestPRMerged

#3435 [AutoPR] iothub/resource-manager
  lib/services/iothub/lib/models/certificateListDescription.js
  lib/services/iothub/lib/models/cloudToDeviceProperties.js
  lib/services/iothub/lib/models/iotHubProperties.js
  lib/services/iothub/lib/models/iotHubSkuDescription.js
  lib/services/iothub/lib/models/matchedRoute.js
  lib/services/iothub/lib/models/operation.js
  lib/services/iothub/lib/models/routeCompilationError.js
  lib/services/iothub/lib/models/routeErrorRange.js
  lib/services/iothub/lib/models/routingEndpoints.js
  lib/services/iothub/lib/models/routingProperties.js
  lib/services/iothub/lib/models/testAllRoutesInput.js
  lib/services/iothub/lib/models/testAllRoutesResult.js
  lib/services/iothub/lib/models/testRouteInput.js
  lib/services/iothub/lib/models/testRouteResult.js
  lib/services/iothub/lib/models/testRouteResultDetails.js
  lib/services/iothub/lib/models/userSubscriptionQuota.js
  lib/services/iothub/lib/models/userSubscriptionQuotaListResult.js
  lib/services/iothub/package-lock.json
  lib/services/iothub/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3385 [AutoPR visualstudio/resource-manager] Support for pipeline templates in microsoft.visualstudio RP
  lib/services/visualstudioManagement/LICENSE.txt
  lib/services/visualstudioManagement/README.md
  lib/services/visualstudioManagement/lib/visualStudioResourceProviderClient.d.ts
  lib/services/visualstudioManagement/lib/visualStudioResourceProviderClient.js
  lib/services/visualstudioManagement/package.json
Labels: RestPRMerged, in progress

#3443 [AutoPR] visualstudio/resource-manager
  lib/services/visualstudioManagement/LICENSE.txt
  lib/services/visualstudioManagement/README.md
  lib/services/visualstudioManagement/lib/models/accountResourceListResult.js
  lib/services/visualstudioManagement/lib/models/extensionResourceListResult.js
  lib/services/visualstudioManagement/lib/models/extensionResourceRequest.js
  lib/services/visualstudioManagement/lib/models/operation.js
  lib/services/visualstudioManagement/lib/models/operationListResult.js
  lib/services/visualstudioManagement/lib/models/projectResourceListResult.js
  lib/services/visualstudioManagement/lib/visualStudioResourceProviderClient.d.ts
  lib/services/visualstudioManagement/lib/visualStudioResourceProviderClient.js
  lib/services/visualstudioManagement/package-lock.json
  lib/services/visualstudioManagement/package.json
Labels: ServicePR, Unplanned-Sprint-123, in progress

#3432 [AutoPR] storagesync/resource-manager
  lib/services/storagesyncManagement/LICENSE.txt
  lib/services/storagesyncManagement/README.md
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/serverEndpointUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/storageSyncServiceUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/trackedResource.js
  lib/services/storagesyncManagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/operations.js
  lib/services/storagesyncManagement/lib/operations/registeredServers.js
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncManagement/lib/operations/syncGroups.js
  lib/services/storagesyncManagement/lib/operations/workflows.js
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.d.ts
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
  lib/services/storagesyncManagement/package-lock.json
  lib/services/storagesyncManagement/package.json
Labels: ServicePR, Unplanned-Sprint-123, in progress

#3293 [AutoPR] sql/resource-manager
  lib/services/sqlManagement2/lib/models/databaseUpdate.js
  lib/services/sqlManagement2/lib/models/databaseVulnerabilityAssessment.js
  lib/services/sqlManagement2/lib/models/editionCapability.js
  lib/services/sqlManagement2/lib/models/elasticPoolEditionCapability.js
  lib/services/sqlManagement2/lib/models/elasticPoolPerDatabaseMaxPerformanceLevelCapability.js
  lib/services/sqlManagement2/lib/models/elasticPoolPerformanceLevelCapability.js
  lib/services/sqlManagement2/lib/models/elasticPoolUpdate.js
  lib/services/sqlManagement2/lib/models/failoverGroupUpdate.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/locationCapabilities.js
  lib/services/sqlManagement2/lib/models/managedInstanceEditionCapability.js
  lib/services/sqlManagement2/lib/models/managedInstanceFamilyCapability.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/models/managedInstanceVersionCapability.js
  lib/services/sqlManagement2/lib/models/maxSizeRangeCapability.js
  lib/services/sqlManagement2/lib/models/metric.js
  lib/services/sqlManagement2/lib/models/metricDefinition.js
  lib/services/sqlManagement2/lib/models/operation.js
  lib/services/sqlManagement2/lib/models/serverVersionCapability.js
  lib/services/sqlManagement2/lib/models/serviceObjectiveCapability.js
  lib/services/sqlManagement2/lib/models/syncFullSchemaProperties.js
  lib/services/sqlManagement2/lib/models/syncFullSchemaTable.js
  lib/services/sqlManagement2/lib/models/syncGroupSchema.js
  lib/services/sqlManagement2/lib/models/syncGroupSchemaTable.js
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessments.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/sensitivityLabels.js
  lib/services/sqlManagement2/package-lock.json
  lib/services/sqlManagement2/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3446 [AutoPR automation/resource-manager] Fixing the spec for DSCConfigurations.
  lib/services/automationManagement/lib/operations/dscConfigurationOperations.js
  lib/services/automationManagement/lib/operations/index.d.ts
Labels: RestPRMerged

#3451 [AutoPR storagesync/resource-manager] Change ApiVersion in examples. Change csharp output folder
  lib/services/storagesyncManagement/lib/models/operationEntity.js
  lib/services/storagesyncManagement/lib/models/postRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/preRestoreRequest.js
  lib/services/storagesyncManagement/lib/models/storageSyncError.js
  lib/services/storagesyncManagement/lib/models/workflowArray.js
  lib/services/storagesyncManagement/package.json
Labels: RestPRMerged, in progress

#3046 [AutoPR] mediaservices/resource-manager
  lib/services/mediaServicesManagement/lib/azureMediaServices.d.ts
  lib/services/mediaServicesManagement/lib/azureMediaServices.js
  lib/services/mediaServicesManagement/lib/models/akamaiAccessControl.js
  lib/services/mediaServicesManagement/lib/models/apiError.js
  lib/services/mediaServicesManagement/lib/models/asset.js
  lib/services/mediaServicesManagement/lib/models/cbcsDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/cencDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCbcs.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCenc.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicy.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyOption.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyPlayReadyLicense.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyPlayReadyPlayRight.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyProperties.js
  lib/services/mediaServicesManagement/lib/models/envelopeEncryption.js
  lib/services/mediaServicesManagement/lib/models/filters.js
  lib/services/mediaServicesManagement/lib/models/iPAccessControl.js
  lib/services/mediaServicesManagement/lib/models/job.js
  lib/services/mediaServicesManagement/lib/models/jobError.js
  lib/services/mediaServicesManagement/lib/models/jobOutput.js
  lib/services/mediaServicesManagement/lib/models/jobOutputAsset.js
  lib/services/mediaServicesManagement/lib/models/listContentKeysResponse.js
  lib/services/mediaServicesManagement/lib/models/listPathsResponse.js
  lib/services/mediaServicesManagement/lib/models/liveEventInput.js
  lib/services/mediaServicesManagement/lib/models/liveEventPreview.js
  lib/services/mediaServicesManagement/lib/models/liveEventPreviewAccessControl.js
  lib/services/mediaServicesManagement/lib/models/mediaService.js
  lib/services/mediaServicesManagement/lib/models/noEncryption.js
  lib/services/mediaServicesManagement/lib/models/oDataError.js
  lib/services/mediaServicesManagement/lib/models/operation.js
  lib/services/mediaServicesManagement/lib/models/streamingEndpoint.js
  lib/services/mediaServicesManagement/lib/models/streamingEndpointAccessControl.js
  lib/services/mediaServicesManagement/lib/models/streamingLocator.js
  lib/services/mediaServicesManagement/lib/models/streamingLocatorContentKey.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicy.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyContentKey.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyContentKeys.js
  lib/services/mediaServicesManagement/lib/models/subscriptionMediaService.js
  lib/services/mediaServicesManagement/lib/models/trackSelection.js
  lib/services/mediaServicesManagement/lib/models/transform.js
  lib/services/mediaServicesManagement/lib/models/transformOutput.js
  lib/services/mediaServicesManagement/package-lock.json
  lib/services/mediaServicesManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3449 [AutoPR] datafactory/resource-manager
  lib/services/datafactoryManagement/lib/models/datasetFolder.js
  lib/services/datafactoryManagement/lib/models/pipelineFolder.js
  lib/services/datafactoryManagement/package-lock.json
  lib/services/datafactoryManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3457 Update azure-arm-website version to 5.0.0
  lib/services/websiteManagement2/package-lock.json
  lib/services/websiteManagement2/package.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3273 [AutoPR] containerinstance/resource-manager
  lib/services/containerinstanceManagement/lib/models/container.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/models/containerGroupDiagnostics.js
  lib/services/containerinstanceManagement/lib/models/containerGroupPropertiesInstanceView.js
  lib/services/containerinstanceManagement/lib/models/containerProbe.js
  lib/services/containerinstanceManagement/lib/models/containerPropertiesInstanceView.js
  lib/services/containerinstanceManagement/lib/models/ipAddress.js
  lib/services/containerinstanceManagement/lib/models/operation.js
  lib/services/containerinstanceManagement/lib/models/operationListResult.js
  lib/services/containerinstanceManagement/lib/models/resourceRequirements.js
  lib/services/containerinstanceManagement/lib/models/usage.js
  lib/services/containerinstanceManagement/lib/models/usageListResult.js
  lib/services/containerinstanceManagement/lib/models/volume.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/package-lock.json
  lib/services/containerinstanceManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3460 Revert azure-cognitiveservices-face README.md file
  lib/services/cognitiveServicesFace/README.md
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#3298 [AutoPR] monitor/resource-manager
  lib/services/monitorManagement/lib/models/activityLogAlertActionList.js
  lib/services/monitorManagement/lib/models/activityLogAlertAllOfCondition.js
  lib/services/monitorManagement/lib/models/alertRuleResourcePatch.js
  lib/services/monitorManagement/lib/models/autoscaleNotification.js
  lib/services/monitorManagement/lib/models/autoscaleProfile.js
  lib/services/monitorManagement/lib/models/autoscaleSettingResourcePatch.js
  lib/services/monitorManagement/lib/models/baselineMetadataValue.js
  lib/services/monitorManagement/lib/models/baselineResponse.js
  lib/services/monitorManagement/lib/models/calculateBaselineResponse.js
  lib/services/monitorManagement/lib/models/diagnosticSettingsCategoryResourceCollection.js
  lib/services/monitorManagement/lib/models/diagnosticSettingsResourceCollection.js
  lib/services/monitorManagement/lib/models/eventData.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/logProfileResourcePatch.js
  lib/services/monitorManagement/lib/models/logSettings.js
  lib/services/monitorManagement/lib/models/metadataValue.js
  lib/services/monitorManagement/lib/models/metric.js
  lib/services/monitorManagement/lib/models/metricAlertResourcePatch.js
  lib/services/monitorManagement/lib/models/metricAlertStatus.js
  lib/services/monitorManagement/lib/models/metricAlertStatusCollection.js
  lib/services/monitorManagement/lib/models/metricCriteria.js
  lib/services/monitorManagement/lib/models/metricDefinition.js
  lib/services/monitorManagement/lib/models/metricSettings.js
  lib/services/monitorManagement/lib/models/operation.js
  lib/services/monitorManagement/lib/models/operationListResult.js
  lib/services/monitorManagement/lib/models/recurrence.js
  lib/services/monitorManagement/lib/models/response.js
  lib/services/monitorManagement/lib/models/ruleCondition.js
  lib/services/monitorManagement/lib/models/scaleRule.js
  lib/services/monitorManagement/lib/models/timeSeriesElement.js
  lib/services/monitorManagement/lib/models/triggerCondition.js
  lib/services/monitorManagement/package-lock.json
  lib/services/monitorManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3304 [AutoPR] containerservices/resource-manager
  lib/services/containerservicesManagement/lib/models/containerServiceDiagnosticsProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceLinuxProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceServicePrincipalProfile.js
  lib/services/containerservicesManagement/lib/models/containerServiceSshConfiguration.js
  lib/services/containerservicesManagement/lib/models/credentialResult.js
  lib/services/containerservicesManagement/lib/models/credentialResults.js
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedClusterUpgradeProfile.js
  lib/services/containerservicesManagement/lib/models/orchestratorVersionProfile.js
  lib/services/containerservicesManagement/lib/models/orchestratorVersionProfileListResult.js
  lib/services/containerservicesManagement/package-lock.json
  lib/services/containerservicesManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3310 [AutoPR] apimanagement/resource-manager
  lib/services/apimanagement/lib/apiManagementClient.d.ts
  lib/services/apimanagement/lib/apiManagementClient.js
  lib/services/apimanagement/lib/models/additionalLocation.js
  lib/services/apimanagement/lib/models/apiCreateOrUpdateParameter.js
  lib/services/apimanagement/lib/models/apiEntityBaseContract.js
  lib/services/apimanagement/lib/models/apiManagementServiceBaseProperties.js
  lib/services/apimanagement/lib/models/apiManagementServiceUpdateHostnameParameters.js
  lib/services/apimanagement/lib/models/apiRevisionInfoContract.js
  lib/services/apimanagement/lib/models/apiUpdateContract.js
  lib/services/apimanagement/lib/models/authenticationSettingsContract.js
  lib/services/apimanagement/lib/models/authorizationServerContractBaseProperties.js
  lib/services/apimanagement/lib/models/backendBaseParameters.js
  lib/services/apimanagement/lib/models/backendCredentialsContract.js
  lib/services/apimanagement/lib/models/backendProperties.js
  lib/services/apimanagement/lib/models/backendServiceFabricClusterProperties.js
  lib/services/apimanagement/lib/models/backendUpdateParameters.js
  lib/services/apimanagement/lib/models/certificateConfiguration.js
  lib/services/apimanagement/lib/models/diagnosticContract.js
  lib/services/apimanagement/lib/models/emailTemplateUpdateParameters.js
  lib/services/apimanagement/lib/models/errorResponse.js
  lib/services/apimanagement/lib/models/errorResponseBody.js
  lib/services/apimanagement/lib/models/hostnameConfiguration.js
  lib/services/apimanagement/lib/models/hostnameConfigurationOld.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/index.js
  lib/services/apimanagement/lib/models/loggerContract.js
  lib/services/apimanagement/lib/models/networkStatusContract.js
  lib/services/apimanagement/lib/models/networkStatusContractByLocation.js
  lib/services/apimanagement/lib/models/operation.js
  lib/services/apimanagement/lib/models/operationEntityBaseContract.js
  lib/services/apimanagement/lib/models/operationResultContract.js
  lib/services/apimanagement/lib/models/operationUpdateContract.js
  lib/services/apimanagement/lib/models/policyCollection.js
  lib/services/apimanagement/lib/models/policySnippetsCollection.js
  lib/services/apimanagement/lib/models/productContract.js
  lib/services/apimanagement/lib/models/productEntityBaseParameters.js
  lib/services/apimanagement/lib/models/productUpdateParameters.js
  lib/services/apimanagement/lib/models/quotaCounterCollection.js
  lib/services/apimanagement/lib/models/quotaCounterContract.js
  lib/services/apimanagement/lib/models/recipientEmailCollection.js
  lib/services/apimanagement/lib/models/recipientUserCollection.js
  lib/services/apimanagement/lib/models/representationContract.js
  lib/services/apimanagement/lib/models/requestContract.js
  lib/services/apimanagement/lib/models/responseContract.js
  lib/services/apimanagement/lib/models/tagResourceContract.js
  lib/services/apimanagement/lib/models/userCreateParameters.js
  lib/services/apimanagement/lib/models/userEntityBaseParameters.js
  lib/services/apimanagement/lib/models/userUpdateParameters.js
  lib/services/apimanagement/lib/operations/apiDiagnostic.js
  lib/services/apimanagement/lib/operations/diagnostic.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/index.js
  lib/services/apimanagement/lib/operations/logger.js
  lib/services/apimanagement/lib/operations/product.js
  lib/services/apimanagement/package-lock.json
  lib/services/apimanagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3319 [AutoPR] consumption/resource-manager
  lib/services/consumptionManagement/lib/consumptionManagementClient.d.ts
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/errorResponse.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/index.js
  lib/services/consumptionManagement/lib/models/managementGroupAggregatedCostResult.js
  lib/services/consumptionManagement/lib/models/operation.js
  lib/services/consumptionManagement/lib/models/priceSheetProperties.js
  lib/services/consumptionManagement/lib/operations/aggregatedCost.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/index.js
  lib/services/consumptionManagement/lib/operations/usageDetails.js
  lib/services/consumptionManagement/package-lock.json
  lib/services/consumptionManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3439 [AutoPR network/resource-manager] Use only PublicIpAddress in Azure Firewall, not both Public and InternalPublic
  lib/services/networkManagement2/lib/models/azureFirewallIPConfiguration.js
  lib/services/networkManagement2/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#2829 [AutoPR] trafficmanager/resource-manager
  lib/services/trafficManagerManagement2/LICENSE.txt
  lib/services/trafficManagerManagement2/README.md
  lib/services/trafficManagerManagement2/lib/models/endpoint.js
  lib/services/trafficManagerManagement2/lib/models/endpointPropertiesCustomHeadersItem.js
  lib/services/trafficManagerManagement2/lib/models/endpointPropertiesSubnetsItem.js
  lib/services/trafficManagerManagement2/lib/models/index.d.ts
  lib/services/trafficManagerManagement2/lib/models/index.js
  lib/services/trafficManagerManagement2/lib/models/monitorConfig.js
  lib/services/trafficManagerManagement2/lib/models/monitorConfigCustomHeadersItem.js
  lib/services/trafficManagerManagement2/lib/models/monitorConfigExpectedStatusCodeRangesItem.js
  lib/services/trafficManagerManagement2/lib/models/profile.js
  lib/services/trafficManagerManagement2/lib/models/region.js
  lib/services/trafficManagerManagement2/lib/models/trafficFlow.js
  lib/services/trafficManagerManagement2/lib/models/userMetricsModel.js
  lib/services/trafficManagerManagement2/lib/operations/endpoints.js
  lib/services/trafficManagerManagement2/lib/operations/geographicHierarchies.js
  lib/services/trafficManagerManagement2/lib/operations/heatMap.js
  lib/services/trafficManagerManagement2/lib/operations/index.d.ts
  lib/services/trafficManagerManagement2/lib/operations/profiles.js
  lib/services/trafficManagerManagement2/lib/operations/trafficManagerUserMetricsKeys.js
  lib/services/trafficManagerManagement2/lib/trafficManagerManagementClient.d.ts
  lib/services/trafficManagerManagement2/lib/trafficManagerManagementClient.js
  lib/services/trafficManagerManagement2/package-lock.json
  lib/services/trafficManagerManagement2/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#2887 [AutoPR] cognitiveservices/data-plane/CustomWebSearch
  lib/services/cognitiveServicesCustomSearch/LICENSE.txt
  lib/services/cognitiveServicesCustomSearch/README.md
  lib/services/cognitiveServicesCustomSearch/lib/customSearchAPIClient.d.ts
  lib/services/cognitiveServicesCustomSearch/lib/customSearchAPIClient.js
  lib/services/cognitiveServicesCustomSearch/lib/models/answer.js
  lib/services/cognitiveServicesCustomSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesCustomSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesCustomSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesCustomSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesCustomSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesCustomSearch/lib/models/index.js
  lib/services/cognitiveServicesCustomSearch/lib/models/query.js
  lib/services/cognitiveServicesCustomSearch/lib/models/queryContext.js
  lib/services/cognitiveServicesCustomSearch/lib/models/response.js
  lib/services/cognitiveServicesCustomSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesCustomSearch/lib/models/searchResponse.js
  lib/services/cognitiveServicesCustomSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesCustomSearch/lib/models/thing.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webMetaTag.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webPage.js
  lib/services/cognitiveServicesCustomSearch/lib/models/webWebAnswer.js
  lib/services/cognitiveServicesCustomSearch/lib/operations/customInstance.js
  lib/services/cognitiveServicesCustomSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesCustomSearch/lib/operations/index.js
  lib/services/cognitiveServicesCustomSearch/package-lock.json
  lib/services/cognitiveServicesCustomSearch/package.json
  lib/services/customSearch/package.json
  test/services/cognitiveServicesSearch/customSearch-tests.js
  test/testlistarm.txt
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#2828 [AutoPR] cognitiveservices/data-plane/TextAnalytics
  lib/services/cognitiveServicesTextAnalytics/LICENSE.txt
  lib/services/cognitiveServicesTextAnalytics/README.md
  lib/services/cognitiveServicesTextAnalytics/lib/models/batchInput.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/detectedLanguage.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/entitiesBatchResult.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/entitiesBatchResultItem.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/entityRecord.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/errorRecord.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/errorResponse.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/index.d.ts
  lib/services/cognitiveServicesTextAnalytics/lib/models/index.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/input.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/internalError.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/keyPhraseBatchResult.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/keyPhraseBatchResultItem.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/languageBatchResult.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/languageBatchResultItem.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/matchRecord.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/multiLanguageBatchInput.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/multiLanguageInput.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/sentimentBatchResult.js
  lib/services/cognitiveServicesTextAnalytics/lib/models/sentimentBatchResultItem.js
  lib/services/cognitiveServicesTextAnalytics/lib/textAnalyticsClient.d.ts
  lib/services/cognitiveServicesTextAnalytics/lib/textAnalyticsClient.js
  lib/services/cognitiveServicesTextAnalytics/package-lock.json
  lib/services/cognitiveServicesTextAnalytics/package.json
  lib/services/textAnalytics/package.json
  test/services/cognitiveServicesLanguage/textAnalyticsAPIClient-tests.js
  test/testlistarm.txt
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#2696 [AutoPR] operationalinsights/resource-manager
  lib/services/operationalInsightsManagement/lib/models/operation.js
  lib/services/operationalInsightsManagement/lib/models/usageMetric.js
  lib/services/operationalInsightsManagement/lib/operationalInsightsManagementClient.d.ts
  lib/services/operationalInsightsManagement/lib/operationalInsightsManagementClient.js
  lib/services/operationalInsightsManagement/package-lock.json
  lib/services/operationalInsightsManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3467 Change swagger_to_sdk_config to use latest autorest.nodejs generator
  swagger_to_sdk_config.json
Labels: Started-Sprint-123, Unplanned-Sprint-123, in progress

#2827 [AutoPR] cognitiveservices/data-plane/WebSearch
  lib/services/cognitiveServicesWebSearch/LICENSE.txt
  lib/services/cognitiveServicesWebSearch/README.md
  lib/services/cognitiveServicesWebSearch/lib/models/answer.js
  lib/services/cognitiveServicesWebSearch/lib/models/article.js
  lib/services/cognitiveServicesWebSearch/lib/models/computation.js
  lib/services/cognitiveServicesWebSearch/lib/models/creativeWork.js
  lib/services/cognitiveServicesWebSearch/lib/models/errorModel.js
  lib/services/cognitiveServicesWebSearch/lib/models/errorResponse.js
  lib/services/cognitiveServicesWebSearch/lib/models/identifiable.js
  lib/services/cognitiveServicesWebSearch/lib/models/imageObject.js
  lib/services/cognitiveServicesWebSearch/lib/models/images.js
  lib/services/cognitiveServicesWebSearch/lib/models/index.d.ts
  lib/services/cognitiveServicesWebSearch/lib/models/index.js
  lib/services/cognitiveServicesWebSearch/lib/models/intangible.js
  lib/services/cognitiveServicesWebSearch/lib/models/mediaObject.js
  lib/services/cognitiveServicesWebSearch/lib/models/news.js
  lib/services/cognitiveServicesWebSearch/lib/models/newsArticle.js
  lib/services/cognitiveServicesWebSearch/lib/models/places.js
  lib/services/cognitiveServicesWebSearch/lib/models/query.js
  lib/services/cognitiveServicesWebSearch/lib/models/queryContext.js
  lib/services/cognitiveServicesWebSearch/lib/models/rankingRankingGroup.js
  lib/services/cognitiveServicesWebSearch/lib/models/rankingRankingItem.js
  lib/services/cognitiveServicesWebSearch/lib/models/rankingRankingResponse.js
  lib/services/cognitiveServicesWebSearch/lib/models/relatedSearchesRelatedSearchAnswer.js
  lib/services/cognitiveServicesWebSearch/lib/models/response.js
  lib/services/cognitiveServicesWebSearch/lib/models/responseBase.js
  lib/services/cognitiveServicesWebSearch/lib/models/searchResponse.js
  lib/services/cognitiveServicesWebSearch/lib/models/searchResultsAnswer.js
  lib/services/cognitiveServicesWebSearch/lib/models/spellSuggestions.js
  lib/services/cognitiveServicesWebSearch/lib/models/structuredValue.js
  lib/services/cognitiveServicesWebSearch/lib/models/thing.js
  lib/services/cognitiveServicesWebSearch/lib/models/timeZone.js
  lib/services/cognitiveServicesWebSearch/lib/models/timeZoneTimeZoneInformation.js
  lib/services/cognitiveServicesWebSearch/lib/models/videoObject.js
  lib/services/cognitiveServicesWebSearch/lib/models/videos.js
  lib/services/cognitiveServicesWebSearch/lib/models/webMetaTag.js
  lib/services/cognitiveServicesWebSearch/lib/models/webPage.js
  lib/services/cognitiveServicesWebSearch/lib/models/webWebAnswer.js
  lib/services/cognitiveServicesWebSearch/lib/models/webWebGrouping.js
  lib/services/cognitiveServicesWebSearch/lib/operations/index.d.ts
  lib/services/cognitiveServicesWebSearch/lib/operations/index.js
  lib/services/cognitiveServicesWebSearch/lib/operations/web.js
  lib/services/cognitiveServicesWebSearch/lib/webSearchAPIClient.d.ts
  lib/services/cognitiveServicesWebSearch/lib/webSearchAPIClient.js
  lib/services/cognitiveServicesWebSearch/package-lock.json
  lib/services/cognitiveServicesWebSearch/package.json
  test/services/cognitiveServicesSearch/webSearch-tests.js
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3175 [AutoPR] keyvault/resource-manager
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.d.ts
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.js
  lib/services/keyVaultManagement/lib/models/accessPolicyEntry.js
  lib/services/keyVaultManagement/lib/models/deletedVault.js
  lib/services/keyVaultManagement/lib/models/networkRuleSet.js
  lib/services/keyVaultManagement/lib/models/operation.js
  lib/services/keyVaultManagement/lib/models/permissions.js
  lib/services/keyVaultManagement/lib/models/serviceSpecification.js
  lib/services/keyVaultManagement/lib/models/vaultAccessPolicyProperties.js
  lib/services/keyVaultManagement/lib/models/vaultPatchProperties.js
  lib/services/keyVaultManagement/lib/models/vaultProperties.js
  lib/services/keyVaultManagement/package-lock.json
  lib/services/keyVaultManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress

#3472 [AutoPR] eventhub/resource-manager
  lib/services/eventHubManagement/LICENSE.txt
  lib/services/eventHubManagement/README.md
  lib/services/eventHubManagement/lib/models/captureDescription.js
  lib/services/eventHubManagement/lib/models/operation.js
  lib/services/eventHubManagement/package-lock.json
  lib/services/eventHubManagement/package.json
Labels: ServicePR, Started-Sprint-123, Unplanned-Sprint-123, in progress
