Repository Azure/azure-sdk-for-node, pull requests merged in 2018-06, with the labels that each got.

#2935 Regenerate mysql package and bump version to 3.0.0
  lib/services/mysqlManagement/lib/models/index.d.ts
  lib/services/mysqlManagement/lib/models/index.js
  lib/services/mysqlManagement/lib/models/virtualNetworkRule.js
  lib/services/mysqlManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/mysqlManagement/lib/mySQLManagementClient.d.ts
  lib/services/mysqlManagement/lib/mySQLManagementClient.js
  lib/services/mysqlManagement/lib/operations/index.d.ts
  lib/services/mysqlManagement/lib/operations/index.js
  lib/services/mysqlManagement/lib/operations/virtualNetworkRules.js
  lib/services/mysqlManagement/package-lock.json
  lib/services/mysqlManagement/package.json
Labels: in progress

#2924 [AutoPR compute/resource-manager] Fix List VM Extension API name, description updates and fix for 2018-…
  lib/services/computeManagement2/lib/computeManagementClient.d.ts
  lib/services/computeManagement2/lib/computeManagementClient.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/index.js
  lib/services/computeManagement2/lib/models/rollbackStatusInfo.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoricalStatusInfo.js
  lib/services/computeManagement2/lib/models/upgradeOperationHistoricalStatusInfoProperties.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetIPConfiguration.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetIpTag.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetPublicIPAddressConfiguration.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/index.js
  lib/services/computeManagement2/lib/operations/virtualMachineExtensions.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged

#2937 [AutoPR eventgrid/data-plane] Replacing # with &#35;
  lib/services/eventgrid/lib/models/deviceLifeCycleEventProperties.js
  lib/services/eventgrid/lib/models/index.d.ts
Labels: RestPRMerged

#2941 [AutoPR containerservices/resource-manager] Rename to "Operation" from "ComputeOperation"
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/index.js
  lib/services/containerservicesManagement/lib/models/operationListResult.js
  lib/services/containerservicesManagement/lib/models/operationValue.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/operations.js
Labels: RestPRMerged, in progress

#2940 [AutoPR containerservices/resource-manager] [AKS] remove maxPods default
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedClusterAgentPoolProfile.js
Labels: RestPRMerged, in progress

#2950 [AutoPR iotcentral/resource-manager] Remove subscriptionId uuid format for IotCentral
  lib/services/iotcentral/lib/iotCentralClient.d.ts
  lib/services/iotcentral/lib/iotCentralClient.js
  lib/services/iotcentral/lib/operations/apps.js
  lib/services/iotcentral/lib/operations/operations.js
Labels: RestPRMerged

#2934 [AutoPR containerinstance/resource-manager] Adding June Swagger Update - Azure Container Instance
  lib/services/containerinstanceManagement/LICENSE.txt
  lib/services/containerinstanceManagement/README.md
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.d.ts
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/container.js
  lib/services/containerinstanceManagement/lib/models/containerExec.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequestTerminalSize.js
  lib/services/containerinstanceManagement/lib/models/containerExecResponse.js
  lib/services/containerinstanceManagement/lib/models/containerGroup.js
  lib/services/containerinstanceManagement/lib/models/containerGroupDiagnostics.js
  lib/services/containerinstanceManagement/lib/models/containerHttpGet.js
  lib/services/containerinstanceManagement/lib/models/containerProbe.js
  lib/services/containerinstanceManagement/lib/models/environmentVariable.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/models/index.js
  lib/services/containerinstanceManagement/lib/models/logAnalytics.js
  lib/services/containerinstanceManagement/lib/operations/containerGroups.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/index.js
  lib/services/containerinstanceManagement/lib/operations/startContainer.js
  lib/services/containerinstanceManagement/package.json
Labels: RestPRMerged

#2963 [AutoPR containerservices/resource-manager] [AKS] add nodeResourceGroup property
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
Labels: RestPRMerged

#2943 [AutoPR cognitiveservices/data-plane/AutoSuggest] Add bing AutoSuggest Spec
  lib/services/autosuggest/LICENSE.txt
  lib/services/autosuggest/lib/autoSuggestAPIClient.d.ts
  lib/services/autosuggest/lib/autoSuggestAPIClient.js
  lib/services/autosuggest/lib/models/action.js
  lib/services/autosuggest/lib/models/answer.js
  lib/services/autosuggest/lib/models/autoSuggest.js
  lib/services/autosuggest/lib/models/creativeWork.js
  lib/services/autosuggest/lib/models/errorModel.js
  lib/services/autosuggest/lib/models/errorResponse.js
  lib/services/autosuggest/lib/models/identifiable.js
  lib/services/autosuggest/lib/models/index.d.ts
  lib/services/autosuggest/lib/models/index.js
  lib/services/autosuggest/lib/models/queryContext.js
  lib/services/autosuggest/lib/models/response.js
  lib/services/autosuggest/lib/models/responseBase.js
  lib/services/autosuggest/lib/models/searchAction.js
  lib/services/autosuggest/lib/models/searchResultsAnswer.js
  lib/services/autosuggest/lib/models/suggestions.js
  lib/services/autosuggest/lib/models/suggestionsSuggestionGroup.js
  lib/services/autosuggest/lib/models/thing.js
  lib/services/autosuggest/package.json
Labels: RestPRMerged

#2951 [AutoPR consumption/resource-manager] Added new api versions for PriceSheet and UsageDetail
  lib/services/consumptionManagement/README.md
  lib/services/consumptionManagement/lib/consumptionManagementClient.d.ts
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/index.js
  lib/services/consumptionManagement/lib/models/priceSheetProperties.js
  lib/services/consumptionManagement/lib/models/usageDetail.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/index.js
  lib/services/consumptionManagement/lib/operations/usageDetails.js
Labels: RestPRMerged, in progress

#2980 [AutoPR dns/resource-manager] Move DNS to use the common definition for resource groups
  lib/services/dnsManagement/LICENSE.txt
  lib/services/dnsManagement/README.md
  lib/services/dnsManagement/lib/operations/index.d.ts
  lib/services/dnsManagement/lib/operations/recordSets.js
  lib/services/dnsManagement/lib/operations/zones.js
  lib/services/dnsManagement/package.json
Labels: RestPRMerged, in progress

#2967 Update deps
  .jshintignore
  ChangeLog.md
  README.md
  gruntfile.js
  lib/azure.js
  lib/services/batch/package-lock.json
  lib/services/batch/package.json
  lib/services/batchManagement/package.json
  lib/services/batchaiManagement/package.json
  lib/services/insights/package.json
  lib/services/insightsManagement/package.json
  lib/services/legacyStorage/package.json
  lib/services/monitoring/package.json
  lib/services/scheduler/package.json
  lib/services/webSiteManagement/package.json
  nodeSDK.njsproj
  package-lock.json
  package.json
  package_service_mapping.json
  runtime/ms-rest-azure/package-lock.json
  runtime/ms-rest-azure/package.json
  runtime/ms-rest/lib/credentials/basicAuthenticationCredentials.js
  runtime/ms-rest/lib/serialization.js
  runtime/ms-rest/package-lock.json
  runtime/ms-rest/package.json
  runtime/ms-rest/test/credentialTests.js
  runtime/ms-rest/test/serializationTests.js
Labels: in progress

#2975 [AutoPR sql/resource-manager] Update BackupShortTermRetentionPolicies Swagger: Add ListByDatabase and update exceptions
  lib/services/sqlManagement2/lib/models/backupShortTermRetentionPolicyListResult.js
  lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/operations/backupShortTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged, in progress

#2923 [AutoPR authorization/resource-manager] Python Authorization to multi api
  lib/services/authorizationManagement/LICENSE.txt
  lib/services/authorizationManagement/README.md
  lib/services/authorizationManagement/package.json
Labels: RestPRMerged, in progress

#2984 Validate authority
  runtime/ms-rest-azure/Changelog.md
  runtime/ms-rest-azure/index.d.ts
  runtime/ms-rest-azure/package.json
Labels: in progress

#2982 [AutoPR cognitiveservices/data-plane/ComputerVision] Add Spanish as an option as ServiceLanguage for ComputerVision
  lib/services/computerVision/lib/computerVisionAPIClient.d.ts
  lib/services/computerVision/lib/computerVisionAPIClient.js
Labels: RestPRMerged, in progress

#2986 Fix typo in year
  ChangeLog.md
Labels: in progress

#2992 [AutoPR containerinstance/resource-manager] Container Instance - Fix Mistake in June Update
  lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequestTerminalSize.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/startContainer.js
Labels: RestPRMerged, in progress

#2991 [AutoPR network/resource-manager] network: add https probe which was missing in the spec
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/probe.js
Labels: RestPRMerged, in progress

#2997 update package.json and publish graph 3.0.0
  lib/services/graphManagement/package-lock.json
  lib/services/graphManagement/package.json
Labels: in progress

#2933 [AutoPR] iotcentral/resource-manager
  lib/services/iotcentral/LICENSE.txt
  lib/services/iotcentral/README.md
  lib/services/iotcentral/lib/iotCentralClient.d.ts
  lib/services/iotcentral/lib/iotCentralClient.js
  lib/services/iotcentral/lib/models/app.js
  lib/services/iotcentral/lib/models/appListResult.js
  lib/services/iotcentral/lib/models/appNameAvailabilityInfo.js
  lib/services/iotcentral/lib/models/appPatch.js
  lib/services/iotcentral/lib/models/appSkuInfo.js
  lib/services/iotcentral/lib/models/errorDetails.js
  lib/services/iotcentral/lib/models/index.d.ts
  lib/services/iotcentral/lib/models/index.js
  lib/services/iotcentral/lib/models/operation.js
  lib/services/iotcentral/lib/models/operationDisplay.js
  lib/services/iotcentral/lib/models/operationInputs.js
  lib/services/iotcentral/lib/models/operationListResult.js
  lib/services/iotcentral/lib/models/resource.js
  lib/services/iotcentral/lib/operations/apps.js
  lib/services/iotcentral/lib/operations/index.d.ts
  lib/services/iotcentral/lib/operations/index.js
  lib/services/iotcentral/lib/operations/operations.js
  lib/services/iotcentral/package.json
Labels: ServicePR, in progress

#3003 [AutoPR sql/resource-manager] adding new state value to keep backward competiblity
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/serverSecurityAlertPolicy.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/serverSecurityAlertPolicies.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged, in progress

#3005 [AutoPR containerinstance/resource-manager] Container Instance - Update Fields For Easier to Understand Documentation
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.d.ts
  lib/services/containerinstanceManagement/lib/containerInstanceManagementClient.js
  lib/services/containerinstanceManagement/lib/models/containerExecRequest.js
  lib/services/containerinstanceManagement/lib/models/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/containerOperations.js
  lib/services/containerinstanceManagement/lib/operations/index.d.ts
  lib/services/containerinstanceManagement/lib/operations/index.js
Labels: RestPRMerged, in progress

#3008 Adding Log Analytics query capabilities
  ChangeLog.md
  lib/azure.js
  lib/services/loganalytics/LICENSE.txt
  lib/services/loganalytics/README.md
  lib/services/loganalytics/lib/logAnalyticsClient.d.ts
  lib/services/loganalytics/lib/logAnalyticsClient.js
  lib/services/loganalytics/lib/models/column.js
  lib/services/loganalytics/lib/models/errorDetail.js
  lib/services/loganalytics/lib/models/errorInfo.js
  lib/services/loganalytics/lib/models/errorResponse.js
  lib/services/loganalytics/lib/models/index.d.ts
  lib/services/loganalytics/lib/models/index.js
  lib/services/loganalytics/lib/models/queryBody.js
  lib/services/loganalytics/lib/models/queryResults.js
  lib/services/loganalytics/lib/models/table.js
  lib/services/loganalytics/package-lock.json
  lib/services/loganalytics/package.json
  package.json
  package_service_mapping.json
  test/recordings/loganalytics-query-tests.nock.js
  test/services/loganalytics/loganalytics-query-tests.js
  test/testlistarm.txt
Labels: in progress

#2987 [AutoPR operationsmanagement/resource-manager] Change Response for Solution PUT call
  lib/services/operationsManagement/LICENSE.txt
  lib/services/operationsManagement/README.md
  lib/services/operationsManagement/lib/models/armTemplateParameter.js
  lib/services/operationsManagement/lib/models/index.d.ts
  lib/services/operationsManagement/lib/models/index.js
  lib/services/operationsManagement/lib/models/managementAssociation.js
  lib/services/operationsManagement/lib/models/managementAssociationProperties.js
  lib/services/operationsManagement/lib/models/managementAssociationPropertiesList.js
  lib/services/operationsManagement/lib/models/managementConfiguration.js
  lib/services/operationsManagement/lib/models/managementConfigurationProperties.js
  lib/services/operationsManagement/lib/models/managementConfigurationPropertiesList.js
  lib/services/operationsManagement/lib/operations/index.d.ts
  lib/services/operationsManagement/lib/operations/index.js
  lib/services/operationsManagement/lib/operations/managementAssociations.js
  lib/services/operationsManagement/lib/operations/managementConfigurations.js
  lib/services/operationsManagement/lib/operations/solutions.js
  lib/services/operationsManagement/lib/operationsManagementClient.d.ts
  lib/services/operationsManagement/lib/operationsManagementClient.js
  lib/services/operationsManagement/package.json
Labels: RestPRMerged, in progress

#2998 [AutoPR cognitiveservices/data-plane/ComputerVision] Update CognitiveService ComputerVision API to V2
  lib/services/computerVision/lib/computerVisionAPIClient.d.ts
  lib/services/computerVision/lib/computerVisionAPIClient.js
  lib/services/computerVision/lib/models/category.js
  lib/services/computerVision/lib/models/categoryDetail.js
  lib/services/computerVision/lib/models/imageAnalysis.js
  lib/services/computerVision/lib/models/imageDescription.js
  lib/services/computerVision/lib/models/imageDescriptionDetails.js
  lib/services/computerVision/lib/models/index.d.ts
  lib/services/computerVision/lib/models/index.js
  lib/services/computerVision/lib/models/landmarkResults.js
  lib/services/computerVision/lib/models/landmarksModel.js
  lib/services/computerVision/package.json
Labels: RestPRMerged, in progress

#3000 [AutoPR datafactory/resource-manager] [Data Factory] Remove maximum maxParallelExecutionsPerNode validation
  lib/services/datafactoryManagement/lib/models/integrationRuntimeComputeProperties.js
Labels: RestPRMerged, in progress

#3012 Add loganalytics to rollup package
  package-lock.json
  package.json
  runtime/ms-rest-azure/package-lock.json
Labels: in progress

#3024 [AutoPR operationalinsights/data-plane] Add nodejs generation for Operational Insights
  lib/services/loganalytics/LICENSE.txt
  lib/services/loganalytics/lib/logAnalyticsClient.d.ts
  lib/services/loganalytics/lib/logAnalyticsClient.js
  lib/services/loganalytics/lib/models/column.js
  lib/services/loganalytics/lib/models/errorDetail.js
  lib/services/loganalytics/lib/models/errorInfo.js
  lib/services/loganalytics/lib/models/errorResponse.js
  lib/services/loganalytics/lib/models/index.d.ts
  lib/services/loganalytics/lib/models/index.js
  lib/services/loganalytics/lib/models/queryBody.js
  lib/services/loganalytics/lib/models/queryResults.js
  lib/services/loganalytics/lib/models/table.js
  lib/services/loganalytics/package.json
Labels: RestPRMerged, in progress

#3001 [AutoPR storagesync/resource-manager] Add new version 2018-04-02 for Microsoft.StorageSync Resource Provider
  lib/services/storagesyncmanagement/LICENSE.txt
  lib/services/storagesyncmanagement/README.md
  lib/services/storagesyncmanagement/lib/models/backupRequest.js
  lib/services/storagesyncmanagement/lib/models/checkNameAvailabilityParameters.js
  lib/services/storagesyncmanagement/lib/models/checkNameAvailabilityResult.js
  lib/services/storagesyncmanagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncmanagement/lib/models/cloudEndpointArray.js
  lib/services/storagesyncmanagement/lib/models/index.d.ts
  lib/services/storagesyncmanagement/lib/models/index.js
  lib/services/storagesyncmanagement/lib/models/operationDisplayInfo.js
  lib/services/storagesyncmanagement/lib/models/operationDisplayResource.js
  lib/services/storagesyncmanagement/lib/models/operationEntity.js
  lib/services/storagesyncmanagement/lib/models/operationEntityListResult.js
  lib/services/storagesyncmanagement/lib/models/postBackupResponse.js
  lib/services/storagesyncmanagement/lib/models/postRestoreRequest.js
  lib/services/storagesyncmanagement/lib/models/preRestoreRequest.js
  lib/services/storagesyncmanagement/lib/models/registeredServer.js
  lib/services/storagesyncmanagement/lib/models/registeredServerArray.js
  lib/services/storagesyncmanagement/lib/models/resource.js
  lib/services/storagesyncmanagement/lib/models/resourcesMoveInfo.js
  lib/services/storagesyncmanagement/lib/models/restoreFileSpec.js
  lib/services/storagesyncmanagement/lib/models/serverEndpoint.js
  lib/services/storagesyncmanagement/lib/models/serverEndpointArray.js
  lib/services/storagesyncmanagement/lib/models/storageSyncError.js
  lib/services/storagesyncmanagement/lib/models/storageSyncErrorDetails.js
  lib/services/storagesyncmanagement/lib/models/storageSyncService.js
  lib/services/storagesyncmanagement/lib/models/storageSyncServiceArray.js
  lib/services/storagesyncmanagement/lib/models/subscriptionState.js
  lib/services/storagesyncmanagement/lib/models/syncGroup.js
  lib/services/storagesyncmanagement/lib/models/syncGroupArray.js
  lib/services/storagesyncmanagement/lib/models/trackedResource.js
  lib/services/storagesyncmanagement/lib/models/workflow.js
  lib/services/storagesyncmanagement/lib/models/workflowArray.js
  lib/services/storagesyncmanagement/lib/operations/cloudEndpoints.js
  lib/services/storagesyncmanagement/lib/operations/index.d.ts
  lib/services/storagesyncmanagement/lib/operations/index.js
  lib/services/storagesyncmanagement/lib/operations/operations.js
  lib/services/storagesyncmanagement/lib/operations/registeredServers.js
  lib/services/storagesyncmanagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncmanagement/lib/operations/storageSyncServices.js
  lib/services/storagesyncmanagement/lib/operations/syncGroups.js
  lib/services/storagesyncmanagement/lib/operations/workflows.js
  lib/services/storagesyncmanagement/lib/storageSyncManagementClient.d.ts
  lib/services/storagesyncmanagement/lib/storageSyncManagementClient.js
  lib/services/storagesyncmanagement/package.json
Labels: RestPRMerged, in progress

#3022 [AutoPR apimanagement/resource-manager] Fix the validation Check for apiId parameter in the productapis
  lib/services/apimanagement/lib/models/errorResponse.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/productApi.js
  lib/services/apimanagement/package.json
Labels: RestPRMerged, in progress

#2996 [AutoPR cosmos-db/resource-manager] Cosmos DB - POST operation for retrieving read only keys
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3029 [AutoPR logic/resource-manager] Adding in description of available filter options
  lib/services/logicManagement/lib/operations/agreements.js
  lib/services/logicManagement/lib/operations/index.d.ts
  lib/services/logicManagement/lib/operations/maps.js
  lib/services/logicManagement/lib/operations/partners.js
  lib/services/logicManagement/lib/operations/schemas.js
  lib/services/logicManagement/lib/operations/sessions.js
  lib/services/logicManagement/lib/operations/workflowRunActions.js
  lib/services/logicManagement/lib/operations/workflowRuns.js
  lib/services/logicManagement/lib/operations/workflowTriggerHistories.js
  lib/services/logicManagement/lib/operations/workflows.js
  lib/services/logicManagement/package.json
Labels: RestPRMerged, in progress

#3027 [AutoPR cognitiveservices/data-plane/ComputerVision] ComputerVision add tag.hint
  lib/services/computerVision/lib/models/imageTag.js
  lib/services/computerVision/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#3033 [AutoPR apimanagement/resource-manager] Fix contract for Error in OperationResultContract
  lib/services/apimanagement/lib/models/errorResponseBody.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/index.js
  lib/services/apimanagement/lib/models/operationResultContract.js
Labels: RestPRMerged, in progress

#3042 [AutoPR mediaservices/resource-manager] Adding Azure Media Services version 2018-06-01-preview version
  lib/services/mediaServicesManagement/README.md
  lib/services/mediaServicesManagement/lib/azureMediaServices.js
  lib/services/mediaServicesManagement/lib/models/aacAudio.js
  lib/services/mediaServicesManagement/lib/models/apiError.js
  lib/services/mediaServicesManagement/lib/models/asset.js
  lib/services/mediaServicesManagement/lib/models/builtInStandardEncoderPreset.js
  lib/services/mediaServicesManagement/lib/models/cbcsDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/cencDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCbcs.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCenc.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyFairPlayConfiguration.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyPlayReadyLicense.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyPlayReadyPlayRight.js
  lib/services/mediaServicesManagement/lib/models/contentKeyPolicyTokenRestriction.js
  lib/services/mediaServicesManagement/lib/models/defaultKey.js
  lib/services/mediaServicesManagement/lib/models/deinterlace.js
  lib/services/mediaServicesManagement/lib/models/enabledProtocols.js
  lib/services/mediaServicesManagement/lib/models/envelopeEncryption.js
  lib/services/mediaServicesManagement/lib/models/filters.js
  lib/services/mediaServicesManagement/lib/models/h264Layer.js
  lib/services/mediaServicesManagement/lib/models/h264Video.js
  lib/services/mediaServicesManagement/lib/models/image.js
  lib/services/mediaServicesManagement/lib/models/index.d.ts
  lib/services/mediaServicesManagement/lib/models/index.js
  lib/services/mediaServicesManagement/lib/models/job.js
  lib/services/mediaServicesManagement/lib/models/jobError.js
  lib/services/mediaServicesManagement/lib/models/jobOutput.js
  lib/services/mediaServicesManagement/lib/models/jobOutputAsset.js
  lib/services/mediaServicesManagement/lib/models/jpgImage.js
  lib/services/mediaServicesManagement/lib/models/listContainerSasInput.js
  lib/services/mediaServicesManagement/lib/models/liveEvent.js
  lib/services/mediaServicesManagement/lib/models/liveEventPreview.js
  lib/services/mediaServicesManagement/lib/models/noEncryption.js
  lib/services/mediaServicesManagement/lib/models/pngImage.js
  lib/services/mediaServicesManagement/lib/models/storageAccount.js
  lib/services/mediaServicesManagement/lib/models/streamingLocator.js
  lib/services/mediaServicesManagement/lib/models/streamingLocatorContentKey.js
  lib/services/mediaServicesManagement/lib/models/streamingPath.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicy.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyContentKey.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyContentKeys.js
  lib/services/mediaServicesManagement/lib/models/trackPropertyCondition.js
  lib/services/mediaServicesManagement/lib/models/transformOutput.js
  lib/services/mediaServicesManagement/lib/models/video.js
  lib/services/mediaServicesManagement/lib/operations/index.d.ts
  lib/services/mediaServicesManagement/lib/operations/jobs.js
  lib/services/mediaServicesManagement/lib/operations/liveEvents.js
  lib/services/mediaServicesManagement/lib/operations/streamingLocators.js
  lib/services/mediaServicesManagement/lib/operations/streamingPolicies.js
  lib/services/mediaServicesManagement/package.json
Labels: RestPRMerged, in progress

#3013 [AutoPR sql/resource-manager] Adding Swagger for POST APIs used to upload a customer TDE certificates
  lib/services/sqlManagement2/lib/models/databaseBlobAuditingPolicy.js
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/tdeCertificate.js
  lib/services/sqlManagement2/lib/operations/backupShortTermRetentionPolicies.js
  lib/services/sqlManagement2/lib/operations/databaseBlobAuditingPolicies.js
  lib/services/sqlManagement2/lib/operations/databaseVulnerabilityAssessmentRuleBaselines.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/managedInstanceTdeCertificates.js
  lib/services/sqlManagement2/lib/operations/tdeCertificates.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged, in progress

#3048 x-nullable
  runtime/ms-rest/Changelog.md
  runtime/ms-rest/index.d.ts
  runtime/ms-rest/lib/serialization.js
  runtime/ms-rest/package.json
  runtime/ms-rest/test/serializationTests.js
Labels: in progress

#3028 [AutoPR network/resource-manager] Release of Azure Networking Network-2018-06-01 (api-version 2018-04-01)
  lib/services/networkManagement2/lib/models/applicationGateway.js
  lib/services/networkManagement2/lib/models/applicationGatewayAutoscaleBounds.js
  lib/services/networkManagement2/lib/models/applicationGatewayAutoscaleConfiguration.js
  lib/services/networkManagement2/lib/models/applicationGatewaySku.js
  lib/services/networkManagement2/lib/models/connectionSharedKey.js
  lib/services/networkManagement2/lib/models/deviceProperties.js
  lib/services/networkManagement2/lib/models/getVpnSitesConfigurationRequest.js
  lib/services/networkManagement2/lib/models/hubVirtualNetworkConnection.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/listHubVirtualNetworkConnectionsResult.js
  lib/services/networkManagement2/lib/models/listVirtualHubsResult.js
  lib/services/networkManagement2/lib/models/listVirtualWANsResult.js
  lib/services/networkManagement2/lib/models/listVpnConnectionsResult.js
  lib/services/networkManagement2/lib/models/listVpnGatewaysResult.js
  lib/services/networkManagement2/lib/models/listVpnSitesResult.js
  lib/services/networkManagement2/lib/models/policies.js
  lib/services/networkManagement2/lib/models/virtualHub.js
  lib/services/networkManagement2/lib/models/virtualWAN.js
  lib/services/networkManagement2/lib/models/vpnConnection.js
  lib/services/networkManagement2/lib/models/vpnGateway.js
  lib/services/networkManagement2/lib/models/vpnSite.js
  lib/services/networkManagement2/lib/models/vpnSiteId.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/lib/operations/applicationGateways.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuitPeerings.js
  lib/services/networkManagement2/lib/operations/hubVirtualNetworkConnections.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/index.js
  lib/services/networkManagement2/lib/operations/virtualHubs.js
  lib/services/networkManagement2/lib/operations/virtualNetworkGatewayConnections.js
  lib/services/networkManagement2/lib/operations/virtualWANs.js
  lib/services/networkManagement2/lib/operations/vpnConnections.js
  lib/services/networkManagement2/lib/operations/vpnGateways.js
  lib/services/networkManagement2/lib/operations/vpnSites.js
  lib/services/networkManagement2/lib/operations/vpnSitesConfiguration.js
Labels: RestPRMerged, in progress

#3052 [AutoPR storage/resource-manager] [Storage] Support HDFS feature and web endpoint in Account properties
  lib/services/storageManagement2/lib/models/endpoints.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
Labels: RestPRMerged, in progress

#3057 No destructuring
  runtime/ms-rest/Changelog.md
  runtime/ms-rest/lib/serialization.js
  runtime/ms-rest/package-lock.json
  runtime/ms-rest/package.json
Labels: in progress

#3043 [AutoPR monitor/resource-manager] Add two missing "by subscription" operations for completeness and compliance
  lib/services/monitorManagement/lib/models/action.js
  lib/services/monitorManagement/lib/models/alertingAction.js
  lib/services/monitorManagement/lib/models/diagnosticSettingsResource.js
  lib/services/monitorManagement/lib/models/eventData.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/logMetricTrigger.js
  lib/services/monitorManagement/lib/models/metricAlertAction.js
  lib/services/monitorManagement/lib/models/metricAlertStatus.js
  lib/services/monitorManagement/lib/models/metricAlertStatusProperties.js
  lib/services/monitorManagement/lib/models/metricCriteria.js
  lib/services/monitorManagement/lib/models/metricDimension.js
  lib/services/monitorManagement/lib/models/triggerCondition.js
  lib/services/monitorManagement/lib/operations/alertRules.js
  lib/services/monitorManagement/lib/operations/autoscaleSettings.js
  lib/services/monitorManagement/lib/operations/diagnosticSettingsOperations.js
  lib/services/monitorManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#3018 [AutoPR cognitiveservices/data-plane/CustomVision/Prediction/cognitiveservices/data-plane/CustomVision/Training] Add more languages support
  lib/services/customVision/prediction/LICENSE.txt
  lib/services/customVision/prediction/lib/models/boundingBox.js
  lib/services/customVision/prediction/lib/models/imagePrediction.js
  lib/services/customVision/prediction/lib/models/imageUrl.js
  lib/services/customVision/prediction/lib/models/index.d.ts
  lib/services/customVision/prediction/lib/models/index.js
  lib/services/customVision/prediction/lib/models/prediction.js
  lib/services/customVision/prediction/lib/predictionAPIClient.d.ts
  lib/services/customVision/prediction/lib/predictionAPIClient.js
  lib/services/customVision/prediction/package.json
  lib/services/customVision/training/LICENSE.txt
  lib/services/customVision/training/lib/models/boundingBox.js
  lib/services/customVision/training/lib/models/domain.js
  lib/services/customVision/training/lib/models/exportModel.js
  lib/services/customVision/training/lib/models/image.js
  lib/services/customVision/training/lib/models/imageCreateResult.js
  lib/services/customVision/training/lib/models/imageCreateSummary.js
  lib/services/customVision/training/lib/models/imageFileCreateBatch.js
  lib/services/customVision/training/lib/models/imageFileCreateEntry.js
  lib/services/customVision/training/lib/models/imageIdCreateBatch.js
  lib/services/customVision/training/lib/models/imageIdCreateEntry.js
  lib/services/customVision/training/lib/models/imagePerformance.js
  lib/services/customVision/training/lib/models/imagePrediction.js
  lib/services/customVision/training/lib/models/imageRegion.js
  lib/services/customVision/training/lib/models/imageRegionCreateBatch.js
  lib/services/customVision/training/lib/models/imageRegionCreateEntry.js
  lib/services/customVision/training/lib/models/imageRegionCreateResult.js
  lib/services/customVision/training/lib/models/imageRegionCreateSummary.js
  lib/services/customVision/training/lib/models/imageRegionProposal.js
  lib/services/customVision/training/lib/models/imageTag.js
  lib/services/customVision/training/lib/models/imageTagCreateBatch.js
  lib/services/customVision/training/lib/models/imageTagCreateEntry.js
  lib/services/customVision/training/lib/models/imageTagCreateSummary.js
  lib/services/customVision/training/lib/models/imageUrl.js
  lib/services/customVision/training/lib/models/imageUrlCreateBatch.js
  lib/services/customVision/training/lib/models/imageUrlCreateEntry.js
  lib/services/customVision/training/lib/models/index.d.ts
  lib/services/customVision/training/lib/models/index.js
  lib/services/customVision/training/lib/models/iteration.js
  lib/services/customVision/training/lib/models/iterationPerformance.js
  lib/services/customVision/training/lib/models/prediction.js
  lib/services/customVision/training/lib/models/predictionQueryResult.js
  lib/services/customVision/training/lib/models/predictionQueryTag.js
  lib/services/customVision/training/lib/models/predictionQueryToken.js
  lib/services/customVision/training/lib/models/project.js
  lib/services/customVision/training/lib/models/projectSettings.js
  lib/services/customVision/training/lib/models/region.js
  lib/services/customVision/training/lib/models/regionProposal.js
  lib/services/customVision/training/lib/models/storedImagePrediction.js
  lib/services/customVision/training/lib/models/tag.js
  lib/services/customVision/training/lib/models/tagPerformance.js
  lib/services/customVision/training/lib/trainingAPIClient.d.ts
  lib/services/customVision/training/lib/trainingAPIClient.js
  lib/services/customVision/training/package.json
Labels: RestPRMerged, in progress

#3025 [AutoPR consumption/resource-manager/cost-management/resource-manager] Created a new provider Microsoft.CostManagement and moved reports and query api documentation from Microsoft.Consumption to it
  lib/services/consumptionManagement/LICENSE.txt
  lib/services/consumptionManagement/README.md
  lib/services/consumptionManagement/lib/consumptionManagementClient.d.ts
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/forecast.js
  lib/services/consumptionManagement/lib/models/forecastPropertiesConfidenceLevelsItem.js
  lib/services/consumptionManagement/lib/models/forecastsListResult.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/index.js
  lib/services/consumptionManagement/lib/models/priceSheetProperties.js
  lib/services/consumptionManagement/lib/models/queryOptions.js
  lib/services/consumptionManagement/lib/models/usageDetail.js
  lib/services/consumptionManagement/lib/operations/forecasts.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/index.js
  lib/services/consumptionManagement/lib/operations/usageDetails.js
  lib/services/consumptionManagement/package.json
Labels: RestPRMerged, in progress

#3030 [AutoPR cosmos-db/resource-manager] Fix Java multi api namespace for cosmos DB
  lib/services/cosmosdbManagement/LICENSE.txt
  lib/services/cosmosdbManagement/README.md
  lib/services/cosmosdbManagement/lib/models/databaseAccount.js
  lib/services/cosmosdbManagement/lib/models/databaseAccountCreateUpdateParameters.js
  lib/services/cosmosdbManagement/lib/models/errorResponse.js
  lib/services/cosmosdbManagement/lib/models/index.d.ts
  lib/services/cosmosdbManagement/lib/models/index.js
  lib/services/cosmosdbManagement/lib/models/regionForOnlineOffline.js
  lib/services/cosmosdbManagement/lib/models/virtualNetworkRule.js
  lib/services/cosmosdbManagement/lib/operations/databaseAccounts.js
  lib/services/cosmosdbManagement/lib/operations/index.d.ts
  lib/services/cosmosdbManagement/package.json
Labels: RestPRMerged, in progress

#3064 [AutoPR automation/resource-manager] Updated Readme.md file
  lib/services/automationManagement/lib/automationClient.d.ts
  lib/services/automationManagement/lib/automationClient.js
  lib/services/automationManagement/lib/models/index.d.ts
  lib/services/automationManagement/lib/models/index.js
  lib/services/automationManagement/lib/models/nodeCount.js
  lib/services/automationManagement/lib/models/nodeCountProperties.js
  lib/services/automationManagement/lib/models/nodeCounts.js
  lib/services/automationManagement/lib/operations/index.d.ts
  lib/services/automationManagement/lib/operations/index.js
  lib/services/automationManagement/lib/operations/nodeCountInformation.js
Labels: RestPRMerged, in progress

#3074 Regenerate storage management SDK and bump version to 5.1.0-preview
  lib/services/storageManagement2/lib/models/endpoints.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/package-lock.json
  lib/services/storageManagement2/package.json
Labels: in progress

#3076 [AutoPR containerregistry/resource-manager] [ACR] Fix list builds odata query
  lib/services/containerRegistryManagement/lib/models/buildFilter.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#3072 update keyvault readme; regen keyvault SDKs
  lib/services/keyVault/LICENSE.txt
  lib/services/keyVault/README.md
  lib/services/keyVault/lib/keyVaultClient.d.ts
  lib/services/keyVault/lib/keyVaultClient.js
  lib/services/keyVault/lib/models/certificateBundle.js
  lib/services/keyVault/lib/models/certificateCreateParameters.js
  lib/services/keyVault/lib/models/certificateImportParameters.js
  lib/services/keyVault/lib/models/certificatePolicy.js
  lib/services/keyVault/lib/models/certificateUpdateParameters.js
  lib/services/keyVault/lib/models/index.d.ts
  lib/services/keyVault/lib/models/jsonWebKey.js
  lib/services/keyVault/lib/models/keyBundle.js
  lib/services/keyVault/lib/models/keyCreateParameters.js
  lib/services/keyVault/lib/models/keyImportParameters.js
  lib/services/keyVault/lib/models/keyProperties.js
  lib/services/keyVault/lib/models/keySignParameters.js
  lib/services/keyVault/lib/models/keyVerifyParameters.js
  lib/services/keyVault/package.json
  lib/services/keyVault/sample.js
  lib/services/keyVaultManagement/LICENSE.txt
  lib/services/keyVaultManagement/lib/keyVaultManagementClient.js
  lib/services/keyVaultManagement/lib/models/vault.js
  lib/services/keyVaultManagement/lib/models/vaultCreateOrUpdateParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchParameters.js
  lib/services/keyVaultManagement/lib/models/vaultPatchProperties.js
  lib/services/keyVaultManagement/lib/models/vaultProperties.js
  lib/services/keyVaultManagement/package.json
  test/recordings/keyVault-certificate-tests.nock.js
  test/recordings/keyVault-key-tests.nock.js
  test/recordings/keyVault-secret-tests.nock.js
  test/recordings/keyvaultmanagement-tests/Key_Vault_Management_Key_Vaults_should_create_a_key_vault_with_vnet_rule_set_correctly.nock.js
  test/recordings/keyvaultmanagement-tests/suite.keyvaultmanagement-tests.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_add_the_storage_account_to_the_vault.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_assign_Key_Vault_the_operator_role_on_a_storage_account.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_create_a_SAS_account_template.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_disable_auto_key-regen.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_remove_the_storage_account_from_the_vault.nock.js
  test/recordings/keyvaultstorage-tests/Key_Vault_Storage_should_successfully_update_the_active_account_key.nock.js
  test/services/keyVault/keyVault-certificate-tests.js
  test/services/keyVault/keyVault-key-tests.js
  test/services/keyVault/keyVault-secret-tests.js
Labels: in progress

#3078 [AutoPR eventhub/resource-manager] Event Hubs : Added property pendingReplicationOperationsCount to GeoDR
  lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/package.json
Labels: RestPRMerged, in progress

#3077 [AutoPR servicebus/resource-manager] ServiceBus: Added property pendingReplicationOperationsCount to GeoDR and Migration
  lib/services/serviceBusManagement2/lib/models/armDisasterRecovery.js
  lib/services/serviceBusManagement2/lib/models/index.d.ts
  lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js
  lib/services/serviceBusManagement2/package.json
Labels: RestPRMerged, in progress

#3075 [AutoPR automation/resource-manager] Reverting the schedule.json response code for Created to 201 as that …
  lib/services/automationManagement/lib/operations/scheduleOperations.js
Labels: RestPRMerged, in progress

#3092 [AutoPR servicebus/resource-manager] ServiceBus: Removed space from pendingReplicationOperationsCount
  lib/services/serviceBusManagement2/lib/models/armDisasterRecovery.js
  lib/services/serviceBusManagement2/lib/models/migrationConfigProperties.js
Labels: RestPRMerged, in progress

#3090 [AutoPR batchai/resource-manager] Rename MPI to CustomMPI to match Batch AI service
  lib/services/batchaiManagement/lib/models/index.d.ts
  lib/services/batchaiManagement/lib/models/job.js
Labels: RestPRMerged, in progress

#3091 [AutoPR eventhub/resource-manager] EventHub: Removed space from pendingReplicationOperationsCount
  lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
Labels: RestPRMerged, in progress

#3095 [AutoPR network/resource-manager] Adding java tag for 2018-04 network
  lib/services/networkManagement2/lib/models/azureFirewall.js
  lib/services/networkManagement2/lib/models/azureFirewallApplicationRule.js
  lib/services/networkManagement2/lib/models/azureFirewallApplicationRuleCollection.js
  lib/services/networkManagement2/lib/models/azureFirewallApplicationRuleProtocol.js
  lib/services/networkManagement2/lib/models/azureFirewallIPConfiguration.js
  lib/services/networkManagement2/lib/models/azureFirewallListResult.js
  lib/services/networkManagement2/lib/models/azureFirewallNetworkRule.js
  lib/services/networkManagement2/lib/models/azureFirewallNetworkRuleCollection.js
  lib/services/networkManagement2/lib/models/azureFirewallRCAction.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/lib/operations/azureFirewalls.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/index.js
Labels: RestPRMerged, in progress

#3084 [AutoPR compute/resource-manager] Swagger change for getting all availability sets in a subscription and StandardSSD
  lib/services/computeManagement2/lib/models/availabilitySetListResult.js
  lib/services/computeManagement2/lib/models/dataDisk.js
  lib/services/computeManagement2/lib/models/disk.js
  lib/services/computeManagement2/lib/models/diskSku.js
  lib/services/computeManagement2/lib/models/diskUpdate.js
  lib/services/computeManagement2/lib/models/image.js
  lib/services/computeManagement2/lib/models/imageDataDisk.js
  lib/services/computeManagement2/lib/models/imageOSDisk.js
  lib/services/computeManagement2/lib/models/imageStorageProfile.js
  lib/services/computeManagement2/lib/models/imageUpdate.js
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/managedDiskParameters.js
  lib/services/computeManagement2/lib/models/oSDisk.js
  lib/services/computeManagement2/lib/models/storageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSet.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetDataDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetManagedDiskParameters.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdate.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateOSDisk.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateStorageProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetUpdateVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVMProfile.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/availabilitySets.js
  lib/services/computeManagement2/lib/operations/disks.js
  lib/services/computeManagement2/lib/operations/images.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSets.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress
