Repository Azure/azure-sdk-for-node, pull requests merged in 2019-01, with the labels that each got.

#4161 [AutoPR] storage/resource-manager
  lib/services/storageManagement2/LICENSE.txt
  lib/services/storageManagement2/lib/models/accountSasParameters.js
  lib/services/storageManagement2/lib/models/azureEntityResource.js
  lib/services/storageManagement2/lib/models/blobContainer.js
  lib/services/storageManagement2/lib/models/blobServiceProperties.js
  lib/services/storageManagement2/lib/models/checkNameAvailabilityResult.js
  lib/services/storageManagement2/lib/models/corsRule.js
  lib/services/storageManagement2/lib/models/corsRules.js
  lib/services/storageManagement2/lib/models/customDomain.js
  lib/services/storageManagement2/lib/models/deleteRetentionPolicy.js
  lib/services/storageManagement2/lib/models/dimension.js
  lib/services/storageManagement2/lib/models/encryption.js
  lib/services/storageManagement2/lib/models/encryptionService.js
  lib/services/storageManagement2/lib/models/encryptionServices.js
  lib/services/storageManagement2/lib/models/endpoints.js
  lib/services/storageManagement2/lib/models/geoReplicationStats.js
  lib/services/storageManagement2/lib/models/iPRule.js
  lib/services/storageManagement2/lib/models/identity.js
  lib/services/storageManagement2/lib/models/immutabilityPolicy.js
  lib/services/storageManagement2/lib/models/immutabilityPolicyProperties.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/keyVaultProperties.js
  lib/services/storageManagement2/lib/models/legalHold.js
  lib/services/storageManagement2/lib/models/legalHoldProperties.js
  lib/services/storageManagement2/lib/models/listAccountSasResponse.js
  lib/services/storageManagement2/lib/models/listContainerItem.js
  lib/services/storageManagement2/lib/models/listContainerItems.js
  lib/services/storageManagement2/lib/models/listServiceSasResponse.js
  lib/services/storageManagement2/lib/models/managementPoliciesRulesSetParameter.js
  lib/services/storageManagement2/lib/models/metricSpecification.js
  lib/services/storageManagement2/lib/models/networkRuleSet.js
  lib/services/storageManagement2/lib/models/operation.js
  lib/services/storageManagement2/lib/models/operationDisplay.js
  lib/services/storageManagement2/lib/models/resource.js
  lib/services/storageManagement2/lib/models/restriction.js
  lib/services/storageManagement2/lib/models/sKUCapability.js
  lib/services/storageManagement2/lib/models/serviceSasParameters.js
  lib/services/storageManagement2/lib/models/serviceSpecification.js
  lib/services/storageManagement2/lib/models/sku.js
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCheckNameAvailabilityParameters.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountKey.js
  lib/services/storageManagement2/lib/models/storageAccountListKeysResult.js
  lib/services/storageManagement2/lib/models/storageAccountManagementPolicies.js
  lib/services/storageManagement2/lib/models/storageAccountRegenerateKeyParameters.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/models/tagProperty.js
  lib/services/storageManagement2/lib/models/trackedResource.js
  lib/services/storageManagement2/lib/models/updateHistoryProperty.js
  lib/services/storageManagement2/lib/models/usage.js
  lib/services/storageManagement2/lib/models/usageName.js
  lib/services/storageManagement2/lib/models/virtualNetworkRule.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/package.json
Labels: ServicePR, in progress

#4506 [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Change from preview to stable for 2018-10-01 ApiVersion
  lib/services/storagesyncManagement/LICENSE.txt
  lib/services/storagesyncManagement/lib/models/cloudEndpoint.js
  lib/services/storagesyncManagement/lib/models/index.d.ts
  lib/services/storagesyncManagement/lib/models/index.js
  lib/services/storagesyncManagement/lib/models/registeredServer.js
  lib/services/storagesyncManagement/lib/models/serverEndpoint.js
  lib/services/storagesyncManagement/lib/models/serverEndpointCreateParameters.js
  lib/services/storagesyncManagement/lib/models/serverEndpointHealth.js
  lib/services/storagesyncManagement/lib/models/serverEndpointUpdateParameters.js
  lib/services/storagesyncManagement/lib/models/syncProgressStatus.js
  lib/services/storagesyncManagement/lib/models/syncSessionStatus.js
  lib/services/storagesyncManagement/lib/operations/index.d.ts
  lib/services/storagesyncManagement/lib/operations/serverEndpoints.js
  lib/services/storagesyncManagement/lib/storageSyncManagementClient.js
Labels: RestPRMerged

#4488 [AutoPR datafactory/resource-manager] [Azure Data Factory] Change Ssis activity property type to support expression
  lib/services/datafactoryManagement/LICENSE.txt
  lib/services/datafactoryManagement/lib/models/executeSSISPackageActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/sSISPackageLocation.js
Labels: RestPRMerged, in progress

#4504 Add client build scripts
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
  package.json
Labels: in progress

#4502 [AutoPR containerservices/resource-manager] [AKS] add empty resource group validation
  lib/services/containerservicesManagement/LICENSE.txt
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
  lib/services/containerservicesManagement/lib/operations/openShiftManagedClusters.js
Labels: RestPRMerged, in progress

#4520 [AutoPR apimanagement/resource-manager] OpenAPIv3 support documented
  lib/services/apimanagement/LICENSE.txt
Labels: RestPRMerged, in progress

#4286 [AutoPR] eventgrid/resource-manager
  lib/services/eventgridManagement/LICENSE.txt
  lib/services/eventgridManagement/README.md
  lib/services/eventgridManagement/lib/eventGridManagementClient.d.ts
  lib/services/eventgridManagement/lib/eventGridManagementClient.js
  lib/services/eventgridManagement/lib/models/advancedFilter.js
  lib/services/eventgridManagement/lib/models/deadLetterDestination.js
  lib/services/eventgridManagement/lib/models/eventHubEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/eventSubscription.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFilter.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionFullUrl.js
  lib/services/eventgridManagement/lib/models/eventSubscriptionUpdateParameters.js
  lib/services/eventgridManagement/lib/models/eventType.js
  lib/services/eventgridManagement/lib/models/hybridConnectionEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/index.d.ts
  lib/services/eventgridManagement/lib/models/index.js
  lib/services/eventgridManagement/lib/models/jsonField.js
  lib/services/eventgridManagement/lib/models/jsonFieldWithDefault.js
  lib/services/eventgridManagement/lib/models/operation.js
  lib/services/eventgridManagement/lib/models/operationInfo.js
  lib/services/eventgridManagement/lib/models/resource.js
  lib/services/eventgridManagement/lib/models/retryPolicy.js
  lib/services/eventgridManagement/lib/models/storageBlobDeadLetterDestination.js
  lib/services/eventgridManagement/lib/models/storageQueueEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/models/topic.js
  lib/services/eventgridManagement/lib/models/topicRegenerateKeyRequest.js
  lib/services/eventgridManagement/lib/models/topicSharedAccessKeys.js
  lib/services/eventgridManagement/lib/models/topicTypeInfo.js
  lib/services/eventgridManagement/lib/models/topicUpdateParameters.js
  lib/services/eventgridManagement/lib/models/trackedResource.js
  lib/services/eventgridManagement/lib/models/webHookEventSubscriptionDestination.js
  lib/services/eventgridManagement/lib/operations/eventSubscriptions.js
  lib/services/eventgridManagement/lib/operations/index.d.ts
  lib/services/eventgridManagement/lib/operations/index.js
  lib/services/eventgridManagement/lib/operations/topics.js
  lib/services/eventgridManagement/package.json
Labels: ServicePR, in progress

#4525 [AutoPR network/resource-manager] Fix errors with ddosCustomPolicy.json
  lib/services/networkManagement2/lib/models/ddosCustomPolicy.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/protocolCustomSettingsFormat.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/lib/operations/ddosCustomPolicies.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/index.js
Labels: RestPRMerged, in progress

#4111 [AutoPR] logic/resource-manager
  lib/services/logicManagement/LICENSE.txt
  lib/services/logicManagement/lib/models/agreementContent.js
  lib/services/logicManagement/lib/models/apiError.js
  lib/services/logicManagement/lib/models/apiErrorBody.js
  lib/services/logicManagement/lib/models/edifactAgreementContent.js
  lib/services/logicManagement/lib/models/edifactOneWayAgreement.js
  lib/services/logicManagement/lib/models/edifactProtocolSettings.js
  lib/services/logicManagement/lib/models/edifactValidationOverride.js
  lib/services/logicManagement/lib/models/edifactValidationSettings.js
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/integrationAccountAgreement.js
  lib/services/logicManagement/lib/models/x12AgreementContent.js
  lib/services/logicManagement/lib/models/x12OneWayAgreement.js
  lib/services/logicManagement/lib/models/x12ProtocolSettings.js
  lib/services/logicManagement/lib/models/x12ValidationOverride.js
  lib/services/logicManagement/lib/models/x12ValidationSettings.js
  lib/services/logicManagement/lib/operations/index.d.ts
  lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
  lib/services/logicManagement/package.json
Labels: ServicePR, in progress

#4517 [AutoPR compute/resource-manager] Update ComputerName definition for OsProfile
  lib/services/computeManagement2/LICENSE.txt
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/oSProfile.js
  lib/services/computeManagement2/lib/models/virtualMachine.js
  lib/services/computeManagement2/lib/models/virtualMachineScaleSetVM.js
  lib/services/computeManagement2/lib/models/virtualMachineUpdate.js
  lib/services/computeManagement2/lib/operations/index.d.ts
  lib/services/computeManagement2/lib/operations/virtualMachineScaleSetVMs.js
  lib/services/computeManagement2/lib/operations/virtualMachines.js
Labels: RestPRMerged, in progress

#4510 [AutoPR servicebus/resource-manager] Updated as per review comments from ARM Team for Eventhub swagger
  lib/services/serviceBusManagement2/LICENSE.txt
Labels: RestPRMerged, in progress

#4523 [AutoPR datafactory/resource-manager] [Datafactory] Add Webhook Activity to Azure Data Factory
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/webHookActivity.js
  lib/services/datafactoryManagement/lib/models/webHookActivityAuthentication.js
Labels: RestPRMerged, in progress

#4531 [AutoPR logic/resource-manager] [LogicApps] Fix more acronyms that don't match API
  lib/services/logicManagement/lib/models/aS2AgreementContent.js
  lib/services/logicManagement/lib/models/aS2ErrorSettings.js
  lib/services/logicManagement/lib/models/aS2MdnSettings.js
  lib/services/logicManagement/lib/models/aS2OneWayAgreement.js
  lib/services/logicManagement/lib/models/aS2ProtocolSettings.js
  lib/services/logicManagement/lib/models/aS2SecuritySettings.js
  lib/services/logicManagement/lib/models/agreementContent.js
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/integrationAccountAgreement.js
  lib/services/logicManagement/lib/operations/index.d.ts
  lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
Labels: RestPRMerged, in progress

#4534 [AutoPR] logic/resource-manager
  lib/services/logicManagement/lib/models/aS2AgreementContent.js
  lib/services/logicManagement/lib/models/aS2ErrorSettings.js
  lib/services/logicManagement/lib/models/aS2MdnSettings.js
  lib/services/logicManagement/lib/models/aS2OneWayAgreement.js
  lib/services/logicManagement/lib/models/aS2ProtocolSettings.js
  lib/services/logicManagement/lib/models/aS2SecuritySettings.js
  lib/services/logicManagement/lib/models/agreementContent.js
  lib/services/logicManagement/lib/models/index.d.ts
  lib/services/logicManagement/lib/models/integrationAccountAgreement.js
  lib/services/logicManagement/lib/operations/index.d.ts
  lib/services/logicManagement/lib/operations/integrationAccountAgreements.js
  lib/services/logicManagement/package.json
Labels: ServicePR, in progress

#4528 Add support for custom MSI endpoint
  runtime/ms-rest-azure/.vscode/launch.json
  runtime/ms-rest-azure/lib/credentials/msiVmTokenCredentials.js
  runtime/ms-rest-azure/package.json
  runtime/ms-rest-azure/test/msiAppServiceTokenCredentialTests.js
  runtime/ms-rest-azure/test/msiVmTokenCredentialTests.js
Labels: in progress

#4544 Update autorest.nodejs to 2.2 version
  swagger_to_sdk_config.json
Labels: in progress

#4541 [AutoPR datafactory/resource-manager] [Azure Data Factory] Add winauth support in SSIS Activity
  lib/services/datafactoryManagement/lib/models/executeSSISPackageActivity.js
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
  lib/services/datafactoryManagement/lib/models/sSISExecutionCredential.js
Labels: RestPRMerged, in progress

#4508 [AutoPR monitor/resource-manager] [Hub Generated] Review request for Microsoft.Insights to add version 2018-11-27-preview
  lib/services/monitorManagement/LICENSE.txt
  lib/services/monitorManagement/lib/models/dataContainer.js
  lib/services/monitorManagement/lib/models/errorModel.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/index.js
  lib/services/monitorManagement/lib/models/proxyResource.js
  lib/services/monitorManagement/lib/models/responseWithError.js
  lib/services/monitorManagement/lib/models/vMInsightsOnboardingStatus.js
  lib/services/monitorManagement/lib/models/workspaceInfo.js
  lib/services/monitorManagement/lib/monitorManagementClient.d.ts
  lib/services/monitorManagement/lib/monitorManagementClient.js
  lib/services/monitorManagement/lib/operations/index.d.ts
  lib/services/monitorManagement/lib/operations/index.js
  lib/services/monitorManagement/lib/operations/vMInsights.js
Labels: RestPRMerged, in progress

#4538 [AutoPR eventgrid/data-plane] Add MediaJobOutputProgressEventData in Media Services EventGrid swagger
  lib/services/eventgrid/LICENSE.txt
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/mediaJobOutputProgressEventData.js
Labels: RestPRMerged, in progress

#4540 [AutoPR devspaces/resource-manager] Adding API version 2019-01-01-preview for Microsoft.DevSpaces
  lib/services/devspacesManagement/LICENSE.txt
  lib/services/devspacesManagement/README.md
  lib/services/devspacesManagement/lib/devSpacesManagementClient.d.ts
  lib/services/devspacesManagement/lib/devSpacesManagementClient.js
  lib/services/devspacesManagement/lib/models/containerHostMapping.js
  lib/services/devspacesManagement/lib/models/controller.js
  lib/services/devspacesManagement/lib/models/controllerConnectionDetails.js
  lib/services/devspacesManagement/lib/models/controllerConnectionDetailsList.js
  lib/services/devspacesManagement/lib/models/controllerList.js
  lib/services/devspacesManagement/lib/models/controllerUpdateParameters.js
  lib/services/devspacesManagement/lib/models/errorDetails.js
  lib/services/devspacesManagement/lib/models/errorResponse.js
  lib/services/devspacesManagement/lib/models/index.d.ts
  lib/services/devspacesManagement/lib/models/index.js
  lib/services/devspacesManagement/lib/models/kubernetesConnectionDetails.js
  lib/services/devspacesManagement/lib/models/orchestratorSpecificConnectionDetails.js
  lib/services/devspacesManagement/lib/models/resource.js
  lib/services/devspacesManagement/lib/models/resourceProviderOperationDefinition.js
  lib/services/devspacesManagement/lib/models/resourceProviderOperationDisplay.js
  lib/services/devspacesManagement/lib/models/resourceProviderOperationList.js
  lib/services/devspacesManagement/lib/models/sku.js
  lib/services/devspacesManagement/lib/models/trackedResource.js
  lib/services/devspacesManagement/lib/operations/containerHostMappings.js
  lib/services/devspacesManagement/lib/operations/controllers.js
  lib/services/devspacesManagement/lib/operations/index.d.ts
  lib/services/devspacesManagement/lib/operations/index.js
  lib/services/devspacesManagement/package.json
Labels: RestPRMerged, in progress

#4559 Fix batch SDK version error
  lib/services/batchManagement/package.json
Labels: in progress

#4564 [AutoPR datafactory/resource-manager] Remove webhook activity
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
Labels: RestPRMerged, in progress

#4565 [AutoPR datafactory/resource-manager] Revert DataFactory Validation Activity
  lib/services/datafactoryManagement/lib/models/index.d.ts
  lib/services/datafactoryManagement/lib/models/index.js
Labels: RestPRMerged, in progress

#4573 [AutoPR iothub/resource-manager] Adding JSON encoding type to storage endpoint
  lib/services/iothub/LICENSE.txt
  lib/services/iothub/lib/models/index.d.ts
  lib/services/iothub/lib/models/routingStorageContainerProperties.js
Labels: RestPRMerged, in progress

#4581 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Align with latest released version of Face API with Snapshot features.
  lib/services/cognitiveServicesFace/LICENSE.txt
  lib/services/cognitiveServicesFace/lib/faceClient.d.ts
  lib/services/cognitiveServicesFace/lib/faceClient.js
  lib/services/cognitiveServicesFace/lib/models/applySnapshotRequest.js
  lib/services/cognitiveServicesFace/lib/models/index.d.ts
  lib/services/cognitiveServicesFace/lib/models/index.js
  lib/services/cognitiveServicesFace/lib/models/operationStatus.js
  lib/services/cognitiveServicesFace/lib/models/snapshot.js
  lib/services/cognitiveServicesFace/lib/models/takeSnapshotRequest.js
  lib/services/cognitiveServicesFace/lib/models/updateSnapshotRequest.js
  lib/services/cognitiveServicesFace/lib/operations/index.d.ts
  lib/services/cognitiveServicesFace/lib/operations/index.js
  lib/services/cognitiveServicesFace/lib/operations/snapshotOperations.js
Labels: RestPRMerged, in progress

#4575 [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get
  lib/services/securityManagement/lib/operations/index.d.ts
  lib/services/securityManagement/lib/operations/workspaceSettings.js
Labels: RestPRMerged, in progress

#4583 Use matrix for vmImage parallelism
  .azure-pipelines/client.test.yml
  .azure-pipelines/client.yml
Labels: in progress

#4570 [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices
  lib/services/recoveryServicesBackupManagement/lib/models/azureIaaSVMJobTaskDetails.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureVmWorkloadItem.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureVmWorkloadProtectableItem.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadRecoveryPoint.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSAPHanaRecoveryPoint.js
  lib/services/recoveryServicesBackupManagement/lib/models/azureWorkloadSQLRecoveryPoint.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBase.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupEngineBaseResource.js
  lib/services/recoveryServicesBackupManagement/lib/models/backupEngineExtendedInfo.js
  lib/services/recoveryServicesBackupManagement/lib/models/dPMProtectedItem.js
  lib/services/recoveryServicesBackupManagement/lib/models/index.d.ts
  lib/services/recoveryServicesBackupManagement/lib/models/keyAndSecretDetails.js
Labels: RestPRMerged, in progress

#4545 [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.
  lib/services/cognitiveServicesManagement/LICENSE.txt
  lib/services/cognitiveServicesManagement/lib/models/cognitiveServicesAccount.js
  lib/services/cognitiveServicesManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4498 [AutoPR resources/resource-manager] Adding ResourceGroup example
  lib/services/resourceManagement/LICENSE.txt
Labels: RestPRMerged, in progress

#4592 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features.
  lib/services/cognitiveServicesFace/lib/models/findSimilarRequest.js
  lib/services/cognitiveServicesFace/lib/models/index.d.ts
  lib/services/cognitiveServicesFace/lib/operations/face.js
  lib/services/cognitiveServicesFace/lib/operations/index.d.ts
  lib/services/cognitiveServicesFace/lib/operations/snapshotOperations.js
Labels: RestPRMerged, in progress

#4595 [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
Labels: RestPRMerged, in progress

#4597 [AutoPR hanaonazure/resource-manager] Add new field 'proximityPlacementGroup' to properties of HanaInstance
  lib/services/hanaonazureManagement/lib/models/hanaInstance.js
  lib/services/hanaonazureManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4594 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add dispatch child to LUIS Runtime response
  lib/services/luis/runtime/LICENSE.txt
  lib/services/luis/runtime/README.md
  lib/services/luis/runtime/lib/models/index.d.ts
  lib/services/luis/runtime/lib/models/luisResult.js
Labels: RestPRMerged, in progress

#4119 [AutoPR] hdinsight/resource-manager
  lib/services/hdInsightManagement/LICENSE.txt
  lib/services/hdInsightManagement/lib/models/index.d.ts
  lib/services/hdInsightManagement/lib/models/storageAccount.js
  lib/services/hdInsightManagement/package.json
Labels: ServicePR, in progress

#4606 [AutoPR sql/resource-manager] Update managedInstances.json
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/managedInstance.js
  lib/services/sqlManagement2/lib/models/managedInstanceUpdate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/managedInstances.js
Labels: RestPRMerged, in progress

#4611 Update azure-cognitiveservices-computervision version to 3.2.1
  lib/services/computerVision/package.json
Labels: in progress

#4599 [AutoPR eventgrid/data-plane] Add Helm Events to ACR Schema for Event Grid
  lib/services/eventgrid/lib/models/containerRegistryArtifactEventData.js
  lib/services/eventgrid/lib/models/containerRegistryArtifactEventTarget.js
  lib/services/eventgrid/lib/models/containerRegistryChartDeletedEventData.js
  lib/services/eventgrid/lib/models/containerRegistryChartPushedEventData.js
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
Labels: RestPRMerged, in progress

#4608 [AutoPR resourcehealth/resource-manager] Resourcehealth events response
  lib/services/resourceHealthManagement/LICENSE.txt
Labels: RestPRMerged, in progress

#4598 [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription
  lib/services/eventHubManagement/LICENSE.txt
  lib/services/eventHubManagement/lib/models/captureDescription.js
  lib/services/eventHubManagement/lib/models/eventhub.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/operations/eventHubs.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
Labels: RestPRMerged, in progress
