Repository Azure/azure-sdk-for-node, pull requests merged in 2019-02, with the labels that each got.

#4623 [AutoPR recoveryservicesbackup/resource-manager] Fixing a minor bug in Recovery Services (Backup)
  lib/services/recoveryServicesBackupManagement/lib/models/backupStatusResponse.js
  lib/services/recoveryServicesBackupManagement/lib/models/index.d.ts
  lib/services/recoveryServicesBackupManagement/lib/models/preValidateEnableBackupRequest.js
  lib/services/recoveryServicesBackupManagement/lib/operations/index.d.ts
  lib/services/recoveryServicesBackupManagement/lib/operations/protectionIntentOperations.js
Labels: RestPRMerged, in progress

#4624 [AutoPR policyinsights/resource-manager] [Hub Generated] Review request for Microsoft.PolicyInsights to add version 2018-07-01-preview
  lib/services/policyinsightsManagement/LICENSE.txt
  lib/services/policyinsightsManagement/lib/models/expressionEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/ifNotExistsEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/index.d.ts
  lib/services/policyinsightsManagement/lib/models/index.js
  lib/services/policyinsightsManagement/lib/models/policyEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/policyState.js
  lib/services/policyinsightsManagement/lib/models/queryOptions.js
  lib/services/policyinsightsManagement/lib/operations/index.d.ts
  lib/services/policyinsightsManagement/lib/operations/operations.js
  lib/services/policyinsightsManagement/lib/operations/policyEvents.js
  lib/services/policyinsightsManagement/lib/operations/policyStates.js
  lib/services/policyinsightsManagement/lib/operations/policyTrackedResources.js
  lib/services/policyinsightsManagement/lib/operations/remediations.js
Labels: RestPRMerged, in progress

#4622 [AutoPR security/resource-manager] Adding new api-version to Microsoft.Security Alerts resource
  lib/services/securityManagement/lib/models/alert.js
  lib/services/securityManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4621 Add script to print package deprecation message
  runtime/ms-rest/.scripts/postinstall.js
  runtime/ms-rest/package.json
Labels: Planned-Sprint-130, in progress

#4634 [AutoPR containerservice/resource-manager] Revert "[AKS] add apiServerAuthorizedIPRanges property"
  lib/services/containerservicesManagement/lib/models/index.d.ts
  lib/services/containerservicesManagement/lib/models/managedCluster.js
  lib/services/containerservicesManagement/lib/operations/index.d.ts
  lib/services/containerservicesManagement/lib/operations/managedClusters.js
Labels: RestPRMerged, in progress

#4620 [AutoPR securityinsights/resource-manager] Adding data connectors APIs
  lib/services/securityInsightManagement/lib/models/aADDataConnector.js
  lib/services/securityInsightManagement/lib/models/aSCDataConnector.js
  lib/services/securityInsightManagement/lib/models/alertsDataTypeOfDataConnector.js
  lib/services/securityInsightManagement/lib/models/alertsDataTypeOfDataConnectorAlerts.js
  lib/services/securityInsightManagement/lib/models/dataConnector.js
  lib/services/securityInsightManagement/lib/models/dataConnectorContextId.js
  lib/services/securityInsightManagement/lib/models/dataConnectorDataTypeCommon.js
  lib/services/securityInsightManagement/lib/models/dataConnectorKind1.js
  lib/services/securityInsightManagement/lib/models/dataConnectorList.js
  lib/services/securityInsightManagement/lib/models/dataConnectorWithAlerts.js
  lib/services/securityInsightManagement/lib/models/index.d.ts
  lib/services/securityInsightManagement/lib/models/index.js
  lib/services/securityInsightManagement/lib/models/mCASDataConnector.js
  lib/services/securityInsightManagement/lib/models/officeDataConnector.js
  lib/services/securityInsightManagement/lib/models/officeDataConnectorDataTypes.js
  lib/services/securityInsightManagement/lib/models/officeDataConnectorDataTypesExchange.js
  lib/services/securityInsightManagement/lib/models/officeDataConnectorDataTypesSharePoint.js
  lib/services/securityInsightManagement/lib/models/tIDataConnector.js
  lib/services/securityInsightManagement/lib/models/tIDataConnectorDataTypes.js
  lib/services/securityInsightManagement/lib/models/tIDataConnectorDataTypesIndicators.js
  lib/services/securityInsightManagement/lib/operations/dataConnectors.js
  lib/services/securityInsightManagement/lib/operations/index.d.ts
  lib/services/securityInsightManagement/lib/operations/index.js
  lib/services/securityInsightManagement/lib/securityInsights.d.ts
  lib/services/securityInsightManagement/lib/securityInsights.js
Labels: RestPRMerged, in progress

#4639 Remove duplicated exports in ms-rest-azure
  runtime/ms-rest-azure/lib/subscriptionManagement/models/index.js
  runtime/ms-rest-azure/package.json
Labels: Unplanned-Sprint-131, in progress

#4642 [AutoPR compute/resource-manager] fixes for reference documentation
  lib/services/computeManagement2/lib/models/index.d.ts
  lib/services/computeManagement2/lib/models/vaultCertificate.js
Labels: RestPRMerged, in progress

#4636 [AutoPR authorization/resource-manager] Removed "x-ms-pageable" from the elevateAccess API
  lib/services/authorizationManagement/LICENSE.txt
Labels: RestPRMerged, in progress

#4645 Update deprecation message
  runtime/ms-rest/.scripts/postinstall.js
  runtime/ms-rest/package.json
Labels: Unplanned-Sprint-131, in progress

#4648 Regenerate azure-arm-kusto package
  lib/services/kustoManagement/LICENSE.txt
  lib/services/kustoManagement/README.md
  lib/services/kustoManagement/lib/kustoManagementClient.d.ts
  lib/services/kustoManagement/lib/kustoManagementClient.js
  lib/services/kustoManagement/lib/models/azureCapacity.js
  lib/services/kustoManagement/lib/models/azureResourceSku.js
  lib/services/kustoManagement/lib/models/azureSku.js
  lib/services/kustoManagement/lib/models/checkNameResult.js
  lib/services/kustoManagement/lib/models/cluster.js
  lib/services/kustoManagement/lib/models/clusterCheckNameRequest.js
  lib/services/kustoManagement/lib/models/clusterUpdate.js
  lib/services/kustoManagement/lib/models/dataConnection.js
  lib/services/kustoManagement/lib/models/dataConnectionListResult.js
  lib/services/kustoManagement/lib/models/dataConnectionValidation.js
  lib/services/kustoManagement/lib/models/dataConnectionValidationListResult.js
  lib/services/kustoManagement/lib/models/dataConnectionValidationResult.js
  lib/services/kustoManagement/lib/models/database.js
  lib/services/kustoManagement/lib/models/databaseCheckNameRequest.js
  lib/services/kustoManagement/lib/models/databasePrincipal.js
  lib/services/kustoManagement/lib/models/databaseStatistics.js
  lib/services/kustoManagement/lib/models/databaseUpdate.js
  lib/services/kustoManagement/lib/models/eventGridDataConnection.js
  lib/services/kustoManagement/lib/models/eventHubConnectionUpdate.js
  lib/services/kustoManagement/lib/models/eventHubDataConnection.js
  lib/services/kustoManagement/lib/models/index.d.ts
  lib/services/kustoManagement/lib/models/index.js
  lib/services/kustoManagement/lib/models/trustedExternalTenant.js
  lib/services/kustoManagement/lib/operations/clusters.js
  lib/services/kustoManagement/lib/operations/dataConnections.js
  lib/services/kustoManagement/lib/operations/databases.js
  lib/services/kustoManagement/lib/operations/index.d.ts
  lib/services/kustoManagement/lib/operations/index.js
  lib/services/kustoManagement/package.json
Labels: in progress

#4651 Remove postinstall script from azure-arm-kusto
  lib/services/kustoManagement/package.json
Labels: in progress

#4652 Remove priting deprecation message
  runtime/ms-rest/.scripts/postinstall.js
  runtime/ms-rest/package.json
Labels: Unplanned-Sprint-131, in progress

#4647 [AutoPR policyinsights/resource-manager] typo: aliase -> alias
  lib/services/policyinsightsManagement/lib/models/expressionEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4653 [AutoPR keyvault/resource-manager] add description of access policies required condition
  lib/services/keyVaultManagement/LICENSE.txt
  lib/services/keyVaultManagement/lib/models/index.d.ts
  lib/services/keyVaultManagement/lib/models/vault.js
  lib/services/keyVaultManagement/lib/models/vaultCreateOrUpdateParameters.js
  lib/services/keyVaultManagement/lib/models/vaultProperties.js
  lib/services/keyVaultManagement/lib/operations/index.d.ts
  lib/services/keyVaultManagement/lib/operations/vaults.js
Labels: RestPRMerged, in progress

#4656 Add postinstall script to azure-arm-kusto package
  lib/services/kustoManagement/.scripts/postinstall.js
  lib/services/kustoManagement/package.json
Labels: in progress

#4600 [AutoPR] cognitiveservices/data-plane/LUIS/Runtime
  lib/services/luis/runtime/.scripts/postinstall.js
  lib/services/luis/runtime/LICENSE.txt
  lib/services/luis/runtime/README.md
  lib/services/luis/runtime/lib/models/index.d.ts
  lib/services/luis/runtime/lib/models/luisResult.js
  lib/services/luis/runtime/package.json
Labels: ServicePR

#4629 [AutoPR eventgrid/data-plane] [Event-Grid Maps] Add Maps publisher schema to EventGrid data-plane
  lib/services/eventgrid/lib/models/index.d.ts
  lib/services/eventgrid/lib/models/index.js
  lib/services/eventgrid/lib/models/mapsGeofenceEnteredEventData.js
  lib/services/eventgrid/lib/models/mapsGeofenceEventProperties.js
  lib/services/eventgrid/lib/models/mapsGeofenceExitedEventData.js
  lib/services/eventgrid/lib/models/mapsGeofenceGeometry.js
  lib/services/eventgrid/lib/models/mapsGeofenceResultEventData.js
Labels: RestPRMerged, in progress

#4664 [AutoPR operationalinsights/resource-manager] Add gateways API
  lib/services/operationalInsightsManagement/LICENSE.txt
Labels: RestPRMerged, in progress

#4630 [AutoPR cognitiveservices/data-plane/ComputerVision] Analyze brands
  lib/services/computerVision/lib/computerVisionClient.d.ts
  lib/services/computerVision/lib/computerVisionClient.js
  lib/services/computerVision/lib/models/detectedBrand.js
  lib/services/computerVision/lib/models/imageAnalysis.js
  lib/services/computerVision/lib/models/index.d.ts
  lib/services/computerVision/lib/models/index.js
Labels: RestPRMerged

#4673 Remove extra LICENSE and package.json files
  lib/services/applicationinsights/lib/LICENSE.txt
  lib/services/applicationinsights/lib/package.json
  lib/services/consumptionManagement/lib/LICENSE.txt
  lib/services/consumptionManagement/lib/package.json
  lib/services/databox/lib/LICENSE.txt
  lib/services/databox/lib/package.json
Labels: Started-Sprint-131, Unplanned-Sprint-131, in progress

#4677 [AutoPR privatedns/resource-manager] Adding Private DNS Swagger spec for API version 2018-09-01
  lib/services/privateDnsManagement/LICENSE.txt
  lib/services/privateDnsManagement/README.md
  lib/services/privateDnsManagement/lib/models/aRecord.js
  lib/services/privateDnsManagement/lib/models/aaaaRecord.js
  lib/services/privateDnsManagement/lib/models/cnameRecord.js
  lib/services/privateDnsManagement/lib/models/index.d.ts
  lib/services/privateDnsManagement/lib/models/index.js
  lib/services/privateDnsManagement/lib/models/mxRecord.js
  lib/services/privateDnsManagement/lib/models/privateZone.js
  lib/services/privateDnsManagement/lib/models/privateZoneListResult.js
  lib/services/privateDnsManagement/lib/models/proxyResource.js
  lib/services/privateDnsManagement/lib/models/ptrRecord.js
  lib/services/privateDnsManagement/lib/models/recordSet.js
  lib/services/privateDnsManagement/lib/models/recordSetListResult.js
  lib/services/privateDnsManagement/lib/models/resource.js
  lib/services/privateDnsManagement/lib/models/soaRecord.js
  lib/services/privateDnsManagement/lib/models/srvRecord.js
  lib/services/privateDnsManagement/lib/models/subResource.js
  lib/services/privateDnsManagement/lib/models/trackedResource.js
  lib/services/privateDnsManagement/lib/models/txtRecord.js
  lib/services/privateDnsManagement/lib/models/virtualNetworkLink.js
  lib/services/privateDnsManagement/lib/models/virtualNetworkLinkListResult.js
  lib/services/privateDnsManagement/lib/operations/index.d.ts
  lib/services/privateDnsManagement/lib/operations/index.js
  lib/services/privateDnsManagement/lib/operations/privateZones.js
  lib/services/privateDnsManagement/lib/operations/recordSets.js
  lib/services/privateDnsManagement/lib/operations/virtualNetworkLinks.js
  lib/services/privateDnsManagement/lib/privateDnsManagementClient.d.ts
  lib/services/privateDnsManagement/lib/privateDnsManagementClient.js
  lib/services/privateDnsManagement/package.json
Labels: RestPRMerged, in progress

#4686 [AutoPR securityinsights/resource-manager] typo: securityinsights/resource-manager/Microsoft.SecurityInsights
  lib/services/securityInsightManagement/lib/models/accountEntity.js
  lib/services/securityInsightManagement/lib/models/hostEntity.js
  lib/services/securityInsightManagement/lib/models/index.d.ts
  lib/services/securityInsightManagement/lib/models/officeConsent.js
  lib/services/securityInsightManagement/lib/operations/index.d.ts
  lib/services/securityInsightManagement/lib/operations/productSettings.js
Labels: RestPRMerged, in progress

#4685 [AutoPR postgresql/resource-manager] Add server creation parameters to Postgres ResourceProvider for SDK
  lib/services/postgresqlManagement/LICENSE.txt
Labels: RestPRMerged, in progress

#4619 [AutoPR cognitiveservices/data-plane/AnomalyFinder] Add cognitive service AnomalyFinder
  lib/services/cognitiveServicesAnomalyFinder/LICENSE.txt
  lib/services/cognitiveServicesAnomalyFinder/README.md
  lib/services/cognitiveServicesAnomalyFinder/lib/anomalyFinder.d.ts
  lib/services/cognitiveServicesAnomalyFinder/lib/anomalyFinder.js
  lib/services/cognitiveServicesAnomalyFinder/lib/anomalyFinderClient.d.ts
  lib/services/cognitiveServicesAnomalyFinder/lib/anomalyFinderClient.js
  lib/services/cognitiveServicesAnomalyFinder/lib/models/aPIError.js
  lib/services/cognitiveServicesAnomalyFinder/lib/models/entireDetectResponse.js
  lib/services/cognitiveServicesAnomalyFinder/lib/models/index.d.ts
  lib/services/cognitiveServicesAnomalyFinder/lib/models/index.js
  lib/services/cognitiveServicesAnomalyFinder/lib/models/lastDetectResponse.js
  lib/services/cognitiveServicesAnomalyFinder/lib/models/point.js
  lib/services/cognitiveServicesAnomalyFinder/lib/models/request.js
  lib/services/cognitiveServicesAnomalyFinder/package.json
Labels: RestPRMerged, in progress

#4687 Adding .docsettings file. Adding Readme analysis to CI.
  .azure-pipelines/client.yml
  .docsettings.yml
Labels: EngSys, in progress

#4695 [AutoPR cognitiveservices/data-plane/LUIS/Authoring] [Cogsvcs] LUIS - add text to simple entity description
  lib/services/luis/authoring/LICENSE.txt
  lib/services/luis/authoring/lib/operations/index.d.ts
  lib/services/luis/authoring/lib/operations/model.js
Labels: RestPRMerged, in progress

#4675 [AutoPR hanaonazure/resource-manager] Add hwRevision field to HanaInstance definition
  lib/services/hanaonazureManagement/lib/models/hanaInstance.js
  lib/services/hanaonazureManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4669 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Remove Face API reference of Gender::genderless to avoid confusion.
  lib/services/cognitiveServicesFace/lib/models/detectedFace.js
  lib/services/cognitiveServicesFace/lib/models/faceAttributes.js
  lib/services/cognitiveServicesFace/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4698 [AutoPR machinelearning/resource-manager] Add an Operations API for Commitment Plan RP
  lib/services/machinelearning/lib/commitmentPlan/azureMLCommitmentPlansManagementClient.d.ts
  lib/services/machinelearning/lib/commitmentPlan/azureMLCommitmentPlansManagementClient.js
  lib/services/machinelearning/lib/commitmentPlan/models/index.d.ts
  lib/services/machinelearning/lib/commitmentPlan/models/index.js
  lib/services/machinelearning/lib/commitmentPlan/models/operationDisplayInfo.js
  lib/services/machinelearning/lib/commitmentPlan/models/operationEntity.js
  lib/services/machinelearning/lib/commitmentPlan/models/operationEntityListResult.js
  lib/services/machinelearning/lib/commitmentPlan/models/skuCapability.js
  lib/services/machinelearning/lib/commitmentPlan/operations/index.d.ts
  lib/services/machinelearning/lib/commitmentPlan/operations/index.js
  lib/services/machinelearning/lib/commitmentPlan/operations/operations.js
  lib/services/machinelearning/lib/webservices/models/index.d.ts
  lib/services/machinelearning/lib/webservices/models/webService.js
  lib/services/machinelearning/lib/webservices/models/webServiceProperties.js
  lib/services/machinelearning/lib/webservices/operations/index.d.ts
  lib/services/machinelearning/lib/webservices/operations/webServices.js
Labels: RestPRMerged, in progress

#4720 Fix deprecation message for already generated packages
  lib/services/kustoManagement/.scripts/postinstall.js
  lib/services/kustoManagement/package.json
  lib/services/luis/authoring/.scripts/postinstall.js
  lib/services/luis/authoring/package.json
  lib/services/luis/runtime/.scripts/postinstall.js
  lib/services/luis/runtime/package.json
Labels: in progress

#4729 Remove deprecation warning message from azure-cognitiveservices-luis-…
  lib/services/luis/runtime/package.json
Labels: in progress

#4732 [AutoPR resourcehealth/resource-manager] Updating the events api response for the changed contract
  lib/services/resourceHealthManagement/LICENSE.txt
  lib/services/resourceHealthManagement/README.md
  lib/services/resourceHealthManagement/lib/microsoftResourceHealth.d.ts
  lib/services/resourceHealthManagement/lib/microsoftResourceHealth.js
  lib/services/resourceHealthManagement/lib/models/availabilityStatus.js
  lib/services/resourceHealthManagement/lib/models/availabilityStatusListResult.js
  lib/services/resourceHealthManagement/lib/models/availabilityStatusProperties.js
  lib/services/resourceHealthManagement/lib/models/availabilityStatusPropertiesRecentlyResolvedState.js
  lib/services/resourceHealthManagement/lib/models/errorResponse.js
  lib/services/resourceHealthManagement/lib/models/index.d.ts
  lib/services/resourceHealthManagement/lib/models/operation.js
  lib/services/resourceHealthManagement/lib/models/operationDisplay.js
  lib/services/resourceHealthManagement/lib/models/operationListResult.js
  lib/services/resourceHealthManagement/lib/models/recommendedAction.js
  lib/services/resourceHealthManagement/lib/models/serviceImpactingEvent.js
  lib/services/resourceHealthManagement/lib/models/serviceImpactingEventIncidentProperties.js
  lib/services/resourceHealthManagement/lib/models/serviceImpactingEventStatus.js
  lib/services/resourceHealthManagement/lib/operations/childAvailabilityStatuses.js
  lib/services/resourceHealthManagement/lib/operations/childResources.js
  lib/services/resourceHealthManagement/lib/operations/index.d.ts
  lib/services/resourceHealthManagement/lib/operations/index.js
  lib/services/resourceHealthManagement/package.json
Labels: RestPRMerged, in progress

#4760 [AutoPR search/resource-manager] [WaitForARMFeedback] Add api get_services_by_subscription of Azure Search
  lib/services/searchManagement/LICENSE.txt
  lib/services/searchManagement/README.md
  lib/services/searchManagement/lib/models/adminKeyResult.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityInput.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityOutput.js
  lib/services/searchManagement/lib/models/identity.js
  lib/services/searchManagement/lib/models/index.d.ts
  lib/services/searchManagement/lib/models/operation.js
  lib/services/searchManagement/lib/models/operationDisplay.js
  lib/services/searchManagement/lib/models/operationListResult.js
  lib/services/searchManagement/lib/models/queryKey.js
  lib/services/searchManagement/lib/models/resource.js
  lib/services/searchManagement/lib/models/searchManagementRequestOptions.js
  lib/services/searchManagement/lib/models/searchService.js
  lib/services/searchManagement/lib/models/sku.js
  lib/services/searchManagement/lib/operations/adminKeys.js
  lib/services/searchManagement/lib/operations/index.d.ts
  lib/services/searchManagement/lib/operations/queryKeys.js
  lib/services/searchManagement/lib/operations/services.js
  lib/services/searchManagement/lib/searchManagementClient.d.ts
  lib/services/searchManagement/lib/searchManagementClient.js
  lib/services/searchManagement/package.json
Labels: RestPRMerged

#4741 [AutoPR imagebuilder/resource-manager] Add private preview API for Azure Image Builder
  lib/services/imagebuilderManagement/LICENSE.txt
  lib/services/imagebuilderManagement/README.md
  lib/services/imagebuilderManagement/lib/imageBuilderClient.d.ts
  lib/services/imagebuilderManagement/lib/imageBuilderClient.js
  lib/services/imagebuilderManagement/lib/models/apiError.js
  lib/services/imagebuilderManagement/lib/models/apiErrorBase.js
  lib/services/imagebuilderManagement/lib/models/imageTemplate.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateCustomizer.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateDistributor.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateIsoSource.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateLastRunStatus.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateListResult.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateManagedImageDistributor.js
  lib/services/imagebuilderManagement/lib/models/imageTemplatePlatformImageSource.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateSharedImageDistributor.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateShellCustomizer.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateSource.js
  lib/services/imagebuilderManagement/lib/models/imageTemplateUpdateParameters.js
  lib/services/imagebuilderManagement/lib/models/index.d.ts
  lib/services/imagebuilderManagement/lib/models/index.js
  lib/services/imagebuilderManagement/lib/models/innerError.js
  lib/services/imagebuilderManagement/lib/models/operation.js
  lib/services/imagebuilderManagement/lib/models/operationDisplay.js
  lib/services/imagebuilderManagement/lib/models/operationListResult.js
  lib/services/imagebuilderManagement/lib/models/provisioningError.js
  lib/services/imagebuilderManagement/lib/models/resource.js
  lib/services/imagebuilderManagement/lib/models/runOutput.js
  lib/services/imagebuilderManagement/lib/models/runOutputCollection.js
  lib/services/imagebuilderManagement/lib/models/subResource.js
  lib/services/imagebuilderManagement/lib/operations/index.d.ts
  lib/services/imagebuilderManagement/lib/operations/index.js
  lib/services/imagebuilderManagement/lib/operations/operations.js
  lib/services/imagebuilderManagement/lib/operations/virtualMachineImageTemplate.js
  lib/services/imagebuilderManagement/package.json
Labels: RestPRMerged, in progress

#4768 [AutoPR mariadb/resource-manager] Update MariaDB api version
  lib/services/mariadbManagement/LICENSE.txt
  lib/services/mariadbManagement/README.md
  lib/services/mariadbManagement/lib/models/configuration.js
  lib/services/mariadbManagement/lib/models/database.js
  lib/services/mariadbManagement/lib/models/firewallRule.js
  lib/services/mariadbManagement/lib/models/index.d.ts
  lib/services/mariadbManagement/lib/models/logFile.js
  lib/services/mariadbManagement/lib/models/nameAvailability.js
  lib/services/mariadbManagement/lib/models/nameAvailabilityRequest.js
  lib/services/mariadbManagement/lib/models/operation.js
  lib/services/mariadbManagement/lib/models/operationDisplay.js
  lib/services/mariadbManagement/lib/models/operationListResult.js
  lib/services/mariadbManagement/lib/models/performanceTierProperties.js
  lib/services/mariadbManagement/lib/models/performanceTierServiceLevelObjectives.js
  lib/services/mariadbManagement/lib/models/proxyResource.js
  lib/services/mariadbManagement/lib/models/server.js
  lib/services/mariadbManagement/lib/models/serverForCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForDefaultCreate.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForGeoRestore.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForRestore.js
  lib/services/mariadbManagement/lib/models/serverSecurityAlertPolicy.js
  lib/services/mariadbManagement/lib/models/serverUpdateParameters.js
  lib/services/mariadbManagement/lib/models/sku.js
  lib/services/mariadbManagement/lib/models/storageProfile.js
  lib/services/mariadbManagement/lib/models/trackedResource.js
  lib/services/mariadbManagement/lib/models/virtualNetworkRule.js
  lib/services/mariadbManagement/lib/models/virtualNetworkRuleListResult.js
  lib/services/mariadbManagement/package.json
Labels: RestPRMerged, in progress

#4756 [AutoPR security/resource-manager] Security - Updating API versions of alerts and pricing types
  lib/services/securityManagement/lib/models/alert.js
  lib/services/securityManagement/lib/models/index.d.ts
  lib/services/securityManagement/lib/models/index.js
  lib/services/securityManagement/lib/models/pricing.js
  lib/services/securityManagement/lib/models/pricingList.js
  lib/services/securityManagement/lib/operations/alerts.js
  lib/services/securityManagement/lib/operations/index.d.ts
  lib/services/securityManagement/lib/operations/pricings.js
Labels: RestPRMerged, in progress

#4723 [AutoPR machinelearning/resource-manager] typo: asscociation -> association
  lib/services/machinelearning/lib/commitmentPlan/azureMLCommitmentPlansManagementClient.d.ts
  lib/services/machinelearning/lib/commitmentPlan/azureMLCommitmentPlansManagementClient.js
  lib/services/machinelearning/lib/commitmentPlan/models/index.d.ts
  lib/services/machinelearning/lib/commitmentPlan/models/index.js
  lib/services/machinelearning/lib/commitmentPlan/models/operationDisplayInfo.js
  lib/services/machinelearning/lib/commitmentPlan/models/operationEntity.js
  lib/services/machinelearning/lib/commitmentPlan/models/operationEntityListResult.js
  lib/services/machinelearning/lib/commitmentPlan/models/skuCapability.js
  lib/services/machinelearning/lib/commitmentPlan/operations/index.d.ts
  lib/services/machinelearning/lib/commitmentPlan/operations/index.js
  lib/services/machinelearning/lib/commitmentPlan/operations/operations.js
  lib/services/machinelearning/lib/webservices/models/index.d.ts
  lib/services/machinelearning/lib/webservices/models/webService.js
  lib/services/machinelearning/lib/webservices/models/webServiceProperties.js
  lib/services/machinelearning/lib/webservices/operations/index.d.ts
  lib/services/machinelearning/lib/webservices/operations/webServices.js
Labels: RestPRMerged, in progress

#4789 Update pipeline job names and dependencies
  .azure-pipelines/client.yml
Labels: in progress
