Repository Azure/azure-sdk-for-node, pull requests merged in 2019-03, with the labels that each got.

#4797 [AutoPR network/resource-manager] Network: fix descriptions & remove unused/duplicate definitions
  lib/services/networkManagement2/lib/models/applicationGatewayProbe.js
  lib/services/networkManagement2/lib/models/expressRouteCircuit.js
  lib/services/networkManagement2/lib/models/expressRouteCircuitPeering.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/models/index.js
  lib/services/networkManagement2/lib/models/p2SVpnServerConfiguration.js
  lib/services/networkManagement2/lib/models/peerExpressRouteCircuitConnection.js
  lib/services/networkManagement2/lib/models/peerExpressRouteCircuitConnectionListResult.js
  lib/services/networkManagement2/lib/models/serviceEndpointPolicyDefinition.js
  lib/services/networkManagement2/lib/models/virtualHub.js
  lib/services/networkManagement2/lib/models/virtualHubRoute.js
  lib/services/networkManagement2/lib/models/virtualHubRouteTable.js
  lib/services/networkManagement2/lib/models/virtualNetworkConnectionGatewayReference.js
  lib/services/networkManagement2/lib/models/virtualWAN.js
  lib/services/networkManagement2/lib/models/vpnConnection.js
  lib/services/networkManagement2/lib/models/vpnGateway.js
  lib/services/networkManagement2/lib/networkManagementClient.d.ts
  lib/services/networkManagement2/lib/networkManagementClient.js
  lib/services/networkManagement2/lib/operations/expressRouteCircuits.js
  lib/services/networkManagement2/lib/operations/index.d.ts
  lib/services/networkManagement2/lib/operations/index.js
  lib/services/networkManagement2/lib/operations/p2sVpnServerConfigurations.js
  lib/services/networkManagement2/lib/operations/peerExpressRouteCircuitConnections.js
  lib/services/networkManagement2/lib/operations/serviceEndpointPolicyDefinitions.js
  lib/services/networkManagement2/lib/operations/virtualHubs.js
  lib/services/networkManagement2/lib/operations/virtualWans.js
  lib/services/networkManagement2/lib/operations/vpnConnections.js
  lib/services/networkManagement2/lib/operations/vpnGateways.js
Labels: RestPRMerged

#4794 [AutoPR mariadb/resource-manager] Update MariaDB default API version to 2018-06-01
  lib/services/mariadbManagement/lib/mariaDBManagementClient.d.ts
  lib/services/mariadbManagement/lib/mariaDBManagementClient.js
  lib/services/mariadbManagement/lib/models/index.d.ts
  lib/services/mariadbManagement/lib/models/index.js
  lib/services/mariadbManagement/lib/models/server.js
  lib/services/mariadbManagement/lib/models/serverPropertiesForReplica.js
  lib/services/mariadbManagement/lib/models/serverUpdateParameters.js
  lib/services/mariadbManagement/lib/operations/index.d.ts
  lib/services/mariadbManagement/lib/operations/index.js
  lib/services/mariadbManagement/lib/operations/replicas.js
  lib/services/mariadbManagement/lib/operations/servers.js
Labels: RestPRMerged, in progress

#4740 [AutoPR apimanagement/resource-manager] Apim Cache resource + DELETE long running + refactor to align with tooling.
  lib/services/apimanagement/LICENSE.txt
  lib/services/apimanagement/lib/apiManagementClient.d.ts
  lib/services/apimanagement/lib/apiManagementClient.js
  lib/services/apimanagement/lib/models/apiManagementServiceBaseProperties.js
  lib/services/apimanagement/lib/models/apiManagementServiceResource.js
  lib/services/apimanagement/lib/models/apiManagementServiceUpdateParameters.js
  lib/services/apimanagement/lib/models/backendBaseParameters.js
  lib/services/apimanagement/lib/models/backendContract.js
  lib/services/apimanagement/lib/models/backendProperties.js
  lib/services/apimanagement/lib/models/backendReconnectContract.js
  lib/services/apimanagement/lib/models/backendServiceFabricClusterProperties.js
  lib/services/apimanagement/lib/models/backendUpdateParameters.js
  lib/services/apimanagement/lib/models/certificateConfiguration.js
  lib/services/apimanagement/lib/models/index.d.ts
  lib/services/apimanagement/lib/models/index.js
  lib/services/apimanagement/lib/models/reportRecordContract.js
  lib/services/apimanagement/lib/models/requestReportRecordContract.js
  lib/services/apimanagement/lib/models/resourceSku.js
  lib/services/apimanagement/lib/models/resourceSkuCapacity.js
  lib/services/apimanagement/lib/models/resourceSkuResult.js
  lib/services/apimanagement/lib/models/resourceSkuResults.js
  lib/services/apimanagement/lib/models/subscriptionCreateParameters.js
  lib/services/apimanagement/lib/operations/apiDiagnosticLogger.js
  lib/services/apimanagement/lib/operations/apiIssue.js
  lib/services/apimanagement/lib/operations/apiIssueAttachment.js
  lib/services/apimanagement/lib/operations/apiIssueComment.js
  lib/services/apimanagement/lib/operations/apiManagementService.js
  lib/services/apimanagement/lib/operations/apiManagementServiceSkus.js
  lib/services/apimanagement/lib/operations/backend.js
  lib/services/apimanagement/lib/operations/diagnosticLogger.js
  lib/services/apimanagement/lib/operations/index.d.ts
  lib/services/apimanagement/lib/operations/index.js
  lib/services/apimanagement/lib/operations/property.js
  lib/services/apimanagement/lib/operations/reports.js
  lib/services/apimanagement/lib/operations/subscription.js
  lib/services/apimanagement/lib/operations/tagDescription.js
Labels: RestPRMerged, in progress

#4807 [AutoPR sql/resource-manager] Update Swagger Files For ManagedInstanceAdministrator
  lib/services/sqlManagement2/lib/models/index.d.ts
  lib/services/sqlManagement2/lib/models/index.js
  lib/services/sqlManagement2/lib/models/virtualCluster.js
  lib/services/sqlManagement2/lib/models/virtualClusterListResult.js
  lib/services/sqlManagement2/lib/models/virtualClusterUpdate.js
  lib/services/sqlManagement2/lib/operations/index.d.ts
  lib/services/sqlManagement2/lib/operations/index.js
  lib/services/sqlManagement2/lib/operations/virtualClusters.js
  lib/services/sqlManagement2/lib/sqlManagementClient.d.ts
  lib/services/sqlManagement2/lib/sqlManagementClient.js
Labels: RestPRMerged

#4813 [AutoPR marketplaceordering/resource-manager] Add missing MarketplaceOrdering operations to swagger
  lib/services/marketplaceorderingManagement/LICENSE.txt
  lib/services/marketplaceorderingManagement/README.md
  lib/services/marketplaceorderingManagement/lib/marketplaceOrderingAgreements.d.ts
  lib/services/marketplaceorderingManagement/lib/marketplaceOrderingAgreements.js
  lib/services/marketplaceorderingManagement/lib/models/agreementTerms.js
  lib/services/marketplaceorderingManagement/lib/models/errorResponse.js
  lib/services/marketplaceorderingManagement/lib/models/errorResponseError.js
  lib/services/marketplaceorderingManagement/lib/models/index.d.ts
  lib/services/marketplaceorderingManagement/lib/models/operation.js
  lib/services/marketplaceorderingManagement/lib/models/operationDisplay.js
  lib/services/marketplaceorderingManagement/lib/models/operationListResult.js
  lib/services/marketplaceorderingManagement/lib/models/resource.js
  lib/services/marketplaceorderingManagement/lib/operations/index.d.ts
  lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js
  lib/services/marketplaceorderingManagement/package.json
Labels: RestPRMerged, in progress

#4811 [AutoPR web/resource-manager] Fix Hosting Environment Network Dependencies pagination
  lib/services/websiteManagement2/lib/models/endpointDependency.js
  lib/services/websiteManagement2/lib/models/endpointDetail.js
  lib/services/websiteManagement2/lib/models/inboundEnvironmentEndpoint.js
  lib/services/websiteManagement2/lib/models/inboundEnvironmentEndpointCollection.js
  lib/services/websiteManagement2/lib/models/index.d.ts
  lib/services/websiteManagement2/lib/models/index.js
  lib/services/websiteManagement2/lib/models/outboundEnvironmentEndpoint.js
  lib/services/websiteManagement2/lib/models/outboundEnvironmentEndpointCollection.js
  lib/services/websiteManagement2/lib/operations/appServiceEnvironments.js
  lib/services/websiteManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4817 Add .prettierrc.yml
  .azure-pipelines/.prettierrc.yml
Labels: in progress

#4796 [AutoPR recoveryservicessiterecovery/resource-manager] [Hub Generated] Review request for Microsoft.RecoveryServices to add version 2018-07-10
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/a2ARecoveryPointDetails.js
  lib/services/recoveryServicesSiteRecoveryManagement/lib/models/index.d.ts
Labels: RestPRMerged, in progress

#4805 [AutoPR cognitiveservices/data-plane/ComputerVision] [Computer Vision] Add read to CV OCR API.
  lib/services/computerVision/lib/computerVisionClient.d.ts
  lib/services/computerVision/lib/computerVisionClient.js
  lib/services/computerVision/lib/models/detectedBrand.js
  lib/services/computerVision/lib/models/imageAnalysis.js
  lib/services/computerVision/lib/models/index.d.ts
  lib/services/computerVision/lib/models/index.js
  lib/services/computerVision/lib/models/line.js
  lib/services/computerVision/lib/models/readOperationResult.js
  lib/services/computerVision/lib/models/textOperationResult.js
  lib/services/computerVision/lib/models/textRecognitionResult.js
  lib/services/computerVision/lib/models/word.js
Labels: RestPRMerged, in progress

#4808 [AutoPR network/resource-manager] Add support for Local Sku
  lib/services/networkManagement2/lib/models/expressRouteCircuit.js
  lib/services/networkManagement2/lib/models/expressRouteCircuitSku.js
  lib/services/networkManagement2/lib/models/index.d.ts
  lib/services/networkManagement2/lib/operations/expressRouteCircuits.js
  lib/services/networkManagement2/lib/operations/index.d.ts
Labels: RestPRMerged, in progress

#4825 [AutoPR eventhub/resource-manager] MultiApi EventHub for Python
  lib/services/eventHubManagement/LICENSE.txt
  lib/services/eventHubManagement/README.md
  lib/services/eventHubManagement/lib/models/accessKeys.js
  lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
  lib/services/eventHubManagement/lib/models/armDisasterRecoveryListResult.js
  lib/services/eventHubManagement/lib/models/authorizationRule.js
  lib/services/eventHubManagement/lib/models/authorizationRuleListResult.js
  lib/services/eventHubManagement/lib/models/captureDescription.js
  lib/services/eventHubManagement/lib/models/checkNameAvailabilityParameter.js
  lib/services/eventHubManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/eventHubManagement/lib/models/consumerGroup.js
  lib/services/eventHubManagement/lib/models/consumerGroupListResult.js
  lib/services/eventHubManagement/lib/models/destination.js
  lib/services/eventHubManagement/lib/models/eHNamespace.js
  lib/services/eventHubManagement/lib/models/eHNamespaceListResult.js
  lib/services/eventHubManagement/lib/models/errorResponse.js
  lib/services/eventHubManagement/lib/models/eventHubListResult.js
  lib/services/eventHubManagement/lib/models/eventhub.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/messagingPlan.js
  lib/services/eventHubManagement/lib/models/messagingRegions.js
  lib/services/eventHubManagement/lib/models/messagingRegionsListResult.js
  lib/services/eventHubManagement/lib/models/messagingRegionsProperties.js
  lib/services/eventHubManagement/lib/models/operation.js
  lib/services/eventHubManagement/lib/models/operationDisplay.js
  lib/services/eventHubManagement/lib/models/operationListResult.js
  lib/services/eventHubManagement/lib/models/regenerateAccessKeyParameters.js
  lib/services/eventHubManagement/lib/models/resource.js
  lib/services/eventHubManagement/lib/models/sku.js
  lib/services/eventHubManagement/lib/models/trackedResource.js
  lib/services/eventHubManagement/lib/operations/consumerGroups.js
  lib/services/eventHubManagement/lib/operations/disasterRecoveryConfigs.js
  lib/services/eventHubManagement/lib/operations/eventHubs.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
  lib/services/eventHubManagement/package.json
Labels: RestPRMerged, in progress

#4833 [AutoPR search/resource-manager] Azure Search: Resource Manager: Support 'None' Identity type
  lib/services/searchManagement/LICENSE.txt
  lib/services/searchManagement/README.md
  lib/services/searchManagement/lib/models/adminKeyResult.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityInput.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityOutput.js
  lib/services/searchManagement/lib/models/identity.js
  lib/services/searchManagement/lib/models/index.d.ts
  lib/services/searchManagement/lib/models/operation.js
  lib/services/searchManagement/lib/models/operationDisplay.js
  lib/services/searchManagement/lib/models/operationListResult.js
  lib/services/searchManagement/lib/models/queryKey.js
  lib/services/searchManagement/lib/models/resource.js
  lib/services/searchManagement/lib/models/searchManagementRequestOptions.js
  lib/services/searchManagement/lib/models/searchService.js
  lib/services/searchManagement/lib/models/sku.js
  lib/services/searchManagement/lib/operations/adminKeys.js
  lib/services/searchManagement/lib/operations/index.d.ts
  lib/services/searchManagement/lib/operations/queryKeys.js
  lib/services/searchManagement/lib/operations/services.js
  lib/services/searchManagement/lib/searchManagementClient.d.ts
  lib/services/searchManagement/lib/searchManagementClient.js
  lib/services/searchManagement/package.json
Labels: RestPRMerged

#4835 [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version 2019-01-01
  lib/services/consumptionManagement/LICENSE.txt
  lib/services/consumptionManagement/README.md
  lib/services/consumptionManagement/lib/consumptionManagementClient.d.ts
  lib/services/consumptionManagement/lib/consumptionManagementClient.js
  lib/services/consumptionManagement/lib/models/balance.js
  lib/services/consumptionManagement/lib/models/balancePropertiesAdjustmentDetailsItem.js
  lib/services/consumptionManagement/lib/models/balancePropertiesNewPurchasesDetailsItem.js
  lib/services/consumptionManagement/lib/models/budget.js
  lib/services/consumptionManagement/lib/models/budgetTimePeriod.js
  lib/services/consumptionManagement/lib/models/budgetsListResult.js
  lib/services/consumptionManagement/lib/models/chargeSummary.js
  lib/services/consumptionManagement/lib/models/chargesListResult.js
  lib/services/consumptionManagement/lib/models/currentSpend.js
  lib/services/consumptionManagement/lib/models/errorDetails.js
  lib/services/consumptionManagement/lib/models/errorResponse.js
  lib/services/consumptionManagement/lib/models/filters.js
  lib/services/consumptionManagement/lib/models/forecast.js
  lib/services/consumptionManagement/lib/models/forecastPropertiesConfidenceLevelsItem.js
  lib/services/consumptionManagement/lib/models/index.d.ts
  lib/services/consumptionManagement/lib/models/index.js
  lib/services/consumptionManagement/lib/models/managementGroupAggregatedCostResult.js
  lib/services/consumptionManagement/lib/models/marketplace.js
  lib/services/consumptionManagement/lib/models/marketplacesListResult.js
  lib/services/consumptionManagement/lib/models/meterDetails.js
  lib/services/consumptionManagement/lib/models/notification.js
  lib/services/consumptionManagement/lib/models/operation.js
  lib/services/consumptionManagement/lib/models/operationDisplay.js
  lib/services/consumptionManagement/lib/models/operationListResult.js
  lib/services/consumptionManagement/lib/models/priceSheetProperties.js
  lib/services/consumptionManagement/lib/models/priceSheetResult.js
  lib/services/consumptionManagement/lib/models/proxyResource.js
  lib/services/consumptionManagement/lib/models/queryOptions.js
  lib/services/consumptionManagement/lib/models/reservationDetail.js
  lib/services/consumptionManagement/lib/models/reservationDetailsListResult.js
  lib/services/consumptionManagement/lib/models/reservationRecommendation.js
  lib/services/consumptionManagement/lib/models/reservationRecommendationsListResult.js
  lib/services/consumptionManagement/lib/models/reservationSummariesListResult.js
  lib/services/consumptionManagement/lib/models/reservationSummary.js
  lib/services/consumptionManagement/lib/models/resource.js
  lib/services/consumptionManagement/lib/models/resourceAttributes.js
  lib/services/consumptionManagement/lib/models/tag.js
  lib/services/consumptionManagement/lib/models/tagsResult.js
  lib/services/consumptionManagement/lib/models/usageDetail.js
  lib/services/consumptionManagement/lib/models/usageDetailsListResult.js
  lib/services/consumptionManagement/lib/operations/budgets.js
  lib/services/consumptionManagement/lib/operations/charges.js
  lib/services/consumptionManagement/lib/operations/index.d.ts
  lib/services/consumptionManagement/lib/operations/index.js
  lib/services/consumptionManagement/lib/operations/marketplaces.js
  lib/services/consumptionManagement/lib/operations/reservationRecommendations.js
  lib/services/consumptionManagement/lib/operations/tags.js
  lib/services/consumptionManagement/lib/operations/usageDetails.js
  lib/services/consumptionManagement/package.json
Labels: RestPRMerged

#4850 [AutoPR batch/data-plane] Update some descriptions.
  lib/services/batch/LICENSE.txt
  lib/services/batch/lib/models/cloudJob.js
  lib/services/batch/lib/models/cloudPool.js
  lib/services/batch/lib/models/computeNode.js
  lib/services/batch/lib/models/index.d.ts
  lib/services/batch/lib/models/multiInstanceSettings.js
  lib/services/batch/lib/models/resourceFile.js
  lib/services/batch/lib/models/virtualMachineConfiguration.js
  lib/services/batch/lib/operations/account.js
  lib/services/batch/lib/operations/application.js
  lib/services/batch/lib/operations/certificateOperations.js
  lib/services/batch/lib/operations/computeNodeOperations.js
  lib/services/batch/lib/operations/file.js
  lib/services/batch/lib/operations/index.d.ts
  lib/services/batch/lib/operations/job.js
  lib/services/batch/lib/operations/jobSchedule.js
  lib/services/batch/lib/operations/pool.js
  lib/services/batch/lib/operations/task.js
Labels: RestPRMerged, in progress

#4854 Generate azure-arm-marketplaceordering package
  lib/services/marketplaceorderingManagement/.scripts/postinstall.js
  lib/services/marketplaceorderingManagement/LICENSE.txt
  lib/services/marketplaceorderingManagement/README.md
  lib/services/marketplaceorderingManagement/lib/marketplaceOrderingAgreements.d.ts
  lib/services/marketplaceorderingManagement/lib/marketplaceOrderingAgreements.js
  lib/services/marketplaceorderingManagement/lib/models/agreementTerms.js
  lib/services/marketplaceorderingManagement/lib/models/errorResponse.js
  lib/services/marketplaceorderingManagement/lib/models/errorResponseError.js
  lib/services/marketplaceorderingManagement/lib/models/index.d.ts
  lib/services/marketplaceorderingManagement/lib/models/operation.js
  lib/services/marketplaceorderingManagement/lib/models/operationDisplay.js
  lib/services/marketplaceorderingManagement/lib/models/operationListResult.js
  lib/services/marketplaceorderingManagement/lib/models/resource.js
  lib/services/marketplaceorderingManagement/lib/operations/index.d.ts
  lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js
  lib/services/marketplaceorderingManagement/package.json
Labels: in progress

#4855 Generate azure-cognitiveservices-computervision package
  lib/services/computerVision/.scripts/postinstall.js
  lib/services/computerVision/lib/computerVisionClient.d.ts
  lib/services/computerVision/lib/computerVisionClient.js
  lib/services/computerVision/lib/models/detectedBrand.js
  lib/services/computerVision/lib/models/imageAnalysis.js
  lib/services/computerVision/lib/models/index.d.ts
  lib/services/computerVision/lib/models/index.js
  lib/services/computerVision/lib/models/line.js
  lib/services/computerVision/lib/models/readOperationResult.js
  lib/services/computerVision/lib/models/textOperationResult.js
  lib/services/computerVision/lib/models/textRecognitionResult.js
  lib/services/computerVision/lib/models/word.js
  lib/services/computerVision/package.json
Labels: in progress

#4852 [AutoPR eventhub/resource-manager] EventHub: added VNet API to 2017 stable version
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/index.js
  lib/services/eventHubManagement/lib/models/nWRuleSetIpRules.js
  lib/services/eventHubManagement/lib/models/nWRuleSetVirtualNetworkRules.js
  lib/services/eventHubManagement/lib/models/networkRuleSet.js
  lib/services/eventHubManagement/lib/models/subnet.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#4864 [AutoPR eventhub/resource-manager] EventHub : corrected typo
  lib/services/eventHubManagement/lib/operations/namespaces.js
Labels: RestPRMerged, in progress

#4870 [AutoPR eventhub/resource-manager] EventHub: Revert the NetworkRuleSet
  lib/services/eventHubManagement/LICENSE.txt
  lib/services/eventHubManagement/README.md
  lib/services/eventHubManagement/lib/models/accessKeys.js
  lib/services/eventHubManagement/lib/models/armDisasterRecovery.js
  lib/services/eventHubManagement/lib/models/armDisasterRecoveryListResult.js
  lib/services/eventHubManagement/lib/models/authorizationRule.js
  lib/services/eventHubManagement/lib/models/authorizationRuleListResult.js
  lib/services/eventHubManagement/lib/models/captureDescription.js
  lib/services/eventHubManagement/lib/models/checkNameAvailabilityParameter.js
  lib/services/eventHubManagement/lib/models/checkNameAvailabilityResult.js
  lib/services/eventHubManagement/lib/models/consumerGroup.js
  lib/services/eventHubManagement/lib/models/consumerGroupListResult.js
  lib/services/eventHubManagement/lib/models/destination.js
  lib/services/eventHubManagement/lib/models/eHNamespace.js
  lib/services/eventHubManagement/lib/models/eHNamespaceListResult.js
  lib/services/eventHubManagement/lib/models/errorResponse.js
  lib/services/eventHubManagement/lib/models/eventHubListResult.js
  lib/services/eventHubManagement/lib/models/eventhub.js
  lib/services/eventHubManagement/lib/models/index.d.ts
  lib/services/eventHubManagement/lib/models/messagingPlan.js
  lib/services/eventHubManagement/lib/models/messagingRegions.js
  lib/services/eventHubManagement/lib/models/messagingRegionsListResult.js
  lib/services/eventHubManagement/lib/models/messagingRegionsProperties.js
  lib/services/eventHubManagement/lib/models/operation.js
  lib/services/eventHubManagement/lib/models/operationDisplay.js
  lib/services/eventHubManagement/lib/models/operationListResult.js
  lib/services/eventHubManagement/lib/models/regenerateAccessKeyParameters.js
  lib/services/eventHubManagement/lib/models/resource.js
  lib/services/eventHubManagement/lib/models/sku.js
  lib/services/eventHubManagement/lib/models/trackedResource.js
  lib/services/eventHubManagement/lib/operations/consumerGroups.js
  lib/services/eventHubManagement/lib/operations/disasterRecoveryConfigs.js
  lib/services/eventHubManagement/lib/operations/eventHubs.js
  lib/services/eventHubManagement/lib/operations/index.d.ts
  lib/services/eventHubManagement/lib/operations/namespaces.js
  lib/services/eventHubManagement/package.json
Labels: RestPRMerged, in progress

#4843 Remove unnecessary packages from main package.json
  package.json
Labels: in progress

#4885 Generate azure-arm-policyinsights package
  lib/services/policyinsightsManagement/.scripts/postinstall.js
  lib/services/policyinsightsManagement/LICENSE.txt
  lib/services/policyinsightsManagement/README.md
  lib/services/policyinsightsManagement/lib/models/expressionEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/ifNotExistsEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/index.d.ts
  lib/services/policyinsightsManagement/lib/models/index.js
  lib/services/policyinsightsManagement/lib/models/policyEvaluationDetails.js
  lib/services/policyinsightsManagement/lib/models/policyState.js
  lib/services/policyinsightsManagement/lib/models/queryOptions.js
  lib/services/policyinsightsManagement/lib/operations/index.d.ts
  lib/services/policyinsightsManagement/lib/operations/operations.js
  lib/services/policyinsightsManagement/lib/operations/policyEvents.js
  lib/services/policyinsightsManagement/lib/operations/policyStates.js
  lib/services/policyinsightsManagement/lib/operations/policyTrackedResources.js
  lib/services/policyinsightsManagement/lib/operations/remediations.js
  lib/services/policyinsightsManagement/package.json
Labels: in progress

#4889 [AutoPR storage/resource-manager] SRP Swagger changes for 2018-11-01
  lib/services/storageManagement2/lib/models/dateAfterCreation.js
  lib/services/storageManagement2/lib/models/dateAfterModification.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/managementPolicy.js
  lib/services/storageManagement2/lib/models/managementPolicyAction.js
  lib/services/storageManagement2/lib/models/managementPolicyBaseBlob.js
  lib/services/storageManagement2/lib/models/managementPolicyDefinition.js
  lib/services/storageManagement2/lib/models/managementPolicyFilter.js
  lib/services/storageManagement2/lib/models/managementPolicyRule.js
  lib/services/storageManagement2/lib/models/managementPolicySchema.js
  lib/services/storageManagement2/lib/models/managementPolicySnapShot.js
  lib/services/storageManagement2/lib/models/sku.js
  lib/services/storageManagement2/lib/models/storageAccount.js
  lib/services/storageManagement2/lib/models/storageAccountCreateParameters.js
  lib/services/storageManagement2/lib/models/storageAccountUpdateParameters.js
  lib/services/storageManagement2/lib/operations/blobContainers.js
  lib/services/storageManagement2/lib/operations/blobServices.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/managementPolicies.js
  lib/services/storageManagement2/lib/operations/operations.js
  lib/services/storageManagement2/lib/operations/skus.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
Labels: RestPRMerged

#4887 [AutoPR monitor/resource-manager] Add insights 2019-03-01 package to Go SDK
  lib/services/monitorManagement/README.md
  lib/services/monitorManagement/package.json
Labels: RestPRMerged, in progress

#4899 [AutoPR monitor/resource-manager] fix package tag for new API version
  lib/services/monitorManagement/lib/models/armRoleReceiver.js
  lib/services/monitorManagement/lib/models/automationRunbookReceiver.js
  lib/services/monitorManagement/lib/models/azureFunctionReceiver.js
  lib/services/monitorManagement/lib/models/emailReceiver.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/logicAppReceiver.js
  lib/services/monitorManagement/lib/models/webhookReceiver.js
  lib/services/monitorManagement/lib/operations/actionGroups.js
Labels: RestPRMerged, in progress

#4905 Generate azure-arm-monitor package
  lib/services/monitorManagement/lib/models/armRoleReceiver.js
  lib/services/monitorManagement/lib/models/automationRunbookReceiver.js
  lib/services/monitorManagement/lib/models/azureFunctionReceiver.js
  lib/services/monitorManagement/lib/models/emailReceiver.js
  lib/services/monitorManagement/lib/models/index.d.ts
  lib/services/monitorManagement/lib/models/logicAppReceiver.js
  lib/services/monitorManagement/lib/models/webhookReceiver.js
  lib/services/monitorManagement/lib/operations/actionGroups.js
  lib/services/monitorManagement/package.json
Labels: in progress

#4906 [AutoPR storage/resource-manager] Remove GZRS and RAGZRS sku from SRP 2018-11-01 because feature slipped.
  lib/services/storageManagement2/lib/models/dateAfterCreation.js
  lib/services/storageManagement2/lib/models/dateAfterModification.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/managementPolicy.js
  lib/services/storageManagement2/lib/models/managementPolicyAction.js
  lib/services/storageManagement2/lib/models/managementPolicyBaseBlob.js
  lib/services/storageManagement2/lib/models/managementPolicyDefinition.js
  lib/services/storageManagement2/lib/models/managementPolicyFilter.js
  lib/services/storageManagement2/lib/models/managementPolicyRule.js
  lib/services/storageManagement2/lib/models/managementPolicySchema.js
  lib/services/storageManagement2/lib/models/managementPolicySnapShot.js
  lib/services/storageManagement2/lib/operations/blobContainers.js
  lib/services/storageManagement2/lib/operations/blobServices.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/managementPolicies.js
  lib/services/storageManagement2/lib/operations/operations.js
  lib/services/storageManagement2/lib/operations/skus.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
Labels: RestPRMerged

#4918 [AutoPR policyinsights/resource-manager] Fix PolicyInsights code generation issue
  lib/services/policyinsightsManagement/README.md
  lib/services/policyinsightsManagement/package.json
Labels: RestPRMerged, in progress

#4923 [AutoPR mediaservices/resource-manager] Add filter to StreamingLocator and Streaming presets.
  lib/services/mediaServicesManagement/LICENSE.txt
  lib/services/mediaServicesManagement/README.md
  lib/services/mediaServicesManagement/lib/models/audioAnalyzerPreset.js
  lib/services/mediaServicesManagement/lib/models/audioOverlay.js
  lib/services/mediaServicesManagement/lib/models/cbcsDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/cencDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCbcs.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCenc.js
  lib/services/mediaServicesManagement/lib/models/envelopeEncryption.js
  lib/services/mediaServicesManagement/lib/models/faceDetectorPreset.js
  lib/services/mediaServicesManagement/lib/models/format.js
  lib/services/mediaServicesManagement/lib/models/h264Layer.js
  lib/services/mediaServicesManagement/lib/models/image.js
  lib/services/mediaServicesManagement/lib/models/imageFormat.js
  lib/services/mediaServicesManagement/lib/models/index.d.ts
  lib/services/mediaServicesManagement/lib/models/index.js
  lib/services/mediaServicesManagement/lib/models/job.js
  lib/services/mediaServicesManagement/lib/models/jobInputClip.js
  lib/services/mediaServicesManagement/lib/models/jobInputHttp.js
  lib/services/mediaServicesManagement/lib/models/jpgFormat.js
  lib/services/mediaServicesManagement/lib/models/jpgImage.js
  lib/services/mediaServicesManagement/lib/models/mp4Format.js
  lib/services/mediaServicesManagement/lib/models/multiBitrateFormat.js
  lib/services/mediaServicesManagement/lib/models/outputFile.js
  lib/services/mediaServicesManagement/lib/models/overlay.js
  lib/services/mediaServicesManagement/lib/models/pngFormat.js
  lib/services/mediaServicesManagement/lib/models/pngImage.js
  lib/services/mediaServicesManagement/lib/models/standardEncoderPreset.js
  lib/services/mediaServicesManagement/lib/models/streamingLocator.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicy.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyFairPlayConfiguration.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyPlayReadyConfiguration.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyWidevineConfiguration.js
  lib/services/mediaServicesManagement/lib/models/transportStreamFormat.js
  lib/services/mediaServicesManagement/lib/models/videoLayer.js
  lib/services/mediaServicesManagement/lib/models/videoOverlay.js
  lib/services/mediaServicesManagement/lib/operations/index.d.ts
  lib/services/mediaServicesManagement/lib/operations/jobs.js
  lib/services/mediaServicesManagement/lib/operations/streamingLocators.js
  lib/services/mediaServicesManagement/lib/operations/streamingPolicies.js
Labels: RestPRMerged

#4930 [AutoPR cognitiveservices/data-plane/AnomalyDetector] [AnomalyDetector] add cognitive service AnomalyDetector [DO NOT MERGE]
  lib/services/cognitiveServicesAnomalyDetector/LICENSE.txt
  lib/services/cognitiveServicesAnomalyDetector/README.md
  lib/services/cognitiveServicesAnomalyDetector/lib/anomalyDetectorClient.d.ts
  lib/services/cognitiveServicesAnomalyDetector/lib/anomalyDetectorClient.js
  lib/services/cognitiveServicesAnomalyDetector/lib/models/aPIError.js
  lib/services/cognitiveServicesAnomalyDetector/lib/models/entireDetectResponse.js
  lib/services/cognitiveServicesAnomalyDetector/lib/models/index.d.ts
  lib/services/cognitiveServicesAnomalyDetector/lib/models/index.js
  lib/services/cognitiveServicesAnomalyDetector/lib/models/lastDetectResponse.js
  lib/services/cognitiveServicesAnomalyDetector/lib/models/point.js
  lib/services/cognitiveServicesAnomalyDetector/lib/models/request.js
  lib/services/cognitiveServicesAnomalyDetector/package.json
Labels: RestPRMerged

#4904 Add GitHub AutoPR branch cleanup script
  .scripts/github.ts
  .travis.yml
  package.json
  tsconfig.json
Labels: in progress

#4959 [AutoPR search/resource-manager] [Azure Search] Add L-Series SKU values to management plane
  lib/services/searchManagement/LICENSE.txt
  lib/services/searchManagement/README.md
  lib/services/searchManagement/lib/models/adminKeyResult.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityInput.js
  lib/services/searchManagement/lib/models/checkNameAvailabilityOutput.js
  lib/services/searchManagement/lib/models/identity.js
  lib/services/searchManagement/lib/models/index.d.ts
  lib/services/searchManagement/lib/models/operation.js
  lib/services/searchManagement/lib/models/operationDisplay.js
  lib/services/searchManagement/lib/models/operationListResult.js
  lib/services/searchManagement/lib/models/queryKey.js
  lib/services/searchManagement/lib/models/resource.js
  lib/services/searchManagement/lib/models/searchManagementRequestOptions.js
  lib/services/searchManagement/lib/models/searchService.js
  lib/services/searchManagement/lib/models/sku.js
  lib/services/searchManagement/lib/operations/adminKeys.js
  lib/services/searchManagement/lib/operations/index.d.ts
  lib/services/searchManagement/lib/operations/queryKeys.js
  lib/services/searchManagement/lib/operations/services.js
  lib/services/searchManagement/lib/searchManagementClient.d.ts
  lib/services/searchManagement/lib/searchManagementClient.js
  lib/services/searchManagement/package.json
Labels: RestPRMerged

#4969 [AutoPR marketplaceordering/resource-manager] [Hub Generated] Review request for Microsoft.MarketplaceOrdering to add version 2015-06-01
  lib/services/marketplaceorderingManagement/README.md
  lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js
  lib/services/marketplaceorderingManagement/package.json
Labels: RestPRMerged

#4986 Remove Readme Verification
  .azure-pipelines/client.yml
Labels: in progress

#4990 Generate azure-arm-marketplaceordering
  lib/services/marketplaceorderingManagement/lib/operations/marketplaceAgreements.js
  lib/services/marketplaceorderingManagement/package.json
Labels: in progress

#4949 Generate azure-arm-storage package
  lib/services/storageManagement2/.scripts/postinstall.js
  lib/services/storageManagement2/README.md
  lib/services/storageManagement2/lib/models/azureResource.js
  lib/services/storageManagement2/lib/models/dateAfterCreation.js
  lib/services/storageManagement2/lib/models/dateAfterModification.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/managementPoliciesRulesSetParameter.js
  lib/services/storageManagement2/lib/models/managementPolicy.js
  lib/services/storageManagement2/lib/models/managementPolicyAction.js
  lib/services/storageManagement2/lib/models/managementPolicyBaseBlob.js
  lib/services/storageManagement2/lib/models/managementPolicyDefinition.js
  lib/services/storageManagement2/lib/models/managementPolicyFilter.js
  lib/services/storageManagement2/lib/models/managementPolicyRule.js
  lib/services/storageManagement2/lib/models/managementPolicySchema.js
  lib/services/storageManagement2/lib/models/managementPolicySnapShot.js
  lib/services/storageManagement2/lib/operations/blobContainers.js
  lib/services/storageManagement2/lib/operations/blobServices.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/managementPolicies.js
  lib/services/storageManagement2/lib/operations/operations.js
  lib/services/storageManagement2/lib/operations/skus.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usageOperations.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
  lib/services/storageManagement2/package.json
  package.json
  test/services/keyVault/keyVault-storage-tests.js
  test/services/storageManagement/storageManagementClient-tests.js
Labels: in progress

#5001 [AutoPR containerregistry/resource-manager] [ACR] Update Webhook Event Target Schema to Add Name and Version
  lib/services/containerRegistryManagement/lib/models/credentials.js
  lib/services/containerRegistryManagement/lib/models/customRegistryCredentials.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildRequest.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/event.js
  lib/services/containerRegistryManagement/lib/models/eventContent.js
  lib/services/containerRegistryManagement/lib/models/eventRequestMessage.js
  lib/services/containerRegistryManagement/lib/models/fileTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/run.js
  lib/services/containerRegistryManagement/lib/models/secretObject.js
  lib/services/containerRegistryManagement/lib/models/sourceRegistryCredentials.js
  lib/services/containerRegistryManagement/lib/models/target.js
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/tasks.js
Labels: RestPRMerged

#5003 Increase version of azure-arm-containerservice package
  lib/services/containerservicesManagement/package.json
Labels: in progress

#5013 [AutoPR healthcareapis/resource-manager] Adding swagger spec for healthcareapis resource manager and examples.
  lib/services/healthcareapisManagement/LICENSE.txt
  lib/services/healthcareapisManagement/README.md
  lib/services/healthcareapisManagement/lib/healthcareApisManagementClient.d.ts
  lib/services/healthcareapisManagement/lib/healthcareApisManagementClient.js
  lib/services/healthcareapisManagement/lib/models/checkNameAvailabilityParameters.js
  lib/services/healthcareapisManagement/lib/models/errorDetails.js
  lib/services/healthcareapisManagement/lib/models/errorDetailsInternal.js
  lib/services/healthcareapisManagement/lib/models/index.d.ts
  lib/services/healthcareapisManagement/lib/models/index.js
  lib/services/healthcareapisManagement/lib/models/moveResourcesParameters.js
  lib/services/healthcareapisManagement/lib/models/operation.js
  lib/services/healthcareapisManagement/lib/models/operationDisplay.js
  lib/services/healthcareapisManagement/lib/models/operationListResult.js
  lib/services/healthcareapisManagement/lib/models/operationResultsDescription.js
  lib/services/healthcareapisManagement/lib/models/resource.js
  lib/services/healthcareapisManagement/lib/models/serviceAccessPolicyEntry.js
  lib/services/healthcareapisManagement/lib/models/serviceCosmosDbConfigurationInfo.js
  lib/services/healthcareapisManagement/lib/models/servicesDescription.js
  lib/services/healthcareapisManagement/lib/models/servicesDescriptionListResult.js
  lib/services/healthcareapisManagement/lib/models/servicesNameAvailabilityInfo.js
  lib/services/healthcareapisManagement/lib/models/servicesPatchDescription.js
  lib/services/healthcareapisManagement/lib/models/servicesProperties.js
  lib/services/healthcareapisManagement/lib/operations/index.d.ts
  lib/services/healthcareapisManagement/lib/operations/index.js
  lib/services/healthcareapisManagement/lib/operations/moveResourcesStatus.js
  lib/services/healthcareapisManagement/lib/operations/operationResults.js
  lib/services/healthcareapisManagement/lib/operations/operations.js
  lib/services/healthcareapisManagement/lib/operations/services.js
  lib/services/healthcareapisManagement/package.json
Labels: in progress

#5018 [AutoPR storage/resource-manager] [Storage] Add a new return code to Create Container
  lib/services/storageManagement2/lib/models/dateAfterCreation.js
  lib/services/storageManagement2/lib/models/dateAfterModification.js
  lib/services/storageManagement2/lib/models/index.d.ts
  lib/services/storageManagement2/lib/models/index.js
  lib/services/storageManagement2/lib/models/managementPolicy.js
  lib/services/storageManagement2/lib/models/managementPolicyAction.js
  lib/services/storageManagement2/lib/models/managementPolicyBaseBlob.js
  lib/services/storageManagement2/lib/models/managementPolicyDefinition.js
  lib/services/storageManagement2/lib/models/managementPolicyFilter.js
  lib/services/storageManagement2/lib/models/managementPolicyRule.js
  lib/services/storageManagement2/lib/models/managementPolicySchema.js
  lib/services/storageManagement2/lib/models/managementPolicySnapShot.js
  lib/services/storageManagement2/lib/operations/blobContainers.js
  lib/services/storageManagement2/lib/operations/blobServices.js
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/index.js
  lib/services/storageManagement2/lib/operations/managementPolicies.js
  lib/services/storageManagement2/lib/operations/operations.js
  lib/services/storageManagement2/lib/operations/skus.js
  lib/services/storageManagement2/lib/operations/storageAccounts.js
  lib/services/storageManagement2/lib/operations/usages.js
  lib/services/storageManagement2/lib/storageManagementClient.d.ts
  lib/services/storageManagement2/lib/storageManagementClient.js
Labels: RestPRMerged

#5015 [AutoPR peering/resource-manager] Adding Specifications for Peering
  lib/services/peeringManagement/LICENSE.txt
  lib/services/peeringManagement/lib/models/bgpSession.js
  lib/services/peeringManagement/lib/models/contactInfo.js
  lib/services/peeringManagement/lib/models/directConnection.js
  lib/services/peeringManagement/lib/models/directPeeringFacility.js
  lib/services/peeringManagement/lib/models/errorResponse.js
  lib/services/peeringManagement/lib/models/exchangeConnection.js
  lib/services/peeringManagement/lib/models/exchangePeeringFacility.js
  lib/services/peeringManagement/lib/models/index.d.ts
  lib/services/peeringManagement/lib/models/index.js
  lib/services/peeringManagement/lib/models/operation.js
  lib/services/peeringManagement/lib/models/operationDisplayInfo.js
  lib/services/peeringManagement/lib/models/operationListResult.js
  lib/services/peeringManagement/lib/models/peerAsn.js
  lib/services/peeringManagement/lib/models/peerAsnListResult.js
  lib/services/peeringManagement/lib/models/peering.js
  lib/services/peeringManagement/lib/models/peeringBandwidthOffer.js
  lib/services/peeringManagement/lib/models/peeringListResult.js
  lib/services/peeringManagement/lib/models/peeringLocation.js
  lib/services/peeringManagement/lib/models/peeringLocationListResult.js
  lib/services/peeringManagement/lib/models/peeringLocationPropertiesDirect.js
  lib/services/peeringManagement/lib/models/peeringLocationPropertiesExchange.js
  lib/services/peeringManagement/lib/models/peeringPropertiesDirect.js
  lib/services/peeringManagement/lib/models/peeringPropertiesExchange.js
  lib/services/peeringManagement/lib/models/peeringSku.js
  lib/services/peeringManagement/lib/models/resource.js
  lib/services/peeringManagement/lib/models/resourceTags.js
  lib/services/peeringManagement/lib/models/subResource.js
  lib/services/peeringManagement/lib/operations/index.d.ts
  lib/services/peeringManagement/lib/operations/index.js
  lib/services/peeringManagement/lib/operations/legacyPeerings.js
  lib/services/peeringManagement/lib/operations/operations.js
  lib/services/peeringManagement/lib/operations/peerAsns.js
  lib/services/peeringManagement/lib/operations/peeringLocations.js
  lib/services/peeringManagement/lib/operations/peerings.js
  lib/services/peeringManagement/lib/peeringManagementClient.d.ts
  lib/services/peeringManagement/lib/peeringManagementClient.js
  lib/services/peeringManagement/package.json
Labels: RestPRMerged, in progress

#5023 [AutoPR mediaservices/resource-manager] Add preset enum ContentAwareEncodingExperimental
  lib/services/mediaServicesManagement/LICENSE.txt
  lib/services/mediaServicesManagement/README.md
  lib/services/mediaServicesManagement/lib/models/audioAnalyzerPreset.js
  lib/services/mediaServicesManagement/lib/models/audioOverlay.js
  lib/services/mediaServicesManagement/lib/models/builtInStandardEncoderPreset.js
  lib/services/mediaServicesManagement/lib/models/cbcsDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/cencDrmConfiguration.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCbcs.js
  lib/services/mediaServicesManagement/lib/models/commonEncryptionCenc.js
  lib/services/mediaServicesManagement/lib/models/envelopeEncryption.js
  lib/services/mediaServicesManagement/lib/models/faceDetectorPreset.js
  lib/services/mediaServicesManagement/lib/models/format.js
  lib/services/mediaServicesManagement/lib/models/h264Layer.js
  lib/services/mediaServicesManagement/lib/models/image.js
  lib/services/mediaServicesManagement/lib/models/imageFormat.js
  lib/services/mediaServicesManagement/lib/models/index.d.ts
  lib/services/mediaServicesManagement/lib/models/index.js
  lib/services/mediaServicesManagement/lib/models/job.js
  lib/services/mediaServicesManagement/lib/models/jobInputClip.js
  lib/services/mediaServicesManagement/lib/models/jobInputHttp.js
  lib/services/mediaServicesManagement/lib/models/jpgFormat.js
  lib/services/mediaServicesManagement/lib/models/jpgImage.js
  lib/services/mediaServicesManagement/lib/models/mp4Format.js
  lib/services/mediaServicesManagement/lib/models/multiBitrateFormat.js
  lib/services/mediaServicesManagement/lib/models/outputFile.js
  lib/services/mediaServicesManagement/lib/models/overlay.js
  lib/services/mediaServicesManagement/lib/models/pngFormat.js
  lib/services/mediaServicesManagement/lib/models/pngImage.js
  lib/services/mediaServicesManagement/lib/models/standardEncoderPreset.js
  lib/services/mediaServicesManagement/lib/models/streamingLocator.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicy.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyFairPlayConfiguration.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyPlayReadyConfiguration.js
  lib/services/mediaServicesManagement/lib/models/streamingPolicyWidevineConfiguration.js
  lib/services/mediaServicesManagement/lib/models/transportStreamFormat.js
  lib/services/mediaServicesManagement/lib/models/videoLayer.js
  lib/services/mediaServicesManagement/lib/models/videoOverlay.js
  lib/services/mediaServicesManagement/lib/operations/index.d.ts
  lib/services/mediaServicesManagement/lib/operations/jobs.js
  lib/services/mediaServicesManagement/lib/operations/streamingLocators.js
  lib/services/mediaServicesManagement/lib/operations/streamingPolicies.js
Labels: RestPRMerged

#5009 [AutoPR containerregistry/resource-manager] [ACR] Add Readonly RunErrorMessage to RunProperties
  lib/services/containerRegistryManagement/README.md
  lib/services/containerRegistryManagement/lib/models/credentials.js
  lib/services/containerRegistryManagement/lib/models/customRegistryCredentials.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildRequest.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStep.js
  lib/services/containerRegistryManagement/lib/models/dockerBuildStepUpdateParameters.js
  lib/services/containerRegistryManagement/lib/models/encodedTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/event.js
  lib/services/containerRegistryManagement/lib/models/eventContent.js
  lib/services/containerRegistryManagement/lib/models/eventRequestMessage.js
  lib/services/containerRegistryManagement/lib/models/fileTaskRunRequest.js
  lib/services/containerRegistryManagement/lib/models/index.d.ts
  lib/services/containerRegistryManagement/lib/models/index.js
  lib/services/containerRegistryManagement/lib/models/run.js
  lib/services/containerRegistryManagement/lib/models/secretObject.js
  lib/services/containerRegistryManagement/lib/models/sourceRegistryCredentials.js
  lib/services/containerRegistryManagement/lib/models/target.js
  lib/services/containerRegistryManagement/lib/models/task.js
  lib/services/containerRegistryManagement/lib/models/taskUpdateParameters.js
  lib/services/containerRegistryManagement/lib/operations/index.d.ts
  lib/services/containerRegistryManagement/lib/operations/tasks.js
Labels: RestPRMerged, in progress

#5027 [AutoPR signalr/resource-manager] 3 new APIs added to SignalR service and rename the sample files
  lib/services/signalrManagement/LICENSE.txt
  lib/services/signalrManagement/README.md
  lib/services/signalrManagement/lib/models/dimension.js
  lib/services/signalrManagement/lib/models/index.d.ts
  lib/services/signalrManagement/lib/models/metricSpecification.js
  lib/services/signalrManagement/lib/models/nameAvailability.js
  lib/services/signalrManagement/lib/models/nameAvailabilityParameters.js
  lib/services/signalrManagement/lib/models/operation.js
  lib/services/signalrManagement/lib/models/operationDisplay.js
  lib/services/signalrManagement/lib/models/operationList.js
  lib/services/signalrManagement/lib/models/operationProperties.js
  lib/services/signalrManagement/lib/models/regenerateKeyParameters.js
  lib/services/signalrManagement/lib/models/resource.js
  lib/services/signalrManagement/lib/models/resourceSku.js
  lib/services/signalrManagement/lib/models/serviceSpecification.js
  lib/services/signalrManagement/lib/models/signalRCreateOrUpdateProperties.js
  lib/services/signalrManagement/lib/models/signalRCreateParameters.js
  lib/services/signalrManagement/lib/models/signalRKeys.js
  lib/services/signalrManagement/lib/models/signalRResource.js
  lib/services/signalrManagement/lib/models/signalRResourceList.js
  lib/services/signalrManagement/lib/models/signalRUpdateParameters.js
  lib/services/signalrManagement/lib/models/signalRUsage.js
  lib/services/signalrManagement/lib/models/signalRUsageList.js
  lib/services/signalrManagement/lib/models/signalRUsageName.js
  lib/services/signalrManagement/lib/models/trackedResource.js
  lib/services/signalrManagement/lib/operations/index.d.ts
  lib/services/signalrManagement/lib/operations/signalR.js
  lib/services/signalrManagement/package.json
Labels: RestPRMerged

#5029 [AutoPR storage/resource-manager] Added feature revoke user delegation key
  lib/services/storageManagement2/lib/operations/index.d.ts
  lib/services/storageManagement2/lib/operations/storageAccounts.js
Labels: RestPRMerged, in progress

#5036 Generate azure-cognitiveservices-customvision-training package
  lib/services/customVision/training/.scripts/postinstall.js
  lib/services/customVision/training/LICENSE.txt
  lib/services/customVision/training/README.md
  lib/services/customVision/training/lib/models/boundingBox.js
  lib/services/customVision/training/lib/models/customVisionError.js
  lib/services/customVision/training/lib/models/domain.js
  lib/services/customVision/training/lib/models/exportModel.js
  lib/services/customVision/training/lib/models/image.js
  lib/services/customVision/training/lib/models/imageCreateResult.js
  lib/services/customVision/training/lib/models/imageCreateSummary.js
  lib/services/customVision/training/lib/models/imageFileCreateBatch.js
  lib/services/customVision/training/lib/models/imageFileCreateEntry.js
  lib/services/customVision/training/lib/models/imageIdCreateBatch.js
  lib/services/customVision/training/lib/models/imageIdCreateEntry.js
  lib/services/customVision/training/lib/models/imagePerformance.js
  lib/services/customVision/training/lib/models/imagePrediction.js
  lib/services/customVision/training/lib/models/imageRegion.js
  lib/services/customVision/training/lib/models/imageRegionCreateBatch.js
  lib/services/customVision/training/lib/models/imageRegionCreateEntry.js
  lib/services/customVision/training/lib/models/imageRegionCreateResult.js
  lib/services/customVision/training/lib/models/imageRegionProposal.js
  lib/services/customVision/training/lib/models/imageTag.js
  lib/services/customVision/training/lib/models/imageTagCreateBatch.js
  lib/services/customVision/training/lib/models/imageUrl.js
  lib/services/customVision/training/lib/models/imageUrlCreateBatch.js
  lib/services/customVision/training/lib/models/imageUrlCreateEntry.js
  lib/services/customVision/training/lib/models/index.d.ts
  lib/services/customVision/training/lib/models/index.js
  lib/services/customVision/training/lib/models/iteration.js
  lib/services/customVision/training/lib/models/iterationPerformance.js
  lib/services/customVision/training/lib/models/prediction.js
  lib/services/customVision/training/lib/models/predictionQueryResult.js
  lib/services/customVision/training/lib/models/predictionQueryToken.js
  lib/services/customVision/training/lib/models/project.js
  lib/services/customVision/training/lib/models/projectSettings.js
  lib/services/customVision/training/lib/models/region.js
  lib/services/customVision/training/lib/models/regionProposal.js
  lib/services/customVision/training/lib/models/storedImagePrediction.js
  lib/services/customVision/training/lib/models/tag.js
  lib/services/customVision/training/lib/models/tagPerformance.js
  lib/services/customVision/training/lib/trainingAPIClient.d.ts
  lib/services/customVision/training/lib/trainingAPIClient.js
  lib/services/customVision/training/package.json
Labels: in progress

#5040 Generate azure-cognitiveservices-customvision-prediction package
  lib/services/customVision/prediction/README.md
  lib/services/customVision/prediction/lib/models/boundingBox.js
  lib/services/customVision/prediction/lib/models/customVisionError.js
  lib/services/customVision/prediction/lib/models/imagePrediction.js
  lib/services/customVision/prediction/lib/models/imageUrl.js
  lib/services/customVision/prediction/lib/models/index.d.ts
  lib/services/customVision/prediction/lib/models/index.js
  lib/services/customVision/prediction/lib/models/prediction.js
  lib/services/customVision/prediction/lib/predictionAPIClient.d.ts
  lib/services/customVision/prediction/lib/predictionAPIClient.js
  lib/services/customVision/prediction/package.json
Labels: in progress

#5046 [AutoPR security/resource-manager] Adding the NorthSouth API for Public Preview
  lib/services/securityManagement/lib/models/adaptiveNetworkHardening.js
  lib/services/securityManagement/lib/models/adaptiveNetworkHardeningEnforceRequest.js
  lib/services/securityManagement/lib/models/adaptiveNetworkHardeningsList.js
  lib/services/securityManagement/lib/models/allowlistCustomAlertRule.js
  lib/services/securityManagement/lib/models/customAlertRule.js
  lib/services/securityManagement/lib/models/denylistCustomAlertRule.js
  lib/services/securityManagement/lib/models/deviceSecurityGroup.js
  lib/services/securityManagement/lib/models/deviceSecurityGroupList.js
  lib/services/securityManagement/lib/models/effectiveNetworkSecurityGroups.js
  lib/services/securityManagement/lib/models/index.d.ts
  lib/services/securityManagement/lib/models/index.js
  lib/services/securityManagement/lib/models/listCustomAlertRule.js
  lib/services/securityManagement/lib/models/rule.js
  lib/services/securityManagement/lib/models/thresholdCustomAlertRule.js
  lib/services/securityManagement/lib/models/timeWindowCustomAlertRule.js
  lib/services/securityManagement/lib/operations/adaptiveNetworkHardenings.js
  lib/services/securityManagement/lib/operations/deviceSecurityGroups.js
  lib/services/securityManagement/lib/operations/index.d.ts
  lib/services/securityManagement/lib/operations/index.js
  lib/services/securityManagement/lib/securityCenter.d.ts
  lib/services/securityManagement/lib/securityCenter.js
Labels: RestPRMerged, in progress
